- views/config.mako
> Fix for config black panel

- static/js/edit-show.js
> Fixed anime black/white list. Typo in js metaTobool usage.

- medusa/providers/torrent/html/animebytes.py
- pytest.ini
> Fix AnimeBytes login, lint. Fixes #1577

- medusa/name_parser/rules/rules.py
> Changing log level to info in guessit rules

- lib/knowit/__init__.py
- lib/knowit/providers/mediainfo.py
> Upgrading knowit to 0.1.4.1

- medusa/providers/nzb/newznab.py
- medusa/search/core.py
- medusa/search/manual.py
- medusa/server/web/home/handler.py
- medusa/show_name_helpers.py
- medusa/tv.py
- static/css/style.css
- views/config_subtitles.mako
- views/displayShow.mako
- views/snatchSelection.mako
As requested here: https://github.com/pymedusa/Medusa/issues/1546
Also moved a lot of python code from mako to python. Moved only. didn't changed code
@nicoleoca @duramato
> Show newznab pubdate in manual search results

- medusa/helpers.py
> Only rename if name has changed

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Enhancing TvChaosUK rule to remove conflicting hdtv.x264

- medusa/providers/nzb/newznab.py
> Fixed missing '!!!' separator in nzb list

- medusa/helpers.py
- medusa/post_processor.py
> Bring sanity to list_associated_files

- medusa/providers/torrent/html/torrentbytes.py
Titles that are obtained via the title tag don't need to get the "[F L]" removed, only the others have it.
> Fix torrentbytes title getting cut

- medusa/providers/torrent/html/speedcd.py
> Fix Speed.CD parsing

- medusa/providers/torrent/html/tvchaosuk.py
> Skip tvchaosuk highlighted torrents

- medusa/providers/torrent/html/danishbits.py
> Fix DanishBits download url

- medusa/providers/torrent/json/t411.py
> Change t411 domain to .li

- medusa/search/manual.py
- views/snatchSelection.mako
Fix failed_history returning unicode for some provider qualities instead of int
Fix missing indexerApi import in snatchSelection.mako
> Snatch fix

- views/config_subtitles.mako
> Fix error in config_subtitles.mako

- medusa/__main__.py
Fixes https://github.com/pymedusa/Medusa/issues/1620
> Fix pymedusa/Medusa/issues/1620

- medusa/post_processor.py
> Fixed occasionally wrong subtitles renaming. Fixes #1619

- medusa/notifiers/plex.py
> Fix pymedusa/Medusa/issues/1623

- views/IRC.mako
> Fix error in IRC.mako

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Fix TvChaosUK rule when both format and video_codec conflicts.

- medusa/providers/generic_provider.py
- medusa/providers/nzb/binsearch.py
- medusa/providers/nzb/womble.py
- medusa/providers/torrent/json/hdbits.py
- medusa/providers/torrent/rss/nyaatorrents.py
- medusa/providers/torrent/rss/rsstorrent.py
- medusa/providers/torrent/rss/shazbat.py
- medusa/search/core.py
- medusa/search/queue.py
- medusa/tv_cache.py
- tests/legacy/feedparser_tests.py
> Cleanup tv_cache.py + final flake

- medusa/providers/torrent/xml/bitsnoop.py
> Avoids url redirects

- medusa/providers/torrent/html/gftracker.py
> Add season pack search support for GFT

- medusa/__main__.py
- medusa/failed_history.py
Disable failed history trim on start (it's not like the file will suddenly be good in 30 days)
Improve failed history trim (allow for variable age trimming of failed history)
> Failed history

- medusa/__main__.py
- medusa/classes.py
- medusa/clients/download_station_client.py
- medusa/failed_history.py
- medusa/metadata/kodi_12plus.py
- medusa/metadata/mede8er.py
- medusa/metadata/media_browser.py
- medusa/metadata/tivo.py
- medusa/metadata/wdtv.py
- medusa/providers/nzb/womble.py
- medusa/server/api/v1/core.py
- medusa/server/core.py
- medusa/show_queue.py
- medusa/tv.py
- pytest.ini
- tests/legacy/ssl_sni_tests.py
- tests/report_guessit.py
- tests/test_guessit.py
- tests/test_subtitles.py
> flake8 fixes

- medusa/failed_history.py
- medusa/history.py
- medusa/post_processor.py
- medusa/search/core.py
- medusa/search/queue.py
- medusa/server/web/home/handler.py
> Fix log snatch AttributeError

- medusa/post_processor.py
> Fix subtitles always being associated. Fixes #1642

- medusa/providers/torrent/html/gftracker.py
- pytest.ini
> Fix GFTracker using all sections for season packs

- lib/pytimeparse/timeparse.py
> Upgrade pytimeparse to 1.1.5

- medusa/version_checker.py
> Trying to fix dll update

- medusa/providers/torrent/html/transmitthenet.py
> Fix TtN pubdate

- .gitignore
- lib/guessit/rules/common/comparators.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/film.py
- lib/guessit/rules/properties/format.py
- lib/guessit/rules/properties/other.py
- lib/guessit/rules/properties/release_group.py
- lib/guessit/rules/properties/video_codec.py
- lib/guessit/rules/properties/website.py
- lib/guessit/test/episodes.yml
- lib/guessit/test/rules/episodes.yml
- lib/guessit/test/rules/format.yml
- lib/guessit/test/rules/other.yml
- medusa/name_parser/rules/properties.py
- medusa/name_parser/rules/rules.py
- pytest.ini
- tests/test_guessit.yml
> Updating guessit to d1dce4d98273049cfd1815f03dfdb2214d7431a0

- medusa/post_processor.py
Fix: https://github.com/pymedusa/Medusa/issues/1654
> Change log message to be a warning and more descriptive

- medusa/indexers/indexer_config.py
- medusa/server/api/v2/show.py
- medusa/tv.py
> Fixing indexer mapping in rest api v2

- medusa/notifiers/plex.py
- medusa/tv.py
> Fix codacy issues

- medusa/tv.py
Fixes:
Duplicate import time
I201 Missing newline before sections or imports
Line too long
Force not used in subtitles
Missing AND in SQL
Too broad exception
> Minor improvement/fixes

- medusa/helpers.py
> Add complementary log message

- medusa/post_processor.py
@ratoaq2 why pycharm didn't showed this usage?
> Fix pymedusa/Medusa/issues/1677

- medusa/generic_queue.py
- medusa/providers/nzb/newznab.py
- medusa/search/backlog.py
- medusa/search/queue.py
> Fix instance attribute defined outside __init_

- medusa/clients/download_station_client.py
> Fix parameter 'msg' unfilled

- views/schedule.mako
> Fix paused shows not hidden in schedule

- medusa/providers/torrent/html/tvchaosuk.py
> Fix when titles get cut on tvchaosuk

- medusa/providers/torrent/html/tvchaosuk.py
> Fix TVCUK when there are no results

- medusa/providers/torrent/html/limetorrents.py
> Fix https://github.com/pymedusa/Medusa/issues/1675

- medusa/providers/torrent/json/btn.py
- pytest.ini
> Fix BTN search params logging

- medusa/common.py
- medusa/post_processor.py
- medusa/search/backlog.py
- medusa/search/core.py
- medusa/server/web/config/general.py
- medusa/server/web/home/add_shows.py
- medusa/server/web/home/handler.py
- medusa/server/web/manage/handler.py
- medusa/tv.py
- static/js/add-show-options.js
- static/js/add-shows/init.js
- static/js/quality-chooser.js
- views/displayShow.mako
- views/editShow.mako
- views/inc_addShowOptions.mako
- views/inc_qualityChooser.mako
- views/manage_massEdit.mako
> Create a method to quality check (keep current behaviour)

- medusa/providers/torrent/html/hdtorrents.py
- medusa/providers/torrent/html/torrentbytes.py
- medusa/providers/torrent/json/hd4free.py
- medusa/providers/torrent/json/rarbg.py
> Fix TorrentByte size parsing, improve date parsing, lint

- views/inc_qualityChooser.mako
> Fixing again mako

- medusa/common.py
> Use "Medusa" as user agent

- medusa/indexers/indexer_config.py
- medusa/scene_exceptions.py
> Fix custom exceptions, replace xem_origin with identifier.

- medusa/app.py
- views/config_notifications.mako
> Fix Pushover URLs

- medusa/logger.py
- medusa/name_parser/guessit_parser.py
- medusa/name_parser/parser.py
- tests/test_guessit.py
> Minor minor logging improvements.

- lib/guessit/rules/__init__.py
- lib/guessit/rules/common/date.py
- lib/guessit/rules/processors.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/other.py
- lib/guessit/rules/properties/streaming_service.py
- lib/guessit/test/episodes.yml
- lib/guessit/test/rules/other.yml
- lib/guessit/test/various.yml
- lib/rebulk/__version__.py
- lib/rebulk/chain.py
- lib/rebulk/match.py
- lib/rebulk/pattern.py
- lib/rebulk/rebulk.py
- lib/rebulk/test/test_chain.py
- lib/rebulk/test/test_pattern.py
- lib/rebulk/utils.py
- medusa/name_parser/rules/__init__.py
- medusa/name_parser/rules/properties.py
- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Guessit and rebulk update

- medusa/server/api/v2/asset.py
- medusa/server/api/v2/config.py
- medusa/tv.py
- tests/apiv2/test_config.py
@ratoaq2 this moves `?detailed=true` to only contain the seasons.
> Fix show detailed & posterThumb

- medusa/helpers.py
- medusa/indexers/__init__.py
- medusa/indexers/indexer_config.py
- medusa/server/api/v1/core.py
This fixes the api v1 shows and show calls.
* Removed the module import for indexers from init. As that is used nowhere. Think it's legacy, and can cause circular imports.
I started this with the intention to fix the int casts on imdb ids. But ended with removing allot of crappy code.
> Removed mapIndexersToShow, and replaced it with call to the show objects externals.

- medusa/providers/torrent/json/torrentday.py
> Fix pymedusa/Medusa/issues/1043

- medusa/common.py
- medusa/post_processor.py
- medusa/search/core.py
- medusa/tv.py
- tests/test_quality_replace.py
The goal of this PR is to improve the `want_episode` method to use new method `should_replace`
The `should_replace` method returns a tuple of (True|False, reason_of_true|false)
Added some more tests
Im also running this PR in my branch. Passed all pytests so Im confidant is all ok
> More quality improvements

- medusa/common.py
- medusa/post_processor.py
- medusa/search/core.py
- medusa/tv.py
- tests/test_quality_replace.py
I wrote the method so it could be easy do understand and to "read"
@pymedusa/developers i will run this on my branch for a few days
would be nice if someone could review this.
> Create a method to check if we should replace existing quality

- medusa/db.py
@p0psicles to find sql issues like from ripper1967 user
https://github.com/pymedusa/Medusa/issues/1716
> Log query on DB error. Don't need to enable dbdebug

- medusa/sab.py
> Fix https://github.com/pymedusa/Medusa/issues/1185

- medusa/providers/torrent/json/btn.py
> Fix pymedusa/Medusa/issues/1701

- medusa/common.py
- medusa/search/backlog.py
- medusa/search/core.py
- medusa/server/web/manage/handler.py
- medusa/tv.py
- tests/test_quality_replace.py
- views/manage_backlogOverview.mako
@pymedusa/developers can you try and give feedback please?
> Fix backlogOverview. Use new quality method

- medusa/indexers/tmdb/tmdb.py
- medusa/metadata/generic.py
- medusa/trakt_checker.py
- setup.py
@p0psicles @ratoaq2 why have to be this way in the first commit?
> Several fixes

- medusa/helpers.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/torrent_provider.py
- pytest.ini
- tests/legacy/providers/generic_provider_tests.py
> Fixed missing return in download_file, improve handling

- medusa/providers/torrent/html/morethantv.py
> Fix MTV when season pack doesn't have filelist_path

- medusa/helpers.py
- medusa/providers/torrent/torrent_provider.py
> Remove premature filename check in download_file

- lib/imdb/__init__.py
- lib/imdb/parser/http/movieParser.py
> Update imdbpy to version 5.1, fixes plot parser and more

- medusa/indexers/tvdbv2/tvdbv2_api.py
@p0psicles need you to check last commit
> Fix signature and use same param description

- medusa/__init__.py
- medusa/__main__.py
- medusa/init/__init__.py
- medusa/init/logconfig.py
- medusa/logger.py
> Early logging configuration

- medusa/init/filesystem.py
- tests/__init__.py
@ratoaq2 code. thanks!
Fixes https://github.com/pymedusa/Medusa/issues/1713
> Fix pymedusa/Medusa/issues/1713

- medusa/common.py
- medusa/search/core.py
I'm testing this in my branch. But its safe.
> More quality improvements v3

- medusa/__main__.py
- medusa/event_queue.py
> Minor shutdown refactoring

- medusa/common.py
- tests/test_quality_replace.py
@labrys 
i need to fix any test that fails. i web commited
> Snatch only one allowed

- medusa/failed_history.py
- medusa/search/queue.py
- medusa/server/web/manage/handler.py
@medariox please confirm it fixed. Mine worked as my gist in chat
> Fix failed not working when manually setting as failed in displayShow

- medusa/scene_numbering.py
> Add aditional log line to xem update

- lib/traktor/trakt.py
- medusa/notifiers/trakt.py
- medusa/server/web/home/add_shows.py
- medusa/show/recommendations/trakt.py
Fixed refresh of token when expired.
> Fixed refresh of trakt token.

- medusa/server/web/manage/handler.py
- medusa/subtitles.py
Postpone only if status is SNATCHED.
@nicoleoca in your case the 720p HDTV will need to manually be deleted
> Fixes pymedusa/Medusa/issues/1752

- medusa/name_parser/rules/rules.py
- tests/test_guessit.py
- tests/test_guessit.yml
> Adding more anime scenarios to guessit

- medusa/databases/main_db.py
> Fix log and fix sequence

- medusa/providers/nzb/newznab.py
Fixes https://github.com/pymedusa/Medusa/issues/1759
@Thraxis
> Fix pymedusa/Medusa/issues/1759

- medusa/helpers.py
- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvmaze/tvmaze_api.py
* Only supported by tvmaze & tmdb api. As the new v2 tvdb api, doesn't support getting the thumbnail url's in batch. And we are not going to do one api call per episode.
> Fix creation of tmb and jpg thumbnail files for episodes.

- medusa/process_tv.py
> Fix pymedusa/Medusa/issues/1790

- lib/pytimeparse/timeparse.py
> Pytimeparse

- tests/legacy/search_tests.py
finally found the issue!
just need to run: python search_tests.py
> Fix search_tests.py

- medusa/providers/torrent/html/hdspace.py
Fixes: https://github.com/pymedusa/Medusa/issues/1410#issuecomment-267423914
> Quick fix HD-Space

- medusa/indexers/tvmaze/tvmaze_api.py
@p0psicles do agree with my fix?
Fixes https://github.com/pymedusa/Medusa/issues/1801
> Fix pymedusa/Medusa/issues/1801

- static/css/style.css
- views/viewlogs.mako
> Fixed log view.

- views/home.mako
> Fix home.mako syntax error

- medusa/server/web/home/handler.py
- static/css/style.css
- views/addShows_recommended.mako
- views/addShows_trendingShows.mako
- views/displayShow.mako
- views/errorlogs.mako
- views/history.mako
- views/home.mako
- views/layouts/main.mako
- views/partials/showheader.mako
- views/partials/submenu.mako
- views/schedule.mako
- views/snatchSelection.mako
- views/viewlogs.mako
* Small, banner and simple filter controls, now properly allign right.
> Responsive changes wave 2, mostly fixes.

- views/home.mako
> Fix home.mako syntax error (#2)

- medusa/server/web/core/base.py
- static/js/home/index.js
- static/js/schedule/index.js
- views/partials/home/banner.mako
- views/partials/home/poster.mako
- views/partials/home/simple.mako
- views/partials/home/small.mako
- views/schedule.mako
> Add indexer column to home

- medusa/clients/generic.py
> Join invalid torrent log messages

- medusa/post_processor.py
Log should_replace return message to help debug possible issues after release
> Debug PP should_replace

- medusa/server/web/core/base.py
- medusa/server/web/core/history.py
- medusa/server/web/home/handler.py
- static/css/style.css
- views/home.mako
- views/partials/showheader.mako
Vertical aligned (chrome):
Not aligned (ff):
> Responsive design fixes, wave 3

- medusa/name_parser/parser.py
> Use OrderedDict instead of Dict in name parser

- views/config_postProcessing.mako
- views/home_postprocess.mako
> Fixed postProcess view.

- lib/subliminal/providers/itasa.py
> Fix score detection for itasa subtitle provider

- lib/cfscrape/__init__.py
> Update cfscrape to 1.6.8

- medusa/providers/torrent/torrent_provider.py
> Keep original order for _custom_trackers

- medusa/server/web/home/handler.py
Specials have `0` as the season
> Fix https://github.com/pymedusa/Medusa/issues/1515

- medusa/providers/torrent/xml/bitsnoop.py
Fix https://github.com/pymedusa/Medusa/issues/1410#issuecomment-269413532
@OmgImAlexis
> Fix BitSnoop

- medusa/indexers/tvmaze/tvmaze_api.py
> Switched to using the image -> medium as poster for tvmaze shows.

- medusa/search/core.py
> Fix Error: 'TVEpisode' object has no attribute 'formatted_file_name'

- medusa/__main__.py
- medusa/providers/__init__.py
- medusa/providers/nzb/__init__.py
- medusa/providers/torrent/__init__.py
- medusa/providers/torrent/html/__init__.py
- medusa/providers/torrent/html/elitetorrent.py
- medusa/providers/torrent/html/newpct.py
- medusa/providers/torrent/json/__init__.py
- medusa/providers/torrent/rss/__init__.py
- medusa/providers/torrent/xml/__init__.py
- medusa/server/web/config/providers.py
- pytest.ini
Including long lines
@ratoaq2 i did some changes to imports. See if is ok. i runned a manual search and no issues with providers.
> Final flake for providers

- views/manage_massEdit.mako
@p0psicles you were right. I forgot to double check
the code inside the script block can't be used in the content block.
@OmgImAlexis fixed
> Fix NameError: 'allowed_qualities' is not defined

- static/js/home/index.js
- views/partials/home/banner.mako
- views/partials/home/poster.mako
- views/partials/home/simple.mako
- views/partials/home/small.mako
> Add XEM column/icon in home

- medusa/post_processor.py
> Fix _is_priority checking conditions it shouldn't

- lib/jwt/__init__.py
- lib/jwt/__main__.py
- lib/jwt/algorithms.py
- lib/jwt/api_jws.py
- lib/jwt/api_jwt.py
- lib/jwt/compat.py
- lib/jwt/exceptions.py
- lib/jwt/utils.py
This adds the JWT Python library which we need for the new API.
> add jwt lib

- static/js/history/index.js
@duramato apparently this was way more broken than you said
> fix history search

- static/js/add-shows/add-existing-show.js
- static/js/common/init.js
- static/js/config/init.js
- static/js/history/index.js
- static/js/home/display-show.js
- static/js/manage/failed-downloads.js
- static/js/mass-update.js
- static/js/test-rename.js
This "should" fix Edge being stupid and ignoring the base href that we use for relative links.
Ref: https://github.com/pymedusa/Medusa/issues/1652
That "should" also fix https://github.com/pymedusa/Medusa/issues/1574
> fix Edge being stupid with base href

- medusa/server/api/v1/core.py
> Fixed searching for shows using apiv1.

- medusa/post_processor.py
> Fix episodes wrongfully parsed as air-by-date

- static/js/core.js
- static/js/history/index.js
- static/js/schedule/index.js
Fixes the tablesorter for the schedule and history page.
Schedule
* Fixed ajax ep search spinner.
History
* Fixed sorter in detailed view.
Fixes #1942
> Fixed tablesorter initialization for pages history and schedule.

- medusa/providers/torrent/html/hounddawgs.py
> Fix HoundDawgs download url

- medusa/tv.py
> Fix episode nfo, after heavy refactor of the metadata provider code.

- medusa/post_processor.py
- tests/test_should_process.py
Re-sending
@p0psicles i did some readings and its ok to return status like this.
Anyway this may be removed soon with new quality system.
At least now we have tests and better logging.
> Log should_process reason and add test

- medusa/app.py
- medusa/helpers.py
- medusa/indexers/indexer_config.py
- medusa/network_timezones.py
- medusa/server/web/core/calendar.py
@OmgImAlexis, here you go.,
Can you double check I got everything?
> Made cdn.pymedusa.com configurable in app.

- medusa/common.py
- medusa/post_processor.py
- tests/test_quality_replace.py
- tests/test_should_process.py
- tests/test_should_replace.py
- tests/test_should_search.py
> Adds better docs strings to should_replace and should_search methods

- medusa/server/web/manage/handler.py
> Fix status check in subtitleMissedPP

- medusa/scene_numbering.py
- views/partials/home/banner.mako
- views/partials/home/poster.mako
- views/partials/home/simple.mako
- views/partials/home/small.mako
@p0psicles @duramato 
sorry about that @ripper1967
> Don't refresh xem data when loading home page even data is outdated

- medusa/helpers.py
> Don't complain about broken providers if there are no broken ones

- medusa/helpers.py
- medusa/providers/torrent/json/btn.py
- Fixes BTN search by name
- Fixes Scene names with colons, ie: `MythBusters: The Search` released as `MythBusters-The Search` by the Scene
> Fix BTN search

- medusa/tv.py
> Fix season update leftover bug, when trying to delete a show.

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
Fixed guessit exception reported in guessit repo
https://github.com/guessit-io/guessit/issues/397
> Fix guessit exception due to tv chaos workaround

- medusa/providers/torrent/json/t411.py
Search term should be URL-encoded
Use params for search
Fix no results returned (thanks to @fernandog #1992)
Fixes: #1985
> Search term should be URL-encoded params for search

- medusa/tv.py
> Shouldn't be a warning.

- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/indexers/tvmaze/tvmaze_api.py
> Fix indexers log object init on each log call.

- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/name_parser/parser.py
- medusa/show_updater.py
> Replaced warn with warning, as warn is deprecated from python 3.3.

- medusa/databases/main_db.py
> Fix main sanity check not running update_old_propers DUH!

- medusa/clients/transmission_client.py
- medusa/post_processor.py
- views/config_search.mako
Fixes https://github.com/pymedusa/Medusa/issues/2045
> Fix incorrect grammar in log.

- medusa/name_parser/rules/rules.py
> Fix for #1850

- lib/guessit/rules/common/comparators.py
- lib/guessit/rules/processors.py
- lib/guessit/rules/properties/episode_title.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/website.py
- lib/guessit/test/episodes.yml
- medusa/name_parser/rules/rules.py
Updating guessit with fixes for guessit PRs: #402, #403, #404, #405
> Guessit fixes from latest PRs

- medusa/helper/common.py
- medusa/search/manual.py
- static/js/common/init.js
- static/js/home/snatch-selection.js
- views/manage_subtitleMissedPP.mako
- views/partials/home/banner.mako
- views/snatchSelection.mako
won't touch pubdate now as is undefined how we will handle the naive/aware pubdates from providers
> Relative time in manual search updated date

- medusa/server/web/home/add_shows.py
- medusa/server/web/home/handler.py
- views/addShows_newShow.mako
- views/editShow.mako
> Catch and handle IndexerException, when switching languages.

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
Thanks @IDerr for reporting it -> https://github.com/guessit-io/guessit/issues/406
Btw, this is a medusa issue, not a guessit issue. These kind of issues you should initially report it here. If we realize that's indeed a guessit problem, then we can instruct to open an issue there.
> Fix for issue https://github.com/guessit-io/guessit/issues/406

- medusa/server/web/home/handler.py
> Fix do_update referenced before assignment.

- medusa/helpers.py
- medusa/notifiers/boxcar2.py
- medusa/tv.py
- pytest.ini
BTW the helper method already checks if is_dir so its **just a logging issue**
but as method expects a directory, i will only pass directorty
Fixes #2036
> fix show-refresh tries to cleanup empty "files" instead of just folders

- medusa/name_parser/parser.py
> Improve NameParserCache logic. Try to fix #2044, #2035

- medusa/__main__.py
- medusa/server/web/config/subtitles.py
- views/config_subtitles.mako
@ratoaq2 as you requested some time ago
```
2017-01-27 13:31:03 DEBUG    MAIN :: [de0be9e] Removing subtitles cache file: /home/osmc/Medusa/cache/subliminal.dbm
2017-01-27 13:31:03 DEBUG    MAIN :: [de0be9e] Removing subtitles cache file: /home/osmc/Medusa/cache/application.dbm
```
> Add option to erase subtitles cache file on next boot

- static/js/home/display-show.js
- static/js/home/snatch-selection.js
- views/partials/showheader.mako
- [x ] PR is based on the DEVELOP branch
- [x ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
> Fixes Right horizontal space in displayShow

- medusa/post_processor.py
Not needed anymore since the guessit fixes.
> Remove folder_path from _find_info()

- medusa/name_cache.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/html/animetorrents.py
- medusa/providers/torrent/json/btn.py
- medusa/scene_exceptions.py
- medusa/server/web/home/handler.py
- medusa/show_name_helpers.py
- medusa/tv.py
- tests/legacy/scene_helpers_tests.py
> Fix scene_exceptions usage for shows added through tvmaze or tmdb.

- medusa/tv.py
> Fix status log line

- medusa/post_processor.py
Fixes https://github.com/pymedusa/Medusa/issues/2086
> Fix wrong log

- medusa/common.py
- medusa/search/backlog.py
- medusa/search/core.py
- medusa/tv.py
- tests/test_should_search.py
Tests are still good
@OmgImAlexis
> Log should_search reason. Explicity rules to better debug

- static/js/home/edit-show.js
- views/inc_qualityChooser.mako
> add js for quality selector explanation

- medusa/server/web/home/handler.py
Fix adding single scene exception
Fix removing last scene exception
> Fix scene exceptions

- medusa/server/web/home/handler.py
> Fix error message when changing show language to None

- medusa/tv.py
- tests/test_should_refresh.py
> Fix local episode file not detected when status is on snatched

- views/config.mako
> Fix missing slash in config.mako

- medusa/post_processor.py
- tests/conftest.py
- tests/test_postprocessor_find_info.py
- tests/test_postprocessor_parse_info.py
As @ratoaq2 reported:
https://gist.github.com/ratoaq2/94042449045a9fd6f410fb92fc3581d2
As expected first commit fails as GoT episode expected is [10] but got []
Second commit passed in all tests
> Fix PP season pack with nzbtomedia

- medusa/post_processor.py
> Make name_list consistent with the one in _parse_info()

- medusa/name_cache.py
> Fix dictionary changed size during iteration

- medusa/post_processor.py
@medariox ideas to the comment above the name_list ?
> PP: Define name_list once

- medusa/server/web/home/handler.py
> Fix editing scene exceptions

- static/js/home/edit-show.js
- static/js/quality-chooser.js
@OmgImAlexis fixed
Why we have js\edit-show.js and home\edit-show.js?
ping @Thraxis too because of the fanart background in those files
Can't they be unified?
Fixes https://github.com/pymedusa/Medusa/issues/2118
> Fixes dynamic quality explanation not working when adding shows

- medusa/post_processor.py
- medusa/process_tv.py
Improve a lot of duplicate code and:
1) Commit 1 tested ok ~~needs more testing~~: Fixes when method is hardlink but it should move the media (It already works for not postpone)
2) Commit 2 tested ok: Fixes when medusa download a subtitle and when I remove torrent with data, folder is not deleted because of subtitles (that wasn't part of the torrent)
> Postpone: Fixes when method is hardlink but it should move the media

- static/js/quality-chooser.js
- views/inc_qualityChooser.mako
> Add dynamic quality explanation to quality presets

- static/js/manage/backlog-overview.js
> backlog force search use ajax

- medusa/server/web/home/handler.py
> Fix KeyError: u'status'

- static/js/ajax-episode-search.js
https://regex101.com/r/BIStGf/1
@OmgImAlexis
> Also support SNATCHED PROPER in status regex

- medusa/search/backlog.py
- medusa/search/core.py
> Should_search reasons for backlog and daily as DEBUG

- medusa/process_tv.py
>  Improve extension check and log unwanted files if we are not going to remove then

- medusa/search/queue.py
- medusa/tv/cache.py
> Fix propers split in certain situations

- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvmaze/tvmaze_api.py
- medusa/show_updater.py
You can easily test this by modifying your lastUpdate in cache.db for the indexer you'd like to test.
> Feature/fix tvmaze & tmdb show update

- medusa/server/web/home/handler.py
Fixes https://github.com/pymedusa/Medusa/issues/1565
> Catch trakt validate_account error

- medusa/server/api/v2/show.py
- medusa/tv/series.py
- static/js/quality-chooser.js
@OmgImAlexis @duramato
Same:
Increase:
Decrease:
Related to: https://github.com/pymedusa/Medusa/issues/2091
> Improve backlogged episodes count

- static/js/common/init.js
- views/history.mako
- views/home.mako
- views/schedule.mako
- views/status.mako
- views/viewlogs.mako
Fixes https://github.com/pymedusa/Medusa/issues/2169
ping @Thraxis
> Can't show fanart if no shows added

- views/displayShow.mako
- views/snatchSelection.mako
> Fix CSS issue on snatchSelection and displayShow

- static/js/home/snatch-selection.js
This should fix the text / spinner not working after a few searches.
While the tableSorter is initializing the text will disappear for but
will come back when the sort and filter options are available.
+ Fix for #2165
> Fix disappearing spinner on search

- static/css/style.css
- views/history.mako
- views/schedule.mako
+ Fixes #2159 and Partial Fix for #2084
> Fix History and Schedule Mobile View

- medusa/databases/main_db.py
- medusa/tv/series.py
- static/js/home/display-show.js
- views/partials/showheader.mako
Now info can be displayed in displayShow
TODO:
ping @wimpyrbx and @Thraxis
> Add show plot to imdb_info table

- medusa/server/api/v2/show.py
- medusa/server/web/home/handler.py
- medusa/tv/series.py
- static/js/quality-chooser.js
- views/inc_qualityChooser.mako
As discussed in here: https://github.com/pymedusa/Medusa/issues/2091
@OmgImAlexis 
about layout, i think we can improve but im not good with it =)
------------------------------------------------
> Convert final quality episodes with DOWNLOADED status to ARCHIVED

- medusa/tv/series.py
> Prioritize plot to plot_outline

- medusa/network_timezones.py
Fixes https://github.com/pymedusa/Medusa/issues/1716
> Fix OperationalError: too many SQL variables

- medusa/providers/nzb/newznab.py
> Log when no returned results from newznab

- static/css/dark.css
- static/css/style.css
> fix genre tags styles to pad same on right as on left side.

- views/partials/seasonEpisode.mako
- views/partials/showheader.mako
> SnatchSelection improve:  better header

- views/partials/showheader.mako
Fixes https://github.com/pymedusa/Medusa/issues/2185
@wimpyrbx don't use str in mako
also mind tabs. Use spaces
> Fix plot error: UnicodeEncodeError: 'charmap' codec can't encode character

- views/editShow.mako
> Remove blank option for language from editShow

- medusa/providers/torrent/html/bithdtv.py
Fixes https://github.com/pymedusa/Medusa/issues/2043
@duramato
> Fix list index out of range

- medusa/databases/main_db.py
Fixed https://github.com/pymedusa/Medusa/issues/2082
> Don't update propers over and over

- static/css/style.css
- views/manage_backlogOverview.mako
> fix pill overlap on backlogOverview

- readme.md
> New logo in readme.md

- static/css/dark.css
- static/css/style.css
- static/js/home/display-show.js
- views/partials/showheader.mako
This is what things look like when all the current UI changes are merged with this PR
> give the checkboxControls a full width background

- static/css/dark.css
+ changes hover to a darker grey color
+ darkens nav bar and sub-menu
> will change the dark theme to fix button hover color

- views/apiBuilder.mako
- views/layouts/main.mako
+ changes mobile address bar color for dark theme
+ left the if statement even though both are same color now in case this
changes
> will fix the mobile address bar color being blue

- views/partials/showheader.mako
> just a small fix to center items for episode selection in the new div.

- static/js/quality-chooser.js
> Fix backlogged episode count grammar

- medusa/providers/torrent/json/btn.py
> Fix BTN when air by date but show is indexed with SxxExx

- medusa/tv/series.py
Log current episode status before archive (compound)
Im trying to debug a nasty and rare issue while show update.
Happens like once each 1-2 months to me
> Log current episode status before archive (compound)

- views/partials/showheader.mako
> fix spacing between showheader and show table.

- medusa/server/api/v2/config.py
- static/js/config/index.js
- views/config_general.mako
I liked this stuff lol
@OmgImAlexis
> Auto refresh page after change theme

- medusa/name_parser/parser.py
> Fix air-by-date shows with same day special

- medusa/name_cache.py
Internal name cache for Legion set to: [[u'show']]
to
Internal name cache for Legion set to: [u'show']
> Fix name cache log

- static/js/common/init.js
- static/js/config-providers.js
- static/js/core.js
- static/js/history/index.js
- static/js/home/display-show.js
- static/js/home/index.js
- static/js/home/snatch-selection.js
- static/js/quality-chooser.js
- static/js/schedule/index.js
Fixes problems in the javascript files
> will fix several javascript lint errors

- static/js/mass-edit.js
Fixes https://github.com/pymedusa/Medusa/issues/2229
@OmgImAlexis
> Fix editing root dir in mass update, redirects to default home page

- static/js/common/init.js
> will fix broken highlight code and move it into the init function

- lib/pathlib2.py
- lib/rarfile.py
- lib/scandir.py
- medusa/post_processor.py
> Use smart rar_basename() instead of list comprehensions

- .gitattributes
@medariox @wimpyrbx can this please be merged.
> force LF line endings

- medusa/exception_handler.py
- medusa/post_processor.py
> Fix is_rarfile() using a directory

- medusa/post_processor.py
TODO:
UPDATE: will add pytest in another PR. too much complicated
> Create a new method rename_associated_files

- medusa/show_queue.py
Catch IndexerShowNotFoundInLanguage while adding show
Fixes https://github.com/pymedusa/Medusa/issues/2206
ping @p0psicles
> Catch IndexerShowNotFoundInLanguage while adding show

- static/js/quality-chooser.js
- views/inc_qualityChooser.mako
@p0psicles 
it will open backlog Overview in a new tab:
it also fixes showing the archive button in decrease
> Improve archive text

- medusa/providers/nzb/newznab.py
> No results from nzb proviger log message as DEBUG

- views/partials/home/simple.mako
> Add responsive home page, simple layout

- static/js/home/index.js
- static/js/manage/backlog-overview.js
- static/js/quality-chooser.js
Fix yarn issues
@OmgImAlexis
static/js/common/init.js:210:29
✖  210:29  Unexpected trailing comma.                                                     comma-dangle
static/js/manage/backlog-overview.js:68:26
✖   68:26  Unexpected space before function parentheses.                                  space-before-function-paren
✖   68:28  The catch parameter should be named err.                                       unicorn/catch-error-name
static/js/home/index.js:352:9
✖  352:9   backendPieces is not defined.                                                  no-undef
✖  353:9   backendDirs is not defined.                                                    no-undef
✖  353:23  backendPieces is not defined.                                                  no-undef
✖  355:9   backendDirs is not …
> Fix again JS lint issues

- package.json
- static/css/country-flags.css
- static/css/dark.css
- static/css/light.css
- static/css/style.css
> Lint css v2

- static/js/errorlogs/viewlogs.js
- views/viewlogs.mako
Fix inverted order in mobile when pulling right
and double row in my desktop
No one noticed this filter logs since 19 Dec 2016 ?! lol
> Fix viewlog objects not working and improve mobile view

- views/manage_backlogOverview.mako
Fixes https://github.com/pymedusa/Medusa/issues/2281
@thraxis
> Fix button and keys in two rows

- medusa/helpers/__init__.py
- medusa/helpers/externals.py
- medusa/helpers/quality.py
- medusa/server/api/v1/core.py
- medusa/show/coming_episodes.py
- medusa/show_queue.py
- medusa/tv/series.py
- pytest.ini
- tests/legacy/helper/quality_tests.py
> Convert helpers.py to a package

- lib/guessit/api.py
- lib/guessit/options.py
- lib/guessit/rules/common/words.py
- lib/guessit/rules/properties/audio_codec.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/format.py
- lib/guessit/rules/properties/language.py
- lib/guessit/rules/properties/other.py
- lib/guessit/rules/properties/release_group.py
- lib/guessit/rules/properties/screen_size.py
- lib/guessit/rules/properties/streaming_service.py
- lib/guessit/rules/properties/title.py
- lib/guessit/rules/properties/video_codec.py
- lib/guessit/test/episodes.yml
- lib/guessit/test/movies.yml
- lib/guessit/test/rules/audio_codec.yml
- lib/guessit/test/rules/episodes.yml
- lib/guessit/test/rules/format.yml
- lib/guessit/test/rules/other.yml
- lib/guessit/test/rules/video_codec.yml
- medusa/name_parser/guessit_parser.py
- medusa/name_parser/rules/__init__.py
- medusa/name_parser/rules/properties.py
- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
- Updating to lastest development guessit version and removed all customizations that are not needed anymore.
> Updating guessit and removing unneeded customizations

- medusa/server/web/home/handler.py
> will fix home page not loading due to no RootDirs defined

- medusa/search/queue.py
> Fix string format

- lib/imdbpie/imdbpie.py
- lib/imdbpie/objects.py
Fixes IMDB showing a LOT of logs in console
Fixes: https://github.com/pymedusa/Medusa/issues/2312
> Don't print IMDB data and response in console

- medusa/issue_submitter.py
Fixes: https://github.com/pymedusa/Medusa/issues/2309
ping @thraxis
> Fix error while submitting erros

- .travis.yml
- dredd_hook.py
- package.json
- static/js/manage/backlog-overview.js
- tox.ini
> add yarn cache & yarn js testing

- lib/tvdbapiv2/apis/search_api.py
- lib/tvdbapiv2/configuration.py
> Removed print from lib.

- medusa/post_processor.py
> Don't warn when looping in all rar files

- medusa/providers/torrent/rss/extratorrent.py
[Old domain has been shut down](https://torrentfreak.com/extratorrents-main-domain-name-shut-down-by-registrar-170302/)
> Change extratorrent to new domain

- medusa/tv/episode.py
- static/js/plot-tooltip.js
fixes https://github.com/pymedusa/Medusa/issues/2326
TODO:
> Fixes TypeError: isoformat() argument 1 must be char, not unicode

- medusa/providers/nzb/newznab.py
> Improved log for no results from NZB providers

- medusa/search/queue.py
> Fix missed log standardization

- lib/guessit/rules/properties/audio_codec.py
- lib/guessit/rules/properties/edition.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/other.py
- lib/guessit/test/episodes.yml
- lib/guessit/test/movies.yml
- lib/guessit/test/rules/episodes.yml
- lib/guessit/test/rules/other.yml
- medusa/name_parser/rules/properties.py
- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
- Removing more customizations
> Updating guessit to db8e3fc

- medusa/clients/torrent/transmission_client.py
Remove torrent and not just log it
Log ratio limit
Log stalled and unregistered torrents
Remove unneeded fields for Transmission POST
@duramato as we talked
> Remove torrent! Also log stalled and unregistered. Remove unneeded fields

- views/manage.mako
> Adds row highlighting to Manage page.

- medusa/tv/series.py
> Cast indexer runtime and imdb rating/votes to str.

- medusa/post_processor.py
User won't be able to submit as its not an error to submit. It will raise a PP exception
Fixes: https://github.com/pymedusa/Medusa/issues/2357 and https://github.com/pymedusa/Medusa/issues/2358 and https://github.com/pymedusa/Medusa/issues/2362
@duramato
> Raise PP error if we can't create folder

- medusa/server/web/manage/handler.py
@OmgImAlexis
Fixed https://github.com/pymedusa/Medusa/issues/2369
> Fix ugly Mass update notification

- medusa/helpers/externals.py
- medusa/name_parser/parser.py
- medusa/server/web/home/add_shows.py
- medusa/server/web/home/handler.py
- medusa/show_queue.py
- medusa/show_updater.py
Fixes view log auto refreshing when http body response has javascript code
@p0psicles 
```
2017-03-10 07:59:44 WARNING  SHOWUPDATER :: [c7533e5] Problem running show_updater, Indexer TVDBv2 seems to be having connectivity issues. While trying to look for show updates on show: The Blacklist: Redemption
2017-03-10 07:59:44 WARNING  SHOWUPDATER :: [c7533e5] could not authenticate to the indexer TheTvdb.com, with reason 'HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=)'.
2017-03-10 07:57:42 WARNING  SHOWUPDATER :: [c7533e5] Problem running show_updater, Indexer TVDBv2 seems to be having connectivity issues. While trying to look for show updates on show: Legion
2017-03-10 07:55:40 WARNING  SHOWUPDATER :: [c7533e5] Problem running show_updater, Indexer …
```
> Log only error message. Avoid logs body response. Fix {trace} not defined

- medusa/tv/episode.py
@duramato @ratoaq2
Fixes https://github.com/pymedusa/Medusa/issues/1980
> Catch requests error while send subtitle notifications

- medusa/indexers/tvdbv2/tvdbv2_api.py
Fixes https://github.com/pymedusa/Medusa/issues/2379
@p0psicles
> Fix log rendering as html

- medusa/providers/torrent/json/torrentday.py
> add more cats

- medusa/clients/torrent/deluge_client.py
- medusa/clients/torrent/deluged_client.py
- medusa/clients/torrent/transmission_client.py
- medusa/post_processor.py
- static/js/config/search.js
- views/config_search.mako
Both use deluge/deluged right?
@OmgImAlexis @ratoaq2
I didn't test this, wondering if you could. But code is pretty simple
Docs:
http://deluge.readthedocs.io/en/develop/core/rpc.html#deluge.__rpcapi.RpcApi.core.move_storage
> Adds "move torrent after PP"  feature to Deluge/Deluged

- medusa/providers/torrent/html/speedcd.py
Now we loop in all =)
@duramato
> Fix speed.cd changing login URL

- medusa/auto_post_processor.py
- medusa/process_tv.py
- medusa/server/api/v1/core.py
- medusa/server/web/home/post_process.py
- medusa/subtitles.py
- tests/conftest.py
- tests/test_process_tv.py
> Initial refactor of process_tv

- medusa/process_tv.py
@medariox 
If at least one video file was postponed, don't delete rar content
> Don't delete extracted media file it file was postponed

- medusa/helpers/__init__.py
- medusa/notifiers/__init__.py
- medusa/post_processor.py
- medusa/search/core.py
- medusa/tv/episode.py
Second round for https://github.com/pymedusa/Medusa/issues/1980
@labrys
> Catch Error in notifications and catch socket.error

- medusa/server/web/home/add_shows.py
- views/home_massAddTable.mako
Fixes https://github.com/pymedusa/Medusa/issues/2418
> Fix not using default indexer in mass add shows if no indexer found in metadata

- static/js/add-shows/new-show.js
Fixes https://github.com/pymedusa/Medusa/issues/2389
@OmgImAlexis
> Fix root dir not changing on show add

- medusa/post_processor.py
> Create function to move torrent to seeding folder feature.

- medusa/process_tv.py
> Fix multiple video files with nzb_name

- medusa/auto_post_processor.py
- medusa/subtitles.py
> Add missing process_method for ProcessResult class

- views/snatchSelection.mako
> Fix mako while manual searching

- medusa/tv/episode.py
- medusa/tv/series.py
@ratoaq2
Fixes saving shows to DB while in shutdown when nothing has really changed
> Add missing ignored_properties in Series and Episode object

- medusa/clients/torrent/generic.py
> Fix wrong log formatting

- medusa/history.py
- medusa/post_processor.py
- medusa/server/web/home/handler.py
- views/snatchSelection.mako
@medariox please test when you can
> Fix history size comparison and add size to downloaded status

- medusa/init/logconfig.py
- tests/test_logger.py
- TODO: Replace legacy log style in order to completely drop it
> Fixing new log style conflicting with legacy

- medusa/tv/series.py
Cherry-picked from plex fallback branch
Fixes https://github.com/pymedusa/Medusa/issues/2348
Ping @wimpyrbx
> Disable self.create_indexer() call as it's not needed in that method.

- medusa/databases/main_db.py
- views/partials/home/banner.mako
- views/partials/home/simple.mako
- views/partials/home/small.mako
@p0psicles 
```python
import urllib2
import json
status_list = []
for i in range(1, 10):
url = "http://api.tvmaze.com/shows?page={}".format(i)
content = urllib2.urlopen(url=url).read()
json_data = json.loads(content)
for i in json_data:
status = i.get('status', None)
if status:
status_list.append(str(status))
print set(status_list)
```
set(['In Development', 'Ended', 'Running', 'To Be Determined'])
> Add missing status from indexers

- medusa/server/web/home/handler.py
- medusa/server/web/manage/handler.py
- views/manage_massEdit.mako
Fix change show location not creating show folder when setting 'CREATE_MISSING_SHOW_DIRS' is set
> Fix change show location not creating show folder

- views/config_providers.mako
as discussed
I added the manual search provider feature. this was the concept and scope of it when i designed
@OmgImAlexis better?
> Improve "manual search provider" feature description

- medusa/server/web/home/handler.py
- medusa/server/web/manage/handler.py
Fixes https://github.com/pymedusa/Medusa/issues/2457
And some other fixes
> Fix mako error while mass editing

- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/indexers/tvmaze/tvmaze_api.py
- views/displayShow.mako
- views/manage.mako
Fixes https://github.com/pymedusa/Medusa/issues/2459
Add dvd_order indicator to mass update
Improve logs by removing the "[" and "["
Fix displayshow issue
>  Fix KeyError: u'dvd_season' while updating show in TVmaze with dvd_order enabled

- medusa/clients/nzb/sab.py
Fix sab api key not being initialized until a proper auth is added.
> Fix sab api-key

- medusa/search/core.py
Fix charmap cant encode character during notification.
> Fix encoding error in notifications

- medusa/trakt_checker.py
Fix return when it should continue.
Remove some missing year from title
> Some more trakt fixes

- medusa/metadata/generic.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/html/animebytes.py
- medusa/providers/torrent/html/animetorrents.py
- medusa/show_name_helpers.py
- medusa/tv/series.py
- tests/legacy/scene_helpers_tests.py
Just moved code to the series object
> Move all_possible_names to Series object

- medusa/search/proper.py
If user have few providers, it will use few items
If has lot of providers, it will have more items.
It uses PROPER_SEARCH_DAYS
> Store N days of already processed propers. Not 100 items

- medusa/server/api/v2/auth.py
It only get updated in github update
Fixes https://github.com/pymedusa/Medusa/issues/2471
@ratoaq2 @OmgImAlexis
> Fix TypeError: Unsupported header value None

- medusa/databases/main_db.py
- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvmaze/tvmaze_api.py
- medusa/tv/series.py
TODO: 
@p0psicles
```sql
SELECT indexer_id, count(mindexer) from indexer_mapping
GROUP by indexer_id
```
will return only one row per indexer_id. when it should return at least 4 like mine SS after i modified table:
> Fix all externals being lost in the INSERT - except the last one

- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/indexers/tvmaze/tvmaze_api.py
> Fix dvd order log message

- medusa/notifiers/kodi.py
> Clean up/kodi

- medusa/search/proper.py
> Fix AttributeError: 'dict' object has no attribute 'name'

- medusa/logger/adapters/style.py
Fixes brace message for dict logging.
> Fix BraceMessage dict logging

- medusa/__main__.py
- medusa/app.py
- medusa/config.py
- medusa/server/web/config/search.py
- views/config_search.mako
> Change propers frequency without restart

- medusa/process_tv.py
- medusa/server/web/home/post_process.py
- pytest.ini
- tests/test_process_tv.py
> Allow processing of single file or folder in process_tv

- medusa/providers/torrent/json/t411.py
Fixes https://github.com/pymedusa/Medusa/issues/2482
@duramato
> Change T411 api url

- medusa/helpers/__init__.py
> Fix log key error.

- views/testRename.mako
> Warn user that rename files will broken symlinks

- medusa/databases/main_db.py
Fixes episode being dirty because indexer u'1' != 1
TODO:
ping @p0psicles
> Convert indexer and indexer_id to INTEGER in tv_episodes table

- views/partials/showheader.mako
> Fix mako issue - AGAIN

- medusa/search/daily.py
> Fix show_id referenced before assignment

- medusa/subtitles.py
- medusa/tv/series.py
@ratoaq2 let it crash so we know what errors could happen and where
as you commented in here: https://github.com/pymedusa/Medusa/issues/1219#issuecomment-282399236
and here: https://github.com/pymedusa/Medusa/issues/1432
> Subtitle broad exception remove

- lib/traktor/__init__.py
- lib/traktor/exceptions.py
- lib/traktor/trakt.py
- medusa/helpers/externals.py
- medusa/notifiers/trakt.py
- medusa/trakt_checker.py
@p0psicles now I'm getting the correct message:
2017-03-27 18:05:10 DEBUG    TRAKTCHECKER :: [99dae51] Unable to retrieve shows from Trakt collection. Error: Trakt may have some issues and it's unavailable. Try again later please
> Improve Traktor exception handler

- medusa/search/proper.py
- Line too long
- Broad catch
- Referenced before assignement
> Minor Propers fix

- medusa/failed_history.py
- medusa/server/web/home/handler.py
Fixes: https://github.com/pymedusa/Medusa/issues/536 (finally!)
@duramato @OmgImAlexis 
Detailed:
Compact:
Logs:
```
2017-03-30 17:42:32 INFO     SEARCHQUEUE-RETRY-257248 :: [b4a8a54] Marking episode as bad: [Major Crimes - S05E19 - Intersection]
2017-03-30 17:42:32 DEBUG    SEARCHQUEUE-RETRY-257248 :: [b4a8a54] Failed release found for Major Crimes S05E19: Major_Crimes_S05E19_720p_HDTV_x264_FLEET
2017-03-30 17:42:32 INFO     SEARCHQUEUE-RETRY-257248 :: [b4a8a54] Reverting episode status for Major Crimes S05E19. Checking if we have previous status
2017-03-30 17:42:32 DEBUG    SEARCHQUEUE-RETRY-257248 :: [b4a8a54] Episode does not have a previous snatched status to revert. Setting it back to WANTED
```
> Fix showing the N/A quality when failed downloads

- medusa/providers/torrent/html/bithdtv.py
@duramato
Fixes https://github.com/pymedusa/Medusa/issues/1410
> Fix TypeError: 'NoneType' object has no attribute '__getitem__'

- medusa/metadata/helpers.py
> Standardize logging

- medusa/search/proper.py
Revert
fixes https://github.com/pymedusa/Medusa/issues/2557
> Fix AttributeError: 'ProperFinder' object has no attribute '_set_last_proper_search'

- medusa/search/core.py
- medusa/server/web/home/add_shows.py
> Fix spelling

- medusa/notifiers/kodi.py
> Fix missed positional indexes

- medusa/providers/torrent/json/rarbg.py
> Add missing tags to rarbg

- medusa/providers/generic_provider.py
- medusa/providers/torrent/rss/rsstorrent.py
- static/js/config-providers.js
- views/config_providers.mako
@labrys tested with: https://thepiratebay.org/rss/top100/208
as i said, first commit of `bugfix/add-custom-provider` works for me
Proof:
> More fix to RSS torrent

- medusa/providers/generic_provider.py
- medusa/providers/torrent/rss/rsstorrent.py
- static/js/config-providers.js
- views/config_providers.mako
> Fix add custom provider

- views/home_massAddTable.mako
@ripper1967 please try this. Worked for me
> Fix not showing correct default indexer

- medusa/providers/nzb/newznab.py
> Reduce huge min_time on newznab

- lib/adba/aniDBtvDBmaper.py
Fix https://github.com/pymedusa/Medusa/issues/1729
merged against @labrys branch
if he doesn't like, after that one gets merged i change my base branch to develop
> Fix AttributeError: 'NoneType' object has no attribute 'indexer'

- medusa/providers/torrent/json/rarbg.py
> Add additional trackers to rarbg's magnets like all other providers

- medusa/failed_history.py
Revert 909 from old repo as there is no reason to comment that
@medariox
> Uncommented the code that clear old snatches in FDH

- medusa/tv/series.py
> Fix logging without a level.

- medusa/post_processor.py
> Add file size comparison to post-processing logs

- medusa/server/web/home/handler.py
> Fix showing provider image when Release group is equal to provider name

- medusa/trakt_checker.py
- views/config_notifications.mako
@p0psicles your code was there but the button not.
Also i fixed the remove from collection as it wasn't using status like the add to collection
> Add missing button to force Trakt sync

- views/home.mako
- views/partials/home/banner.mako
- views/partials/home/small.mako
> Add missing indexer sorting for poster

- medusa/indexers/tvdbv2/tvdbv2_api.py
@p0psicles against your branch https://github.com/pymedusa/Medusa/pull/2375
> Fix double plex notifications and also log when plex is used

- medusa/tv/series.py
> Don't allow user submit error with EpisodeNotFoundException

- medusa/tv/series.py
> Fix error trying to add show: invalid literal for int() with base 10: ''

- medusa/tv/episode.py
- medusa/tv/series.py
> Fixing episode 404 for existing episodes

- medusa/trakt_checker.py
Create episode object because we need the actual status (from db)
Otherwise we will read default blank episode status (UNKNOWN)
This can happen if show never got updated
So self.episodes would be empty and the episode object in trakt would be None
> Trakt: Create episode object because we need the actual status (from db)

- views/config_notifications.mako
> Add Trakt notes

- medusa/helpers/__init__.py
Don't log as ERROR an OSError
Related to: https://github.com/pymedusa/Medusa/issues/2576
@ratoaq2
> Don't log as ERROR an OSError

- medusa/providers/torrent/html/limetorrents.py
> Fix limetorrents daily

- medusa/notifiers/libnotify.py
Fix: https://github.com/pymedusa/Medusa/issues/2610
> Don't log as ERROR: "cannot import name Notify"

- views/home.mako
> Fix not changing poster in home

- medusa/server/web/home/handler.py
- tox.ini
> Rebuild show name cache after scene exception change. Fixes #2645

- views/config_general.mako
Changing log level doesn't need restart as rato said
Fixes: https://github.com/pymedusa/Medusa/issues/2612
> Log privacy: 'disabled' option not available

- medusa/server/web/config/general.py
and in boot, converted to ARCHIVED (UNKNOWN)
`Found X shows with bare archived status, attempting automatic conversion`
very very old issue
> Fix episodes being converted to bare archived

- medusa/process_tv.py
> Change 'moving torrent' log message to debug

- medusa/post_processor.py
- medusa/process_tv.py
- medusa/server/web/manage/handler.py
- medusa/tv/episode.py
- medusa/tv/series.py
- tests/test_list_associated_files.py
- tox.ini
> Add associated files refiner

- medusa/server/web/home/handler.py
https://github.com/pymedusa/Medusa/issues/1432
@duramato
> Remove another broad exception for subtitles

- medusa/subtitles.py
Fixes https://github.com/pymedusa/Medusa/issues/2696
> Fix scaning/refining video in the _unpack folder causing MalformedMKVError

- medusa/server/core.py
- medusa/server/web/config/general.py
- views/config_general.mako
@medariox @OmgImAlexis 
also log the web root in the log
> Change web root in config general

- medusa/providers/torrent/html/animebytes.py
- tox.ini
> Fix AnimeBytes login and download

- medusa/helpers/__init__.py
> Fix incorrectly named placeholder

- medusa/providers/torrent/html/newpct.py
> Streamline newpct title processing

- medusa/providers/torrent/json/hdbits.py
> Rewrite HDBits

- medusa/helpers/__init__.py
Add missing exception
@p0psicles @duramato 
Fixes: https://github.com/pymedusa/Medusa/issues/2669
> Don't allow submit error when can't refresh show because of indexer issues

- medusa/logger/adapters/style.py
> Add stack to BraceMessage fallback

- medusa/providers/torrent/html/danishbits.py
> Fix logging for Danishbits provider. Fixes #2779

- views/home.mako
- views/status.mako
- views/viewlogs.mako
As reporte in IRC:
https://thepasteb.in/p/3lh7q1E0P3Mf1
Reproduce:
1) New medusa
2) Add show
3) While show is loading from indexer, keep refreshing home until error happens
4) After show is fully loaded from indexer (indexerid available) error is gone
If happens because app.showList has a show but that show doesn't have a indexer id yet
> Fix mako error when no shows in library

- medusa/indexers/tvdbv2/fallback.py
@duramato this should fix your issue.
> Add valid tvdb exceptions for which we don't want to fall back to plex.

- medusa/providers/torrent/html/limetorrents.py
That's what you get for 6 months old PRs that pass unit tests lol
How to reporduce? Search for`Marvels Agents of S H I E L D S04E21`
> Quick fix limetorrents pubdate "Yesterday - in TV shows"

- medusa/providers/torrent/html/bithdtv.py
- medusa/providers/torrent/html/cpasbien.py
- medusa/providers/torrent/html/gftracker.py
> Single quotify providers

- medusa/providers/torrent/json/rarbg.py
> Fix Rarbg 'BraceAdapter' object has no attribute 'DEBUG'. Fixes #2786

- medusa/providers/torrent/html/speedcd.py
> Fix speedcd

- medusa/providers/generic_provider.py
> Pass str (.message) in stead of object.

- medusa/clients/torrent/generic.py
- medusa/clients/torrent/utorrent_client.py
> Various fixes to uTorrent client. Fixes #2685

- medusa/providers/torrent/html/anidex.py
> Fix labels in AniDex provider. Fixes #2806

- CONTRIBUTING.md
> Update logging style (2). Replaces #2801

- views/editShow.mako
Form had the wrong field name
Fixes https://github.com/pymedusa/Medusa/issues/2810
@p0psicles
> Fix TypeError: editShow() got an unexpected keyword argument 'dvdorder'

- medusa/server/web/manage/handler.py
- medusa/subtitles.py
Same as https://github.com/pymedusa/Medusa/pull/2698 @medariox
> Check if folder is _unpack in missed subtitleMissedPP

- medusa/server/web/manage/handler.py
- static/js/manage/subtitle-missed-post-process.js
- views/manage_subtitleMissedPP.mako
Removes the lambda sorting in handler
> Sort in UI only and add row filter in subtitleMissedPP

- lib/guessit/__version__.py
- lib/guessit/options.py
- lib/guessit/rules/properties/country.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/language.py
- lib/guessit/test/episodes.yml
- lib/guessit/test/movies.yml
- lib/guessit/test/test_yml.py
Thanks to @ratoaq2 for the fix!
> Update guessit to 268167b

- medusa/providers/generic_provider.py
- medusa/providers/nzb/newznab.py
- medusa/providers/torrent/html/alpharatio.py
- medusa/providers/torrent/html/anidex.py
- medusa/providers/torrent/html/animetorrents.py
- medusa/providers/torrent/html/bithdtv.py
- medusa/providers/torrent/html/cpasbien.py
- medusa/providers/torrent/html/danishbits.py
- medusa/providers/torrent/html/gftracker.py
- medusa/providers/torrent/html/hdspace.py
- medusa/providers/torrent/html/hdtorrents.py
- medusa/providers/torrent/html/horriblesubs.py
- medusa/providers/torrent/html/hounddawgs.py
- medusa/providers/torrent/html/limetorrents.py
- medusa/providers/torrent/html/morethantv.py
- medusa/providers/torrent/html/nebulance.py
- medusa/providers/torrent/html/torrentbytes.py
- medusa/providers/torrent/html/torrentproject.py
- medusa/providers/torrent/json/hd4free.py
- medusa/providers/torrent/json/rarbg.py
- medusa/providers/torrent/json/torrentday.py
- medusa/providers/torrent/rss/extratorrent.py
- medusa/providers/torrent/xml/torrentz2.py
- tests/providers/__init__.py
- tests/providers/test_generic_provider.py
> Make parse_pubdate more generic

- medusa/providers/generic_provider.py
> Add pubdate to failed pubdate exception

- lib/guessit/rules/properties/audio_codec.py
- lib/guessit/rules/properties/container.py
- lib/guessit/rules/properties/episode_title.py
- lib/guessit/rules/properties/episodes.py
- lib/guessit/rules/properties/website.py
- lib/guessit/test/episodes.yml
- lib/guessit/test/movies.yml
- lib/guessit/test/rules/audio_codec.yml
- lib/guessit/test/rules/episodes.yml
- lib/guessit/test/various.yml
- tests/test_guessit.yml
> Updating guessit to d96859d

- medusa/trakt_checker.py
> Fix trakt_checker trying to get episodes that don't exist. Fixes #2782

- medusa/search/manual.py
Fixes https://github.com/pymedusa/Medusa/issues/2596#issuecomment-301526508
> Fix TypeError: int() argument must be a string or a number, not 'NoneType'

- medusa/clients/torrent/transmission_client.py
Fixes https://github.com/pymedusa/Medusa/issues/1701#issuecomment-267098143
> Fix ValueError: No JSON object could be decoded

- medusa/providers/torrent/html/torrentproject.py
> Use human_time for TorrentProject provider. Fixes #2842

- medusa/version_checker.py
To be merged after https://github.com/pymedusa/Medusa/pull/2851
> Add BraceAdapter to version_checker. Fixes #2846

- medusa/indexers/tvdbv2/tvdbv2_api.py
> Add series ID to warning logs

- medusa/version_checker.py
> Add BraceAdapter to version_checker. Fixes #2846 (2)

- medusa/process_tv.py
- tests/test_process_tv.py
> Refactor postponed processing in process_tv, cleaned up a bit

- medusa/providers/generic_provider.py
> Map episode numbers to str. Fixes #2871

- medusa/tv/series.py
- tests/test_should_refresh.py
Related to: https://github.com/pymedusa/Medusa/issues/2859
tests may fail but I will handle it later
> Allow refresh of UNKNOWN qualities

- medusa/clients/torrent/deluge_client.py
- medusa/clients/torrent/deluged_client.py
Now instead of logging only, it will actually remove it
@ratoaq2 @OmgImAlexis
> Start removing torrents from Deluge|Deluged

- static/js/config-providers.js
Fixes https://github.com/pymedusa/Medusa/issues/2879
> Fix TypeError: $(...).removeOption is not a function

- medusa/providers/generic_provider.py
> Add thetorrent

- medusa/providers/torrent/json/torrentday.py
> Changed back to TorrentDay's original url.

- medusa/common.py
- medusa/init/__init__.py
> Fix knowit update

- medusa/logger/__init__.py
- medusa/subtitle_providers/legendastv.py
Also add some logs to better debug the search
All known issues and discussed with @ratoaq2 a couple of months ago
> LTV:  Fix not finding new subtitles and empty archive for vip/donors

- medusa/providers/torrent/html/zooqle.py
> Replace yesterday with 24 hours for Zooqle provider. Fixes #1729

- medusa/search/core.py
Fixes https://github.com/pymedusa/Medusa/issues/2909
> Fix TypeError: pick_best_result() takes exactly 1 argument (2 given)

- medusa/subtitle_providers/legendastv.py
@ratoaq2 with the changes you asked. If is ok, I will also PR upstream
> LTV provider: Add debug logs when discarding title

- medusa/classes.py
Related to https://github.com/pymedusa/Medusa/issues/2896
@p0psicles can you evaluate? I didn't test. In theory it should work
> Removing log about creating all ep object

- medusa/subtitle_providers/legendastv.py
@ratoaq2 done
will add this commits to upstream if ok
> LTV: Add logs when discarding movie title

- medusa/logger/__init__.py
Some logs appears and some don't
Fixes https://github.com/pymedusa/Medusa/issues/2913
I couldn't find another fix but I'm not the expert here
@ratoaq2  If another solution please close this
> Fix custom subtitle providers having some weird log issues 

- medusa/logger/adapters/style.py
- medusa/providers/generic_provider.py
> Update style adapter (and fix a missed show->series refactor)

- views/testRename.mako
Fix https://github.com/pymedusa/Medusa/issues/2939
> TypeError: tuple indices must be integers, not unicode

- medusa/init/__init__.py
- medusa/subtitle_providers/subscenter.py
- pytest.ini
> Use Subscenter as custom subtitle provider with latest fixes

- medusa/server/web/core/base.py
- medusa/ui.py
- static/js/ajax-notifications.js
Code from @sharkykh
I did a quick test and it's not working
Fixes: https://github.com/pymedusa/Medusa/issues/2897
> Fix to N notifications (N tabs open)

- medusa/server/api/v1/core.py
* Replaced double quotes with single, where possible.
* Removed ex.
* Replaced %s string parsing.
* Removed string concatenations with formats.
> new logging: cleaned up api/v1/core.py

- medusa/providers/torrent/html/abnormal.py
- medusa/providers/torrent/html/scenetime.py
- medusa/providers/torrent/json/norbits.py
- medusa/session/core.py
This should fix:
abnormal
scenetime
norbits.
As well as other requests that were depending on the User-Agent. Although by default we're using medusa's custom user-agent.
> bugfixes after remove-get-url pr

- medusa/providers/generic_provider.py
> Configure proper User-Agent for providers.

- views/manage_subtitleMissed.mako
> Add language code to language names in the missed subtitles page

- medusa/scene_exceptions.py
> Move the scene_exception request get, within the try/catch.

- medusa/providers/generic_provider.py
> Added 2 .torrent hosts to complement the existing

- medusa/providers/torrent/json/danishbits.py
> Handle api error

- lib/knowit/providers/mediainfo.py
> Minor knowit fix

- medusa/providers/torrent/json/danishbits.py
> Fix warning

- COPYING.txt
This should do it.
Referencing https://github.com/SickRage/SickRage/pull/3938
> Update copyright license to the original author's license

- tox.ini
> Fix ninja_test.py - ImportError while importing test module

- medusa/providers/torrent/html/shanaproject.py
I noticed it had occasionally some troubles parsing the date. Let's hope this will fix that. And else we'll get some more info with this.
> Use the parse_pubdate helper for shanaproject date parsing.

- medusa/search/proper.py
> New logging for propers.py

- medusa/name_cache.py
> New logging for name_cache.py

- static/js/ajax-notifications.js
> Add webroot to websocket url.

- medusa/clients/torrent/transmission_client.py
Fix https://gist.github.com/duramato/8e17661da07d76788aa49c94d484e421#file-application-log-L8 from @duramato using Transmission recommendation https://github.com/transmission/transmission/issues/231#issuecomment-296385711
> Fixes Transmission conflict status code by using urllib3.util.retry

- medusa/providers/torrent/html/scc.py
> Fix SCC login and add pubdate

- medusa/failed_processor.py
- medusa/post_processor.py
- tests/test_rename_associated_file.py
- Fixes bug reported here: https://github.com/pymedusa/Medusa/issues/3006
- Fixes bug with subtitles and absolute paths
- Lint post_processor.py
> Add tests to rename_associated_file and fix 2 bugs. #Fixes 3006

- medusa/failed_processor.py
> Fix loglevel param in wrong position.

- medusa/providers/torrent/html/hounddawgs.py
> Fix HoundDawgs login

- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvmaze/tvmaze_api.py
- medusa/subtitles.py
- medusa/tv/series.py
> Obtain show's countries from tmdb

- static/js/common/init.js
- views/home.mako
- views/status.mako
- views/viewlogs.mako
* Renamed the #showID to #series-id, as 1. i'd rather use hyphened. And 2. the id showID is already used on pages. And i'd like to prevent this from being reused.
> Fix exception thrown when no series added and viewlog is opened.

- medusa/post_processor.py
> Partially fix #3036

- medusa/providers/torrent/html/yggtorrent.py
> Fix translation for heures.

- medusa/providers/torrent/html/limetorrents.py
> Fix limetorrents table headers.

- medusa/tv/series.py
Fix https://github.com/pymedusa/Medusa/issues/1729
> Fix AttributeError: 'NoneType' object has no attribute 'year'

- static/js/ajax-episode-search.js
- static/js/home/display-show.js
- static/js/home/edit-show.js
- static/js/manage/backlog-overview.js
- static/js/quality-chooser.js
- static/js/test-rename.js
- views/displayShow.mako
- views/editShow.mako
- views/history.mako
- views/partials/showheader.mako
- views/schedule.mako
- views/snatchSelection.mako
- views/testRename.mako
> Renamed showID and series_slug to series-id and series-slug.

- static/js/ajax-notifications.js
- static/js/core.js
> Used a custom event to trigger when Medusa's config has been loaded in.

- static/js/mass-update.js
> Use post in stead of get, for massUpdate and massEdit.

- medusa/helpers/__init__.py
@medariox
`SEARCHQUEUE-MANUAL-311945 :: [Rarbg] :: [4c2ace8] Consider adding 'Bull' in scene exceptions for show 'Bull (2016)'`
> Warn about scene exception without year

- medusa/helpers/__init__.py
> Insensitive comparison in scene exceptions check

- medusa/providers/generic_provider.py
- medusa/server/web/home/handler.py
- medusa/session/hooks.py
http://www.i18nqa.com/debug/bug-double-conversion.html
Fixes #3004
> Fix double mis-conversion

- medusa/scene_exceptions.py
> Fix not sending the correct xem url

- medusa/providers/torrent/html/anidex.py
> Fix anidex url.

- medusa/helpers/__init__.py
- medusa/subtitle_providers/itasa.py
> Fix Codacy errros

- medusa/providers/torrent/rss/rsstorrent.py
- views/config_providers.mako
> Make cookies optional for custom providers. Fixes #3096

- medusa/providers/generic_provider.py
http://www.i18nqa.com/debug/bug-double-conversion.html
http://www.i18nqa.com/debug/utf8-debug.html
Fixes #3087
> Fix double mis-conversion for latin1

- medusa/session/hooks.py
http://www.i18nqa.com/debug/bug-double-conversion.html
http://www.i18nqa.com/debug/utf8-debug.html
Fixes #3087 
This applies the fix from #3099 to the session hooks as well.
> Fix double mis-conversion for latin1 in session hooks

- medusa/providers/generic_provider.py
- medusa/session/hooks.py
> Fix incorrect logging parameters

- medusa/notifiers/nma.py
> Fix nma after changing to config v.10.

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
Fixes https://github.com/guessit-io/guessit/issues/499
> Fixes 4K/2160p detection leading to GuessitException

- medusa/config.py
- medusa/logger/__init__.py
I've introduced a rule that a string needs to have 4 chars at minimum to be censored.
Should fix #3128
> The sickbeard index api_key has a value of 0. This results on all '0' being censored.

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Absolute episode should be detected for no season animes

- medusa/__main__.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/rss/rsstorrent.py
- medusa/server/web/config/providers.py
- pytest.ini
- views/config_providers.mako
* Got lost after restart.
Should really fix #3130
> Fix loading of the rsstorrent cookies and url attributes.

- medusa/providers/generic_provider.py
> Fix Jackett path for torrents. Fixes #3149

- medusa/helper/metadata.py
- medusa/indexers/indexer_base.py
- medusa/indexers/indexer_config.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/metadata/__init__.py
- medusa/metadata/generic.py
- medusa/metadata/helpers.py
- medusa/search/backlog.py
- pytest.ini
- tox.ini
> Query only needed episodes on NFO or thumbnail creation

- medusa/providers/generic_provider.py
> Verify response before list creation in cookie_login(). Fixes #1729

- medusa/tv/series.py
> Load countries even if there's little info in IMDb

- medusa/tv/series.py
> Fix imdb info

- medusa/session/core.py
Got broken after moving to requests classes.
> Fix ssl verification.

- medusa/helpers/__init__.py
In that case we need to loop through them.
This issue can be reproduced by trying to refresh a number of episodes for the show Jojo's..
I can share the list of episode names, if someone wants to reproduce.
This will fix the following exception:
```
2017-10-26 22:42:58 ERROR    SHOWQUEUE-REFRESH :: [42b1e5f] 262954: Error while refreshing show JoJo's Bizarre Adventure (2012). Error: 'list' object has no attribute 'replace'
File "/opt/medusa/medusa/show_queue.py", line 629, in run
self.show.refresh_dir()
File "/opt/medusa/medusa/tv/series.py", line 1744, in refresh_dir
self.load_episodes_from_dir()
File "/opt/medusa/medusa/tv/series.py", line 928, in load_episodes_from_dir
cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
File …
```
> The medusa parser can give back multiple series titles in a list

- medusa/providers/torrent/html/torrent9.py
> Update Torrent9 URL

- medusa/providers/torrent/html/yggtorrent.py
YggTorrent's filter category is finally available
> Add Video category to yggtorrent

- medusa/post_processor.py
> Add log to PostProcessing exception

- medusa/providers/nzb/newznab.py
- medusa/server/web/config/providers.py
> Fix duplicate settings for newznab providers. Fixes #3207

- medusa/providers/generic_provider.py
- medusa/providers/nzb/newznab.py
> Add magnets support for newznab providers. Fixes #3213

- medusa/clients/nzb/sab.py
> Use MedusaSafeSession for sabnzbd client. Fixes #3203

- medusa/process_tv.py
> Fix folder checks for post-processing. Fixes #3219

- static/css/style.css
- static/js/home/snatch-selection.js
> Show full (un-ellipsed) release name when clicking on it.

- medusa/providers/generic_provider.py
> Fix use scene exception, when a show has season scene name exceptions.

- medusa/search/proper.py
Related to: https://github.com/pymedusa/Medusa/issues/3227
Concept validated with @duramato
Downloaded:
Mr.Robot.S03E04.eps3.3.m3tadata.par2.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
Log:
2017-11-06 10:44:47 INFO     FINDPROPERS :: [4c2ace8] Ignoring proper because streaming service is different: Mr.Robot.S03E04.PROPER.1080p.WEB.H264-STRiFE[rartv]
> Only PROPER from same streaming service

- medusa/post_processor.py
Fixes https://github.com/pymedusa/Medusa/issues/3232
> Don't warn missing info hash for nzb downloads

- medusa/clients/nzb/sab.py
- medusa/clients/torrent/deluge_client.py
- medusa/clients/torrent/generic.py
- medusa/common.py
- medusa/failed_history.py
- medusa/helper/common.py
- medusa/helpers/__init__.py
- medusa/issue_submitter.py
- medusa/logger/__init__.py
- medusa/name_cache.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/__init__.py
- medusa/scheduler.py
- medusa/server/api/v2/base.py
- medusa/server/web/core/base.py
- medusa/server/web/home/add_shows.py
- medusa/show/recommendations/imdb.py
- medusa/trakt_checker.py
- medusa/tv/episode.py
- medusa/version_checker.py
- tests/test_list_associated_files.py
- tests/test_should_refresh.py
> Try to remove the I202 warnings.

- static/js/home/snatch-selection.js
> Attach on click to document.

- static/css/dark.css
- static/css/style.css
- views/addShows_addExistingShow.mako
> Remove dark background for add existing show

- medusa/__main__.py
- medusa/config.py
- medusa/helpers/utils.py
- medusa/providers/nzb/newznab.py
- medusa/server/web/config/providers.py
- medusa/version_checker.py
- views/config_providers.mako
In the end it was a stupid typo.
Do realize that with this fix the cats are saved as a string. While we have done allot to store lists really as lists in the config.
If we want to store this as a list, it'l take more work.
Will fix #3215
> Fixed custom newznab providers not saving the categories after restart.

- medusa/process_tv.py
> Fix post-processing ignoring files in subdirectories. Fixes #3255

- medusa/common.py
> Use the Medusa version in the user agent

- .travis.yml
> use newest nodejs for tests

- medusa/scene_numbering.py
- medusa/session/core.py
> Use get_json(), which has build in exception handling.

- medusa/clients/nzb/sab.py
- medusa/clients/torrent/deluge_client.py
- medusa/clients/torrent/generic.py
- medusa/common.py
- medusa/failed_history.py
- medusa/helper/common.py
- medusa/helpers/__init__.py
- medusa/issue_submitter.py
- medusa/logger/__init__.py
- medusa/name_cache.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/__init__.py
- medusa/providers/torrent/html/yggtorrent.py
- medusa/scheduler.py
- medusa/server/api/v2/base.py
- medusa/server/web/core/base.py
- medusa/server/web/home/add_shows.py
- medusa/show/recommendations/imdb.py
- medusa/trakt_checker.py
- medusa/tv/episode.py
- medusa/version_checker.py
- tests/test_list_associated_files.py
- tests/test_should_refresh.py
> Yggtorrent: Fix the parsing of download link.

- medusa/scene_numbering.py
> Fix get scene_numbering get_json()

- ext/subliminal/core.py
- requirements.txt
> Subliminal: Log error instead of traceback when can't refine mkv

- medusa/search/backlog.py
> Fix BacklogSearchScheduler.next_run

- medusa/subtitles.py
Fix https://github.com/pymedusa/Medusa/issues/3304
> Don't exception when invalid language code

- medusa/metadata/kodi_12plus.py
Fix for #3242
Did not actually test if it works in kodi... but I made the changes according to the specifications of the new url (except for escaped quotes)
> Switch to tvdbapi v2 episodeguide url

- medusa/providers/torrent/json/xthor.py
Update xthor tld xthor.bz > xthor.to
> update xthor tld

- medusa/notifiers/nma.py
> Don't log error when can't connnect to NMA

- medusa/__main__.py
- medusa/server/api/v1/core.py
- views/config_general.mako
> Rebrand SR to Medusa

- medusa/providers/torrent/html/yggtorrent.py
> Update YggTorrent URL

- medusa/issue_submitter.py
- tests/test_issuesubmitter.py
Clean up IssueSubmitter and fixes #3209
> Clean up IssueSubmitter

- .codebeatignore
> Add .codebeatignore file

- .codebeatignore
> Use recursive ignore for ext and lib folders

- medusa/indexers/indexer_base.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
> Remove superfluous _clean_data. Fixes #3350

- ext/subliminal/providers/legendastv.py
- ext/subliminal/providers/opensubtitles.py
- requirements.txt
LegendasTV and Opensubtitles changes
Dont not merge for now. I think another PR will be merged today
> Sync latest Subliminal

- medusa/notifiers/__init__.py
Fixes https://github.com/pymedusa/Medusa/issues/3226
> Fix notifiers timeout by socket

- medusa/process_tv.py
- tests/test_process_tv.py
> Allow deleting files after copy for manual post-processing

- medusa/common.py
> Bump USER_AGENT version 0.1.20 (dev).

- medusa/name_parser/guessit_parser.py
> Added 20-40 as an expected group for guessit parsing.

- tests/test_guessit.yml
> Added test for expected_group '20-40'.

- medusa/clients/torrent/transmission_client.py
- medusa/session/hooks.py
```
File Medusa\medusa\session\hooks.py", line 31, in log_url
if 'multipart/form-data' not in request.headers.get('content-type') \
```
> Transmission. Error: argument of type 'NoneType' is not iterable

- readme.md
> Alternate docker repo.

- readme.md
> Fix bad link to changes.MD

- medusa/issue_submitter.py
Fixes the malformed Issue Report
> Fix Issue report format

- medusa/logger/adapters/style.py
Fixes the style adapter fallback when string conversion fails.
> Fix style adapter repr fallback

- medusa/providers/torrent/html/alpharatio.py
> Fix AlphaRatio provider login by using https URL

- medusa/providers/torrent/html/yggtorrent.py
Also, daily search doesn't seem to be working.
> Fix download link for YGG provider

- readme.md
- views/config_providers.mako
> Clarify Jackett's configuration

- medusa/providers/torrent/html/yggtorrent.py
They changed their url again... It's starting to be depressing actually.
> Fix Yggtorrent 

- medusa/server/api/v1/core.py
> Fix API root directories

- medusa/indexers/indexer_base.py
* Flattening of the image structure had a bug.
Fix #3484
> Fix pick the highest rated image.

- medusa/post_processor.py
Related to: https://github.com/pymedusa/Medusa/issues/3457
> Log more info in PP

- medusa/indexers/indexer_base.py
> Clean up image saving

- medusa/logger/adapters/style.py
> Improve BraceMessage

- static/js/home/index.js
Broken after the order series/anime PR.
> Fix select column.

- medusa/post_processor.py
Related to https://github.com/pymedusa/Medusa/issues/3457
> Improved logs for missing hash

- medusa/clients/torrent/deluge_client.py
- medusa/clients/torrent/transmission_client.py
Fixed bug introduced in https://github.com/pymedusa/Medusa/pull/3411/commits/7ce73077960cc82b74e1b2bc1ad3a060488a0e43
> Fix not checking for RARed torrents in history because is not media file

- Dockerfile
> Fix for subtitles w/ Python 2.7 GDBM

- medusa/search/core.py
> Fix leftovers from searchType refactor.

- ext/imdbpie/imdbpie.py
- requirements.txt
> Fix IMDb's search by title

- medusa/__main__.py
> Fix freeleech option not being saved. Fixes #3524

- readme.md
@bobbysteel you may want to leave your build up incase others are using it.
> replace boobysteel docker hub link with pymedusa's one

- views/partials/home/banner.mako
- views/partials/home/poster.mako
- views/partials/home/simple.mako
- views/partials/home/small.mako
Fixes https://github.com/pymedusa/Medusa/issues/3532
> Fix anime split show layout

- medusa/indexers/indexer_base.py
> Continue when there is no image in the sorted list.

- medusa/image_cache.py
- medusa/media/banner.py
- medusa/media/fan_art.py
- medusa/media/generic.py
- medusa/media/network_logo.py
- medusa/media/poster.py
- medusa/server/api/v1/core.py
- medusa/server/api/v2/series_asset.py
- medusa/server/web/home/handler.py
- medusa/tv/series.py
- tests/legacy/media/generic_media_tests.py
- tests/legacy/media/show_banner_tests.py
- tests/legacy/media/show_fan_art_tests.py
- tests/legacy/media/show_network_logo_tests.py
- tests/legacy/media/show_poster_tests.py
Rewrite image caching and media classes.
> Classless ImageCache

- medusa/process_tv.py
Implements https://github.com/pymedusa/Medusa/issues/3551
> Ignore folders #recycle (DSM)

- medusa/logger/adapters/style.py
> Fix BraceMessage KeyError

- medusa/subtitles.py
> Don't encode paths with UTF-8 for Windows. Fixes #3345

- medusa/init/filesystem.py
> Don't encode input for Windows

- medusa/process_tv.py
Fixes  https://github.com/pymedusa/Medusa/issues/3597
> Fix move torrent key error

- static/css/style.css
Implements https://github.com/pymedusa/Medusa/issues/3592
> Don't wrap status column for medium devices and up

- medusa/server/web/manage/handler.py
> Fix logging in massEditSubmit. Fixes #3160

- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/metadata/generic.py
- medusa/tv/episode.py
- medusa/tv/series.py
> Fix thumbnails not being generated on post-processing. Fixes #3539

- medusa/tv/episode.py
> Don't reuse indexer API if it differs from show indexer. Fixes #3626

- medusa/image_cache.py
- medusa/server/web/home/handler.py
- medusa/show_queue.py
> do not remove images early in a force full refresh.

- medusa/helpers/externals.py
- medusa/indexers/indexer_api.py
- medusa/indexers/indexer_base.py
- medusa/indexers/indexer_config.py
- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/indexers/tvmaze/tvmaze_api.py
- medusa/indexers/utils.py
- medusa/metadata/generic.py
- medusa/notifiers/trakt.py
- medusa/providers/nzb/newznab.py
- medusa/providers/torrent/html/sdbits.py
- medusa/server/web/home/handler.py
- medusa/server/web/manage/handler.py
- medusa/show/recommendations/recommended.py
- medusa/show/show.py
- medusa/trakt_checker.py
- medusa/tv/indexer.py
- medusa/tv/series.py
- views/config_notifications.mako
- views/displayShow.mako
- views/editShow.mako
- views/schedule.mako
> Add name property to BaseIndexer to use name attribute for indexers

- ext/subliminal/providers/addic7ed.py
- ext/subliminal/providers/opensubtitles.py
- requirements.txt
Addic7ed: Change regex to allow shows with asterisk
Addic7ed: Fix `get_matches` function for `alternative series` feature
OpenSubtitles: Add support to multi-episode
> Upgrade Subliminal to 044f781235b23dce3268831b35a23009db06a8cd

- medusa/version_checker.py
> use the safe session for version_checker.py.

- medusa/helpers/__init__.py
Fallback to the file's extension.
Fix for #3630
> Fix image size not detected for jpegs without exim data.

- medusa/issue_submitter.py
> Fix a tiny typo in issue_submitter.py

- ext/subliminal/providers/tvsubtitles.py
- requirements.txt
TVSubtitles: Fix TypeError: unhashable type: 'list' when multi-ep
@duramato
> Upgrade Subliminal to 4c0bcbfd68728241324f509317afdf6beb681f99
