- medusa/providers/torrent/html/torrentleech.py
> Add pubdate to Torrentleech, improve code a bit

- medusa/providers/__init__.py
- medusa/providers/torrent/__init__.py
- medusa/providers/torrent/html/torrentday.py
- medusa/providers/torrent/json/torrentday.py
> Attempt to fix td.

- medusa/providers/generic_provider.py
- medusa/providers/torrent/json/btn.py
- tests/providers/test_generic_provider.py
Cause lazy @duramato just didn't bother
> Add fromtimestamp to parse_pubdate, add pubdate to BTN

- medusa/providers/torrent/html/newpct.py
- tests/providers/torrent/newpct/newpct_test.yaml
> Fix Newpct download links for old torrents

- medusa/providers/torrent/html/torrentday.py
* Fixed issue with detecting no torrents found.
* Fixed issue with parsing pubdate.
fix #3670
> Fixed td parsing.

- medusa/providers/torrent/html/torrent9.py
- tests/providers/torrent/torrent9/torrent9_test.yaml
> Fix download for Torrent9 provider

- medusa/providers/nzb/newznab.py
- tests/legacy/test_lib.py
> Update usenet-crawler url

- ext/tornado/__init__.py
- ext/tornado/curl_httpclient.py
- ext/tornado/http1connection.py
- ext/tornado/iostream.py
- ext/tornado/options.py
- ext/tornado/test/httpserver_test.py
- ext/tornado/test/iostream_test.py
- ext/tornado/test/options_test.py
- ext/tornado/test/simple_httpclient_test.py
- ext/tornado/test/util.py
- ext/tornado/test/web_test.py
- ext/tornado/test/websocket_test.py
- ext/tornado/testing.py
- ext/tornado/web.py
- ext/tornado/websocket.py
- requirements.txt
- setup.py
> Update tornado to version 4.5.3. Fixes #3424

- medusa/subtitles.py
> Only encode/decode if needed in subtitles.py. Fixes #3707

- medusa/post_processor.py
- medusa/tv/episode.py
> Postprocess: Cut long filenames to 255 chars max.

- medusa/tv/series.py
> image_cache.get_artwork() requires whole object. Fixes #3731

- medusa/clients/torrent/download_station_client.py
> Parse error code to string before passing on to logger.

- medusa/tv/series.py
Should fix https://github.com/tidusjar/Ombi/issues/1945
> Cast season to list, if passed as integer.

- medusa/indexers/tvdbv2/tvdbv2_api.py
> Use fixed value of 1, self.indexer as a direct TVDBv2 attribute.

- medusa/indexers/tvdbv2/tvdbv2_api.py
> Use fixed value of 1, self.indexer as a direct TVDBv2 attribute

- readme.md
> Update Medusa logo in readme.md

- medusa/cache.py
- medusa/show/recommendations/anidb.py
- medusa/show/recommendations/imdb.py
- medusa/show/recommendations/recommended.py
- medusa/show/recommendations/trakt.py
* Fixed imdb recommended list, for series without the possibility to rate.
All shows from recommended lists, are cached now on disk.
Cache expires after 1 week.
Also fixes #3749
> Recommended series: Use dogpile for caching of the imdb, trakt and anidb shows

- medusa/scene_numbering.py
This PR fix xem_refresh() not updating shows with valid xem data (e.g. Cardcaptor Sakura)
**N.B.: This bug is also present in master**
> Fix xem_refresh not working

- medusa/providers/torrent/html/newpct.py
- tests/providers/torrent/newpct/newpct_test.yaml
> Fix Newpct download parsing, update domain

- medusa/server/api/v1/core.py
- themes-default/legacy/views/apiBuilder.mako
- themes-default/slim/views/apiBuilder.mako
- themes/dark/templates/apiBuilder.mako
- themes/light/templates/apiBuilder.mako
> apiv1: Add error handling, for looking up show artwork through apiv1.

- medusa/clients/nzb/nzbget.py
Tries to fix https://github.com/pymedusa/Medusa/issues/3831
> Use future xmlrpc.client instead of six.moves.xmlrpc_client

- medusa/server/web/home/handler.py
> Use absolute_number argument instead of absolute. Fixes #3836

- themes-default/legacy/views/config_postProcessing.mako
- themes-default/slim/views/config_postProcessing.mako
- themes/dark/templates/config_postProcessing.mako
- themes/legacy/templates/config_postProcessing.mako
- themes/light/templates/config_postProcessing.mako
This PR fixes errors in config_postProcessing.mako
> Fix errors in config_postProcessing.mako

- medusa/process_tv.py
> Fix "RuntimeError: dictionary changed size during iteration"

- medusa/failed_history.py
- medusa/notifiers/prowl.py
- [x PR is based on the DEVELOP branch
@duramato
> More changes for Python 3 compatibility

- medusa/clients/torrent/deluge_client.py
> Fix deluge client reference to wrong variable. Fixes #3850

- medusa/issue_submitter.py
> Fix missing credential when submiting issues using git token

- medusa/show_updater.py
> Fix ConnectionError reported as exception in ShowUpdater

- medusa/providers/torrent/html/yggtorrent.py
> Translate "à l'instant" for Yggtorrent provider. Fixes #3865

- medusa/providers/torrent/html/cinemaz.py
- medusa/providers/torrent/html/privatehd.py
> Fix trying to get text with get_text from response object

- themes/light/templates/home_postprocess.mako
> Fix typo in home_postprocess.mako

- medusa/helpers/utils.py
- medusa/server/web/core/file_browser.py
Closes https://github.com/pymedusa/Medusa/issues/3873
@OmgImAlexis
> Add truth_to_bool to support a wide range of truth values

- themes-default/slim/static/js/blackwhite.js
- themes/dark/assets/js/blackwhite.js
- themes/light/assets/js/blackwhite.js
Fixes https://github.com/pymedusa/Medusa/issues/3887
> Fix blackwhite.js

- lib/pkg_resources/__init__.py
- lib/pkg_resources/_vendor/appdirs.py
- lib/pkg_resources/_vendor/packaging/__about__.py
- lib/pkg_resources/_vendor/packaging/__init__.py
- lib/pkg_resources/_vendor/packaging/_compat.py
- lib/pkg_resources/_vendor/packaging/_structures.py
- lib/pkg_resources/_vendor/packaging/markers.py
- lib/pkg_resources/_vendor/packaging/requirements.py
- lib/pkg_resources/_vendor/packaging/specifiers.py
- lib/pkg_resources/_vendor/packaging/utils.py
- lib/pkg_resources/_vendor/packaging/version.py
- lib/pkg_resources/_vendor/pyparsing.py
- lib/pkg_resources/_vendor/six.py
- lib/pkg_resources/_vendor/vendored.txt
- lib/pkg_resources/api_tests.txt
- lib/pkg_resources/extern/__init__.py
- lib/pkg_resources/py31compat.py
- lib/pkg_resources/tests/test_find_distributions.py
- lib/pkg_resources/tests/test_markers.py
- lib/pkg_resources/tests/test_pkg_resources.py
- lib/pkg_resources/tests/test_resources.py
- lib/pkg_resources/tests/test_working_set.py
> Add back pkg_resources to /lib as it is required by babelfish

- ext/subliminal/core.py
- ext/subliminal/providers/addic7ed.py
- ext/subliminal/providers/opensubtitles.py
- ext/subliminal/providers/tvsubtitles.py
- ext/subliminal/subtitle.py
- ext/subliminal/video.py
- requirements.txt
Addic7ed: Use new search URL
Revert multi-episode support
Tvsubtitles: log error for `show id` only after query all titles
> Upgrade Subliminal to 879c0c8d18618e32ad466bb63bd939edb268bc60

- themes-default/legacy/views/inc_addShowOptions.mako
- themes-default/slim/views/inc_addShowOptions.mako
- themes/dark/templates/inc_addShowOptions.mako
- themes/legacy/templates/inc_addShowOptions.mako
- themes/light/templates/inc_addShowOptions.mako
Fixes #3838 
(`class="cb"` wasn't adding anything to the UI)
> Rename Flatten Folders to Season Folders

- medusa/helpers/__init__.py
[The upstream pull request](https://gitlab.com/rubdos/pyreflink/merge_requests/3) is now merged so this isn't necessary anymore.
> Remove now unnecessary path encoding for reflink

- medusa/providers/nzb/newznab.py
- medusa/providers/torrent/torznab/torznab.py
> Fix Newznab providers without supportedParams. Fixes #1729

- .codebeatignore
> add themes and themes-default to codebeat ignore

- medusa/server/api/v2/stats.py
- medusa/server/core.py
- medusa/tv/cache.py
show statistics, for example:
```json
{
"seriesStat": [
{
"seriesId": 70851,
"epTotal": 100,
"epAirsPrev": 733416,
"epSnatched": 0,
"seriesSize": 178656514235,
"epDownloaded": 100,
"epAirsNext": null,
"indexerId": 1
},
{
"seriesId": 72449,
"epTotal": 214,
"epAirsPrev": 733252,
"epSnatched": 0,
"seriesSize": 156658035456,
"epDownloaded": 214,
"epAirsNext": null,
"indexerId": 1
}
],
"maxDownloadCount": 1000
}
```
> Add the stats API v2 endpoint

- medusa/__main__.py
> Configure subtitle cache after "erase subtitle cache" action

- themes-default/slim/views/layouts/main.mako
- themes-default/slim/views/vue-components/saved-message.mako
- themes/dark/templates/layouts/main.mako
- themes/dark/templates/vue-components/saved-message.mako
- themes/light/templates/layouts/main.mako
- themes/light/templates/vue-components/saved-message.mako
Messages will fade-out after a specific amount of time. The messages will also appear for a minimum amount of time.
Currently used in the editShow PR here: #3849
> Added component for showing saving, saved, or error messages.

- medusa/clients/torrent/qbittorrent_client.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/torrent_provider.py
- medusa/search/core.py
- medusa/server/core.py
- medusa/session/core.py
> Fix client download for Jackett providers with magnet redirects

- themes-default/slim/views/layouts/main.mako
- themes/dark/templates/layouts/main.mako
- themes/light/templates/layouts/main.mako
> Fix 'FixME' in title while loading page. (backwards-compatible)

- medusa/notifiers/tweet.py
> Fix Twitter DM

- medusa/clients/nzb/sab.py
> Fix sab when there's no connection

- medusa/providers/torrent/json/btn.py
Credits & thanks to @sharkykh for the fix.
@duramato
> Fix BTN API exception on connection error

- themes-default/slim/static/js/lib/vue.js
- themes/dark/assets/js/lib/vue.js
- themes/light/assets/js/lib/vue.js
To be merged after https://github.com/pymedusa/Medusa/pull/3818
> update vue to v2.5.16

- medusa/common.py
> Bump User-Agent version

- themes-default/slim/views/config_providers.mako
- themes/dark/templates/config_providers.mako
- themes/light/templates/config_providers.mako
> Clarify the provider config invalid url alert. Closes #4083

- medusa/notifiers/growl.py
> Fix import for gntp. Fixes #4084

- medusa/providers/torrent/json/torrentday.py
- medusa/providers/torrent/torznab/torznab.py
> Fix torznab for providers without seeders/leechers

- themes-default/slim/static/js/common/init.js
- themes/dark/assets/js/common/init.js
- themes/light/assets/js/common/init.js
Closes https://github.com/pymedusa/Medusa/issues/4127
> fix touchscreen hack causing menu double tap to apply base twice

- themes-default/slim/views/addRecommended.mako
- themes-default/slim/views/addShows.mako
- themes/dark/templates/addRecommended.mako
- themes/dark/templates/addShows.mako
- themes/light/templates/addRecommended.mako
- themes/light/templates/addShows.mako
> convert addShows and addrecommended to vue

- medusa/post_processor.py
> Fix reference to import of anidb_setup_connection().

- themes-default/slim/views/vue-components/app-link.mako
- themes/dark/templates/vue-components/app-link.mako
- themes/light/templates/vue-components/app-link.mako
Tested, works for me.
Fixes #3359 
@OmgImAlexis If you have any more fixes queued up for `app-link` maybe we should combine them into one PR.
> app-link: Fix undefined url with empty anonRedirect

- themes-default/slim/views/addShows_newShow.mako
- themes/dark/templates/addShows_newShow.mako
- themes/light/templates/addShows_newShow.mako
> Fix Frisbee path

- medusa/name_parser/guessit_parser.py
Also fixes https://github.com/pymedusa/Medusa/issues/3004 and https://github.com/pymedusa/Medusa/issues/3575
> guessit expected_groups should be a set

- medusa/session/core.py
As suggested in https://github.com/pymedusa/Medusa/pull/3076#issuecomment-387554278
> MedusaSession: Remove dot after url in log

- medusa/name_parser/guessit_parser.py
- medusa/name_parser/rules/rules.py
Unicode rules and options are not supported and will break the parser.
> Don't use unicode for guessit rules and options

- medusa/logger/adapters/style.py
This fixes the double exception not showing the actual error in reports, e.g.: https://github.com/pymedusa/Medusa/issues/3004#issuecomment-388619071
> Force representation on BraceMessage exception

- medusa/providers/torrent/html/nebulance.py
Fixes: https://github.com/pymedusa/Medusa/issues/4181
> Fix Nebulance's size parsing.

- medusa/server/web/home/handler.py
I checked changing status from display show and the apiv1.
Apiv1 appeared to work fine.
Fixes #4209
> Fix changing status from displayShow.

- medusa/issue_submitter.py
- medusa/search/core.py
`AttributeError: PaginatedList instance has no attribute '__len__'`
> IssueSubmitter: Fix AttributeError

- medusa/providers/generic_provider.py
> Add 2 new torrent cachers

- medusa/notifiers/emby.py
As suggested in https://github.com/pymedusa/Medusa/issues/4141#issuecomment-390580220
> Emby: Add info logs

- medusa/providers/torrent/html/bjshare.py
> Small linting.

- medusa/show/recommendations/imdb.py
> imdb-popular: Only get 'year' item if available

- medusa/providers/torrent/json/btn.py
@duramato 
Should fix #4226 by reporting it as a warning.
> Catch BTN "524 Origin Time-out" error

- themes-default/slim/views/layouts/main.mako
- themes/dark/templates/layouts/main.mako
- themes/light/templates/layouts/main.mako
@sharkykh @p0psicles this should help out. You just need to install the extension.
https://github.com/vue-perf-devtool/vue-perf-devtool
> enable vue perf stats for devs

- medusa/clients/torrent/deluge_client.py
> Deluge: Check that the request didn't fail

- medusa/post_processor.py
> Fix sports shows not post-processing. Fixes #3708

- medusa/name_parser/rules/rules.py
Reported here: https://github.com/pymedusa/Medusa/issues/4248#issuecomment-391608744
> Fix UnicodeDecodeError on guessit guess

- medusa/tv/episode.py
Fixes #3821
Credits to @h3llrais3r for the fix
> Fix #3821 - anime naming %E with only absolute number

- medusa/server/web/home/handler.py
> Fix ShowDirectoryNotFoundException on massEdit

- themes-default/slim/views/editShow.mako
- themes-default/slim/views/vue-components/quality-chooser.mako
- themes/dark/templates/editShow.mako
- themes/dark/templates/vue-components/quality-chooser.mako
- themes/light/templates/editShow.mako
- themes/light/templates/vue-components/quality-chooser.mako
Fixes #4327 
https://stackoverflow.com/a/1908655/7597273
> Fix #4327 by converting quality to unsigned int

- medusa/tv/series.py
1. Fix inconsistency with web frontend - Plot from indexer should override the plot from IMDB.
2. Fix Series.to_json not serializable. Related to #3958. A step in the right direction.
> Fix Series.to_json

- medusa/issue_submitter.py
- medusa/logger/__init__.py
- tests/test_logger.py
- Add AttributeError: 'NoneType' ... to diff overrides
- More fixes for the `format_to_html` function
> Update issue submitter

- medusa/providers/torrent/json/btn.py
Fixes https://github.com/pymedusa/Medusa/issues/1043#issuecomment-394824635
> BTN: Fix AttributeError on DownloadURL

- medusa/clients/nzb/nzbget.py
> NZBget: Handle socket.error gracefully. Fixes #4340

- themes-default/slim/views/partials/home/banner.mako
- themes-default/slim/views/partials/home/small.mako
- themes-default/slim/views/vue-components/asset.mako
- themes/dark/templates/partials/home/banner.mako
- themes/dark/templates/partials/home/small.mako
- themes/dark/templates/vue-components/asset.mako
- themes/light/templates/partials/home/banner.mako
- themes/light/templates/partials/home/small.mako
- themes/light/templates/vue-components/asset.mako
> fix assets not loading in some home layouts

- themes-default/slim/static/js/store.js
- themes/dark/assets/js/store.js
- themes/light/assets/js/store.js
This shouldn't effect anything as it's just adding more fields to the store, none of which are used right now.
> add more config fields to store

- medusa/process_tv.py
> Ignore .@__thumb folders.

- medusa/show/history.py
Fixes https://github.com/pymedusa/Medusa/issues/4092#issuecomment-397112349
**Tested.**
How to get the error:
`http://localhost:8081/api/APIKEY/?cmd=history&type=downloaded`
> API v1 - Fix fetching history with type

- medusa/providers/torrent/json/btn.py
> BTN: Catch 500 Internal Server Error

- medusa/github_client.py
- medusa/issue_submitter.py
- medusa/logger/__init__.py
- tests/conftest.py
- tests/test_issue_submitter.py
- tests/test_logger.py
- Fix find_similar_issues logging and tests
- Fix empty issue title and add test
Fixes titles like #4369
> Fix similar issues tests and empty issue titles

- lib/shutil_custom/__init__.py
- medusa/process_tv.py
Big thanks to @labrys for the code!
I've only changed the imports: `SpecialFileError` was meant to be `SameFileError`
and removed the function overwrite in `process_tv` as that's not needed.
Should fix #4362
> Improve shutil_custom. Should fix #4362

- medusa/logger/__init__.py
> Fix #4375 - support unicode chars in censored items

- medusa/post_processor.py
> Make sure the file exists before checking is_rarfile(). Fixes #4405

- medusa/clients/torrent/transmission_client.py
- medusa/search/queue.py
> Fix exception when Transmission is unreachable

- themes-default/slim/views/addShows_addExistingShow.mako
- themes-default/slim/views/addShows_newShow.mako
- themes/dark/templates/addShows_addExistingShow.mako
- themes/dark/templates/addShows_newShow.mako
- themes/light/templates/addShows_addExistingShow.mako
- themes/light/templates/addShows_newShow.mako
Fixing my broken code on `addShows/existingShows`,
and use the same solution in `addShows/newShow` for consistency.
Tested
> addShows: Fix Windows paths

- themes-default/slim/views/editShow.mako
- themes/dark/templates/editShow.mako
- themes/light/templates/editShow.mako
> EditShow: Fix saving dvdOrder

- dredd/api-description.yml
- medusa/server/api/v2/config.py
- tests/apiv2/test_config.py
- themes-default/slim/static/js/store.js
- themes/dark/assets/js/store.js
- themes/light/assets/js/store.js
@sharkykh @p0psicles 
From Slack:
> OmgImAlexis [10:30]
> I want to remove some of the fields from the API such as `PLEX_SERVER_PASSWORD` and other API keys, etc. I'm thinking instead we return a boolean depending on if it's set or not?
> add more fields to config including patch

- medusa/indexers/indexer_config.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/show/recommendations/trakt.py
Current URLs still work, but we should be moving forward.
> Update TVDB urls

- .github/ISSUE_TEMPLATE/bug_report.md
Fixes https://github.com/pymedusa/Medusa/pull/4469#discussion_r198166745
> Add logs section to bug template

- medusa/providers/torrent/html/scenetime.py
Fixes SceneTime parsing and adds missing pubdate.
Also adds missing cats.
> Fix SceneTime and add missing pubdate

- medusa/helper/common.py
- medusa/providers/torrent/html/yggtorrent.py
- tests/helper/test_common.py
- tests/providers/conftest.py
- tests/providers/test_search.py
- tests/providers/torrent/yggtorrent/yggtorrent_backlog.yaml
- tests/providers/torrent/yggtorrent/yggtorrent_daily.yaml
- tests/providers/torrent/yggtorrent/yggtorrent_test.yaml
* Fix YggTorrent size parsing, as reported here: https://github.com/pymedusa/Medusa/issues/3134#issuecomment-400973047
* Log a stack trace for providers on `try_int` exception.
* Enable tests for YggTorrent
* Improve `convert_size` and update tests
> Fix YggTorrent size parsing + enable tests

- tests/providers/test_search.py
Based on the changes made in #4485 
- Dynamically generate tests
- Remove duplicate code
- Limit compared results based on expected results
> Refactor provider tests

- themes-default/slim/views/partials/home/small.mako
- themes-default/slim/views/partials/schedule/poster.mako
- themes/dark/templates/partials/home/small.mako
- themes/dark/templates/partials/schedule/poster.mako
- themes/light/templates/partials/home/small.mako
- themes/light/templates/partials/schedule/poster.mako
- Fix poster size on schedule - Fixes #4501
- Fix network size home small poster view
> Fix asset sizes

- medusa/server/web/home/handler.py
- themes-default/slim/views/snatchSelection.mako
- themes/dark/templates/snatchSelection.mako
- themes/light/templates/snatchSelection.mako
Should fix #3134 (original post)
**I didn't test it yet**, but if both episode and season results work, then we should be good
**Edit:**
Episode: :heavy_check_mark: 
Multi-Episode: :heavy_check_mark: 
Season: :heavy_check_mark: 
@medariox 
I think your idea for why it happened was correct.
> Update pickManualSearch - fixes #3134

- .github/config.yml
This is needed for the todo bot we have enabled.
> set todo config

- .github/config.yml
> sharkykh [15:49]
We should probably also exclude `lib/` & `ext/`
:+1: 1
> Update todo config to exclude vendored packages

- medusa/common.py
- tests/test_should_replace.py
- themes-default/slim/views/vue-components/quality-chooser.mako
- themes/dark/templates/vue-components/quality-chooser.mako
- themes/light/templates/vue-components/quality-chooser.mako
Also disables the preferred quality selection if no allowed quality is selected.
> Fix better allowed quality versions not being downloaded. Fixes #4511

- medusa/notifiers/emailnotify.py
- pytest.ini
- tests/notifiers/__init__.py
- tests/notifiers/test_emailnotify.py
Fixes #4159
Some of my regex tests: https://regex101.com/r/KxDpoT/2
#3062 would be the better option, but this should be good for now.
> Patch email notifier episode parsing. Fixes #4159

- themes-default/slim/gulpfile.js
> add vue linting to gulp

- medusa/helpers/__init__.py
- themes-default/slim/views/partials/header.mako
- themes/dark/templates/partials/header.mako
- themes/light/templates/partials/header.mako
Remove `app.ANON_REDIRECT` references from `mako`.
Also remove unused `medusa.helpers.anon_url`.
> Remove `app.ANON_REDIRECT` references from `mako`

- medusa/helpers/__init__.py
> Rename errno.EXIST to errno.EEXIST. Fixes #4084

- medusa/common.py
> Bump version to v0.2.6

- .pyup.yml
> Disable Pyup pull requests

- themes-default/slim/static/js/templates/config.vue
- themes/dark/assets/js/templates/config.vue
- themes/light/assets/js/templates/config.vue
Fixes https://github.com/pymedusa/Medusa/pull/4374#discussion_r200008156
> fix store typo

- themes-default/slim/package.json
- themes-default/slim/test/specs/app-link.spec.js
- themes-default/slim/yarn.lock
- themes/dark/package.json
- themes/light/package.json
>  Upgrade eslint to 5.0.1

- .travis.yml
- themes-default/slim/gulpfile.js
- themes-default/slim/package.json
- themes/dark/package.json
- themes/light/package.json
The jobs are running in parallel.
> Split travis builds into jobs

- requirements.txt
> Remove vcrpy

- ext/readme.md
@medariox 
Made some mistakes :stuck_out_tongue:
> Fix dependency listing

- medusa/server/web/home/add_recommended.py
- medusa/server/web/home/add_shows.py
... to reflect conversion to `VueRouter`.
> Update docstrings for addShows/addRecommended

- .github/config.yml
- renovate.json
Ignore paths:
- `.build/**` - Closes #4571, closes #4614, closes #4604, closes #4608, closes #4607, closes #4606
- `themes/**` - Just duplicates of `themes-default/slim`
- `ext/**` - Future-proofing
- `lib/**` - Future-proofing
Ignore dependencies:
- `guessit` - Needs work to be upgraded. Closes #4609 
Ignore paths:
- `.build/**`
> Update renovate/todo config

- medusa/providers/torrent/json/norbits.py
urljoin removes '?' in end of "download.php?" making the download links be "download.phpid=" instead of "download.php?id="
> Fix norbits provider formatting download url incorrectly.

- CHANGELOG.md
> Update changelog information with NorBits fix

- themes-default/slim/views/manage_episodeStatuses.mako
- themes-default/slim/views/manage_massEdit.mako
- themes/dark/templates/manage_episodeStatuses.mako
- themes/dark/templates/manage_massEdit.mako
- themes/light/templates/manage_episodeStatuses.mako
- themes/light/templates/manage_massEdit.mako
This PR expands the capabilities of `Episode Status Management`. It will be allowed to manage `Downloaded` and `Archived` statuses as well now.
> Expand episode status management functionality. Fixes #4562

- medusa/server/api/v2/base.py
- themes-default/slim/static/css/style.css
- themes-default/slim/views/vue-components/plot-info.mako
- themes/dark/assets/css/style.css
- themes/dark/templates/vue-components/plot-info.mako
- themes/light/assets/css/style.css
- themes/light/templates/vue-components/plot-info.mako
- The plot info bug is only on `develop`, due to the changes made to the API in #4488.
- Fix exception when requesting a non-existent API v2 route.
I can't find the error right now but it was due to this line:
https://github.com/pymedusa/Medusa/blob/be7902d5608279ac408d47effd673bf922699bd8/medusa/server/api/v2/base.py#L99
`self.allowed_methods` was `None`, and you can't concatenate `tuple` and `NoneType`.
> Fix plot info & APIv2 exception

- .codecov.yml
- themes-default/slim/package.json
- tox.ini
> Enable codecov flags

- themes-default/slim/views/config_providers.mako
- themes/dark/templates/config_providers.mako
- themes/light/templates/config_providers.mako
As that is actually what it is.
> Rename Season search mode to Backlog search mode

- medusa/server/web/home/handler.py
Credits & thanks to @sharkykh for the fix.
> Fix KeyError on show removal. Fixes #4670

- .github/build-themes-check.sh
- .travis.yml
- Run `gulp sync` and verify that it works, and that the themes were synced.
It's not foolproof, but might help. @OmgImAlexis 
- Utilize a new feature on Travis - [job names](https://docs.travis-ci.com/user/build-stages?utm_source=blog&utm_medium=web&utm_campaign=build_stages_ga#Naming-your-Jobs-within-Build-Stages)
- Split the frontend test commands (instead of having `&&` everywhere)
> Improve Travis

- themes-default/slim/static/js/templates/root-dirs.vue
- themes-default/slim/views/addShows_addExistingShow.mako
- themes-default/slim/views/addShows_newShow.mako
- themes-default/slim/views/addShows_recommended.mako
- themes-default/slim/views/addShows_trendingShows.mako
- themes/dark/assets/js/templates/root-dirs.vue
- themes/dark/templates/addShows_addExistingShow.mako
- themes/dark/templates/addShows_newShow.mako
- themes/dark/templates/addShows_recommended.mako
- themes/dark/templates/addShows_trendingShows.mako
- themes/light/assets/js/templates/root-dirs.vue
- themes/light/templates/addShows_addExistingShow.mako
- themes/light/templates/addShows_newShow.mako
- themes/light/templates/addShows_recommended.mako
- themes/light/templates/addShows_trendingShows.mako
> Fix tabs (addShows/*)

- medusa/version_checker.py
Fixes https://github.com/pymedusa/Medusa/issues/4683
> Fix Github error 500 exception

- themes-default/slim/views/addShows_addExistingShow.mako
- themes-default/slim/views/addShows_newShow.mako
- themes/dark/templates/addShows_addExistingShow.mako
- themes/dark/templates/addShows_newShow.mako
- themes/light/templates/addShows_addExistingShow.mako
- themes/light/templates/addShows_newShow.mako
Not sure how I missed the fact it didn't actually hide the black/white lists.
> More fixes for addShows

- medusa/providers/torrent/html/yggtorrent.py
> Update YggTorrent URL. Fixes #4723

- CHANGELOG.md
- medusa/providers/torrent/html/abnormal.py
> Fix Abnormal provider login check. Fixes #4724

- themes-default/slim/views/addShows_addExistingShow.mako
- themes-default/slim/views/addShows_newShow.mako
- themes/dark/templates/addShows_addExistingShow.mako
- themes/dark/templates/addShows_newShow.mako
- themes/light/templates/addShows_addExistingShow.mako
- themes/light/templates/addShows_newShow.mako
> Fixes for addShows

- themes-default/slim/views/manage_manageSearches.mako
- themes/dark/templates/manage_manageSearches.mako
- themes/light/templates/manage_manageSearches.mako
- Fix #4738
- Fix disabled buttons weren't actually disabled
- Convert more of the page to Vue format.
> Fix manage/manageSearches

- themes-default/slim/views/manage_massEdit.mako
- themes/dark/templates/manage_massEdit.mako
- themes/light/templates/manage_massEdit.mako
> Fix massEdit page

- CHANGELOG.md
- themes-default/slim/views/home.mako
- themes/dark/templates/home.mako
- themes/light/templates/home.mako
It seems to work. Javascript seems to still work.
> Fix home tabs

- CHANGELOG.md
- medusa/providers/torrent/html/yggtorrent.py
> Update base url to ww3.

- medusa/databases/main_db.py
- medusa/tv/episode.py
Fixes the episode obj queries.
> Add missing commas

- medusa/providers/torrent/html/yggtorrent.py
The issue was caused by the POST redirect that changed the request to a GET (as specification requires) and returned 200. This now made future proof by using `get_redirect_url()` which will return the resolved URL. Also added a better way to check if the user is already authenticated (wasn't checked at all and kept re-authenticating on every snatch).
> Fix Yggtorrent provider login, update URL, made future proof. Fixes #4901

- medusa/providers/nzb/binsearch.py
> Add response verification to BinSearch provider. Fixes #4844

- medusa/clients/torrent/utorrent_client.py
- medusa/providers/torrent/html/yggtorrent.py
- medusa/providers/torrent/json/btn.py
Fixes #4994 - uTorrent
Fixes #4226 - BTN
> Fix uTorrent client & BTN provider

- themes-default/slim/static/css/style.css
- themes/dark/assets/css/style.css
- themes/light/assets/css/style.css
Fix the poster not being aligned.
> Fix home tabs poster layout

- medusa/server/api/v2/internal.py
- Fixes searching indexers for shows broken
- Fixes existing shows list broken
Thanks @medariox
No need for a changelog, directly caused by #4970 which is only in `develop`.
> Fix internal API routes

- ext/github/Consts.py
- ext/github/MainClass.py
- ext/github/Organization.py
- ext/github/Project.py
- ext/github/ProjectCard.py
- ext/github/ProjectColumn.py
- ext/github/Repository.py
- ext/readme.md
> Upgrade pygithub to 1.43.1

- medusa/providers/__init__.py
- medusa/providers/torrent/__init__.py
- medusa/providers/torrent/html/btdb.py
> Add BTDB.to search engine. Closes #5084

- medusa/providers/torrent/json/btn.py
> Add 502 to handled codes for BTN. Fixes #5291

- medusa/__main__.py
- medusa/init/filesystem.py
Hopefully fixes https://github.com/pymedusa/Medusa/issues/5234
> Remove encoding hack, replace with warning

- medusa/sbdatetime.py
- themes-default/slim/views/config_general.mako
- themes-default/slim/views/partials/footer.mako
- themes-default/slim/views/snatchSelection.mako
- themes-default/slim/views/status.mako
- themes/dark/templates/config_general.mako
- themes/dark/templates/partials/footer.mako
- themes/dark/templates/snatchSelection.mako
- themes/dark/templates/status.mako
- themes/light/templates/config_general.mako
- themes/light/templates/partials/footer.mako
- themes/light/templates/snatchSelection.mako
- themes/light/templates/status.mako
> Fix strftime() incompatibility with unicode (for Python 2). Fixes #5301

- medusa/clients/nzb/sab.py
- medusa/server/web/home/handler.py
Also added the warning for missing API key.
> Fix BraceException on SABnzbd snatch. Fixes #5364

- CHANGELOG.md
- medusa/process_tv.py
> Add support for SABnzbd's Direct Unpack feature. Fixes #5379

- themes-default/slim/views/manage_subtitleMissed.mako
- themes/dark/templates/manage_subtitleMissed.mako
- themes/light/templates/manage_subtitleMissed.mako
> Fix subtitleMissed

- CHANGELOG.md
- medusa/server/api/v2/base.py
The config fields were not being updated at all (METADATA_KODI, METADATA_KODI_12PLUS, ...).
> Fix metadata settings not being saved. Fixes #5352

- medusa/helper/common.py
Should fix: https://github.com/pymedusa/Medusa/issues/5434
> Add strm file format support.

- medusa/version_checker.py
RawGit is shutting down: https://rawgit.com/
> Replace cdn.rawgit.com with rawcdn.githack.com

- ext/guessit/__version__.py
- ext/guessit/config/options.json
- ext/guessit/jsonutils.py
- ext/guessit/rules/common/date.py
- ext/guessit/rules/common/formatters.py
- ext/guessit/rules/properties/audio_codec.py
- ext/guessit/rules/properties/country.py
- ext/guessit/rules/properties/episodes.py
- ext/guessit/rules/properties/language.py
- ext/guessit/rules/properties/other.py
- ext/guessit/rules/properties/release_group.py
- ext/guessit/rules/properties/title.py
- ext/guessit/rules/properties/video_codec.py
- ext/guessit/rules/properties/website.py
- ext/guessit/test/episodes.yml
- ext/guessit/test/movies.yml
- ext/guessit/test/rules/title.yml
- ext/guessit/test/rules/video_codec.yml
- ext/guessit/test/test_yml.py
- ext/guessit/test/various.yml
- ext/readme.md
- ext/rebulk/__version__.py
- ext/rebulk/loose.py
- ext/rebulk/match.py
- ext/rebulk/processors.py
- ext/rebulk/rules.py
- ext/rebulk/utils.py
- medusa/name_parser/rules/rules.py
- requirements.txt
- tests/test_guessit.yml
> Update guessit to v3.0.1, rebulk to v1.0.0

- medusa/tv/cache.py
> Fix exception when forcing daily search with season results

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Fix word getting parsed as language with multiple fileparts. Fixes #5181

- CHANGELOG.md
> Move changelog item from 0.2.9 to unreleased.

- medusa/name_parser/rules/rules.py
- medusa/post_processor.py
- medusa/process_tv.py
>  Standardize processing method

- medusa/name_parser/rules/rules.py
> Make rebulk rules Py2/3 compatible

- medusa/search/core.py
Thanks to @sharkykh for the bug report.
> Fix single episodes released as multi not being snatched

- CHANGELOG.md
- medusa/clients/torrent/downloadstation_client.py
> Fix Download Station BraceAdapter exception. Fixes #5572

- medusa/__init__.py
- medusa/app.py
- themes-default/slim/views/partials/footer.mako
- themes/dark/templates/partials/footer.mako
- themes/light/templates/partials/footer.mako
* Use app object instead of having everything on a module level.
This allows us to start using @property and @property.setter annotations.
> Created class for medusa's global app config

- medusa/app.py
> Replace six.viewitems with items() in app.py

- medusa/providers/torrent/html/hdtorrents.py
- medusa/providers/torrent/html/torrentbytes.py
Fixes https://github.com/pymedusa/Medusa/issues/5615
> Fix HD-Torrent's size

- medusa/providers/torrent/json/btn.py
> Add 521 to handled codes for BTN. "Web Server Is Down"

- medusa/search/queue.py
> Fix the evaluation for the snatch_queue item.

- medusa/clients/torrent/downloadstation_client.py
> Fix Download Station BraceAdapter exception (2). Fixes #5588, #5632

- medusa/providers/generic_provider.py
- medusa/providers/torrent/html/btdb.py
>  Update .torrent providers & add missing trackers to btdb magnet

- themes-default/slim/views/partials/schedule/list.mako
- themes/dark/templates/partials/schedule/list.mako
- themes/light/templates/partials/schedule/list.mako
When no show runtime.
Fix #5535
> Fix schedule list layout.

- medusa/app.py
- medusa/version_checker.py
Used for checking if medusa is running in a docker container.
> Added new function runs_in_docker.

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Make FixParentFolderReplacingTitle more strict. Fixes #5713

- CHANGELOG.md
- medusa/server/api/v2/config.py
Fixes https://github.com/pymedusa/Medusa/issues/5727
> fix clients.torrents.path path type

- CHANGELOG.md
- medusa/clients/torrent/__init__.py
> Rename DS client name in clients.torrent init

- themes-default/slim/views/config_subtitles.mako
- themes/dark/templates/config_subtitles.mako
- themes/light/templates/config_subtitles.mako
Following #5740, I forgot to adjust help message of perfect match option.
> Fix perfect match help

- medusa/scene_exceptions.py
attempt to fix https://github.com/pymedusa/Medusa/issues/3451#issuecomment-441791066
> Add logging and return statement, to detect None indexer.

- CHANGELOG.md
- medusa/scene_numbering.py
> Attempt to fix double absolute_numbers getting in

- CHANGELOG.md
- medusa/server/web/manage/handler.py
> Fix episode status comparison in subtitleMissedPP

- .travis.yml
- tests/test_process_tv.py
- themes-default/slim/views/config_search.mako
- themes/dark/templates/config_search.mako
- themes/light/templates/config_search.mako
> Restore the ability to change the daily search interval.

- Dockerfile
> Change handle

- medusa/providers/torrent/html/limetorrents.py
> Update LimeTorrents domain. Fixes #5859

- medusa/server/api/v2/config.py
> Fix saving setting notifiers - kodi allways on.

- medusa/providers/nzb/anizb.py
- medusa/providers/torrent/json/animebytes.py
- medusa/providers/torrent/json/btn.py
- medusa/providers/torrent/json/hdbits.py
- medusa/providers/torrent/json/xthor.py
> Add convert_size to missing providers

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Don't add multiple alias (guessit)

- themes-default/slim/views/config_search.mako
- themes/dark/templates/config_search.mako
- themes/light/templates/config_search.mako
Also fixes: https://github.com/pymedusa/Medusa/issues/5890
> Add 30m proper search interval

- medusa/post_processor.py
- themes-default/slim/views/config_search.mako
- themes/dark/templates/config_search.mako
- themes/light/templates/config_search.mako
> Fix wrong param for add_to_mylist(), fix SABnzbd test button

- ext/readme.md
- ext/six.py
- medusa/helpers/__init__.py
- medusa/server/web/config/general.py
- requirements.txt
> Fix git_reset_branches saved as bytes, update six

- medusa/helpers/__init__.py
* Should still be fixed upstream. Therefor added as error log.
fix #5900
> Added workaround for searching shows like 'Мажор' with imdbpie.

- requirements.txt
> Update requirements subliminal entry

- dredd/dredd_hook.py
- medusa/__main__.py
- medusa/helpers/__init__.py
> Fix config encryption exception. Fixes #5910

- medusa/server/api/v1/core.py
- themes-default/slim/views/apiBuilder.mako
- themes/dark/templates/apiBuilder.mako
- themes/light/templates/apiBuilder.mako
> Fix API v1 arguments values as bytes. Fixes #5819

- medusa/logger/__init__.py
- medusa/server/web/core/error_logs.py
> Fix block size computation for log viewer. Fixes #5931

- medusa/version_checker.py
- setup.py
- tests/providers/conftest.py
- tests/providers/test_search.py
- themes-default/slim/views/partials/home/banner.mako
- themes-default/slim/views/partials/home/poster.mako
- themes-default/slim/views/partials/home/simple.mako
- themes-default/slim/views/partials/home/small.mako
- themes/dark/templates/partials/home/banner.mako
- themes/dark/templates/partials/home/poster.mako
- themes/dark/templates/partials/home/simple.mako
- themes/dark/templates/partials/home/small.mako
- themes/light/templates/partials/home/banner.mako
- themes/light/templates/partials/home/poster.mako
- themes/light/templates/partials/home/simple.mako
- themes/light/templates/partials/home/small.mako
> Fix progressbars (home)

- medusa/show/recommendations/anidb.py
- medusa/show/recommendations/imdb.py
- medusa/show/recommendations/recommended.py
- medusa/show/recommendations/trakt.py
@p0psicles 
Switching from Py2 to 3 and vice versa still doesn't work. The cache file needs to be delete every time. Not sure why.
> Fix recommended shows error. Fixes #5962

- ext/readme.md
- ext/soupsieve/__meta__.py
- ext/soupsieve/css_match.py
- ext/soupsieve/css_parser.py
- ext/soupsieve/css_types.py
- ext2/backports/__init__.py
- ext2/backports/functools_lru_cache.py
> Update soupsieve to v1.7, add missing dependency. Fixes #5968

- medusa/clients/torrent/generic.py
> Catch RequestException in torrent clients, make warning. Fixes: #5921

- medusa/metadata/generic.py
> Fix validate_location usage on episode object. Fixes #5999

- medusa/name_parser/parser.py
> Fix OrderedDict mutated during iteration in name_parser. Fixes #6064

- medusa/__main__.py
> Fix restart after update

- medusa/helpers/__init__.py
- medusa/indexers/indexer_api.py
- medusa/indexers/indexer_config.py
- medusa/name_cache.py
- medusa/notifiers/__init__.py
- medusa/notifiers/kodi.py
- medusa/post_processor.py
- medusa/providers/nzb/newznab.py
- medusa/sbdatetime.py
- medusa/scene_exceptions.py
- medusa/search/core.py
- medusa/server/api/v2/internal.py
- medusa/server/web/config/providers.py
- medusa/server/web/config/subtitles.py
- medusa/server/web/manage/handler.py
- medusa/show/naming.py
- medusa/updater/source_updater.py
- setup.cfg
> Fix tests by updating flake8 rules

- medusa/name_parser/rules/rules.py
- setup.py
https://github.com/pymedusa/Medusa/issues/3575#issuecomment-458011454
😖
> Fix guessit exception when trying to parse music releases

- medusa/server/web/home/add_shows.py
> Decode other_shows in newShow. Fixes #6185

- themes-default/slim/views/config_search.mako
- themes/dark/templates/config_search.mako
- themes/light/templates/config_search.mako
> Fix wrong Forced backlog search day(s) description. Fixes #6161

- medusa/providers/nzb/binsearch.py
> Use response.text instead of content for nzb_check_segment. Fixes #6195

- medusa/clients/nzb/nzbget.py
> Fix wrong placeholder name causing BraceException. Fixes #6165

- lib/synchronousdeluge/__init__.py
- lib/synchronousdeluge/exceptions.py
- lib/synchronousdeluge/protocol.py
- lib/synchronousdeluge/transfer.py
Fixes https://github.com/pymedusa/Medusa/issues/5304#issuecomment-465297171
> Fix synchronousdeluge lib returning bytes. Fixes #5304

- medusa/show_updater.py
> Fix unnecessary float comparison in show_updater. Fixes #6247

- medusa/__main__.py
- medusa/naming.py
- medusa/server/api/v1/core.py
- medusa/tv/episode.py
- medusa/tv/series.py
- themes-default/slim/views/editShow.mako
- themes/dark/templates/editShow.mako
- themes/light/templates/editShow.mako
Multi-ep examples now show 3 episodes instead of 2 to properly display the `Limited` pattern:
>  Clean up naming pattern validation. Fixes #6237

- medusa/server/web/home/add_shows.py
Fixes https://github.com/pymedusa/Medusa/issues/5884#issuecomment-467691185
> Decode one more other_shows in add_shows. Fixes #5884

- medusa/session/hooks.py
Fixes https://github.com/pymedusa/Medusa/issues/5819#issuecomment-468495408
> Fix log_url() error if request.body is bytes. Fixes #5819

- medusa/session/hooks.py
> Use errors='replace' if request.body decoding fails

- runscripts/init.systemd
> Default systemd to Type=simple

- medusa/server/api/v1/core.py
> Fix History APIv1 call reference, rename tvdbid to show_id

- medusa/name_parser/parser.py
- medusa/tv/cache.py
- medusa/tv/series.py
- setup.cfg
Also tries to fix https://github.com/pymedusa/Medusa/issues/3451#issuecomment-468987693
> Discard releases with multiple versions. Fixes #5429

- medusa/helpers/__init__.py
Closes https://github.com/pymedusa/Medusa/issues/6231
> Change consider adding show suggestion to info

- .travis.yml
- ext/readme.md
- ext2/yaml/__init__.py
- ext2/yaml/composer.py
- ext2/yaml/constructor.py
- ext2/yaml/cyaml.py
- ext2/yaml/dumper.py
- ext2/yaml/emitter.py
- ext2/yaml/loader.py
- ext2/yaml/reader.py
- ext2/yaml/representer.py
- ext2/yaml/scanner.py
- ext3/yaml/__init__.py
- ext3/yaml/composer.py
- ext3/yaml/constructor.py
- ext3/yaml/cyaml.py
- ext3/yaml/dumper.py
- ext3/yaml/emitter.py
- ext3/yaml/loader.py
- ext3/yaml/reader.py
- ext3/yaml/representer.py
- ext3/yaml/scanner.py
- setup.py
- tests/providers/conftest.py
- tests/test_guessit.py
> Update pyyaml to version 5.1

- CHANGELOG.md
- medusa/notifiers/kodi.py
- medusa/notifiers/slack.py
- medusa/providers/torrent/html/bjshare.py
- medusa/providers/torrent/json/torrentday.py
- medusa/scene_exceptions.py
> Fix Kodi notifications decoding. Fixes #6354

- CHANGELOG.md
- medusa/app.py
- medusa/databases/main_db.py
- medusa/tv/series.py
- medusa/updater/github_updater.py
- medusa/updater/version_checker.py
> Fix auto update causing DB issues

- medusa/clients/torrent/deluged.py
> Fix trying to retrieve 'hash' from an empty dict. Fixes #6377

- medusa/notifiers/kodi.py
> Fix sending kodi notifications using python3

- CHANGELOG.md
- medusa/classes.py
Fixes https://github.com/pymedusa/Medusa/issues/5657#issuecomment-478948606
> Fix snatching of air by date shows specials

- .github/build-themes-check.sh
Big thanks to @sharkykh for making sure this actually works.
> Improve Travis build check by adding size comparison

- medusa/__main__.py
- medusa/helper/common.py
- medusa/metadata/tivo.py
- medusa/name_parser/parser.py
- medusa/notifiers/emailnotify.py
- medusa/post_processor.py
- medusa/providers/generic_provider.py
- medusa/providers/torrent/html/elitetracker.py
- medusa/scene_exceptions.py
- medusa/search/core.py
- medusa/server/web/home/add_shows.py
- medusa/server/web/home/handler.py
- medusa/subtitle_providers/wizdom.py
- tests/name_parser/test_parse_anime.py
- tests/name_parser/test_parse_series.py
> Fix anime series not being matched to found results

- medusa/logger/__init__.py
> Open log file as unicode instead of bytes. Fixes #5463

- medusa/providers/torrent/html/yggtorrent.py
- readme.md
Since 2 days Yggtorrent have a new domain (.ch) and .to is unreachable
> New url for Yggtorrent provider

- medusa/server/api/v2/alias.py
- medusa/server/api/v2/alias_source.py
- medusa/server/api/v2/auth.py
- medusa/server/api/v2/base.py
- medusa/server/api/v2/config.py
- medusa/server/api/v2/episodes.py
- medusa/server/api/v2/internal.py
- medusa/server/api/v2/log.py
- medusa/server/api/v2/series.py
- medusa/server/api/v2/series_asset.py
- medusa/server/api/v2/series_legacy.py
- medusa/server/api/v2/series_operation.py
- medusa/server/api/v2/stats.py
- medusa/server/core.py
- Better exception logging
- Async code is more DRY and more dynamic,
as the async function is bound for every request.
> Further improvements to API v2 multithreading

- medusa/server/api/v2/stats.py
- medusa/server/web/home/handler.py
I don't know if and how much it will help for #5311 (in the meantime at least)
> Optimize show_statistics()

- medusa/providers/torrent/html/btdb.py
> Fix rare BTDB exception when there are no recent items. Fixes #6729

- medusa/clients/torrent/deluged.py
Avoids a few unnecessary exceptions.
> Improve DelugeD connect() to only return True if connected

- medusa/updater/source_updater.py
> Catch RequestException in list_remote_branches(). Fixes #6312, #6767

- medusa/providers/torrent/torrent_provider.py
> Use old method to get the redirect URL for Jackett. Fixes #6788

- medusa/system/schedulers.py
- themes-default/slim/views/apiBuilder.mako
- themes-default/slim/views/layouts/main.mako
- themes/dark/templates/apiBuilder.mako
- themes/dark/templates/layouts/main.mako
- themes/light/templates/apiBuilder.mako
- themes/light/templates/layouts/main.mako
#6820
Also fix `apiBuilder` page
> Fix 'show_dir' referenced before assignment

- medusa/system/schedulers.py
> Fix #6820 - RuntimeError: threads can only be started once

- CHANGELOG.md
- medusa/providers/torrent/html/hdtorrents.py
> Fix pubdate should have the date parsed with the day first

- medusa/server/web/home/handler.py
- medusa/server/web/manage/handler.py
- medusa/tv/series.py
Also remove some `future` imports and fix incorrect checks
> Fix incorrect cache image type in Series class

- themes-default/slim/views/config_notifications.mako
- themes/dark/templates/config_notifications.mako
- themes/light/templates/config_notifications.mako
> Remove mako declarations.

- medusa/indexers/utils.py
> Use pre-compiled show slug pattern

- dredd/api-description.yml
- medusa/tv/episode.py
* Change content from array to object.
* Update api-description.yml
Removing weight from #6709
> Add property watched to episode to_json.

- medusa/tv/series.py
Fixes #6928 
I changed the type in [#6880](https://github.com/pymedusa/Medusa/pull/6880/commits/d610b4d91963c5f758b2f2515929ca066334f5f0#diff-698951749413f44382a71a0c0de61886)
> Fix saving release groups

- .travis.yml
- medusa/common.py
- medusa/post_processor.py
- medusa/recompiled/tags.py
- medusa/tagger/episode.py
- tests/test_postprocessor_parse_info.py
* Allow for upgrading the found quality from filename -> full path.
* Added unit test
inspired by: #6967
> Improve postprocessing name parsing.

- medusa/common.py
Forgot to add it in https://github.com/pymedusa/Medusa/pull/6982
> Add optional anime argument in name parser recursion

- medusa/show/naming.py
> Escape word used in regex filter. Fixes #7068

- Dockerfile
> Add timezone package

- medusa/tv/series.py
Fixes https://github.com/pymedusa/Medusa/issues/7074
> Only show warning if app.CREATE_MISSING_SHOW_DIRS is disabled

- ext/readme.md
- requirements.txt
- setup.py
Be sure to update `medusa_vendor_tools` to `v0.3.0`.
> Update requirement lists

- medusa/show_queue.py
After `self.show.default_ep_status = self.default_status_after` the changes need to be saved or they will be lost when force terminating Medusa.
Fixes https://github.com/pymedusa/Medusa/issues/6187
> Save updated show info when adding new show

- medusa/providers/generic_provider.py
- medusa/scene_numbering.py
- medusa/search/queue.py
- tests/providers/test_generic_provider.py
It will be set, but won't be used until enabled.
Closes https://github.com/pymedusa/Medusa/issues/7105
> Allow to set scene numbering even if disabled

- CHANGELOG.md
- medusa/providers/torrent/json/animebytes.py
Attempt to fix #7173 
As it depends on which eps currently are provided by the daily search, I could not test the fix.
> Add multi episode start + end, instead of asuming it starts with 1.

- CHANGELOG.md
- medusa/name_parser/rules/rules.py
- medusa/search/queue.py
Fixes https://github.com/pymedusa/Medusa/issues/5304#issuecomment-534214402
> Fix guessit UnicodeDecodeError on join (Py2)

- CHANGELOG.md
- ext/adba/aniDBtvDBmaper.py
- ext/readme.md
- requirements.txt
Fixes https://github.com/pymedusa/Medusa/issues/6147#issuecomment-541270407
> Fix exception when there is no anime XML

- themes-default/slim/views/partials/schedule/list.mako
- themes/dark/templates/partials/schedule/list.mako
- themes/light/templates/partials/schedule/list.mako
> fix schedule list plot info

- themes-default/slim/views/partials/schedule/list.mako
- themes/dark/templates/partials/schedule/list.mako
- themes/light/templates/partials/schedule/list.mako
I messed up on #7260 and completely missed it. Sorry.
> correctly fix schedule list plot info

- medusa/classes.py
- medusa/providers/generic_provider.py
- medusa/providers/nzb/nzb_provider.py
- medusa/providers/torrent/torrent_provider.py
- medusa/providers/torrent/torznab/torznab.py
- medusa/search/core.py
- medusa/search/proper.py
- medusa/server/web/home/handler.py
- medusa/tv/cache.py
- tests/conftest.py
- tests/test_search_core.py
> Refactor SearchResult

- themes-default/slim/views/manage_backlogOverview.mako
- themes/dark/templates/manage_backlogOverview.mako
- themes/light/templates/manage_backlogOverview.mako
* Bug introduced by merge of displayShow.vue PR.
> manage_backlogOverview.mako: Fix updating forced search icons.

- CHANGELOG.md
- medusa/image_cache.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/metadata/generic.py
> Changes for TVDB API v3

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
This should still be reported to guessit.
> Fix guessit anime titles treated as multiple episodes. Fixes #7396

- medusa/name_parser/parser.py
> Fix missing episode numbers when anime doesn't have scene season

- .build/package.json
- .build/yarn.lock
> Update bower to version 1.8.8

- medusa/search/queue.py
> Fix backlog search queue with multiple items. Fixes #7448

- themes-default/slim/views/manage_manageSearches.mako
- themes/dark/templates/manage_manageSearches.mako
- themes/light/templates/manage_manageSearches.mako
> Fix show number forced searches, in manage_manageSearches.mako.

- medusa/tv/series.py
> Add last_update_indexer to Series() to_json().

- medusa/providers/torrent/html/yggtorrent.py
YggTorrent updated its domain name once again.
> Update YggTorrent Domain

- medusa/name_parser/parser.py
> Make NameParserCache thread safe. Fixes #7537

- medusa/name_parser/parser.py
- medusa/scene_numbering.py
No idea why this was like this. Fixes https://github.com/pymedusa/Medusa/issues/7575
Also fixes https://github.com/pymedusa/Medusa/issues/7576
> Fix parse result removing episodes if they are like absolute episodes

- medusa/name_parser/parser.py
- medusa/scene_numbering.py
This method should always return something. Introduced with previous PR.
> Fix absolute number returned as None if not existing as scene exception

- ext/cfscrape/__init__.py
- ext/js2py/internals/constructors/jsfunction.py
- ext/js2py/py_node_modules/underscore.py
- ext/js2py/test_internals.py
- ext/pyjsparser/__init__.py
- ext/pyjsparser/parser.py
- ext/pyjsparser/pyjsparserdata.py
- ext/pyjsparser/std_nodes.py
- ext/readme.md
- requirements.txt
> Update cfscrape to fix new CF challenge

- ext/readme.md
- setup.py
> Mention Monkey-patched libraries on `ext/readme.md`

- CHANGELOG.md
- medusa/scene_numbering.py
Fixes https://github.com/pymedusa/Medusa/issues/5883#issuecomment-577066307
> Fix rare parser exception when anime episode doesn't exist. Fixes #5883

- .build/package.json
- .build/yarn.lock
> Update grunt dependencies

- CHANGELOG.md
- medusa/name_parser/guessit_parser.py
> Fix guessit parser not using scene exceptions

- CHANGELOG.md
- tests/report_guessit.py
> Update report guessit to work with aliases

- .travis.yml
To fix the `aliases` warning I used https://link.medium.com/vUG5hZ9oW3
> Fix travis config warnings

- medusa/__main__.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/scheduler.py
- medusa/show_updater.py
- medusa/tv/series.py
Shows will always be updated after max. 12 weeks or when the indexer has an update for them.
> Fix show updater not updating shows without recent updates

- medusa/indexers/indexer_base.py
- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvdbv2/fallback.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/indexers/tvmaze/tvmaze_api.py
- Use the same logic across all indexers
- Fix TheTVDB fallback triggering when it was not required (fixes https://github.com/pymedusa/Medusa/issues/7817)
- Fix https://github.com/pymedusa/Medusa/issues/7567
> Standardize show search across indexers

- medusa/providers/torrent/html/pretome.py
> Add pubdate support to pretome

- medusa/indexers/tvdbv2/tvdbv2_api.py
Fixes https://github.com/pymedusa/Medusa/issues/7809
Fixes https://github.com/pymedusa/Medusa/issues/7511
> Fix updating seasons of shows without episodes. Fixes #7511

- CHANGELOG.md
- medusa/show_queue.py
> Catch indexer specific exceptions in show refresh

- medusa/server/api/v2/auth.py
> Fix auth token returned as bytes. Fixes #7777

- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/providers/torrent/json/xthor.py
Fixes https://github.com/pymedusa/Medusa/issues/7329#issuecomment-599161246
> Fix TVDB error when no paginated data is returned

- medusa/providers/torrent/torznab/torznab.py
> Add torznab cat "other" by default. fixes providers without cats.

- medusa/app.py
> Use own API key for TheTVDB

- medusa/post_processor.py
- medusa/subtitles.py
- tests/test_subtitles.py
- themes-default/slim/views/config_subtitles.mako
- themes/dark/templates/config_subtitles.mako
- themes/light/templates/config_subtitles.mako
Prevents the execution of RCE. Thanks to @Sudneo for the report!
> Restrict scripts execution to Python scripts for security reasons

- CHANGELOG.md
- medusa/post_processor.py
Feature request https://github.com/pymedusa/Medusa/issues/4034
> Search sub-folders for subtitles during post-processing

- medusa/scheduler.py
> Make scheduler runs thread safe

- medusa/providers/torrent/html/yggtorrent.py
> Add Saison as a season pack search word

- medusa/server/core.py
> Fix setting event loop policy

- CHANGELOG.md
- themes-default/slim/views/partials/schedule/calendar.mako
- themes/dark/templates/partials/schedule/calendar.mako
- themes/light/templates/partials/schedule/calendar.mako
> Fix schedule calendar view

- medusa/subtitles.py
Fixes https://github.com/pymedusa/Medusa/issues/7988, https://github.com/pymedusa/Medusa/issues/7958
subliminal bug report: https://github.com/Diaoul/subliminal/issues/999
> Fix subliminal exception when passing titles that are not strings

- medusa/providers/torrent/html/scenetime.py
Fixes: https://github.com/pymedusa/Medusa/issues/6729
> Fix SceneTime when there are no results

- CHANGELOG.md
- medusa/classes.py
- medusa/indexers/tmdb/tmdb.py
- medusa/indexers/tvdbv2/tvdbv2_api.py
- medusa/indexers/tvmaze/tvmaze_api.py
* A search by id is tried when the search term is a digit.
* Fixed searching by alias (tvdb)
> Add feature to search by indexer id.

- ext/readme.md
- ext/tmdbsimple/__init__.py
- ext/tmdbsimple/account.py
- ext/tmdbsimple/base.py
- ext/tmdbsimple/changes.py
- ext/tmdbsimple/configuration.py
- ext/tmdbsimple/discover.py
- ext/tmdbsimple/find.py
- ext/tmdbsimple/genres.py
- ext/tmdbsimple/movies.py
- ext/tmdbsimple/people.py
- ext/tmdbsimple/search.py
- ext/tmdbsimple/tv.py
- lib/readme.md
- medusa/indexers/tmdb/api.py
- requirements.txt
My PR from 2 years ago got merged so there's no need to use a custom version.
> Update `tmdbsimple` to 2.2.5

- themes-default/slim/package.json
- themes-default/slim/yarn.lock
> Use tar.gz instead of git

- medusa/updater/update_manager.py
> Catch exception on version check. Fixes #7997, #8005

- medusa/providers/nzb/newznab.py
Also removed deprecated Torznab support.
> Fix Newznab support for docker container names

- .travis.yml
https://docs.travis-ci.com/user/common-build-problems/#travis_retry
> Make use of `travis_retry`

- medusa/helpers/__init__.py
> Change urls to https

- medusa/indexers/utils.py
- medusa/show/recommendations/recommended.py
> Check trakt external id's, for shows that are already in the library.

- ext/readme.md
- ext/ttl_cache.py
- medusa/helpers/utils.py
- medusa/tv/series.py
> Replace custom timed cache decorator with ttl-cache

- medusa/search/core.py
- medusa/tv/cache.py
- Cached season results will now be used
- If after a cache search there are still episodes needed, a provider search will be triggered
> Add support for cached season results

- medusa/tv/series.py
> By default return a list, not string.

- medusa/search/core.py
> Fix backlog search ignoring found cached results

- medusa/updater/github_updater.py
> Don't warn when using deprecated git options

- renovate.json
> Limit PRs per hour to reduce Travis workload

- medusa/post_processor.py
> Fix no max seasons when the show is incomplete. Fixes #8429

- ext/readme.md
- ext/validators/__init__.py
- ext/validators/url.py
- renovate.json
- requirements.txt
This reverts commit c30eaa2393a16c5589797ac173fd3c753439259a.
> Revert "Update Python dependency validators to v0.16.0 (#8326)"

- medusa/name_parser/guessit_parser.py
Fixes https://github.com/pymedusa/Medusa/issues/8516
> Fix scene exceptions with year not being used

- medusa/clients/torrent/qbittorrent.py
> Fix qBittorrent Unsupported Media Type

- medusa/network_timezones.py
Fixes constant report of https://github.com/pymedusa/Medusa/issues/8423
> Don't strip() channel names so they are matched correctly

- .travis.yml
> chore(travis): bump node version to 12.18.2

- medusa/server/web/core/base.py
Fixes https://github.com/pymedusa/Medusa/issues/8230
> Avoid exception when headers have no host

- medusa/server/api/v2/base.py
Fixes https://github.com/pymedusa/Medusa/issues/8506
> Use b64decode instead of deprecated decodestring

- medusa/providers/torrent/html/iptorrents.py
Fixes https://github.com/pymedusa/Medusa/issues/8674
> Fix IPTorrents layout change

- medusa/providers/torrent/json/eztv.py
Thanks to @JorgMuskens for the original PR.
> Update eztv provider url

- medusa/notifiers/emailnotify.py
- medusa/notifiers/prowl.py
- medusa/tv/series.py
- tests/notifiers/test_emailnotify.py
> Fix email/powl notifications

- lib/rtorrent/lib/xmlrpc/basic_auth.py
- medusa/helpers/__init__.py
> Change decode/encode string -> bytes

- medusa/providers/generic_provider.py
- medusa/tv/episode.py
> Add properties for scene numbering

- CHANGELOG.md
- medusa/indexers/tmdb/api.py
- medusa/tv/series.py
> Fix searching show, episodes and fanart by language code.

- medusa/queues/show_queue.py
- medusa/server/api/v2/search.py
> Fix backlog search on new show add & wanted switch for old episodes

- medusa/clients/torrent/generic.py
> Fix exception when torrent clients don't respond

- .github/workflows/api-tests.yml
- .github/workflows/python-backend.yml
> Use pull_request for GH actions

- medusa/app.py
> Add Processing failed for ... to custom logs

- medusa/__main__.py
- medusa/updater/github_updater.py
> Fix startup with git install without valid git

- .github/check_version.py
- .github/workflows/version-check.yml
> Add app version check

- .github/ISSUE_TEMPLATE/feature_request.md
> Update template for feature requests

- CHANGELOG.md
- medusa/queues/show_queue.py
> Fix setting default episode status.

- medusa/post_processor.py
- medusa/process_tv.py
> Revert "Allow torrent client move when process_method is 'copy'"

- medusa/app.py
> Fix starting threads on startup

- medusa/schedulers/utils.py
> Add episode updater to the schedulers

- medusa/process_tv.py
> Move testrar() to avoid high CPU load

- medusa/failed_history.py
- medusa/post_processor.py
- medusa/schedulers/episode_updater.py
- medusa/schedulers/trakt_checker.py
- medusa/search/core.py
- medusa/server/web/home/handler.py
- medusa/tv/episode.py
- medusa/tv/series.py
- tests/test_update_status_quality.py
> Use setter to set episode status

- medusa/search/queue.py
- medusa/server/api/v2/episodes.py
- medusa/server/web/home/handler.py
- medusa/tv/base.py
- medusa/tv/episode.py
- medusa/tv/series.py
- tests/test_guessit.py
> Fix setting dirty setter for properties

- medusa/name_parser/guessit_parser.py
- medusa/name_parser/parser.py
- medusa/name_parser/rules/rules.py
- medusa/post_processor.py
- medusa/tv/episode.py
- tests/test_guessit.yml
> Fix post-processor missing some episode attributes

- medusa/providers/generic_provider.py
- medusa/providers/torrent/torrent_provider.py
> Remove the pipes

- medusa/notifiers/trakt.py
- medusa/server/web/home/handler.py
- medusa/tv/episode.py
> Fix trakt sync exception

- themes-default/slim/views/config_providers.mako
- themes/dark/templates/config_providers.mako
- themes/light/templates/config_providers.mako
Adds missing buttons reported in #9034
> Add missing save button

- medusa/tv/series.py
> Avoid exception for shows that don't have show_lists in DB

- medusa/tv/series.py
> Fix setting air attr for shows

- ext/dogpile/__init__.py
- ext/dogpile/cache/api.py
- ext/dogpile/cache/backends/__init__.py
- ext/dogpile/cache/backends/file.py
- ext/dogpile/cache/backends/memcached.py
- ext/dogpile/cache/backends/memory.py
- ext/dogpile/cache/backends/redis.py
- ext/dogpile/cache/proxy.py
- ext/dogpile/cache/region.py
- ext/dogpile/cache/util.py
- ext/dogpile/lock.py
- ext/dogpile/util/compat.py
- ext/dogpile/util/langhelpers.py
- ext/dogpile/util/nameregistry.py
- ext/dogpile/util/readwrite_lock.py
- ext/readme.md
- ext/validators/__init__.py
- ext/validators/btc_address.py
- ext/validators/url.py
- ext/validators/uuid.py
- renovate.json
- requirements.txt
> Update validators & dogpile.cache

- medusa/server/api/v2/base.py
> Fix exception caused when Basic auth header is send.

- medusa/updater/github_updater.py
This is what was probably causing the auto updater to brake. Since a checkout doesn't get any new files.
> Never use checkout on update

- medusa/common.py
- medusa/tv/episode.py
> Use location as fallback if there is no release group for SQN

- medusa/server/web/home/handler.py
> Fix delete show.

- medusa/common.py
- medusa/tv/episode.py
> Use location as fallback if there is no release group for SQN (2)

- medusa/server/web/home/handler.py
- themes-default/slim/static/js/ajax-episode-search.js
- themes/dark/assets/js/ajax-episode-search.js
- themes/light/assets/js/ajax-episode-search.js
> Fix getManualSearchStatus when called by schedule page.

- CHANGELOG.md
- medusa/clients/torrent/qbittorrent.py
* Requires qbit api version > 2.0.0
Fix for #7529
> Fix set label qbittorrent

- CHANGELOG.md
- medusa/name_parser/rules/rules.py
> Fix guessit exception because of missed unique episodes detection

- ext/readme.md
- ext/trakt/__init__.py
- ext/trakt/calendar.py
- ext/trakt/sync.py
- requirements.txt
> Update trakt back to pyTrakt release 2.15.0

- medusa/post_processor.py
- medusa/tv/episode.py
Fixes https://github.com/pymedusa/Medusa/issues/8931
> Post-process fallback as anime if the show is anime

- medusa/server/web/home/handler.py
- medusa/server/web/manage/handler.py
> Put back the legacy setStatus route.

- medusa/providers/nzb/newznab.py
- medusa/providers/torrent/torznab/torznab.py
> Don't force new search if results are found for newznab/torznab

- medusa/providers/generic_provider.py
- medusa/providers/nzb/newznab.py
- medusa/providers/torrent/torrent_provider.py
> Use info_hash as identifier for providers, that use a magnet url.

- medusa/providers/torrent/html/iptorrents.py
> Add custom url option

- CHANGELOG.md
- medusa/tv/episode.py
> Don't save removed episode location as dot

- medusa/providers/torrent/json/ncore.py
> Ncore base url is changed

- medusa/providers/torrent/json/animebytes.py
* These prevented from getting results for some shows.
> Remove params

- medusa/providers/torrent/html/iptorrents.py
In order to take advantage of the newly added custom_url
property (from commit #9273 which closed issue #9185), 
this change updates the default url variable with
the custom_url variable (if it is populated).
> IPTorrents: use custom_url in search() and login()

- medusa/providers/torrent/html/nebulance.py
> Extract download id, as primary key for result

- medusa/providers/torrent/json/animebytes.py
> Add aditional AB check for Episode.

- medusa/history.py
> Fix error with ClientStatus import

- medusa/schedulers/download_handler.py
> Added error handling, to get provider that's causing this.

- medusa/session/handlers.py
> Add Cloudflare BFM detection

- medusa/providers/torrent/html/iptorrents.py
- medusa/providers/torrent/html/yggtorrent.py
- medusa/providers/torrent/json/torrentday.py
- medusa/session/handlers.py
> Update some provider domains

- medusa/__main__.py
> Fix provider ratio getting lost after restart

- medusa/helpers/__init__.py
> Only use imdb titles matched by year.

- medusa/schedulers/episode_updater.py
> This is the query that can get all prev_dates in one go.

- medusa/providers/torrent/html/beyondhd.py
Fixes #8835  #8786.  Code was referencing 3 table cells but only checking for the count of two.
> Fix IndexError:list index out of range [Beyond-HD]

- medusa/post_processor.py
> Use parent folder to check for free disk space

- medusa/providers/torrent/html/tokyotoshokan.py
- tests/providers/torrent/tokyotoshokan/tokyotoshokan_test.yaml
> Fixed parsing size property of Tokyo Toshokan search results (#9467)

- medusa/clients/torrent/qbittorrent.py
- medusa/clients/torrent/rtorrent.py
- medusa/clients/torrent/utorrent.py
Introduced this bug recently myself.
> Fix qbittorrent

- medusa/queues/show_queue.py
> Add refreshShow to end of the the show_queue.addShow thread.

- CHANGELOG.md
- medusa/metadata/kodi_12plus.py
> Use uniqueid to specify the indexer used. (tvdb, tmdb, tvmaze, etc).

- medusa/server/api/v2/auth.py
> Fix JWT generation for API v2

- medusa/process_tv.py
> Fix PP starting to pp entire download folder, when processing season packs with multiple video files.

- medusa/generic_update_queue.py
- medusa/server/api/v2/recommended.py
- medusa/show/recommendations/trakt.py
With this change it won't attempt a trakt sync when trakt is disabled in config - notifications.
Also exception handling has been improved.
> Improve trakt recommended list sync, exceptions and warnings/feedback.

- medusa/name_parser/parser.py
...instead of continuing just to fail later on
@duramato
> Raise InvalidNameException for unsupported release names

- medusa/name_parser/parser.py
> Fix name parser not accepting season results

- medusa/name_parser/parser.py
> Fix parsing specials. (season 0, ep x)

- medusa/providers/torrent/json/animebytes.py
> Add basic exception handling

- .github/workflows/docker-image-develop.yml
> Update and rename docker-image.yml to docker-image-develop.yml

- medusa/__main__.py
> Fix loading search_delay on startup

- .github/workflows/docker-image-master.yml
> Add latest tag to Docker master build

- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
In an attempt to fix #9978 
@medariox I tried creating a guessit rule. But it's failing with the error:
No idea what i'm doing wrong.
Can you take a look?
> Add rule for parsin shows that begin with a number as title.

- medusa/clients/torrent/deluge.py
- medusa/clients/torrent/transmission.py
- medusa/clients/torrent/utorrent.py
* deluge
* transmission
* utorrent
> Allow a ratio of 0 to be set for:

- medusa/schedulers/trakt_checker.py
> Don't try to add from sync trakt, when trakt doesnt have the indexer id.

- medusa/providers/torrent/html/morethantv.py
> Fixed provider morethantv

- themes-default/slim/src/components/sub-menu.vue
- themes-default/slim/src/router/sub-menus.js
Fix update library button from displayShow page.
Fix #10111
> Fix update kodi library

- medusa/scene_numbering.py
> All() should only get one value.

- CHANGELOG.md
> Testing docker build

- .github/workflows/docker-image-develop.yml
> merge workflow back into develop

- medusa/providers/torrent/json/torrentday.py
when parsing a result with single backslash in it.
> Fix torrentday generating a JSONDecodeError

- medusa/server/api/v2/notifications.py
> Fix Plex Server library update from /manage/plex

- medusa/helpers/externals.py
- medusa/helpers/trakt.py
- medusa/notifiers/trakt.py
- medusa/queues/show_queue.py
- medusa/schedulers/trakt_checker.py
- medusa/server/web/home/add_shows.py
- medusa/server/web/home/handler.py
- test_requirements.txt
> Added RequestException to trakt exception handling.

- medusa/name_parser/rules/rules.py
- test_requirements.txt
- tests/test_guessit.yml
> Fix guessit parsing for show 1883

- medusa/indexers/tmdb/api.py
> Fix searching by id, when the show's title is a number.

- medusa/server/web/home/handler.py
- themes-default/slim/src/components/manage-mass-edit.vue
> small typos

- .github/workflows/docker-image-master.yml
> Use new docker build action

- medusa/__main__.py
- themes-default/slim/src/components/config-post-processing.vue
> Remove dereferer references, default anon_redirect to anonym.to

- CHANGELOG.md
- medusa/metadata/generic.py
> Fix saving season posters/banners for tvdb.

- medusa/tv/series.py
> Load seach templates when loading from indexer.

- medusa/queues/show_queue.py
- medusa/tv/series.py
- themes-default/slim/src/components/change-indexer.vue
> After running change-indexer. Update the link to the new show.

- medusa/metadata/generic.py
* Broken because of recent metadata changes.
> Fix getting the show's indexer/indexer_id from metadata.

- medusa/post_processor.py
Fix for #8378 
credits to [h3llrais3r](https://github.com/h3llrais3r)
> Fix detecting thumb images as an associated file.

- themes-default/slim/src/components/config-subtitles.vue
- themes-default/slim/src/components/helpers/config-subtitle-languages.vue
> Fix using multi-country same language codes

- medusa/clients/torrent/deluge.py
- medusa/clients/torrent/qbittorrent.py
> Use content_path for the resource.

- medusa/__main__.py
- themes-default/slim/src/components/manage/change-indexer-row.vue
> Fix update the selected indexer when using the search component.

- CHANGELOG.md
- medusa/name_parser/parser.py
- medusa/search/core.py
> Fix season packs not parsed.

- medusa/providers/torrent/torznab/torznab.py
> Fix parsing torrent_size for torznab providers

- themes-default/slim/src/components/manage-mass-update.vue
> Fix manage-mass-update: Starting the refresh action

- medusa/indexers/imdb/api.py
> Fix getting the default poster

- themes-default/slim/src/components/helpers/externals.vue
> Remove indexer from externals

- themes-default/slim/src/components/app-header.vue
- themes-default/slim/test/specs/__snapshots__/app-header.spec.js.snap
* Use a grid to render two rows with three columns.
before:
after:
> Improve the menu on mobile

- medusa/indexers/imdb/api.py
> Fix adding shows that don't have an imdb id

- medusa/tv/series.py
> Improve the way next-airdate is calculated

- themes-default/slim/src/components/config-anime.vue
- themes-default/slim/src/components/config-general.vue
- themes-default/slim/src/components/config-providers.vue
- themes-default/slim/src/components/config-search.vue
- themes-default/slim/src/components/helpers/config-custom-newznab.vue
- themes-default/slim/src/components/helpers/config-custom-torrentrss.vue
- themes-default/slim/src/components/helpers/config-custom-torznab.vue
- themes-default/slim/src/components/helpers/config-provider-nzb.vue
- themes-default/slim/src/components/helpers/config-provider-torrent.vue
- themes-default/slim/src/components/new-show-search.vue
- themes-default/slim/src/components/recommended.vue
- themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap
> Add media query to improve he sizing of the show search input.

- themes-default/slim/src/components/edit-show.vue
> Disable experimental for search templates

- medusa/indexers/tmdb/api.py
> Fix tmdb indexer search with other language not working

- themes-default/slim/src/components/config-providers.vue
> Make sure the "Save Changes" button has a purpose.

- themes-default/slim/src/components/display-show.vue
> Fix api calls in displayShow.

- themes-default/slim/src/store/modules/provider.js
- themes-default/slim/src/store/modules/shows.js
> Fix errors in using rootState auth.

- themes-default/slim/src/components/app.vue
- themes-default/slim/src/components/config-notifications.vue
- themes-default/slim/src/components/config-search.vue
- themes-default/slim/src/components/recommended-poster.vue
- themes-default/slim/src/components/sub-menu.vue
> Fix missing auth.client mappings

- themes-default/slim/src/components/manual-post-process.vue
> Fix manual pp

- themes-default/slim/src/components/recommended-poster.vue
> Fix removedFromMedusa.

- CHANGELOG.md
- themes-default/slim/src/components/helpers/config-scene-exceptions.vue
> Add ability to select xem seasons for season scene exceptions

- themes-default/slim/src/components/app.vue
- themes-default/slim/src/components/new-shows-existing.vue
> Exclude new-show component from <keep-alive />

- themes-default/slim/static/css/style.css
- themes/dark/assets/css/style.css
- themes/light/assets/css/style.css
> Improve alignment menu buttons.

- themes-default/slim/src/components/sub-menu.vue
> Fix submenu spacing

- .gitignore
- medusa/server/api/v2/system.py
- medusa/server/web/config/backup_restore.py
- themes-default/slim/src/components/config-backup-restore.vue
- themes-default/slim/src/components/display-show.vue
> Move backup/restore to apiv2

- medusa/failed_processor.py
> Fix joining segments in log for failed episodes

- medusa/providers/torrent/html/morethantv.py
> Fixed morethentv (prob layout change)

- medusa/name_parser/guessit_parser.py
- medusa/server/api/v2/guessit.py
- tests/test_guessit.py
- tests/test_guessit.yml
* Added guessit test for 9-1-1
* Use the guessit test tool, uncached.
> Add option to use the guessit parser, uncached

- medusa/metadata/plex.py
> Fix Plex metadata creation.

- Dockerfile
- runscripts/init.docker
> Run docker container as non-root

- .dockerignore
- runscripts/init.docker
I'm not that well versed with docker. But i've tested this script within a docker container with and without providing PUID/PGID. So i think this should work
> Fix docker running with and without PUID/PGID

- medusa/server/api/v2/series_mass_edit.py
- themes-default/slim/src/components/manage-mass-edit.vue
> Add option to mass-update the info language.

- runscripts/init.docker
> Simplify PUID and PGID default values for Docker

- medusa/__main__.py
> Always overwrite app.BRANCH when we have a commit_branch_env.

- medusa/server/api/v2/internal.py
> Fix isoFormat on None.

- medusa/indexers/imdb/api.py
Fix #10514 
Should fix adding shows like http://localhost:8081/medusa2/home/displayShow?showslug=imdb52507
> Fix adding older shows. With releases without a startYear.

- medusa/name_parser/parser.py
> Add more logging to parsing

- medusa/__main__.py
- medusa/updater/version_checker.py
> Improve test, if we're running in docker

- medusa/failed_processor.py
- medusa/name_parser/parser.py
- medusa/post_processor.py
- medusa/process_tv.py
- tests/conftest.py
> Disable guessit cache for postprocessing

- medusa/helper/exceptions.py
- medusa/post_processor.py
- medusa/process_tv.py
* Exempt manually snatched downloads.
@medariox what do you think of these rules?
> Don't overwrite already arhived episodes when postprocessing.

- medusa/__main__.py
- medusa/app.py
- medusa/scene_exceptions.py
- medusa/scene_numbering.py
- medusa/tv/series.py
> Add config setting to allow overriding xem url.

- lib/pymediainfo/__init__.py
> Minor typo fix for pymediainfo error output

- medusa/subtitle_providers/addic7ed.py
* Extended the session timeout to 30s.
Fix #10344
> Changed warning to info.

- medusa/providers/torrent/json/eztv.py
> Strip tt from Imdb ID for Eztv provider

- medusa/indexers/imdb/api.py
> Fix setting an imdb_id from None or ''.

- themes-default/slim/src/components/helpers/config-custom-prowlarr.vue
Write `prowlarr` instead of misspelled `prowler`
reviewed in https://github.com/pymedusa/Medusa/pull/9653
> Fix prowlarr typo

- Dockerfile
> Use aports mirror on github to go around 429 error.

- themes-default/slim/src/components/test-rename.vue
@JorisMolnar, tnx. But we also require a build.
In the themes-default/slim/ folder run:
`yarn install`
`yarn dev` or `yarn dev --watch`
> Fix nulReference on testRename tnx. @JorisMolnar

- medusa/server/api/v2/guessit.py
> Fix test guessit

- medusa/subtitle_providers/addic7ed.py
> Change log error to info.

- medusa/helper/metadata.py
> Make log debug when metadata image can't be retrieved

- medusa/tv/episode.py
- themes-default/slim/src/components/config-post-processing.vue
- themes-default/slim/src/components/helpers/name-pattern.vue
- themes-default/slim/test/specs/__snapshots__/config-post-processing.spec.js.snap
> Added %Mm and %MM for using month (short and full) in the templating.

- themes-default/slim/src/components/test-rename.vue
> Order seasons in reversed order

- medusa/subtitle_providers/addic7ed.py
- medusa/subtitle_providers/converters/addic7ed.py
* Added language code convertor
* Added fre (can) to language convertor.
Fix #10542
> Added check for failed logins

- themes-default/slim/src/components/app-header.vue
- themes-default/slim/test/__fixtures__/common.json
- themes-default/slim/test/specs/__snapshots__/app-header.spec.js.snap
> isConnected should be false.

- themes-default/slim/src/components/display-show.vue
* Not only for Archived / Downloaded.
For discussion #10760
> Always show subtitle flag

- medusa/subtitle_providers/wizdom.py
> Fix wizdom subtitle provider

- CHANGELOG.md
- medusa/name_parser/rules/rules.py
- tests/test_guessit.yml
> Fix erai-raws anime release name parsing.

- dredd/api-description.yml
> Change Authentication header to x-auth

- themes-default/slim/src/components/config-general.vue
> Fix compareDbUpgrade check

- tests/test_guessit.yml
> remove duplicate line

- CHANGELOG.md
- medusa/search/queue.py
- medusa/server/api/v2/search.py
> Only change status to wanted when triggered through api.

- CHANGELOG.md
- medusa/show/recommendations/anidb.py
- medusa/show/recommendations/recommended.py
- medusa/show/recommendations/trakt.py
* Should fix the large recommended.dbm cache files.
> Fix dogpile keys for recommended shows.

- medusa/subtitles.py
> Don't error when parsing files without subs

- medusa/metadata/plex.py
> Add encoding when working with plexmatch file

- medusa/helpers/anidb.py
- medusa/logger/__init__.py
> Fix anidb cache key causing exceptions

- medusa/generic_update_queue.py
- medusa/logger/__init__.py
> Various small fixes

- medusa/name_parser/parser.py
> Don't raise InvalidNameException for absolute numbered anime

- medusa/tv/series.py
This is an upstream issue, but we're working around.
> Catch exception when we can't translate a title to imdb_id.

- medusa/ws/handler.py
> Authenticate websocket connections

- medusa/indexers/tvmaze/api.py
- medusa/tv/series.py
* make sure we store imdb_id without `tt` in indexer_mapping
> Normalize the imdb_id

- medusa/__main__.py
> Always get current version on startup

- medusa/metadata/plex.py
> Replace non-UTF8 chars instead of error for Plexmatch files

- medusa/server/api/v2/log.py
- themes-default/slim/src/components/config-post-processing.vue
- themes-default/slim/test/specs/__snapshots__/config-post-processing.spec.js.snap
Also add min value and unit to the frequency param description
> Fix Download Handler log filter

- .github/workflows/python-backend.yml
- setup.py
- tox.ini
> Add tests for Python 3.11

- medusa/post_processor.py
> Fix error log when ffmpeg doesn't detect audio or video

- medusa/name_parser/guessit_parser.py
> Allow to add scene exception to force show title match

- themes-default/slim/src/components/new-show-search.vue
> Put showid search results on top

- medusa/tv/episode.py
> Change missing directory log level to debug

- medusa/name_parser/rules/rules.py
> Avoid exception when the filepart doesn't match a season

- medusa/clients/nzb/nzbget.py
> Encode NZBGet username, password and host

- medusa/updater/github_updater.py
> Ensure that git_path is a valid file

- Dockerfile
> Update to Python 3.10.8 in Dockerfile

- medusa/updater/github_updater.py
> Fix git subprocess call for Windows paths with spaces (2)

- medusa/providers/torrent/html/yggtorrent.py
> Fix/ Provider YggTorrent changed domain name on 20/03/2023

- medusa/indexers/tvdbv2/api.py
> Fix error with malformed TVDB data missing links

- themes-default/slim/package.json
- themes-default/slim/yarn.lock
> Revert eslint changes

- medusa/indexers/tvdbv2/api.py
> Raise exception when TVDB returns malformed data

- medusa/providers/torrent/html/iptorrents.py
> Update default IPT url to com

- medusa/process_tv.py
> Don't overwrite manual post-processing delete folder preference

- medusa/notifiers/discord.py
- medusa/notifiers/slack.py
> Validate webhook URL for Slack and Discord

- ext/trakt/core.py
https://github.com/pymedusa/Medusa/issues/11618#issuecomment-1923174313
Thanks to @XxUnkn0wnxX and farni.
> Update Trakt API endpoint

- medusa/server/api/v2/history.py
> Fix history view elements (2)

- medusa/app.py
> Update base Medusa url (2)

- medusa/providers/torrent/json/eztv.py
> Increase EZTV search results

- medusa/schedulers/trakt_checker.py
> Fix trakt episode sync

- medusa/tv/episode.py
> Fix rare mass download of unset episodes
