pymedusa/Medusa

tests/scene_helpers_tests.py

until create a new github page

Disable exceptions change for now

---

sickbeard/dailysearcher.py

```
2016-02-24 00:46:33 INFO     DAILYSEARCHER :: New episode American Crime Story - S01E04 - 100% Not Guilty airs today, setting to default episode status for this show: Wanted
2016-02-23 23:46:31 INFO     DAILYSEARCHER :: New episode Marvel's Agent Carter - S02E09 - A Little Song and Dance airs today, setting to default episode status for this show: Wanted
2016-02-23 23:46:31 INFO     DAILYSEARCHER :: New episode Marvel's Agent Carter - S02E08 - The Edge of Mystery airs today, setting to default episode status for this show: Wanted
2016-02-23 22:46:28 INFO     DAILYSEARCHER :: New episode The Flash (2014) - S02E15 - King Shark airs today, setting to default episode status for this show: Wanted
```

Make ep wanted only after show finish airs

---

sickbeard/webserve.py

Add more threads to LOGFILTER and increase number of lines as we don't do pagination (not yet)

Add more threads to LOGFILTER

---

sickbeard/providers/newznab.py
sickrage/providers/GenericProvider.py

Fixes log echoing.
- Adds echo kwarg to get_url to selectively disable logging of output
- Disable echoing of newznab search

Log log log log log log log log log

---

sickbeard/classes.py
sickrage/providers/torrent/TorrentProvider.py

TODO: BTN and HDBITs have custom findPropers and they don't have seeders/leechers/size
https://github.com/pymedusa/SickRage/blob/manual-search/sickbeard/providers/hdbits.py#L123
https://github.com/pymedusa/SickRage/blob/manual-search/sickbeard/providers/btn.py#L280

Fix PROPER

---

sickbeard/logger.py
tests/scene_helpers_tests.py

Fixes #
-
-
-
Re-enable skipped tests

Move logging commit hash

---

sickbeard/webserve.py

Fix AttributeError: 'NoneType' object has no attribute 'get_id

---

gui/slick/views/manualSelect.mako
sickbeard/webserve.py

We need to show provider name in UI but pass provider_id when snatching item

Fix provider name in UI

---

sickbeard/webserve.py

Fix sorting: sort as int not string :/

---

.editorconfig

Fixes mako files having tabs instead of spaces

Add mako indenting

---

sickbeard/__init__.py

- only run CheckVersion at startup

Improve SR startup: only run CheckVersion at startup

---

gui/slick/views/config_search.mako
sickbeard/__init__.py
sickbeard/search.py
sickbeard/webserve.py

Change preferred words vars

---

sickbeard/tvcache.py
sickrage/providers/GenericProvider.py

and revert last commit to tvcache.py
https://github.com/pymedusa/SickRage/issues/45

Fixes https://github.com/pymedusa/SickRage/issues/45

---

sickbeard/providers/t411.py

Fixes #
- Update T411 domain name

Update T411 domain name

---

sickrage/providers/GenericProvider.py

Add _get_size

---

sickbeard/webserve.py

@duramato waiting your "OK" that it worked

[Manual Search] Search providers even if backlog search is disabled

---

sickbeard/webserve.py

TODO: 
Check unused keys in "result":
from here: https://github.com/pyMedusa/SickRage/blob/manual-search/sickbeard/search_queue.py#L263
to here: https://github.com/pyMedusa/SickRage/blob/manual-search/sickbeard/search.py#L94

[Manual search] Fix "url not valid" check

---

sickbeard/classes.py

Re-order PROPER class

---

sickbeard/search.py

Tweaks in search.py

---

sickbeard/providers/rarbg.py

@duramato cpu preset can be "2" depending on what user select
changing sleep to 3 seconds for all users no matter cpu preset

Try to fix "Too many requests per second"

---

sickbeard/manual_search.py

@p0psicles I already fixed here: https://github.com/pymedusa/SickRage/commit/6328076e102dc79801cc80e310e83ccc19935074
don't know what you did to remove it

[Manual Search] Fix sort again

---

sickrage/providers/nzb/NZBProvider.py

blind commit. please test @duramato @labrys

Try to cache torznab seeders/leechers

---

sickbeard/providers/newznab.py

[Manual Search] Fix seeders/leechers for torznab

---

gui/slick/views/manualSelect.mako

[Manual Search] Remove status from manualselect and add time instead

---

sickbeard/webserve.py

@duramato @medariox @labrys @p0psicles

[Manual Search] Erase cache results when toggling scene numbering

---

sickbeard/manual_search.py

@p0psicles @medariox @duramato 
https://gist.github.com/medariox/d25d2be8cb6f13c2bd62

Fix OperationalError: no such column: seeders

---

lib/subliminal/core.py

- Needs to be reported upstream

Fixed small subliminal bug

---

sickbeard/properFinder.py

@duramato @medariox need to test a proper download in manual-search

Try to fix PROPER

---

sickbeard/network_timezones.py

* Make missing timezones reportable
* Make errors unique per network
* Suppress errors for network of None

Fix network timezone reporting

---

sickbeard/subtitles.py

Check valid PP folder

---

gui/slick/views/manualSelect.mako

@OmgImAlexis 
should we don't change link color when a link is clicked?

Add link in show title to go back to displayShow page

---

sickbeard/tvcache.py

We were creating a "idx_url" so it would only create the index for the first provider
and wouldn't create for the other as index already existed
Now we create idx_url_$providerName
@labrys @medariox

Fix creation of unique index for url and remove wrong ones

---

SickBeard.py
sickbeard/__init__.py
sickbeard/classes.py
sickbeard/webserve.py

* Fix first aired hack
* was preventing finding some shows on tvdb
* Speed up initial start
* delay creating name cache until after browser starts
* Optimize webserve imports
* Fix broad exception for add show
* use indexer_exception instead (may need additional excepts added)

About time

---

sickbeard/properFinder.py

we should download PROPER no matter what.
Otherwise we will have to snatch bad result, PP it and then download the PROPER.

Download PROPER even if we didn't snatched anything from that episode

---

sickbeard/manual_search.py

instead to create table, unique index and new columns seeders, leechers and size
This will fix the issue when fresh cache.db doesn't have results and it will still do a forced search instead of skip provider @medariox

[Manual Search] Don't skip provider if table doesn't exist. Do a forced search

---

sickbeard/manual_search.py
sickbeard/webserve.py

Please test! @pymedusa/developers

[Manual Search] When you delete your cache.db and you start the manual select search, no results are shown, while it should.

---

sickbeard/manual_search.py
sickbeard/tvcache.py
sickbeard/webserve.py

This makes sure the provider table always exists when searches are being done against it.
It may not be the most ideal solution. But for now, this is needed to resolve all issues regarding tables not existing, or not fully migrated.

[Manual Search] Moved the cache queries to the provider TVcache object

---

sickbeard/webserve.py

I also had changed the html, to fix some of the errors, but I lost the changes while playing around.
But these webserve changes were needed.

Added some missing show attributes to displayShow json return

---

sickbeard/webserve.py

Some fixes

---

sickbeard/helpers.py

Fix "Unknown exception in getURL {url} Error: u'error 104 : ECONNRESET'"

---

sickbeard/helpers.py
sickbeard/properFinder.py
sickbeard/search.py

@duramato 
if spamming log, will make it DEBUG again

Proper catch ECONNRESET

---

sickbeard/helpers.py

Add BUYMORE to non-release words

---

sickbeard/processTV.py
sickbeard/subtitles.py

do not merge. wait manual-search branch
@medariox

Log when subs is disabled for show

---

gui/slick/views/schedule.mako

@OmgImAlexis @p0psicles @duramato 
what is the reason for ` <img alt="****]"` and `id="` inside the `<a> </a> `
looks like the `class="epManualSnatch"` is the most important thing isn't?

[Manual Snatch] Add "Manual Snatch" to Schedule page

---

sickbeard/postProcessor.py
sickbeard/subtitles.py

Fix Pre-scripts in subtitles

---

gui/slick/js/ajaxEpSearch.js

..making sure the user can't start a second before it's redirected.

Added disabling manual-snatch icons when one is clicked

---

.checkignore

Add config file for quantified code

---

gui/slick/views/snatchSelection.mako
sickbeard/manual_snatch.py

@OmgImAlexis you are welcome! =)

Move some Manual Snatch code from mako to python

---

sickbeard/clients/deluge_client.py
sickbeard/dailysearcher.py
sickbeard/failed_history.py
sickbeard/generic_queue.py
sickbeard/helpers.py
sickbeard/metadata/generic.py
sickbeard/notifiers/emailnotify.py
sickbeard/notifiers/prowl.py
sickbeard/numdict.py
sickbeard/nzbSplitter.py
sickbeard/postProcessor.py
sickbeard/properFinder.py
sickbeard/providers/binsearch.py
sickbeard/providers/freshontv.py
sickbeard/providers/newpct.py
sickbeard/providers/tntvillage.py
sickbeard/providers/womble.py
sickbeard/scene_numbering.py
sickbeard/search.py
sickbeard/searchBacklog.py
sickbeard/subtitles.py
sickbeard/tv.py
sickbeard/tvcache.py
sickbeard/webapi.py
sickrage/providers/GenericProvider.py
sickrage/show/History.py
sickrage/show/Show.py

* Fix sets by using comprehensions instead of passing lists to set()
* Fix using len() to see if something is empty

Cleanup code

---

gui/slick/js/ajaxEpSearch.js

This will open the manual snatch link in a new tab/window when the link is clicked icw ctrl, shift or middle mouse button.
Pls don't mind the branch name. Something went wrong there.

Open manual snatch href in new tab when clicked with shift, ctrl middle mouse button

---

sickbeard/webserve.py

Fix log level for no root directory when adding from popular lists.

---

sickbeard/providers/hd4free.py

Fixes jdata referenced before assignment

Fix hd4free

---

gui/slick/js/ajaxEpSearch.js
sickbeard/webserve.py

Tested with all possible combinations of the modals.

Fixed displayShows episodeRetry, mark as failed download.

---

sickbeard/logger.py

Fix issue tag

---

lib/cachecontrol/__init__.py
lib/cachecontrol/compat.py
lib/cachecontrol/controller.py
lib/cachecontrol/heuristics.py
lib/cachecontrol/serialize.py

Source: https://github.com/ionrock/cachecontrol

Update cachecontrol to v.0.11.6

---

lib/subliminal/cli.py
lib/subliminal/core.py
lib/subliminal/providers/itasa.py
lib/subliminal/refiners/__init__.py
lib/subliminal/refiners/metadata.py
lib/subliminal/refiners/omdb.py
lib/subliminal/refiners/tvdb.py
lib/subliminal/utils.py

@pymedusa/contributors 
No GUI changes, just needs approval.

Updated subliminal (ceb641d) and itasa subs provider

---

lib/babelfish/converters/opensubtitles.py

Needs to be reported upstream.

Fix babelfish bug that provented modern greek to be recognized as opensubtitles code

---

sickbeard/__init__.py
sickbeard/config.py
sickbeard/helpers.py
sickbeard/providers/rarbg.py
sickrage/helper/common.py
tests/torrent_tests.py

Quantified code 01

---

sickbeard/helpers.py

Fix brassetv

---

sickbeard/event_queue.py
sickbeard/failed_history.py
sickbeard/logger.py
sickbeard/metadata/generic.py
sickbeard/postProcessor.py
sickbeard/providers/__init__.py

Quantified code 2

---

sickbeard/__init__.py
sickbeard/search.py
sickbeard/search_queue.py
sickbeard/webserve.py

Add seeders and leechers information to notifiers

---

sickbeard/providers/transmitthenet.py

Fix Seeders and Leechers on TtN

---

sickbeard/helpers.py

Handle all qualities on non release group

---

sickbeard/versionChecker.py
sickbeard/webserve.py

This will speedup loading the /config page allot!

Fix: We don't need to check for updates if we need the current installed version

---

sickbeard/subtitles.py

my pre_script: python /home/osmc/scripts/rename_releases.py
Its changing python location:
FINDSUBTITLES :: [101b7e0] Absolute path to script: /home/osmc/SickRage/python
@medariox 
With this PR:
```
09:57:20 INFO::FINDSUBTITLES :: [101b7e0] Running subtitle pre-script: python /home/osmc/scripts/rename_releases.py
09:57:20 INFO::FINDSUBTITLES :: [101b7e0] Executing command: ['python', '/home/osmc/scripts/rename_releases.py', '/media/SAMSUNG/media/downloaded/series/*.S10E09.720p.HDTV.x264-ALTEREGO.mkv']
09:57:20 DEBUG::FINDSUBTITLES :: [101b7e0] Script result: Nothing to rename
```

Fix subtitle scripts

---

sickbeard/helpers.py

Cleaner removewordslist

---

sickbeard/common.py
sickrage/recompiled/tags.py
sickrage/tagger/episode.py

* Add widescreen regex
* Add aussie regex
* Add widescreen property
* Add aussie property
* Add Aussie p2p quality check

Make Aussie p2p releases 720p HDTV

---

sickbeard/helpers.py

Revert "Cleaner removewordslist"

---

sickbeard/network_timezones.py
sickbeard/notifiers/pushover.py
sickbeard/postProcessor.py
sickbeard/sbdatetime.py
tests/api_v1_tests.py

More rebranding

---

sickbeard/providers/thepiratebay.py

Fix TPB sizes

---

sickbeard/manual_snatch.py

Fix returning wrong episodes in manual search

---

sickbeard/network_timezones.py

@labrys merge only after previous open PR get merged

Update network timezones URL

---

sickbeard/refiners/release.py
sickbeard/subtitles.py
sickbeard/tv.py
sickbeard/webserve.py

- Only subtitles.py was refactored in order to make the code more readable and maintainable
- Big methods were splittled into small methods
- Refactored duplicated code
- Added docstring to the methods
- Pre-scripts are now executed when post-processing is NOT postponed (before it was executed only when postponed; extra scripts are still not executed when postponed)
- Small fix in release refiner (missing . to separate file extension)
Do NOT merge it yet
Tests are "in progress"
My tests were all successful, but I want to give it more time and execute more scenarios.

Subtitles refactoring, code cleanup and docstrings

---

.gitignore
.gitmodules
sickbeard/clients/download_station_client.py
sickbeard/helpers.py
sickbeard/nzbget.py
sickbeard/providers/binsearch.py

Various "fixes" form SR

---

sickbeard/versionChecker.py

Avoid user to submit those "errors" that are not really code errors

Only logger.ERROR when Exception

---

sickbeard/providers/torrentproject.py

Handle when hash or size are missing

---

sickbeard/search_queue.py
sickbeard/webserve.py

Fixes for multi eps.

---

gui/slick/views/snatchSelection.mako
sickbeard/search_queue.py
sickbeard/webserve.py

@p0psicles PR. I didn't merged into feature branch sorry!
* Changed searchResult to snakecase.
* Removed unneeded params for snatchSelection() method.
* Changed mako to not send unneeded params. rowid is enough.
* Added check for getting the show_obj, chances are slim, but maybe a user leaves a snatchSelection window open, while deleting the show.
* Some pep8 changes.
* Added docstrings to webserve.py and search_queue.py methods.

Moved the creation of the searchResult to the searchQueue item.

---

sickbeard/versionChecker.py

Remove submodule update

---

sickbeard/webapi.py

...and catch None as a return value

Fix webapi for a type of None and add missing keys

---

gui/slick/views/addShows_addExistingShow.mako
gui/slick/views/addShows_newShow.mako
gui/slick/views/addShows_popularShows.mako
gui/slick/views/addShows_trendingShows.mako
gui/slick/views/apiBuilder.mako
gui/slick/views/config_postProcessing.mako
gui/slick/views/config_providers.mako
gui/slick/views/config_subtitles.mako
gui/slick/views/displayShow.mako
gui/slick/views/editShow.mako
gui/slick/views/history.mako
gui/slick/views/layouts/main.mako
gui/slick/views/manage.mako
gui/slick/views/manage_episodeStatuses.mako
gui/slick/views/manage_failedDownloads.mako
gui/slick/views/manage_manageSearches.mako
gui/slick/views/manage_massEdit.mako
gui/slick/views/manage_torrents.mako
gui/slick/views/partials/footer.mako
gui/slick/views/partials/header.mako
gui/slick/views/partials/home/banner.mako
gui/slick/views/partials/home/poster.mako
gui/slick/views/partials/home/simple.mako
gui/slick/views/partials/home/small.mako
gui/slick/views/restart.mako
gui/slick/views/schedule.mako
gui/slick/views/snatchSelection.mako
gui/slick/views/testRename.mako
gui/slick/views/trendingShows.mako

We now set the base URL and everything will be relative to that.

switch to relative urls for images and js files, fixed topImageHtml error

---

gui/slick/js/core.js
gui/slick/views/schedule.mako
sickbeard/webserve.py

[Manual Search] Missing manual search renames

---

gui/slick/js/core.js

cleaned up core.js

---

sickbeard/manual_search.py

Fixes https://github.com/pymedusa/SickRage/issues/264
@p0psicles that's my fault. QC said to avoid:
@duramato please confim this fixes

Fix issue pymedusa/SickRage/issues/264

---

sickbeard/indexers/indexer_config.py

Fix scene exceptions URL for TVMAZE

---

gui/slick/views/partials/footer.mako

https://github.com/pymedusa/SickRage/issues/242
@OmgImAlexis got this from your other PR that got reverted

Fix issue pymedusa/SickRage/issues/242

---

sickbeard/providers/hd4free.py

Fix when there is no response from hd4free provider

---

gui/slick/css/style.css
gui/slick/views/snatchSelection.mako

This adds min-width to avoid wrapping of provider, size or date columns on smaller screens.

Added css classes for provider, size, date, to avoid ugly wrapping and reduce inline css

---

gui/slick/js/core.js

The load() always handles the result, and replace the #container div with that. I've changed this to a $.getJson(), and only kicking the search to start. After this the container div is only refreshed when needed.

[Manual Search] First call to snatchSelection always refreshed page with results

---

lib/subliminal/__init__.py
lib/subliminal/cli.py
lib/subliminal/converters/legendastv.py
lib/subliminal/core.py
lib/subliminal/extensions.py
lib/subliminal/providers/__init__.py
lib/subliminal/providers/addic7ed.py
lib/subliminal/providers/legendastv.py
lib/subliminal/providers/napiprojekt.py
lib/subliminal/providers/opensubtitles.py
lib/subliminal/providers/podnapisi.py
lib/subliminal/providers/shooter.py
lib/subliminal/providers/subscenter.py
lib/subliminal/providers/thesubdb.py
lib/subliminal/providers/tvsubtitles.py
lib/subliminal/refiners/omdb.py
lib/subliminal/refiners/tvdb.py
lib/subliminal/score.py
lib/subliminal/subtitle.py
lib/subliminal/utils.py
lib/subliminal/video.py
sickbeard/subtitles.py

Subliminal Release 2.0-rc1 + ratoaq2 improvements (not merged yet)

---

lib/subliminal/cli.py
lib/subliminal/core.py
lib/subliminal/utils.py

Re-add Itasa subtitle provider

---

lib/subliminal/core.py
lib/subliminal/providers/podnapisi.py
lib/subliminal/providers/shooter.py
lib/subliminal/utils.py

Add back shooter and fixes

---

sickbeard/providers/transmitthenet.py

Forgot this one on TtN

---

lib/subliminal/providers/legendastv.py

LTV: fix KeyError: 'season'

---

gui/slick/views/config_general.mako
sickbeard/__init__.py
sickbeard/logger.py
sickbeard/webserve.py

@ratoaq2 
use `sickbeard.SUBLIMINAL_LOG`

Add setting: 'enable subliminal logs'. Default off

---

sickbeard/webserve.py

Only reconfigure logger if subliminal setting changed

---

gui/slick/views/displayShow.mako
gui/slick/views/manage_manageSearches.mako

[Manual Search] "Forced Search" in manage Searches and failed modal

---

sickbeard/search.py
sickbeard/show_name_helpers.py

Show words overrides global words.

---

gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako

@duramato @p0psicles @medariox

DisplayShow: show required/ignored words excluding/including global words

---

sickbeard/logger.py

@duramato @fernandog 
This should get rid of the time duplication as well.

Fixes dupe warnings and errors in log view

---

sickbeard/scene_exceptions.py

...or when file not available at cdn
DO NO MERGE until cdn has the latest file
@OmgImAlexis your CDN for https://github.com/pymedusa/sickrage.github.io/blob/master/scene_exceptions/scene_exceptions.json is not using the latest file. How often does it update?

Make scene exceptions failed as ERROR. Help debug wrong additions

---

gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako

@duramato 
I was not showing show ignored/required.
Test1: Add one word to global required, and same to show ignored. It shouldn't appear in "Required words" but in Ignored
Test2: Add one word to global ignored, and same to show required. It should appear in "Required words" and not in Ignored

Fix ignored and required words

---

gui/slick/views/schedule.mako

[Manual Search] Add manual search icon to poster and banner layouts in Schedule

---

sickbeard/webserve.py

Fix subtitle page title

---

sickrage/providers/GenericProvider.py

Disable btdig (dead), enable itorrents instead

---

sickbeard/clients/generic.py

Need to remove torrent from cache otherwise every DailySearch error will raise: Unable to bdecode torrent

Remove cached torrent if its invalid torrent

---

gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako

Fix empty require/ignore

---

sickbeard/providers/hd4free.py

Fix https://github.com/pymedusa/SickRage/issues/362

---

sickbeard/tv.py

Fix pymedusa/SickRage/issues/364

---

gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako
sickbeard/webserve.py

@duramato please test the logic! not only UI.

[Manual Search] Highlight ignored/required words in manual search results

---

sickbeard/show_queue.py

Fixes syncing of newly added shows to medusa towards trakt.

Fixed previously introduced bug after snake_case renames

---

sickbeard/logger.py
sickbeard/refiners/release.py
sickbeard/subtitles.py

- Subtitles to use standard logging API.
- Added video cache invalidation after executing pre/extra scripts.

Subtitles to use standard logging API

---

sickbeard/subtitles.py

https://github.com/pymedusa/SickRage/issues/382

Fix pymedusa/SickRage/issues/382

---

sickbeard/providers/omgwtfnzbs.py

Fix the size parsing for Omgwtfnzbs RSS feed items

---

lib/subliminal/refiners/tvdb.py

Update subliminal to 67a48e07a2246a798abc52ec6cbb64be7fee4cbb

---

sickbeard/logger.py

And we have logs again!!
First issue doesnt have logs but second has:
https://github.com/pymedusa/SickRage/issues/307

Try to fix pymedusa/SickRage/issues/307

---

gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako
sickbeard/tv.py

Partially fixes #379.  This prevents the error but does not attempt to validate invalid IMDb IDs.
* fix `KeyError` for `imdb_info`
* remove unnecessary assignment of `show` to `_show`
* fix `KeyError` for `imdb_info`
* fix `==` in img attribute

Fix KeyError in IMDb info

---

gui/slick/js/core.js
gui/slick/views/displayShow.mako
gui/slick/views/schedule.mako
gui/slick/views/snatchSelection.mako
sickbeard/manual_search.py
sickbeard/search.py
sickbeard/search_queue.py
sickbeard/webserve.py
sickrage/providers/GenericProvider.py

[Manual Search] Season manual search

---

gui/slick/views/snatchSelection.mako
sickbeard/name_parser/parser.py

Remove non release groups before apply regex

---

sickbeard/providers/btdigg.py

Add Seeders/leechers to btdigg

---

sickbeard/search.py

Fix AttributeError: 'NewznabProvider' object has no attribute 'minseed'

---

sickbeard/webserve.py

Remove override auto PP setting when 'postpone if no subs'

---

lib/tmdb_api/tmdb_api.py

(cherry picked from commit 45a42442672d576b6c40580244baddd6097a1325)

Fixed tmdb where it didn't get information because of an ssl error

---

gui/slick/views/config_search.mako
sickbeard/__init__.py
sickbeard/show_name_helpers.py
sickbeard/webserve.py
tests/scene_helpers_tests.py

Add option to ignore unknown subbed releases

---

gui/slick/js/core.js
gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako
sickbeard/webserve.py

@p0psicles can you review please? i'm not expert
.
Related to this comment:
https://github.com/pymedusa/SickRage/issues/392#issuecomment-210617288

[Manual Search] Show lastest status from episode in snatchSelection

---

gui/slick/views/snatchSelection.mako
sickbeard/webserve.py

[Manual Search] Remove history limit and fix history action check

---

sickbeard/webserve.py

Fixed newznab categories not saving.

---

sickbeard/network_timezones.py

@duramato 
https://github.com/pymedusa/SickRage/issues/430
https://github.com/pymedusa/SickRage/issues/419
https://github.com/pymedusa/SickRage/issues/417

Log '_network_dict' to help debug missing timezone errors

---

lib/babelfish/converters/opensubtitles.py
lib/babelfish/tests.py

Fixing bug that prevent modern greek to be recognized
@labrys @medariox

Upgrade babelfish to f403000dd63092cfaaae80be9f309fd85c7f20c9

---

gui/slick/css/style.css

Remove text decoration from forcedSearch icon

---

gui/slick/js/ajaxEpSearch.js
gui/slick/views/schedule.mako

[Manual Search] Fix f* JS changing title of forced search icon

---

sickbeard/providers/rarbg.py

https://github.com/pymedusa/SickRage/issues/442
@duramato don't be scared if a lot of warnings pop up.

Temp change rarbg log message to warning. Help debug invalid token

---

gui/slick/views/snatchSelection.mako

Fix https://github.com/pymedusa/SickRage/issues/445
@duramato please test

Fix pymedusa/SickRage/issues/445

---

sickbeard/providers/anizb.py

Made sure only anime marked shows are using this provider

---

lib/six.py

Fix distribution not found error in find subtitles.

Update six to 1.10.0

---

gui/slick/views/snatchSelection.mako

[Manual Search] Fix issue when not painting as snatched

---

lib/contextlib2.py

Add contextlib2 version 0.5.1

---

lib/subliminal/core.py
lib/subliminal/refiners/tvdb.py

Upgrade subliminal to 431f71fb646a0294d3588a5cb057a1c3fd1c77bf

---

sickbeard/postProcessor.py
sickbeard/subtitles.py

Fix unicode issues during post processing.
Addresses #318 as well.

Fix unicode issues during post processing.

---

sickbeard/subtitles.py

@p0psicles as you said in TODO issue
@medariox

Give the CPU a break while searching for subs

---

sickbeard/subtitles.py

Check if subtitle thread is already running. Don't start another

---

sickbeard/providers/limetorrents.py

Add check for no results for limetorrents

---

gui/slick/views/history.mako

Increase a little 'time'  column in. Its wrapping

---

sickbeard/subtitles.py

Only show video name instead of full path for subs logging

---

sickbeard/providers/torrentproject.py

Change magnet to use 1 api

---

sickbeard/providers/limetorrents.py

Fix "too many redirects" error

Fix RSS on limetorrents

---

sickbeard/network_timezones.py

Revert stupid logging.  Dumping the entire dict of timezones to the log is an idiotic decision.

Revert stupid logging

---

sickbeard/search.py

Added this so everybody could confirm new ignored/required code is working properly and to avoid  keeping looking at logs.
If you all say its working, merge this.

Change back ignored/required words log level to INFO

---

gui/slick/views/config_search.mako

Fixing my own bug. min is 720 minutes, so step should be minutes too

Fix backlog search step in UI

---

sickrage/recompiled/tags.py
sickrage/tagger/episode.py

Netflix sources

---

sickbeard/name_parser/parser.py

This helped find this wrong regex matching:
https://github.com/pymedusa/SickRage/pull/510
@duramato

Add log to help debug 'unable to match..." cases

---

lib/rebulk/__version__.py
lib/rebulk/chain.py
lib/rebulk/match.py
lib/rebulk/pattern.py
lib/rebulk/rules.py

- Avoid usage of six.text_type (could cause UnicodeDecodeError)
@medariox

Upgrade rebulk to e06c78e7a45c9d1ad1c47750e70c4e8dd664a289

---

lib/subliminal/core.py
lib/subliminal/providers/addic7ed.py

- Ensure scan_videos continues if unrar is not installed
- Add TooManyRequests safeguard on 304 in addic7ed
@medariox @duramato

Upgrade subliminal to 14707b68ca1f8ed6cdd78697c6bf6055a861ca2d

---

gui/slick/css/style.css

Fix pymedusa/SickRage/issues/525

---

sickbeard/subtitles.py

- Just after a download finishes, the initial subtitle search doesn't have release name and the video is cached with incomplete info (e.g. without release group). When the "FINDSUBTITLE" thread takes place, the incomplete cached video might prevent the subtitle download until it expires, so subtitles are only downloaded after 24h.
- This issue is noticeable when using "episode renaming rules" that doesn't contain "quality" information in the filename (release group, screen size, etc)
- This fix will keep the video cache key as the video path. But the cached video will be invalidated/discarded if any keyword argument changes: in this case the video is scanned again and re-created (the same process as before). I've been testing this for about 10 days now, and it works like a charm.

Use cached video only when keyword args match

---

sickbeard/dailysearcher.py

Implement Force option by allowing forced search even if manual search is running.
Use unicode_literals and single-quoted strings
Use b'' for SQL
Optimize imports
Refactor variables

Clean up daily searcher

---

gui/slick/views/config_providers.mako

As discussed and suggested by @OmgImAlexis 
https://github.com/pymedusa/SickRage/issues/542

Fix pymedusa/SickRage/issues/542

---

sickbeard/providers/hounddawgs.py

Fixes
https://github.com/pymedusa/SickRage/issues/562
https://github.com/pymedusa/SickRage/issues/563
https://github.com/pymedusa/SickRage/issues/564

Fix pymedusa/SickRage/issues/562

---

sickbeard/common.py

Add "disabled" to cpu presets

---

sickbeard/blackandwhitelist.py

Clean-up blackwhitelist.py

---

sickbeard/helpers.py
sickbeard/properFinder.py
sickrage/helper/common.py

Check if new found proper is in the history database to make sure we didn't previously snatched it
This fix was tested in `pubdate2` branch
@duramato @p0psicles 
for now log message is a WARNING to detect duplicate PROPERs easyly

Fix snatch same proper over and over

---

gui/slick/css/style.css
gui/slick/views/viewlogs.mako

Using the same "solution" found in home.mako
TODO:
@p0psicles @OmgImAlexis

Fix pymedusa/SickRage/issues/540

---

gui/slick/views/history.mako
sickbeard/properFinder.py

Use guessit to detect propers instead of regex.

Use guessit for proper detection

---

sickbeard/clients/deluge_client.py

Fix from old repo: SickRage/sickrage-issues/issues/506
-1 is to seed forever so we should disable that stop_at_ratio setting
blank is default client ratio, so we also shouldn't set ratio
@ratoaq2 will test when he can
Transmission does the same:
https://github.com/pymedusa/SickRage/blob/old_issue506/sickbeard/clients/transmission_client.py#L108-L109

Fix deluge sending ratio -1 when it should disable stop_at_ratio setting

---

sickbeard/subtitles.py

This fixes the subs scripts passing the correct arguments to the scripts, as described in #587

Fix subs scripts #587

---

sickbeard/__init__.py

Fix saving config with non-ascii chars for None locale

---

sickbeard/postProcessor.py

Use ek for os.walk until we finish transition to unicode

---

.gitignore
sickbeard/__init__.py
sickbeard/common.py
sickbeard/databases/__init__.py
sickbeard/databases/main_db.py
sickbeard/helpers.py
sickbeard/versionChecker.py
tests/test_lib.py

* Refactor mainDB to main_db
* Bump main_db version to 43.1
* Fix db backup not showing minor versions
* Add *.db to gitignore

Database updates

---

sickbeard/helpers.py

Fixed hardcoded .db extension, when it's also used for config.ini

---

sickbeard/helpers.py

Some small changs to make sure the restore function (if ever used) is consistent with the backup function.

Fix dbver helper

---

sickbeard/databases/mainDB.py

Missed bumping max db version in main_db

HOTFIX: Bump MAX DB version

---

sickbeard/databases/mainDB.py
sickbeard/versionChecker.py

This fixes checkVersion to check for the new database version in `main_db.py` first, and then if that fails check `mainDB.py`.  It also adds a `mainDB.py` that contains pseudo-version numbers for migrations from SickRage.

DB refactor fix for checkVersion

---

sickbeard/databases/main_db.py
sickbeard/helpers.py

Merge hotfixes to Beta

---

gui/slick/views/config_general.mako
sickbeard/__init__.py
sickbeard/common.py
sickbeard/config.py
sickbeard/logger.py
sickbeard/webserve.py
tests/test_lib.py

Like ips/domains , api keys and tokens

Hide sensitive info from the logs

---

gui/slick/views/snatchSelection.mako

Note: not too sure about the mako indent here, it's kind of messy. Please take a look.

Hide History table if there is no history in manual search

---

sickbeard/notifiers/emby.py
sickbeard/notifiers/kodi.py
sickbeard/providers/hdbits.py
sickbeard/providers/norbits.py
sickbeard/webapi.py
sickbeard/webserve.py

As we require python 2.7+, and json is part of the standard libs, there is no need to import simplejson.  In addition simplejson has some unicode issues that may present problems such as this one:
https://code.google.com/archive/p/simplejson/issues/40

Remove simplejson

---

sickbeard/properFinder.py

@p0psicles 
need to merge into master
avoid spam torrent users log

Revert PROPER log message to DEBUG

---

sickbeard/providers/rarbg.py

and Show "Too many requests per second!" as INFO
@duramato

Show RARBG error code next to error message

---

lib/subliminal/providers/legendastv.py

Fix for titles without year in legendastv
@medariox @ratoaq2

Upgrade subliminal to e2331bef2c827406f92b1696b96241137163fe4f

---

sickbeard/providers/tokyotoshokan.py

* You can't check if the show is anime, if there is no show provided, as with RSS searches. Duhhhh.

Fixed TokyoTosho Daily (RSS) search

---

gui/slick/views/config_search.mako
sickbeard/__init__.py
sickbeard/tvcache.py
sickbeard/webserve.py

* Cleans up the Config Search template.
* Adds cache trimming and cache retention settings to allow trimming of provider cache to a user selectable number of days.  Defaults to disabled and 30.0 days.

Cache trimming

---

gui/slick/views/home_postprocess.mako
sickbeard/server/web/home/post_process.py

The nzbToMedia breaks our nzbToMedia PP.
Reference to the nzbToMedia change: https://github.com/clinton-hall/nzbToMedia/commit/24a47cae71252679d546904624df233b0843a085

Sr did a PR at nzbToMedia to change param dir to proc_dir.

---

gui/slick/views/home_postprocess.mako

Fix manual post-processing and nzbToMedia

---

sickbeard/providers/speedcd.py

Fix speedcd search

---

sickbeard/providers/torrentday.py

Fixes #639 
Check provider response status and log errors
Check that provider response is actually json

Fix torrentday searches

---

sickbeard/providers/__init__.py
sickbeard/providers/bithdtv.py

This PR will add support for the provider BIT-HDTV.
Supported is:
* RSS
* Backlog search
* Season pack search using a category paramater
* Freeleech
TODO:
* Some testing

First version BITHDTV provider

---

sickbeard/providers/bithdtv.py

* needed to use html.parser
* need to explicitly get the second table. Not the table with the filters.

Fixed bithdtv provider.

---

lib/rarfile/__init__.py
lib/rarfile/dumprar.py

Fixes solid rar files when using in-memory streams.
https://github.com/Diaoul/subliminal/issues/644

Updating rarfile to 6d547b138e2edb658d4202eae216c2792571c2a6.

---

sickbeard/providers/zooqle.py

Add trackers to magnet (Zooqle)

---

sickbeard/providers/bithdtv.py

Fix Bit-HDTV

---

gui/slick/views/displayShow.mako

Use white icon on dark theme also if season > 1

---

sickbeard/providers/limetorrents.py

Fix and clean up limetorrents provider

---

sickbeard/providers/torrentproject.py

Fix and clean up torrentproject provider

---

sickbeard/server/api/core.py

Add PP missing parameter  'delete_on' to api

---

sickbeard/server/web/__init__.py

Let's fix this before we forget about it.

Duplicate imports

---

lib/subliminal/__init__.py
lib/subliminal/cli.py
lib/subliminal/providers/itasa.py
lib/subliminal/providers/legendastv.py

Update subliminal to 2.0.3 (master), update Itasa

---

sickbeard/search_queue.py
sickbeard/server/web/core/base.py

Fixes #693 and adjust wording of notifications during manual search.

Fix notifications

---

sickbeard/providers/alpharatio.py
sickbeard/providers/btn.py
sickbeard/providers/iptorrents.py
sickbeard/providers/tntvillage.py
sickbeard/providers/torrentday.py
sickbeard/providers/torrentproject.py

More providers

---

sickbeard/tvcache.py
sickrage/providers/GenericProvider.py

This PR started as a bugfix. But while working on it, I took the opportunity to also make it unicode compliant, as where working on that anyway. But then I noticed we just merged the stand-providers, which had also already changes to tvcache. That's when I decided to cleanup the file.
Fixed bug in forced Search: _addCacheEntry paramater mismatch called from GenericProvider.py.
Error shows with ForcedSearch. Maybe also backlogs.
* Cleaned up tvcache.py (format, single quotes and pep8 snake_case nameings where safe.)
* Enabled import unicode_literals for tvcache.py

Fixed bug in forced Search: _addCacheEntry paramater mismatch

---

sickbeard/clients/qbittorrent_client.py

Implements fix from SickRage/SickRage#1996 for issue SickRage/SickRage#1990
All credits go to @ngodber

Fix support for qbittorrent >= 3.3.5

---

lib/simpleanidb/__init__.py
lib/simpleanidb/models.py

* I need this to be able to search by tvdbid and aid. Is used for the recommended lists, to show which tvdb shows are anime classified.

Updated to latest simpleanidb lib dev version

---

sickbeard/providers/rarbg.py

Prevent more WARNING log messages from RARBG. Make it DEBUG

---

sickbeard/server/api/core.py

Add missing qualities to API show commands

---

sickbeard/providers/btn.py

Provider was a mess, now it's more decent (aim is not a full rewrite).

Make BTN more decent

---

sickbeard/versionChecker.py

Fix checkVersion getURL to return response and not text

---

sickbeard/providers/freshontv.py

Fix freshon.tv login, add proper strings

---

lib/simpleanidb/__init__.py
lib/simpleanidb/models.py

Update lib simpleanidb

---

sickbeard/providers/__init__.py
sickbeard/providers/torrentshack.py

Icons for this provider already exist.

Add TorrentShack torrent provider

---

sickbeard/databases/main_db.py
sickbeard/search.py

This also includes following fixes:
- [Unique seasons fix](https://github.com/SickRage/SickRage/pull/2027). Thanks to @guusdk
- [SQL syntax fix](https://github.com/SickRage/SickRage/pull/2029). Thanks to @dgholz

Lint search.py, fix 2 bugs

---

sickbeard/name_parser/guessit_parser.py
sickbeard/name_parser/parser.py
sickbeard/name_parser/rules/properties.py
sickbeard/name_parser/rules/rules.py

Implemented future unicode literals, where neeeded.

---

sickbeard/subtitles.py

Add missing EMBEDDED_SUBTITLES_ALL setting in subtitles 

---

lib/subliminal/providers/itasa.py

Update itasa subs provider to b2545b

---

sickbeard/__init__.py
sickbeard/config.py

Streamline provider initialization

---

sickbeard/postProcessor.py

@nicoleoca @ratoaq2 
Related to:
https://gist.github.com/NicoLeOca/45e3686517e45727116ba38076a3844e

Better log when extension not found in allowed extension

---

gui/slick/views/config_general.mako
sickbeard/__init__.py
sickbeard/name_parser/parser.py
sickbeard/server/web/config/general.py
tests/name_parser_tests.py

"Use legacy name parser", which is enabled by default for now.
Meaning Guessit is disabled now by default.
For the lazy:

Guessit ui controll

---

sickbeard/processTV.py

@ratoaq2 @nicoleoca
Related to:
https://gist.github.com/NicoLeOca/45e3686517e45727116ba38076a3844e

Subtitles enabled check: try to parse NZB name when fails to parse filename

---

sickbeard/common.py
sickbeard/name_parser/parser.py
sickbeard/name_parser/rules/properties.py
tests/datasets/tvshows.yml

- Using guessit information to enhance quality detection when Unknown
- Small enhancement on size detection

Enhance quality detection

---

sickbeard/processTV.py

Quick fix introduced in 0b15f8e942976a4662ac9841d6106fe027319763

---

sickbeard/properFinder.py
sickbeard/providers/newznab.py
sickbeard/tvcache.py
sickrage/providers/GenericProvider.py
sickrage/providers/nzb/NZBProvider.py
sickrage/providers/torrent/TorrentProvider.py

Without this, FINDPROPER with NZB providers were not doing "Search mode: episode" with search string with show+episode that needed to be searched for propers
Related to issue: https://github.com/pymedusa/SickRage/pull/740
We dont have "GET URL" because it isn't doing any kind of query in NZB providers
TODO:
About PROPER search detection in newsnab.py:
```
>>> 'PROPER|REPACK|REAL' in 'The Real Housewives S02E03'
False
>>> 'PROPER|REPACK|REAL' in 'The Real Housewives S02E03 PROPER|REPACK|REAL'
True
```
nzb:
```
2016-07-06 20:19:04 DEBUG    FINDPROPERS :: [NZBGeek] :: [42fd472] Found new proper result: Quantico.S01E17.PROPER.HDTV.x264-BATV
2016-07-06 20:19:04 DEBUG    FINDPROPERS :: [NZBGeek] :: [42fd472] Found new proper result: Quantico.S01E17.PROPER.HDTV.x264-BATV-Obfuscated
2016-07-06 …
```

Fix proper search for NZB

---

sickbeard/providers/gftracker.py

Fix GFTracker download

---

sickbeard/properFinder.py

Fix missing b'' after adding unicode literals

---

sickbeard/name_parser/parser.py

Avoid parsing of air-by-date results with non air-by-date shows

---

sickrage/providers/GenericProvider.py

Or nobody is using develop or nobody tested proper search lol

Fix rebase issue

---

sickbeard/name_parser/rules/__init__.py
sickbeard/name_parser/rules/properties.py
tests/datasets/tvshows.yml

Enhanced audio_channels detection: 
https://github.com/guessit-io/guessit/issues/328

Enhancing audio_channels detection

---

gui/slick/views/config_search.mako

Fixes https://github.com/pymedusa/SickRage/issues/741
Fixes until "UI Cleanup" is merged

Fix Search settings tab

---

gui/slick/views/config_providers.mako

@labrys Cherry pick to master?

Add Kat to broken providers

---

sickbeard/common.py
sickbeard/notifiers/__init__.py
sickbeard/notifiers/boxcar2.py
sickbeard/notifiers/emailnotify.py
sickbeard/notifiers/freemobile.py
sickbeard/notifiers/growl.py
sickbeard/notifiers/kodi.py
sickbeard/notifiers/libnotify.py
sickbeard/notifiers/nma.py
sickbeard/notifiers/nmj.py
sickbeard/notifiers/nmjv2.py
sickbeard/notifiers/plex.py
sickbeard/notifiers/prowl.py
sickbeard/notifiers/pushalot.py
sickbeard/notifiers/pushbullet.py
sickbeard/notifiers/pushover.py
sickbeard/notifiers/pytivo.py
sickbeard/notifiers/synoindex.py
sickbeard/notifiers/synologynotifier.py
sickbeard/notifiers/telegram.py
sickbeard/notifiers/trakt.py
sickbeard/notifiers/tweet.py
sickbeard/search.py

TODO:
Improve proper detection after proper_tags branch gets merged
@p0psicles 
@OmgImAlexis only for PROPER

Change snatch message to 'Started PROPER download' if PROPER

---

sickrage/providers/GenericProvider.py

also need to cherry pick to master
@labrys

Removes - for now - torcache.net

---

sickbeard/providers/extratorrent.py

Rewrite ExtraTorrent

---

gui/slick/views/home_postprocess.mako
sickbeard/processTV.py
sickbeard/server/web/home/post_process.py

If one episode is hanging in PP folder and never gets PP because there is no subs available, this setting will override the associated subtitle check and it will PP the file
Also add some missing descriptions to the settings:

Add ignore_subs setting to manual PP

---

sickbeard/postProcessor.py

Change to single quote and .format()

---

gui/slick/css/light.css

Hotfix light.css for fanart

---

sickbeard/scene_exceptions.py

http://thexem.de/map/allNames?origin=tvdb&seasonNumbers=1 
returns: {"result":"success","data":[],"message":""}
and travis:
```python
scene_helpers_tests.py line 85 in setUp
scene_exceptions.retrieve_exceptions()
/home/travis/build/pymedusa/SickRage/sickbeard/scene_exceptions.py line 226 in retrieve_exceptions
_xem_exceptions_fetcher()
/home/travis/build/pymedusa/SickRage/sickbeard/scene_exceptions.py line 320 in _xem_exceptions_fetcher
for indexerid, names in iteritems(parsedJSON['data']):
/home/travis/build/pymedusa/SickRage/lib/six.py line 599 in iteritems
return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'
```

Fix XEM scene exception

---

gui/slick/views/snatchSelection.mako
sickbeard/classes.py
sickbeard/manual_search.py
sickbeard/name_parser/parser.py
sickbeard/name_parser/rules/rules.py
sickbeard/properFinder.py
sickbeard/tvcache.py
sickrage/providers/GenericProvider.py
tests/datasets/tvshows.yml

As discussed:
Out of the scope of this PR: Add proper_tags in sickbeard.db | history table

Adds proper_tags to cache

---

sickbeard/showUpdater.py
sickbeard/tv.py

* Skip Paused show on Nightly Update
* Log If Show is skipped due to being paused
@pymedusa/developers

Skip Paused show on Nightly Update

---

sickbeard/logger.py

Fixes pymedusa/SickRage/issues/691
@duramato

Fixes pymedusa/SickRage/issues/691

---

gui/slick/views/history.mako
sickbeard/name_parser/parser.py
sickbeard/postProcessor.py
sickbeard/properFinder.py
sickbeard/search.py
sickbeard/search_queue.py
sickrage/show/History.py

@pymedusa/developers 
History.mako is also working
```
2016-07-25 12:43:36 DEBUG    SNATCHQUEUE-MANUALSNATCH-95021 :: [42fd472] Found proper tags for The.Middle.S04E08.PROPER.HDTV.x264-2HD.mp4. Snatching as PROPER
2016-07-25 12:43:36 INFO     SNATCHQUEUE-MANUALSNATCH-95021 :: [42fd472] Downloading The.Middle.S04E08.PROPER.HDTV.x264-2HD.mp4 with 1 seeders and 0 leechers from TorrentProject
2016-07-25 12:43:36 INFO     SNATCHQUEUE-MANUALSNATCH-95021 :: [42fd472] Beginning to manual snatch release: The.Middle.S04E08.PROPER.HDTV.x264-2HD.mp4
```

Remove old detection of propers

---

sickbeard/refiners/release.py

Removing unicode_literals from release refiner

---

lib/appdirs.py

Add lib apps dir, needed for lib simpleanidb

---

gui/slick/views/displayShow.mako

Remove unnecessary bool()s from displayShow.mako

---

gui/slick/views/addShows_popularShows.mako
sickbeard/imdbPopular.py

Fix IMDB's Popular Shows

---

sickbeard/name_parser/parser.py

Discarding season specials (since it's not supported yet).

Fixing season special wrongly detected as season pack

---

sickbeard/providers/newznab.py

@duramato 
Fixes:
SEARCHQUEUE-MANUAL-290300 :: [SickBeard Index] :: [5a0408c] Found result: Hack.My.Life.S02E16.720p.HDTV.x264-W4F with -1 seeders and -1 leechers

Fix seeders/leechers logs

---

sickbeard/__init__.py

My cached used to be 9M. After vacuum its now 350kb

Performs VACUUM on cache.db

---

sickrage/show/History.py

another day, another bug.
Fixes https://github.com/pymedusa/SickRage/issues/831

Fixes pymedusa/SickRage/issues/831

---

gui/slick/js/editShow.js
gui/slick/js/testRename.js
gui/slick/views/editShow.mako
gui/slick/views/testRename.mako

* Added FanArt to editShow.mako
* Added FanArt to testRename.mako

Additional FanArt

---

gui/slick/views/snatchSelection.mako

Fix link to fanart in snatchSelection

---

pytest.ini
sickbeard/subtitles.py
tests/scene_helpers_tests.py
tests/test_subtitles.py
tox.ini

- PEP8 checks
- PEP257 checks
- cryptography import order style
- py.test (tests/test_subtitles.py is a reference implementation)

Experimenting: pytest flake8

---

sickbeard/name_parser/guessit_parser.py
sickbeard/providers/torrent/html/freshontv.py
sickbeard/subtitles.py
sickbeard/tv.py
tests/test_guessit.py
tests/test_subtitles.py
tox.ini

Remove "application-import-names" from tox.ini

---

sickbeard/server/web/config/providers.py

Fixes https://github.com/pymedusa/SickRage/issues/861
@medariox how come this wasn't noticed before?

Fix pymedusa/SickRage/issues/861

---

sickbeard/providers/torrent/json/torrentday.py

Fixes https://github.com/pymedusa/SickRage/issues/853

Fix pymedusa/SickRage/issues/853

---

sickbeard/network_timezones.py

Fix https://github.com/pymedusa/SickRage/issues/856
@medariox are you sure?

Fix pymedusa/SickRage/issues/856

---

.gitignore
pytest.ini
sickbeard/refiners/release.py
sickbeard/tv.py
tests/conftest.py
tests/test_release_refiner.py
tests/test_subtitles.py
tests/test_tvepisode_refiner.py
tox.ini

- Making tests to run faster
- Adding some unit tests for refiners

Improving tests config

---

pytest.ini
sickbeard/subtitles.py
sickrage/helper/common.py
tests/__init__.py
tests/conftest.py
tests/test_guessit.py
tests/test_subtitles.py
tests/test_tvepisode_refiner.py

Improving tests and adding more subtitles tests

---

gui/slick/views/config_general.mako

@OmgImAlexis is there a better way to do this using JS? Also when save settings, it auto-sort without having to reload entire page?
@ratoaq2 @medariox

Show selected branches first

---

sickbeard/name_parser/rules/rules.py
tests/datasets/tvshows.yml

Additional fix for multiple video formats in guessit

---

gui/slick/views/config_general.mako

when can't check remote branches

Fix TypeError: 'NoneType' object is not iterable

---

sickbeard/helpers.py

Fix TypeError: debug() got multiple values for keyword argument 'msg'

---

sickrage/show/recommendations/anidb.py

Fix exception for init the simpleanidb before CACHE_DIR had the chance to be set up

---

gui/slick/views/displayShow.mako

status is DOWNLOADED or ARCHIVED
If previous status is DOWNLOADED and we snatch another release, we shouldn't show those values from old status

Only show location, filaname, size, download link and subtitles if

---

gui/slick/views/displayShow.mako

Fix displayshow

---

gui/slick/views/config_providers.mako
sickbeard/__init__.py
sickbeard/helpers.py

@medariox @ratoaq2 @p0psicles 
I'm done with features until next release

Get broken providers from sickrage.io and force disable provider if is broken

---

gui/slick/views/config_postProcessing.mako
sickbeard/subtitles.py

Possible fix for https://github.com/pymedusa/SickRage/issues/892
Avoid overlapping of PP
@ratoaq2 review & approve please?

Don't call PP in postpone if auto PP is enabled

---

sickbeard/imdbPopular.py
sickrage/show/recommendations/imdb.py

Fix ImdbPopular

---

gui/slick/views/config_postProcessing.mako

Proper english

---

gui/slick/js/qualityChooser.js

The cause was the usage of attr, as that's not compatible with our version of jQuery.

Fixed switching qualities a few times, resulted in not quality selected at all on saving

---

gui/slick/js/ajaxEpSubtitles.js
gui/slick/js/apibuilder.js
gui/slick/js/blackwhite.js
gui/slick/js/configProviders.js
gui/slick/js/core.js
gui/slick/js/editShow.js
gui/slick/js/rootDirs.js

* Changed attr('','') to make use of prop().
* Changed some of the ('selected', 'selected') to ('selected', true)
Todo:
* Noticed that some of the ('disabled', 'disabled') can also be changed to ('disabled', true).
Maybe cleanup some other prop() dom mutations.

Changed the $.attr() dom mutations to make use of $.prop()

---

gui/slick/js/core.js
gui/slick/views/addShows_recommended.mako
gui/slick/views/addShows_trendingShows.mako

Fix viewlog & UI tabs

---

gui/slick/js/core.js

Fix ajax only adding baseurl on relative urls

---

gui/slick/js/configProviders.js
gui/slick/js/core.js
gui/slick/views/addShows_recommended.mako
gui/slick/views/apiBuilder.mako
gui/slick/views/config_subtitles.mako
gui/slick/views/displayShow.mako
gui/slick/views/history.mako
gui/slick/views/home.mako
gui/slick/views/schedule.mako
gui/slick/views/snatchSelection.mako
sickbeard/server/api/v2/info.py
sickbeard/server/web/core/base.py

remove srRoot

---

lib/traktor/trakt.py
sickbeard/__init__.py
sickbeard/notifiers/trakt.py

Fix trakt snatch notification

---

gui/slick/views/addShows_addExistingShow.mako
gui/slick/views/addShows_newShow.mako
gui/slick/views/addShows_recommended.mako
gui/slick/views/addShows_trendingShows.mako

fix rename typo

---

gui/slick/js/ajax-notifications.js
gui/slick/js/core.js
gui/slick/views/addShows_trendingShows.mako

Fix random js issues

---

gui/slick/js/core.js

Fix missing initBlackListShowById

---

gui/slick/js/core.js
gui/slick/views/restart.mako

Fix restart page

---

gui/slick/views/layouts/main.mako

Fix apiKey leaking

---

gui/slick/js/core.js
gui/slick/views/addShows_newShow.mako

Fix anonURL in js

---

gui/slick/js/core.js
gui/slick/views/addShows_recommended.mako
sickbeard/server/web/home/add_shows.py
sickrage/show/recommendations/trakt.py

Show watched (and removed from medusa) recommended show as....watched!

---

sickbeard/providers/torrent/json/t411.py

Fixes pymedusa/SickRage/issues/916

---

sickbeard/providers/torrent/html/iptorrents.py

Thanks @OmgImAlexis for the fix.

Fix IPTorrents, reorder imports

---

sickbeard/server/web/core/base.py

@OmgImAlexis 
This works for me.

Fix base_url with domain

---

gui/slick/js/core.js

Fixes https://github.com/pymedusa/SickRage/issues/940

Fix pymedusa/SickRage/issues/940

---

gui/slick/views/addShows_addExistingShow.mako

Fix addExistingShows page refreshing

---

sickbeard/name_parser/rules/__init__.py
sickbeard/name_parser/rules/properties.py
tests/datasets/tvshows.yml

- To make @duramato happy with his "regular" cases :-)

Adding S00EP00 pattern to guessit

---

sickbeard/tv.py

Fix for #944: Wrong log call in tv.py

---

sickbeard/logger.py
sickbeard/search.py
sickbeard/server/web/home/handler.py
sickbeard/show_queue.py

as discussed with @ratoaq2 for now we will keep broad catch until we use a notifiy manager and rewrite providers
@medariox @p0psicles 
```
SNATCHQUEUE-MANUALSNATCH-305288 :: Adding Stranger Things S01E05 to Trakt watchlist
```

Log all episodes added to trakt watchlist and fix 'e' not referenced

---

gui/slick/js/core.js

Adjust posterPopup resize for Poster view on hover

---

gui/slick/views/addShows_addExistingShow.mako
gui/slick/views/config_anime.mako
gui/slick/views/config_backuprestore.mako
gui/slick/views/config_general.mako
gui/slick/views/config_notifications.mako
gui/slick/views/config_postProcessing.mako
gui/slick/views/config_providers.mako
gui/slick/views/config_search.mako
gui/slick/views/config_subtitles.mako
gui/slick/views/editShow.mako
gui/slick/views/manage_massEdit.mako

Fix tab refreshing page

---

gui/slick/views/addRecommended.mako
gui/slick/views/addShows_recommended.mako
sickbeard/server/web/core/base.py
sickbeard/server/web/home/add_shows.py

This is a just another hack to fix relative pages. We'll be able to remove these soon once we restructure the URLs. 
@p0psicles and @ratoaq2 I need to have a proper talk to both of you so we can decide what'll be the best option as I'd like to mirror the page URLs as closely to the API as possible.

Fix tabs reloading pages

---

sickbeard/helpers.py
sickrage/helper/common.py

Helps disabling provider when user doesn't save any settings or doesnt restart medusa after we update broken providers
@duramato

Improve broken providers disabling

---

sickbeard/helpers.py

Fixes https://github.com/pymedusa/SickRage/issues/452
and 
Fixes https://github.com/pymedusa/SickRage/issues/453

Fix pymedusa/SickRage/issues/452

---

sickbeard/helpers.py

Related to: https://github.com/pymedusa/SickRage/issues/838

Remove another broad catch and improve code

---

sickbeard/name_parser/parser.py

Fixes: https://github.com/pymedusa/SickRage/issues/964
Fixes: https://github.com/pymedusa/SickRage/issues/961
@medariox @ratoaq2

Two more issues fixes

---

sickbeard/metadata/generic.py

@medariox @duramato 
Fixed second issue: https://github.com/pymedusa/SickRage/issues/452#issuecomment-242038984

Fixes pymedusa/SickRage/issues/452

---

gui/slick/js/apibuilder.js
gui/slick/views/apiBuilder.mako

@OmgImAlexis 
```
2016-08-23 17:25:02 WARNING  TORNADO :: [b2476ac] 404 GET /js/core.min.js?12168 (143.107.176.135) 3.16ms
2016-08-23 17:25:01 WARNING  TORNADO :: [b2476ac] 404 GET /images/donate.jpg (143.107.176.135) 2.94ms
2016-08-23 17:25:01 WARNING  TORNADO :: [b2476ac] 404 GET /js/core.min.js?12168 (143.107.176.135) 5.72ms
```

Remove non-existing files

---

sickbeard/providers/torrent/html/transmitthenet.py

Fixes: https://github.com/pymedusa/SickRage/issues/475#issuecomment-242038736

Fix seeders/leechers and info beeing removed from ttn

---

gui/slick/views/addShows_addExistingShow.mako
gui/slick/views/addShows_newShow.mako

@duramato please test and approve

Fix add shows

---

gui/slick/js/add-show-options.js
gui/slick/views/addShows_addExistingShow.mako
gui/slick/views/addShows_newShow.mako

Add show fix

---

gui/slick/views/config_anime.mako
gui/slick/views/config_backuprestore.mako
gui/slick/views/config_general.mako
gui/slick/views/config_notifications.mako
gui/slick/views/config_postProcessing.mako
gui/slick/views/config_providers.mako
gui/slick/views/config_search.mako
gui/slick/views/config_subtitles.mako
gui/slick/views/editShow.mako
gui/slick/views/manage_massEdit.mako

@OmgImAlexis agree?
Related to https://github.com/pymedusa/SickRage/commit/b64c81db48ba7f8f1e8a1382057a1763d3a0d501
I found a bug in backRestor.mako so I saw that all mako files were missing the "hack" we did here:
https://github.com/pymedusa/SickRage/pull/969/commits/db1ba6ff6f4a449d7da3bce3067fb4fa02bb6cba

Fix another tab issue

---

sickbeard/logger.py
sickbeard/name_parser/parser.py
tests/test_logger.py

Fix https://github.com/pymedusa/SickRage/issues/975

---

pytest.ini
tox.ini

- Added PEP8 naming convention checks
- No code changes, only configuration

Adding pep8 naming config

---

gui/slick/js/test-rename.js

Fixed:  "TypeError: SICKRAGE.info is undefined" in /home/testRename

Fix test rename

---

sickbeard/server/web/core/authentication.py

Fixes https://github.com/pymedusa/SickRage/issues/983
can you test this with proxy/rever proxy or whatever you use?
@ratoaq2 @OmgImAlexis @medariox @p0psicles

Fix login redirection

---

gui/slick/js/core.js
sickbeard/server/api/v2/log.py
sickbeard/server/api/v2/show.py
sickbeard/server/core.py

add apiv2/logs & general cleanup

---

sickbeard/subtitles.py

@ratoaq2 
Fixes the `Attribute release_group changed from FOCUS to KILLERS`
```
2016-08-25 10:53:00 DEBUG    FINDSUBTITLES :: [555b0cb] Attribute release_group changed from FOCUS to KILLERS
2016-08-25 10:52:59 DEBUG    FINDSUBTITLES :: [555b0cb] Guessing using /media/SAMSUNG/media/downloaded/series/Suits.S06E07.1080p.WEBRip.DD5.1.x264-FOCUS[rartv]/Suits.S06E07.720p.HDTV.x264-KILLERS.mkv
2016-08-25 10:52:59 DEBUG    FINDSUBTITLES :: [555b0cb] Starting release refiner [extension=release, release_name=Suits.S06E07.720p.HDTV.x264-KILLERS, release_file=None]
2016-08-25 10:52:58 DEBUG    FINDSUBTITLES :: [555b0cb] Scanning video /media/SAMSUNG/media/downloaded/series/Suits.S06E07.1080p.WEBRip.DD5.1.x264-FOCUS[rartv]/Suits.S06E07.1080p.WEBRip.DD5.1.x264-FOCUS.mkv...
```
```
2016-08-25 11:11:40 …
```

Fix wrong release name in refiner when replacing file

---

sickbeard/subtitles.py

Improve subtitles log message

---

sickbeard/providers/torrent/json/rarbg.py

when error_code was 5, code stopped in the first IF.... so i wouldn't reach the check if code is 5

Fix RARBG showing error_code 5 as WARNING

---

gui/slick/views/home_postprocess.mako

Manual PP setting must respect user default setting

---

sickbeard/dailysearcher.py

```
2016-08-27 17:41:32 INFO     SEARCHQUEUE-DAILY-SEARCH :: [998b4fc] No needed episodes found
2016-08-27 17:41:31 INFO     SEARCHQUEUE-DAILY-SEARCH :: [998b4fc] Beginning daily search for new episodes
2016-08-27 17:41:30 INFO     DAILYSEARCHER :: [998b4fc] No newly released episodes found ...
2016-08-27 17:41:29 INFO     DAILYSEARCHER :: [998b4fc] Searching for newly released episodes ...
```
SEARCHQUEUE-DAILY-SEARCH is the one that actually does the search and all logs are under this thread

Remove more duplicate log messages

---

sickbeard/notifiers/growl.py

@Thraxis 
Test notifications doesn't use PROPER check

Fixes pymedusa/SickRage/issues/994

---

gui/slick/js/core.js

Fix pymedusa/SickRage/issues/1011

---

.build/bower.json
gui/slick/css/dark.css
gui/slick/css/light.css
gui/slick/css/print.css
gui/slick/css/style.css
package.json

This doesn't actually change any CSS and I'll add stylelint to Travis once I get all of these files to 100% passing just like I did with the js.

Add stylelint & cleanup CSS

---

sickbeard/server/web/home/handler.py

Change log line to warning

---

sickbeard/logger.py

Fixing duplicated log lines when using standard logging api

---

gui/slick/views/config_postProcessing.mako

@p0psicles need to cherry pick to master
thanks to @themixer2000

Fix pymedusa/SickRage/issues/1017

---

gui/slick/js/ajax-episode-search.js
gui/slick/js/edit-show.js
gui/slick/js/test-rename.js

update click to on click

---

sickbeard/show_queue.py
sickbeard/tv.py

Fix log lines

---

sickbeard/common.py
tests/test_common.py

Fix for #1029 Quality.from_guessit when multiple formats

---

sickbeard/show_queue.py
sickbeard/tv.py

@ratoaq2 there was no try:except when calling it (as we talked a few days ago)
I only found this error because I was running in cmd.

Fixes AttributeError: 'TVShow' object has no attribute 'show'

---

sickbeard/failedProcessor.py
sickbeard/server/web/home/handler.py

Uses the same code from here:
https://github.com/pymedusa/SickRage/blob/develop/sickbeard/server/web/home/handler.py#L947-L959
If works, we can move this code to a `helper`
@ratoaq2 @p0psicles @medariox Thanks for the inputs

Fix pymedusa/SickRage/issues/551

---

pytest.ini
sickbeard/clients/__init__.py
sickbeard/clients/deluge_client.py
sickbeard/clients/deluged_client.py
sickbeard/clients/download_station_client.py
sickbeard/clients/generic.py
sickbeard/clients/mlnet_client.py
sickbeard/clients/qbittorrent_client.py
sickbeard/clients/rtorrent_client.py
sickbeard/clients/transmission_client.py
sickbeard/clients/utorrent_client.py
sickbeard/search.py
sickbeard/server/web/home/handler.py
tests/test_clients.py

Clients: Code linting: flake8 fixes + initial tests for clients

---

gui/slick/views/config_notifications.mako

Fix config/notifications not saving

---

sickbeard/name_parser/parser.py

Fix for #1043: AttributeError: 'NoneType' object has no attribute 'name'

---

sickbeard/versionChecker.py

Fix pymedusa/SickRage/issues/1048

---

pytest.ini
sickbeard/providers/torrent/html/pretome.py
sickbeard/providers/torrent/html/scc.py
sickbeard/providers/torrent/html/thepiratebay.py

* Removed quote
* Fix seeders, leechers, size parsing
* Use try_int
* Remove useless code
* General cleanup
* Pep

Improve Pretome provider

---

gui/slick/views/history.mako
sickbeard/classes.py
sickbeard/databases/main_db.py
sickbeard/history.py
sickbeard/search_queue.py
sickrage/providers/GenericProvider.py

Fix proper tags storing as "P.R.O.P.E.R"

---

sickrage/providers/GenericProvider.py

@medariox @duramato
```
DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: [3018190] Search mode: Season
DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: [3018190] Search string: Paw Patrol S02
```

Fix pymedusa/SickRage/issues/1010

---

gui/slick/views/partials/footer.mako

Fix footer stats not refreshing #1054

---

sickbeard/search_queue.py

Fix making episodes as proper when its not

---

pytest.ini
sickbeard/__init__.py
sickbeard/github_client.py
sickbeard/issuesubmitter.py
sickbeard/server/web/config/general.py
sickbeard/versionChecker.py
tests/test_issuesubmitter.py

Fix pymedusa/SickRage/issues/1050

---

sickbeard/__init__.py
sickbeard/helpers.py

Fix for #1056. Folders should only be removed if they do exist

---

sickbeard/tv.py

Fix pymedusa/SickRage/issues/1078

---

sickbeard/metadata/generic.py

Add exception for ParseError. Fixes #1066

---

sickbeard/metadata/generic.py

Sorry, doesn't work with binary mode.

Revert encoding in metadata/generic

---

gui/slick/js/manage/episode-statuses.js

fix collapse button

---

sickbeard/postProcessor.py

Small optimizations in PP

---

sickbeard/scene_exceptions.py

FYI this is not a new error, we just report it now. :)

Fix ValueError in scene_exceptions #1097

---

sickbeard/name_parser/parser.py
sickbeard/properFinder.py

Avoid snatch proper when codec is different from current proper

---

sickbeard/properFinder.py

Don't use already processed propers if we do a forced proper search

---

sickbeard/providers/torrent/html/extratorrent.py

Fix ExtraTorrent parsing

---

gui/slick/js/manage/subtitle-missed.js

Same as in here: https://github.com/pymedusa/SickRage/pull/1085
@OmgImAlexis

Fix missed subtitles collapse button

---

sickbeard/providers/torrent/html/pretome.py

Fixed seeders/leechers parsing for PTM provider

---

sickbeard/metadata/generic.py

Uses the same way as subliminal
https://github.com/Diaoul/subliminal/blob/develop/subliminal/core.py#L691-L699

Fixes pymedusa/SickRage/issues/484

---

sickbeard/processTV.py

@ratoaq2  need to pass the also the folder to help guess info

Fixes pymedusa/SickRage/issues/1106

---

sickbeard/showUpdater.py
sickbeard/tv.py

I only added a try:except with the imdb exceptions

Fix pymedusa/SickRage/issues/1113

---

sickbeard/scene_exceptions.py

Fix scene exceptions update if AniDB doesn't have the show

---

gui/slick/js/config/search.js
gui/slick/views/config_search.mako
sickbeard/nzbget.py
sickbeard/server/web/home/handler.py

Add NZBget connection test

---

sickbeard/__init__.py
sickbeard/github_client.py
sickbeard/issuesubmitter.py
sickbeard/logger.py
sickbeard/server/web/config/general.py

Github enhancements

---

sickbeard/tv.py

Fix show object being updated with empty imdb data

---

sickbeard/providers/torrent/rss/rsstorrent.py

Fix Too many arguments for format string

---

sickbeard/db.py

Fix No exception type(s) specified

---

sickbeard/notifiers/telegram.py

Fix return statement in finally block may swallow exception

---

sickbeard/databases/__init__.py

Fix Undefined variable name 'cache' in __all__

---

gui/slick/js/manage/init.js

Revert #d85da52

---

pytest.ini
sickbeard/db.py
sickbeard/server/web/manage/handler.py

Fix Dangerous default value [] as argument

---

gui/slick/js/manage/init.js

Rename from "None" to "No subtitles"

---

sickbeard/__init__.py

Fix Expression is assigned to nothing

---

pytest.ini
sickbeard/providers/torrent/html/extratorrent.py

Avoid parsing of 'related torrents' for ET, minor cleanup

---

sickbeard/name_parser/parser.py

Multi season releases should be discarded by release parser

---

sickbeard/providers/torrent/json/torrentday.py

Fix TorrentDay login

---

COPYING.txt

Change copyright

---

gui/slick/js/config-providers.js
gui/slick/js/parsers.js
gui/slick/js/trending-shows.js

fix xo errors

---

sickbeard/providers/torrent/html/extratorrent.py

Fix ET parsing with daily search

---

sickbeard/databases/main_db.py

Update DB version to v44 to keep compatibility

---

gui/slick/js/mass-update.js

Fix massUpdate

---

sickbeard/databases/main_db.py

Update comments in DB upgrade

---

medusa/databases/main_db.py

Bump MAX_DB_VERSION to 44

---

medusa/__init__.py
medusa/versionChecker.py

Executing git clean during update process

---

medusa/versionChecker.py

Fixes https://gist.github.com/medariox/070cf704666f8f46fe542c6d16a8fb86

Fix list to tuple concatenate

---

gui/slick/views/config_postProcessing.mako

Fix mako error in config_postProcessing

---

gui/slick/js/history/index.js

Save sort in history page and sort by "subtitles"

---

medusa/image_cache.py

Fix pymedusa/SickRage/issues/1063

---

medusa/server/api/v1/core.py

Fix pymedusa/SickRage/issues/1172

---

gui/slick/views/config.mako

Fix pymedusa/SickRage/issues/1181

---

.editorconfig
gui/slick/css/style.css

We still have over 400 issues with the CSS that need to be fixed before stylelint can be turned on with Travis. If you're working on the CSS I'd suggest you install one of the [stylelint plugins](https://github.com/stylelint/stylelint#getting-started).

fix css rules

---

gui/slick/css/style.css

fix stupid Bootstrap hack

---

medusa/image_cache.py

@medariox why sometimes I get "0L" and sometimes just "0" ?

Fix image size check

---

medusa/issuesubmitter.py

@ratoaq2  @medariox 
Its submitting an issue in a PR:
https://github.com/pymedusa/SickRage/pull/881#issuecomment-249415545
"This endpoint may also return pull requests in the response. If an issue is a pull request, the object will include a pull_request key."
https://developer.github.com/v3/issues/#list-issues

Only find similar issues, discard PR

---

medusa/server/web/home/handler.py

Fix manual search

---

gui/slick/css/style.css

Fix selects width. It should auto resize

---

medusa/providers/torrent/html/extratorrent.py
medusa/providers/torrent/html/zooqle.py
tox.ini

DON'T SQUASH so we can't revert the travis commit later
@medariox @duramato

Fix ExtraTorrent cropping release_name

---

gui/slick/css/style.css

Fix pymedusa/SickRage/issues/1083

---

package.json

fix branding cleanup for xo and remove unused scss

---

medusa/server/api/v2/base.py

move APIv2's status from JSON to http status code

---

medusa/server/api/v2/base.py

@OmgImAlexis JS loading is broken in develop. Is there a easy fix or revert this?

Revert "move APIv2's status from JSON to http status code"

---

tox.ini

gitlab.com/pycqa/flake8-docstrings/issues/16

Fix flake tests

---

medusa/name_parser/guessit_parser.py
medusa/name_parser/rules/__init__.py
medusa/name_parser/rules/properties.py
medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Several guessit enhancements/bug fixes

---

medusa/logger.py
medusa/server/web/core/error_logs.py

Fix for #1118: log_filter='SEARCHQUEUE' and 'SHOWQUEUE' doesn't work

---

medusa/logger.py
tests/conftest.py
tests/test_logger.py

Fix for #1171: UnicodeDecodeError: utf8 when reading logs

---

medusa/name_parser/rules/rules.py
tests/test_guessit.py
tests/test_guessit.yml

Fixing another multiple formats corner case

---

gui/slick/views/config_postProcessing.mako

We don't need anymore quality in naming pattern

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Enhancing wrong RG and multiple titles when show name contains year

---

medusa/server/api/v2/info.py
medusa/server/web/home/handler.py
static/js/ajax-episode-subtitles.js
static/js/home/display-show.js
static/js/manage/subtitle-missedPP.js

Manual subtitle search small fixes

---

medusa/server/web/home/handler.py

Fix from @beschoenen in SickRage 
Old repo issue: 2437

Compare lowercase for showlist sort

---

medusa/providers/torrent/json/hd4free.py

Change HD4Free log line

---

medusa/providers/torrent/html/limetorrents.py

Fix limetorrents' id regex matching any char instead of a literal dot

---

medusa/subtitles.py
static/js/ajax-episode-subtitles.js

Fix subtitle flag when multi enabled

---

medusa/versionChecker.py

Also use not annotated tags to determine version

---

static/css/dark.css
static/css/style.css

fix bootstrap padding

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Fix guessit exception for multiple same titles

---

static/js/core.js

fix login page js

---

static/js/core.js

fix webroot + reverse proxy on login page

---

medusa/refiners/tvepisode.py
tests/test_tvepisode_refiner.py

subtitle is associated to filename only
@ratoaq2 what do you think?
ping @duramato 
`2016-10-12 19:15:24 DEBUG    Thread-15 :: [76a5be3] Attribute episode changed from 7 to 6`

Fix subtitle search using scene numbering

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Bug fix for #1200. Anime should have absolute episode numbers

---

medusa/server/web/manage/handler.py
views/manage_subtitleMissedPP.mako

Only for postpone if no subs feature

Sort releases in PP by age. Most likely need manual subtitle search

---

medusa/providers/GenericProvider.py

Remove thetorrent org (down since a few days)

---

medusa/server/web/manage/handler.py
views/manage_subtitleMissedPP.mako

it was sorting after every file appended

Fix sort in missing subtitles for postpone

---

medusa/providers/torrent/html/hounddawgs.py
medusa/providers/torrent/html/limetorrents.py
medusa/providers/torrent/html/thepiratebay.py
medusa/providers/torrent/json/rarbg.py
medusa/providers/torrent/json/t411.py
medusa/providers/torrent/rss/nyaatorrents.py

Related: https://github.com/pymedusa/Medusa/issues/1278
@duramato @medariox

Add confirmed/ranked logs

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

Missed rebranding

---

medusa/common.py
medusa/databases/main_db.py
medusa/name_parser/parser.py
medusa/postProcessor.py
medusa/processTV.py
medusa/search/proper.py
medusa/tv.py
pytest.ini

Various improvements/bug fixes to PP

---

medusa/helpers.py

Fixes https://github.com/pymedusa/Medusa/issues/1286

Fix pymedusa/Medusa/issues/1286

---

medusa/logger.py

@pymedusa/developers Please, can someone confirm this fix works on Windows?

Fix #1287: decode unicode not supported

---

medusa/providers/torrent/html/hdspace.py
pytest.ini

Fixes "HDSpace wrongfully parsed" #1284

---

readme.md

Fix dognzb url in readme

---

medusa/name_parser/parser.py

Change log line to be more descriptive

---

views/history.mako
views/manage_subtitleMissedPP.mako

@OmgImAlexis 
the "#S03E04" seems useless. only #season-3 works

Add URL link and fix history link URL

---

medusa/providers/torrent/rss/nyaatorrents.py

Fix nyaatorrent provider.

---

medusa/server/web/home/handler.py

Fix editShow of anime, when it's changed to anime through massEdit

---

medusa/tvcache.py

Remove broad exception from  tv_cache

---

medusa/providers/nzb/omgwtfnzbs.py

```
Hi all, 
We successfully moved to the new site and are working on bringing back the VIP upgrade. Stay tuned!
Our Domain name will from now on be omgwtfnzbs.me.
The old domain will still be vaild for roughly 2 months.
This should give you enough time to update your clients.
Join us on IRC  or use the contact Staff form if you found bugs or have any questions.
- Thanks for your patience the new Team
```

Change omgwtfnzbs url

---

medusa/server/web/manage/handler.py

Fixes https://github.com/pymedusa/Medusa/issues/1313

Fixes AttributeError: 'Logger' object has no attribute 'debug'

---

medusa/search/core.py

Reset location is causing not replacing file issue

---

medusa/providers/torrent/html/extratorrent.py
medusa/providers/torrent/html/torrentproject.py
medusa/providers/torrent/html/zooqle.py

Remove strip() from some providers

---

medusa/server/web/config/general.py
views/config_general.mako

Log is reconfigured on the fly with @ratoaq2 code.

Add DBDEBUG to UI - only if developer

---

lib/tvdbapiv2/configuration.py
lib/tvdbapiv2/rest.py

* Import urllib3 from requests.

Update tvdbapiv2 lib.

---

medusa/server/web/core/base.py

Sorry for the delay @OmgImAlexis 
I changed the code a bit. Does it look good to you?

Don't show login page if user/pass isn't set

---

medusa/providers/torrent/html/extratorrent.py
medusa/providers/torrent/html/thepiratebay.py
medusa/providers/torrent/html/torrentproject.py
medusa/providers/torrent/json/bitcannon.py
medusa/providers/torrent/json/btdigg.py

Fixes https://github.com/pymedusa/Medusa/issues/1328
@wimpyrbx  try this please.
stop medusa, change this file as this and try again
TODO:

Fixes pymedusa/Medusa/issues/1328

---

medusa/providers/GenericProvider.py

Use torrasave.top instead of vr3mrzpy4ugpt2wi.onion.cab

---

lib/subliminal/providers/legendastv.py

Upgrade subliminal to 32578ee626225567c106c17963acb96e67cdab9a

---

medusa/show/recommendations/anidb.py
medusa/show/recommendations/recommended.py

* Now where showing an info log message.

Fixed Exception shown when an anidb OVA can't be mapped to a TVDB id.

---

views/layouts/main.mako

Rename subtitle-missedPP.js to subtitle-missed-post-process.js

---

medusa/providers/torrent/html/torrentbytes.py

Fixes: ```The.Wire.S01.1080p.BluRay.x264-SCENE[F L]```, which should be ```The.Wire.S01.1080p.BluRay.x264-SCENE``` upon parsing.

Fixes TB's FL torrent's having the tagging part of the name

---

medusa/__init__.py
medusa/search/proper.py
medusa/server/web/config/search.py
views/config_search.mako

Use custom proper search days

---

medusa/server/api/v2/base.py
medusa/server/api/v2/config.py
medusa/server/api/v2/info.py
medusa/server/api/v2/show.py
medusa/server/api/v2/status.py
medusa/server/core.py
medusa/server/web/core/base.py
medusa/server/web/core/error_logs.py
medusa/server/web/core/file_browser.py
medusa/server/web/core/history.py
medusa/server/web/home/handler.py
medusa/server/web/home/news.py
static/js/add-shows/init.js
static/js/add-shows/new-show.js
static/js/ajax-episode-subtitles.js
static/js/common/init.js
static/js/config-providers.js
static/js/config/backup-restore.js
static/js/config/init.js
static/js/config/notifications.js
static/js/config/search.js
static/js/config/subtitles.js
static/js/core.js
static/js/home/display-show.js
static/js/home/edit-show.js
static/js/home/index.js
static/js/home/snatch-selection.js
static/js/parsers.js
static/js/schedule/index.js
static/js/trending-shows.js

@ratoaq2 can you review this please.

add more fields to apiv2

---

static/js/add-shows/new-show.js

Inverse the !== condition. As it made sure to return when it HAS a value.

---

medusa/__init__.py
medusa/server/api/v2/config.py

Caching static configuration in config api v2.

---

medusa/ehandler.py
medusa/scheduler.py
medusa/server/web/core/base.py
start.py

Adding a single exception handler to handle unhandled exceptions

---

readme.md

-  [x] PR is based on the DEVELOP branch

Updating with MediaInfo disclaimer

---

medusa/postProcessor.py

Always use EpisodePostProcessingFailedException for failing PP

---

views/config_providers.mako

Fix api key in provider settings beeing shown in plain text

---

medusa/providers/nzb/omgwtfnzbs.py

Fix omgwtfnzbs log line

---

medusa/versionChecker.py

TypeError: argument of type 'NoneType' is not iterable

---

medusa/helper/common.py
medusa/tv.py

@OmgImAlexis @ratoaq2 
I tried:
```python
def to_json(self):
"""JSON representation."""
return json.dumps(self)
```
but i get this:
```python
File "/usr/lib/python2.7/json/encoder.py", line 184, in default
raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <medusa.tv.TVEpisode object at 0x6cf69fb0> is not JSON serializable
```
maybe because tv_episode.show is a TV Show class?

Return tv episode object as JSON

---

static/js/lib/timeago.js
views/layouts/main.mako

This fixes the issue @Thraxis has.

add timeago lib

---

medusa/show/recommendations/trakt.py

Moving tvdb api v2 initialization away from module import

---

static/js/lib/fix-broken-ie.js
views/layouts/main.mako

Add missing endsWith function for IE11.
JS file added for common location to add any other missing functions for
IE11

Adds missing endsWith Function for IE11

---

medusa/indexers/indexer_base.py
medusa/indexers/tvdbv2/tvdbv2_api.py

Fix metadata from TVDB

---

medusa/show/recommendations/trakt.py

Hotfix: Removed the module level import of tvdbapiv2 from the module import.

---

static/js/history/index.js

History: Sort subtitles by title (provider : lang)

---

medusa/tv.py

Fix hide Originally Airs, when it's not available in the indexer.

---

medusa/providers/torrent/json/t411.py
pytest.ini

Fixes https://github.com/pymedusa/Medusa/issues/1372
torrent_rows  is a list of dict
@medariox @duramato @FireBladeNooT
thanks to pycharm

Fix pymedusa/Medusa/issues/1372

---

static/js/add-shows/new-show.js
static/js/ajax-episode-search.js
static/js/home/snatch-selection.js

* At the same time searched for other .ajax() calls, and changed them to use the .done() callback.
* Forcesearch on an episode.
* Searching for a new show.
* Manualsearch on an episode.

Fixed ajax-episode-search.js, as done should be used as a deferred callback.

---

pytest.ini

https://gist.github.com/ratoaq2/0d7d017d4cf71ac0f9728907e0bd1140

pytest.ini updated

---

.github/ISSUE_TEMPLATE.md

Change topics in issue template to bold for easier readability

---

views/config_providers.mako

Fix missing rename

---

lib/OpenSSL/SSL.py
lib/OpenSSL/__init__.py
lib/OpenSSL/_util.py
lib/OpenSSL/crypto.py
lib/OpenSSL/rand.py
lib/OpenSSL/tsafe.py
lib/OpenSSL/version.py

This is a hotfix to master. Added pyOpenSSL 16.1.0 in order to fix infamous 0.14-1 bug.
It needs confirmation that it actually works. And it also needs to be tested on other systems.
This should fix #1385
@whipcracker Are you able to test this branch and report back if that fixed your issue?

Adding pyOpenSSL 16.2.0 as to fix pyOpenSSL 0.14-1 bug

---

medusa/__init__.py
medusa/helpers.py

Update only if last update wasn't done in last hour
@medariox @duramato

Improved check for broken providers

---

medusa/providers/torrent/html/morethantv.py

Fix pymedusa/Medusa/issues/1387

---

views/history.mako

@duramato please test asap or this PR will be closed lol
@medariox review please?

Fix failed actions in compact history

---

medusa/providers/torrent/html/iptorrents.py
pytest.ini

Add cookie login to bypass captcha for IPTorrents

---

medusa/providers/torrent/html/scenetime.py
pytest.ini

Add cookie login to bypass captcha for SceneTime

---

medusa/providers/torrent/torrent_provider.py

Remove useless check in torrent_provider

---

medusa/exception_handler.py
medusa/metadata/generic.py
medusa/scheduler.py
medusa/server/web/core/base.py
start.py

Enhancing exception handler

---

static/js/root-dirs.js

Fix rootDir / parent directory not saving.

---

medusa/helpers.py
medusa/init/filesystem.py

Certifi to always return bytes to avoid pyOpenSSL 0.14-1 rejecting unicode strings

---

views/history.mako

Add a more clear tooltip for failed downloads

---

static/js/history/index.js

Fixes https://github.com/pymedusa/Medusa/issues/1419
@OmgImAlexis

Fix pymedusa/Medusa/issues/1419

---

lib/tvdbapiv2/api_client.py
lib/tvdbapiv2/apis/authentication_api.py
lib/tvdbapiv2/apis/episodes_api.py
lib/tvdbapiv2/apis/languages_api.py
lib/tvdbapiv2/apis/search_api.py
lib/tvdbapiv2/apis/series_api.py
lib/tvdbapiv2/apis/updates_api.py
lib/tvdbapiv2/apis/users_api.py
lib/tvdbapiv2/configuration.py
lib/tvdbapiv2/rest.py
medusa/indexers/indexer_base.py
medusa/indexers/tvdbv2/tvdbv2_api.py

Tvdbv2 no unicode_literals

---

medusa/tv.py

Remove breaking .upper() for ints in tv.py

---

medusa/subtitles.py

@FireBladeNooT can you try this? I didn't test. Its just a "guess it will work" lol
https://github.com/pymedusa/Medusa/issues/1417
ping @ratoaq2 
it will show `version`:  LOL

Fix pymedusa/Medusa/issues/1417

---

medusa/name_parser/guessit_parser.py

Expected titles should be cached against show names and scene exception names

---

medusa/search/core.py

Now user can see the log about show pause
@medariox
Related to: https://github.com/pymedusa/Medusa/issues/1453

Remove duplicate code for show paused in daily

---

tox.ini

Avoid incompatible pycodestyle version in tox.ini

---

medusa/providers/torrent/json/rarbg.py

RARBG: Invalid token as debug (server sync issue)

---

medusa/network_timezones.py

default value is '':
https://github.com/pymedusa/Medusa/blob/develop/medusa/tv.py#L1101
Should we change default to None?
@medariox @p0psicles

Fix missing network when value is empty

---

views/history.mako

forgot one push in pycharm. I only commited =(

Fix history! ops

---

views/history.mako

Fix history, again

---

medusa/name_parser/guessit_parser.py
medusa/name_parser/rules/properties.py
medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Adding more guessit scenarios

---

medusa/logger.py

Fix DB logging level

---

medusa/__init__.py
medusa/process_tv.py
medusa/server/web/config/subtitles.py
medusa/subtitles.py
views/config_subtitles.mako
views/manage_manageSearches.mako

@ratoaq2 this is my initial idea
`knowit` returns a language object using 3 opensubtitles lang? How to compare with app.SUBTITLES_LANGUAGES?

Check if embedded subtitles are wanted and bypass postpone

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Handling guessit issue #357

---

medusa/show_queue.py

Replace wrong error message for EpisodeDeletedException

---

medusa/subtitles.py

@NicoLeOca: This should fix the "do not postpone if any embedded sub matches a wanted language"
Shame on @fernandog. I asked him to test before merging the other PR.

Fixing language detection

---

medusa/scene_numbering.py

Fix set manual season scene numbering for special seasons.

---

lib/knowit/__init__.py
lib/knowit/__main__.py
lib/knowit/properties.py
lib/knowit/provider.py
lib/knowit/providers/enzyme.py
lib/knowit/providers/mediainfo.py

Upgrading knowit to 0.1.4

---

views/config_search.mako

fix missing </div>

---

static/js/core.js
views/config.mako

add vue to config page

---

medusa/exception_handler.py

Handling EnvironmentError to cover IOError and OSError

---

medusa/indexers/tvdbv2/tvdbv2_api.py

Fixed missing tvdb base_url for actor images.

---

views/addShows_newShow.mako
views/config_general.mako

Removed the blank options for the language control.

---

medusa/tv.py

Changing log, as I suspect it's incorrectly showing the status change.

---

medusa/naming.py
views/config_postProcessing.mako

Let's Modernize

---

medusa/process_tv.py

Fix #1093: Another none arg passed to guessit

---

views/displayShow.mako

Now I think about it. I think it was like |drama|adventure| before. At least that's the only explanation I can come up with.

Fix genre pills in displayShow.mako when show can't be mapped to imdb.

---

medusa/helpers.py

committed from phone. if someone else wants to add the new != old check feel free, otherwise just merge it
I will be away for a couple of days or more.

Fix renaming log line

---

medusa/post_processor.py
tests/legacy/feedparser_tests.py
tests/legacy/pp_tests.py
tests/legacy/test_lib.py

This is the best that could be done without completely changing the PP code.

Use parent path instead of folder name. Fixes #1517

---

medusa/name_parser/parser.py
medusa/post_processor.py
medusa/server/api/v1/core.py

Fixing unresolved references
