pymedusa/Medusa

sickbeard/logger.py
tests/scene_helpers_tests.py

Fixes # None
- Move commit hash to beginning of log message
- Change commit hash to apply to all logs
- Re-enable disabled scene exception tests
Re-enable skipped tests

Move logging commit hash

---

sickbeard/providers/rarbg.py

Not an actual error:
{"error":"No results found","error_code":20}
Prevents: https://gist.github.com/fernandog/cd67490ba247380ce4b5

Prevent logging "No results found" message

---

sickbeard/webserve.py

So when user submit an error, gist will always have DEBUG level even if user don't have sickbeard.DEBUG enabled
too much hassle to ask user to reproduce error again with debug enabled
Setting sickbeard.DEBUG will only prevent from show in the UI.
if user wants to see in UI. just need to enabled. Don't need restart

Always write debug/db lines to log file

---

sickbeard/providers/bitsnoop.py
sickbeard/providers/cpasbien.py
sickbeard/providers/danishbits.py
sickbeard/providers/elitetorrent.py
sickbeard/providers/extratorrent.py
sickbeard/providers/freshontv.py
sickbeard/providers/gftracker.py
sickbeard/providers/hd4free.py
sickbeard/providers/hdbits.py
sickbeard/providers/hdspace.py
sickbeard/providers/hdtorrents.py
sickbeard/providers/iptorrents.py
sickbeard/providers/limetorrents.py
sickbeard/providers/morethantv.py
sickbeard/providers/newznab.py
sickbeard/providers/phxbit.py
sickbeard/providers/pretome.py
sickbeard/providers/scc.py
sickbeard/providers/scenetime.py
sickbeard/providers/speedcd.py
sickbeard/providers/strike.py
sickbeard/providers/t411.py
sickbeard/providers/tntvillage.py
sickbeard/providers/tokyotoshokan.py
sickbeard/providers/torrentproject.py
sickbeard/providers/torrentz.py
sickbeard/providers/transmitthenet.py
sickbeard/providers/xthor.py

Fixes double logging on providers
- Add `echo=False` to `get_url` for double-logged providers
- Add `returns` to `get_url` to continue migrating away from deprecated args

Fix double logging

---

gui/slick/views/manualSelect.mako
sickbeard/webserve.py

Also changed dict to make the provider name be part of the "item"
So each item will have all previous info plus "provider" key:
{'seeders': 3, 'name': u'The.Strain.S01E02.The.Box.1080p.WEB-DL.DD5.1.H.264-CtrlHD[rartv]', 'url': u'magnet:?xt=urn:btih:307d92502d6ba9b0dd4bc9ff578408d17879c476', 'season': 1, 'time': 1456440688, 'leechers': 0, 'episodes': u'|2|', 'version': -1, 'rowid': 182, **'provider': u'Rarbg'**, 'indexerid': 276564, 'quality': u'64', 'release_group': u'CtrlHD[rartv]', 'size': 1716910345}
{'Usenet-Crawler': [{"seeders": -1, "name": "The.Strain.S02E06.1080p.WEB-DL.DD5.1.H.264-Juggalotus", "url": "https://www.usenet-crawler.com/getnzb/, "season": 2, "leechers": -1, "episodes": "|6|", "version": -1, "rowid": 27, "time": 1456427252, "indexerid": 276564, "quality": "4", …

Manual Search: Sort default by seeders

---

gui/slick/views/manualSelect.mako

@duramato maye this is the reason we think we have dups
in DB:
How.Its.Made-Dream.Cars.S03E03.Porsche.Panamera.720p.HDTV.x264-W4F[rartv]
How.Its.Made-Dream.Cars.S03E03.Porsche.Panamera.720p.HDTV.x264-W4F
In UI:
How.Its.Made-Dream.Cars.S03E03.Porsche.Panamera.720p.HDTV.x264-W4F
How.Its.Made-Dream.Cars.S03E03.Porsche.Panamera.720p.HDTV.x264-W4F
so user might think its duplicate

Don't remove non-release words from title, only for "group" column

---

sickbeard/tvcache.py

Fix dupe items
Need erase cache.db or should do a ALTER TABLE do change existing cache.db to use UNIQUE?
@labrys @p0psicles @medariox @OmgImAlexis this PR fixed issue..... but we already have this in code but it seems its not working!
```python
self.action("CREATE UNIQUE INDEX IF NOT EXISTS idx_url ON [" + providerName + "] (url)")
```
Seems code already remove dups. but only at boot:
```python
for cur_dupe in sql_results:
self.action("DELETE FROM [" + providerName + "] WHERE url = ?", [cur_dupe["url"]])
```
I know SQL but not an expert

Make URL column unique in providers table in cache database

---

sickbeard/subtitles.py

- Limits the subtitles that are being searched for on each run to 300 (can be adjusted).
- Subtitles are searched based on last time they were searched, meaning that newly added shows will always have precedence.
- Shows with air date <= 30 days, have a limit of 100 results (aka subtitles to search).
- Shows with air date > 30 days, have a limit of 200 results.
@pymedusa/owners @pymedusa/moderators 
What do you think about the limits? Any suggestions/feedback?

Limit subtitle results to search

---

sickbeard/providers/tvchaosuk.py

Testing if we need this for snatching "old" expired sessions (read cookies), where authentication is required.
If this works, requests auth hook should be used, to create a generic solution.

Added check on expired cookies for tvchaosuk.py

---

sickbeard/providers/rarbg.py

Getting tons of this.
If too much queued searches, token can expire in the middle of search-queue
```
2016-03-02 12:34:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [4d6d66c] Invalid token. Use get_token for a new one!
2016-03-02 12:10:19 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [4d6d66c] Invalid token. Use get_token for a new one!
2016-03-02 11:22:18 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [4d6d66c] Invalid token. Use get_token for a new one!
2016-03-02 10:34:35 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [4d6d66c] Invalid token. Use get_token for a new one!
2016-03-02 09:34:21 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [4d6d66c] Invalid token. Use get_token for a new one!
2016-03-02 09:10:15 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [4d6d66c] Invalid …
```

Fixes "Invalid token. Use get_token for a new one!"

---

sickbeard/helpers.py
sickrage/providers/GenericProvider.py

This is purely a POC! Don't merge! Needs to be improved on.
I've put login_required param in GenericProvider.py. This should be Provider param. Need to work that out.

Added authentication hook to helpers.py

---

sickbeard/search.py
sickbeard/search_queue.py
sickbeard/webserve.py
sickrage/providers/GenericProvider.py

Remove unused variables not needed in: 
https://github.com/pyMedusa/SickRage/blob/manual-search/sickbeard/search.py#L94
@adaur @labrys @p0psicles can you please review with care this change?
correct way is checking with an IDE

[Manual Search] Remove unused variables

---

sickbeard/search.py
sickbeard/tvcache.py

Fixes https://gist.github.com/duramato/2bc25e5db8b4c7dffb63
@labrys @medariox @duramato @p0psicles

[Manual Search] Keep original function updateCache and create another for manual search

---

sickbeard/network_timezones.py

Fixes SickRage/sickrage-issues/issues/1098
possibly related to dateutil/dateutil/issues/197 reported upstream.

Hotfix dateutil error for timezone names on Windows

---

sickbeard/manual_search.py
sickbeard/webserve.py

When you delete your cache.db and you start the manual select search, not results shown, while it should.
This is because the tables do not exist when the first manualSelect page is loaded. Meaning there is no last update timestamp in the page available.
This PR should fix that.
I'd still rather see the providers tables created before a first result has been found. For example created when a provider is enabled?

Fix manual search

---

sickbeard/manual_search.py
sickbeard/tvcache.py
sickbeard/webserve.py

When loading the manualSelect.mako or doing the manualSelectCacheCheck ajax calls, the tvcache class is initialized and the provider cache tables are build of they do not exist.
This solves allot of issues, for when searches are done against newly enabled providers that are not giving results.

Moved the cache queries to the provider.TVcache object

---

sickbeard/show_queue.py
sickbeard/traktChecker.py

thus creating another show folder. So user will have a new "Show1" while the existing "Show1 (2016)"
This happens because cache name creation runs (used to) together with trakt thread.
anyway I already fixed trakt thread delaying 5min after boot.
https://github.com/pymedusa/SickRage/commit/89f02fb23908937c51384e4af15a35298f1f2d12
but it could happen again when cache name creation fails

Fix Trakt adding shows without year

---

.github/CONTRIBUTING.md
SickBeard.py
gui/slick/views/config.mako
gui/slick/views/config_postProcessing.mako
readme.md
sickbeard/indexers/indexer_config.py

Update url for SickRage issues

---

sickbeard/versionChecker.py

@pymedusa/developers need to enable the hidden config `developer` in config.ini
this setting also hide the warning about not using master branch

Developers can push branch directly to ORG (feature branches)

---

sickbeard/refiners/__init__.py
sickbeard/refiners/release.py
sickbeard/subtitles.py
sickbeard/tv.py

This will add a new subliminal refiner that will make use of the original release name to "enrich" the video object information before searching for subtitles. That will allow users to choose whatever "renaming rules" they want without worrying about downloading the correct subtitles. It should increase the subtitle search success ratio as well, since the original release name might contain more info then the renamed video file.
I tested this on my local installation. Please, let me know if anything needs to be changed or someone wants to try it first.

Using release name when searching for subtitles

---

gui/slick/css/style.css
gui/slick/views/displayShow.mako
gui/slick/views/snatchSelection.mako

Main reason for this UI change is the underscore. It's ugly.
Then I noticed the sceneExceptionsTooltip.js is included for displayShow.mako and snatchSelection.mako. But it's triggered on $('.title a'). And because the anchor has been removed for the displayShow.mako page, it's of no use. To keep things consistent i've also removed it from snatchSelection.
The text-decoration: none, is set for all 'h1/a'. I've checked but there are no other H1 tags with an anchor, so we're save there.
* Removed sceneExceptionsTooltip.js for displayShow and snatchSelection.mako as it's no longer used for displayShow, I assume there also is no use for it in snatchSelection.mako to keep things consistent.
I've left the id scene_exception_$show.indexerid.. on the a tag, if we want to bring it back some day.
As …

snatchSelection page: Removed scene exception message and H1 anchor underscore

---

sickbeard/search.py
sickbeard/tvcache.py
sickrage/providers/GenericProvider.py

Somehow results = curProvider.cache.update_cache_manual_search(searchResults[curEp]) was always running with curEp= -1. As it should run the function with the episode number as a param.
With this fix it was getting all results for show Fairy Tails S2, for providers nyaatorrent and tokyotosho. As before it only found results from nzb providers.
We'll need to thoroughly test this will all different kinds of shows. I can also image that for some shows, you will get allot more results now.
@fernandog @labrys @duramato

Fixed manual searching for scene named anime shows.

---

sickbeard/refiners/release.py

This change is
- to give the user the possibility to override the release name by just creating a .release file. 
- minor fix when no release_name and no release_file are defined.

Changing parameters precedence in release refiner

---

sickbeard/search.py

Check if the episode is a key if the searchResults before sending it to cache.
* Add the season pack's as a valid search result.

Check if the episode is a key of the searchResults before sending it

---

gui/slick/views/history.mako
sickbeard/common.py
sickbeard/webapi.py
sickbeard/webserve.py
sickrage/show/History.py
tests/sickrage_tests/show/history_tests.py

...and limit it by number of releases, not number of actions
based on #171 by @fernandog
* Change splitCompositeStatus to return a namedtuple(status, quality)
* Optimize imports
* Minor clean-up
* Change to use the named tuples in history
* Optimize imports
* Remove unused variables
* Clean up todo items
* Move compact history subroutine from webserve.py sickrage\show\History
* Optimize imports
* Remove unused variables
* Remove redundant parentheses
* Clean up todo items
* Rewrite compact history subroutine
* Update show.history to use namedtuple instead of dict
* return namedtuple instead of tuple
* limit releases by number of releases and not number of actions
* Optimize imports
* Add todo and docs

Fix compact history results so that all actions for a release are shown

---

gui/slick/views/config_providers.mako
sickbeard/__init__.py
sickbeard/config.py
sickbeard/manual_snatch.py
sickbeard/properFinder.py
sickbeard/search.py
sickbeard/tvcache.py
sickbeard/webserve.py
sickrage/helper/common.py
sickrage/providers/GenericProvider.py

It will only use "manual search" providers when you use "Force results" button. Because this providers don't get updated in DailySearcher as they are manual search only
So its a mix of @duramato and mine (fallback)
- Fixes thread name while doing forced search
Before:
[c352080] Performing episode search for 
After:
[MoreThanTV] :: [c352080] Performing episode search for 
- Fixed "forced search when no results" using backlog enabled providers (in manual_snatch.py we used to use daily). Now we use "enable_manualsearch"
- Fixed: search for propers only in backlog enabled providers
- Initialize provider even if no query to execute
This changes UI but nothing that will break angular @OmgImAlexis

[Manual Search] Add provider setting 'Enable manual searches'

---

sickbeard/manual_snatch.py
sickbeard/search_queue.py
sickbeard/webserve.py

Fixes https://github.com/pymedusa/SickRage/issues/229

[Manual Search] Log multi-epi as snatched

---

gui/slick/views/snatchSelection.mako
sickbeard/search_queue.py
sickbeard/webserve.py

* Changed searchResult to snakecase.
* Removed unneeded params for snatchSelection() method.
* Changed mako to not send unneeded params. rowid is enough.
* Added check for getting the show_obj, chances are slim, but maybe a user leaves a snatchSelection window open, while deleting the show.
* Some pep8 changes.
* Added docstrings to webserve.py and search_queue.py methods.

Moved the creation of the searchResult to the searchQueue item.

---

sickbeard/helpers.py

I extended the disk_usage method to allow optional output in Bytes instead of "human readable format". This allows us to use it instead of that mess we were using before.
As we use getDiskSpaceUsage everywhere else, I hope this won't cause issues with other OS - it would still be very nice if we could test it on different systems before merge, I tested it under Ubuntu 15 for now. Also fixes this bug: https://gist.github.com/medariox/cb9f1c9995ca15ee076888fea38a7abb

Replace messy disk_usage with existing method

---

sickbeard/manual_search.py

if Provider1 returns results, and Provider2, table didn't existed, Medusa was re-adding to cache items from Provider1 because sql_return wasn't cleared while iterating providers

[Manual Search] Initialize sql_return as empty in the right place

---

sickbeard/dailysearcher.py
sickbeard/properFinder.py
sickbeard/searchBacklog.py

It doesn't start other threads when manual search is actually running:
```
SEARCHQUEUE-FORCEDSEARCH-295515 :: [ThePirateBay] :: [1eb2e79] Performing episode search for Quantico
SEARCHQUEUE-FORCEDSEARCH-295515 :: [Speedcd] :: [1eb2e79] Performing episode search for Quantico
SEARCHQUEUE-FORCEDSEARCH-295515 :: [HDTorrents] :: [1eb2e79] Performing episode search for Quantico
SEARCHQUEUE-FORCEDSEARCH-295515 :: [TorrentDay] :: [1eb2e79] Performing episode search for Quantico
SEARCHQUEUE-FORCEDSEARCH-295515 :: [AlphaRatio] :: [1eb2e79] Performing episode search for Quantico
DAILYSEARCHER :: [1eb2e79] Manual search is running. Can't start Daily search
Thread-16 :: [1eb2e79] Daily search forced
SEARCHQUEUE-FORCEDSEARCH-295515 :: [Rarbg] :: [1eb2e79] Performing episode search for Quantico …
```

Don't run daily/backlog/propers searcher when manualsearch is searching

---

sickbeard/subtitles.py

- Minor fixes (docstring)
- Fixing timing issue where the subtitle search might be wrongly skipped (e.g.: searching every hour and the last search was 59min and 58 seconds ago, and because of 1 or 2 seconds, it might always skip the hourly search)
- Experimenting with dogpile.cache API to avoid the need to wrap a method with keyword args in a method without keyword args.

Subs small fixes

---

sickbeard/webserve.py

Fixes https://gist.github.com/duramato/de804af989219f6a921500d1a8864636
@p0psicles 
Maybe a new error message would be more appropriate?

Fixes TypeError when cached_result is None in pickManualSearch

---

sickbeard/logger.py

- Fixing duplicate logging message (when enabling subliminal logging)
- Moving threadName and 'current commit hash' to the logger formatter in order to have the same message pattern for modules other than sickbeard.
Here's a preview:
```
2016-04-05 21:40:15 INFO     Thread-16 :: [6bb3888] No subtitles found for /library/series/Real Humans/Season 02/Real Humans - S02E10 - Episode 10.mkv
2016-04-05 21:40:15 INFO     Thread-16 :: [6bb3888] Searching candidates using the keyword real humans
2016-04-05 21:40:14 INFO     Thread-16 :: [6bb3888] Logging in
2016-04-05 21:40:14 INFO     Thread-16 :: [6bb3888] Initializing provider legendastv
2016-04-05 21:40:14 INFO     Thread-16 :: [6bb3888] Listing subtitles with provider 'legendastv' and languages set([])
2016-04-05 21:40:14 INFO     Thread-16 …
```

Logging improvements

---

sickbeard/refiners/release.py

This is a small fix for #287 (a case when there's no release name - neither in db, nor in a release file). Also fixed the docstring to better describe the precedence.

Fix for #287

---

sickbeard/processTV.py

Disable PP wrapper, since it makes NzbToMedia to not function properly

---

sickbeard/subtitles.py
sickbeard/tv.py

1) Erase one subtitle file for a show in library
2) Refresh files. 
3) CC icon appears
4) Re-add subtitle again
5) CC icon disappears
@ratoaq2 problem is that information is cached and need to wait cache expires to detect properly
can we override cache information when forced refresh?
```
11:22:06 DEBUG::SHOWQUEUE-REFRESH :: [1fc2460] Using cached parse result for: The.Americans.S04E04.1080p.WEB-DL.DD5.1.h.264-NTb
11:22:06 DEBUG::SHOWQUEUE-REFRESH :: [1fc2460] Name The.Americans.S04E04.1080p.WEB-DL.DD5.1.h.264-NTb gave release group of NTb, seems valid
11:22:06 DEBUG::SHOWQUEUE-REFRESH :: [1fc2460] Found cached video information under key sickbeard.subtitles:video|/media/SAMSUNG/media/series/The Americans (2013)/Season 4/The.Americans.S04E04.1080p.WEB-DL.DD5.1.h.264-NTb.mkv|None|True|None| …
```

Fix when the only existing subs is deleted and DB wasnt updated

---

.travis.yml
gui/slick/views/snatchSelection.mako
sickbeard/search.py
sickbeard/show_name_helpers.py
sickbeard/webserve.py
tests/scene_helpers_tests.py

Use the new function "show_words" that display global+show ignored/required words in displayShow and snatchSelection (also to "paint" those words in the results) to filter results in dailysearcher/backlogsearcher
Next step from PR https://github.com/pymedusa/SickRage/pull/370
TODO:

[Manual Search] Move show_words and use new function to filter words

---

sickbeard/__init__.py
sickbeard/search.py
sickbeard/search_queue.py
sickbeard/webserve.py

Snatches found from the manual search are now handled by a dedicated scheduler.
Before they where queued in the searchScheduler thread.
* Fixed the queue_length reporting on manual searches. These are now reported correctly and separate from forced searches.

[Manual Search] Added a manualSnatchScheduler to handle SnatchQueue items

---

gui/slick/views/manage_manageSearches.mako
sickbeard/__init__.py
sickbeard/dailysearcher.py
sickbeard/failedProcessor.py
sickbeard/manual_search.py
sickbeard/properFinder.py
sickbeard/searchBacklog.py
sickbeard/search_queue.py
sickbeard/webapi.py
sickbeard/webserve.py

Added a ForcedSearchQueue scheduler for processing forced searches and failed downloads. These can be run in parallel with the searchQueueScheduler thread (backlog and daily).

[Manual Search] Added a ForcedSearchQueue scheduler for processing forced searches and failed downloads.

---

lib/guessit/api.py
lib/guessit/rules/__init__.py
lib/guessit/rules/common/formatters.py
lib/guessit/rules/properties/audio_codec.py
lib/guessit/rules/properties/language.py
lib/guessit/rules/properties/mimetype.py
lib/guessit/rules/properties/title.py
lib/guessit/test/episodes.yml
lib/guessit/test/movies.yml

Fix "Regression for titles containing dots" like "Marvels.Agents.of.S.H.I.E.L.D."
https://github.com/guessit-io/guessit/issues/278
@medariox @ratoaq2

Upgrade guessit to 61303fa009ff3b17cd91be7a18fcccec8642d027

---

gui/slick/css/style.css

This PR fixed the html: https://github.com/pymedusa/SickRage/pull/440
not needed anymore. reverting

Revert "Remove text decoration from forcedSearch icon"

---

sickbeard/providers/rarbg.py

2016-04-21 07:52:17 SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [39f9fa6] Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later!

Still getting "Too many requests per second."

---

sickbeard/classes.py
sickbeard/config.py
sickbeard/failed_history.py
sickbeard/helpers.py
sickbeard/logger.py
sickbeard/notifiers/emby.py
sickbeard/notifiers/freemobile.py
sickbeard/notifiers/kodi.py
sickbeard/notifiers/nmj.py
sickbeard/notifiers/nmjv2.py
sickbeard/notifiers/prowl.py
sickbeard/notifiers/pushover.py
sickbeard/notifiers/pytivo.py
sickbeard/notifiers/telegram.py
sickbeard/notifiers/tweet.py
sickbeard/nzbget.py
sickbeard/providers/hdspace.py
sickbeard/providers/hdtorrents.py
sickbeard/providers/pretome.py
sickbeard/providers/scc.py
sickbeard/providers/scenetime.py
sickbeard/webapi.py
sickbeard/webserve.py

Use a combination of six and requests.compat for python 3 compatibility, preferring requests.compat when possible as many of the urllib calls should be rewritten using requests.

Fix imports for urllib, urllib2, and httplib for python 3 compatibility

---

gui/slick/js/core.js
gui/slick/views/snatchSelection.mako

* Fixes the automatic hiding of table when results are refreshed. Now it saves the status. If user toggles the history page to show, it keeps showing.

[Manual Search] Fixed saving status of history table

---

sickbeard/name_parser/regexes.py

Fixes "stupid" regex matching Web-Dl and similiar qualities becouse of the "-"
This makes sure it isnt preceded by a "web"
Fixes https://github.com/pymedusa/SickRage/issues/509
Result: `Chernobyl.Zona.otchuzhdeniya.s01.2014.WEB-DLRip.720`
Without this fix (matching result wrongfully) : 
https://regex101.com/r/nU3tR7/1
With fix: not matching : 
https://regex101.com/r/zV6iL2/2
With fix still matching intended results ( any TOPAZ release, the file not dirname *) : https://regex101.com/r/zV6iL2/1
\* aka release name

Fix "stupid" regex wrongfully matching

---

sickbeard/search.py

Issue from old repo. This was added when the name cache creation was removed from SR startup. Then it was reverted and "someone" forgot to remove this line
this was fully tested by me and @duramato in `pubdate2` branch for the past 4 days

Cache is already being created at startup

---

sickbeard/properFinder.py
sickrage/providers/GenericProvider.py

When manual search was implemented, seeders and leechers were added to cache but the sockets timeout issue (catching `TypeError`) were preventing us to see the traceback and submit issue
```
FINDPROPERS :: [Provider] :: [hash] Socket time out while searching for propers in Provider, skipping: __init__() takes exactly 10 arguments (5 given)
```
This PR fixes the error handling and the `__init__` proper error
Alsos fixes the multiple thread names in the log like:
` [provider1] [provider1] [provider1] [provider1] [provider1]`
already tested by me and @duramato at `pubdate2` branch

Fix propers issue since manual search implementation

---

sickbeard/name_parser/regexes.py

Adds support for `The Katering Show Series 2 Episode 1 Red Ramen` (UK,AU), while maintaining support for `Show Name Season 1 Episode 2 Ep Name` (US)  alike namings

Support for non US "season", meaning AU, UK , etc

---

sickbeard/providers/rarbg.py

No need to show warning when show doesnt exist in rarbg , same as done for erro code 20 `No results found` when a show exists in the site already.
error code 14 is preety much the same but its becouse the show isnt even in the site, so no results at all `Cant find thetvdb in database. Are you sure this thetvdb exists? 14 `

Do not log warning when no results exist in RARBG

---

gui/slick/js/configProviders.js

now populateNewznabSection is only called in the tab "Configure custom newznab providers" and only for the provider user selected in the select object.
Today if user refreshes provider list it calls populateNewznabSection for all nzb providers.
@p0psicles

Fix pymedusa/SickRage/issues/533

---

sickrage/helper/common.py

Issue: https://github.com/pymedusa/SickRage/issues/471
```python
seeders = try_int(cells[3].get_text(strip=True).replace(',', ''))
leechers = try_int(cells[4].get_text(strip=True).replace(',', ''))
```
https://github.com/pymedusa/SickRage/commit/8dbe94f62f05c804949d928ab17b7fb63f9b21a2

Catch not-sanitized values passed to try_int

---

sickbeard/providers/newznab.py
sickbeard/providers/rsstorrent.py

There is not an opend issue because I found the issue while reading the code =)
**Issue:** when adding a new NZB provider it wasn't created  with `enable_manualsearch` setting
This PR fixes the creation of new nzb with the missing setting
~~Please provide a valid PR description. As this is not referring to a reported issue, the issue description should be provided in the PR. For ex. what was the impact of the missing setting in functional terms?~~

Fix missing manualsearch provider setting

---

sickbeard/providers/tvchaosuk.py

Fix season search in tvcuk

---

sickbeard/helpers.py
sickbeard/properFinder.py

Improving maintainability. Made it optional using args.
Removed all the camelCase vars, where possible from properFinder.py.

Moved the remove_strings into the remove_non_release_groups() function

---

sickbeard/clients/deluge_client.py
sickbeard/clients/deluged_client.py

When labels are uppercase, SR fails to set them as deluge(d) doesn't support uppercase labels
Issue from old repo

Fix label in deluge, needs to be lower case

---

sickbeard/metadata/kodi_12plus.py
sickbeard/metadata/mede8er.py
sickbeard/metadata/mediabrowser.py
sickbeard/metadata/tivo.py
sickbeard/metadata/wdtv.py

"Fixes" stuff like this showing the full traceback and at the same time making them not submitable but still showing up to the user, as warning
```
2016-05-06 06:10:31 POSTPROCESSER :: [6cb78fe] Unable to connect to theTVDB while creating meta files - skipping - error Connection error HTTPConnectionPool(host='thetvdb.com', port=80): Max retries exceeded with url: /api/F9C450E78D99172E/series/268592/en.xml (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Nome ou servi\xc3\xa7o desconhecido',)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/268592/en.xml
File "/home/home/SickRage/sickbeard/metadata/kodi_12plus.py", line 258, in _ep_data
myShow = t[ep_obj.show.indexerid]
File …
```

	Do not show traceback and as error when issue connecting to indexer occurs in metadata creation

---

sickbeard/manual_search.py
sickbeard/webserve.py

The manual snatched episode is now retrieved from the showsList, instead of being build from the class. Because it was newly initiated, there was no reference to the show in memory. Now there is.

Fixed updating of snatch/download status for manual searched episodes.

---

gui/slick/views/displayShow.mako
sickbeard/scene_exceptions.py
sickbeard/webserve.py

Fixed saving a show with unicode scene name exceptions like Naruto shippuuden. The error only occurs on Windows. I'm explicitly saving scene_exceptions as unicode to the exception list and db.
How to reproduce the issue:
1. Run medusa on windows. I've used Windows 7
2. Make sure used locale is x.cp1252
3. Add Naruto Shippuuden
4. Now you can open the show in displayShow and editShow just fine.
5. Go to editShow and save the show, you should be redirected to displayShow
6. You'r getting a mako 500 error page.

Fixed saving a show with unicode scene name exceptions

---

sickbeard/providers/torrentz.py

@duramato @labrys @p0psicles 
I still prefer replace. Easier to read.
Adding this space will work? Cause using re.sub it appends and not replace.

Add space in torrentz regex

---

sickbeard/refiners/release.py

- MINOR FIX: Release name might come from release file (not only from DB), therefore it needs to be sanitized by calling `remove_non_release_groups`

Sanitize release name in release refiner

---

sickbeard/clients/__init__.py
sickbeard/clients/deluge_client.py
sickbeard/clients/deluged_client.py
sickbeard/clients/download_station_client.py
sickbeard/clients/generic.py
sickbeard/clients/mlnet_client.py
sickbeard/clients/qbittorrent_client.py
sickbeard/clients/rtorrent_client.py
sickbeard/clients/transmission_client.py
sickbeard/clients/utorrent_client.py
sickbeard/helpers.py
sickbeard/name_parser/regexes.py
sickbeard/notifiers/boxcar2.py
sickbeard/notifiers/emailnotify.py
sickbeard/notifiers/pushalot.py
sickbeard/nzbget.py
sickbeard/providers/norbits.py
sickbeard/sab.py
sickbeard/search.py
sickbeard/tv.py
sickbeard/webserve.py

I know this seems like a large PR, but the majority of the changes are fairly minor and have been grouped into similar commits to make review easier.
The majority of this PR is just simple style changes to `sickbeard/clients`:
* Fix triple-quoted strings
* Refactor non-pythonic names
* Use single-quoted strings
* Standardize string formatting
* Use unicode literals
* Use b'' for SQL
* Remove unused variables and code
* Clean up logging
* Clean up comments
* Prettify literal indentation
* Fix line too long
* Simplify url init
* Minimize global usage in code
The meat of the PR is the changes below:
* Fix too broad exceptions
* Catch `RequestException` instead of `Exception`
* Clean up conditional/exceptional statements
* Mostly a style change to conditionals and exceptional statements. …

Spring cleaning

---

sickbeard/tvcache.py

Detail in commit message
Tested for > 20days in pubdate2 branch
@duramato 
How to reproduce:
Add the show "Huang's World" , add "Huangs World" to scene exceptions then search for s02 pack on ExtraTorrent
```
2016-04-29 17:47:34 DEBUG    SEARCHQUEUE-MANUAL-274168 :: [ExtraTorrent] :: [7e5818d] Unable to match Huangs.World.Season.2.WEBRip.x264-[eSc] to a show in your database
2016-04-29 17:47:33 DEBUG    SEARCHQUEUE-MANUAL-274168 :: [ExtraTorrent] :: [7e5818d] Adding to cache item found in manual search: Huangs.World.Season.2.WEBRip.x264-[eSc]
```
Full logs:
https://gist.github.com/duramato/f449ff449abb4ec8a51f34a7361659b9

Fix parsing issue

---

sickrage/providers/nzb/NZBProvider.py

The try-except isn't necessary when using `.get()` on a dict.  Also removes unnecessary logging for invalid size and pubdate info.

Remove unnecessary try-except and logging

---

sickbeard/metadata/generic.py

When adding existing shows, an empty string can raise the above error.

 Fix invalid literal for int() with base 10 when parsing metadata

---

sickbeard/__init__.py
sickbeard/server/web/config/search.py

* Should be cast to int, as we want to step by day, not tenth of day.
@labrys ?
I've changed it because else in config you get to see 30,0. While stepping did change, saving did not.

Fixed cache_retention granularity.

---

gui/slick/views/config_providers.mako

Saving password with a double quote are not parsed correctly in mako templating.

Fix saving provider password with special chars in it. Especially double quote.

---

lib/simpleanidb/__init__.py
lib/simpleanidb/exceptions.py
lib/simpleanidb/helper.py
lib/simpleanidb/models.py

This lib has support for anidb.net's http api, as also the http://anidb.net/api/anime-titles.xml.gz for the show search. It's a step in the direction for building an anidb indexer, with the biggest limitation that the xml does not have the airdates. Making it not ideal for indexer searches.
For now it will be used for retrieving the anidb.net recommended lists.

Add lib simpleanidb

---

sickbeard/subtitles.py

@ratoaq2 also you weren't passing full path creating error:
`Couldn't remove non release groups from video file. Error: error 2 : The system cannot find the file specified`
@medariox

Don't call clear_non_release_groups for non media files

---

gui/slick/views/manage_episodeStatuses.mako
sickbeard/server/web/manage/handler.py

* Also removed a js script include, as that script doesn't exist anymore.
You can reproduce through going to Manage -> episode status management page. And change status for a number of episodes.

Fixes a 404 on mass changing episode statuses.

---

gui/slick/views/history.mako

Seriously guys, really think things through before your going to put these kind of heavy method calls (in a loop) in the template. As for now, these guessit calls really need to be removed, to make this page workable again.

History remove guessit

---

sickbeard/server/web/manage/handler.py

Fixed failedDownoads page, when using limit = all

---

sickbeard/server/web/home/add_shows.py
sickbeard/server/web/home/handler.py

OS: Windows 10
Python: 2.7.11
Medusa: Current dev
When using mass edit to change directories containing non-ascii can cause UnicodeError.  This fixes the issue by removing an unnecessary `.decode()`.
Also fixes minor typo.

Unicode mass edit

---

gui/slick/js/configProviders.js
gui/slick/views/config_providers.mako
sickbeard/__init__.py
sickbeard/providers/rsstorrent.py
sickbeard/providers/torrentday.py
sickbeard/server/web/config/providers.py
sickrage/providers/GenericProvider.py
sickrage/providers/torrent/TorrentProvider.py

Users will now be able to configure cookies for providers with the cookies_ingest attribute.
This is now only enabled for torrentday. To fix the captcha issue.

Added cookies_ingest attribute to torrent providers. Should fix the TD captcha.

---

sickbeard/notifiers/emailnotify.py

Fix from @avdleeuw thanks!
@medariox

Fix encoding userid/password before logging in to SMTP server

---

sickbeard/databases/main_db.py
sickbeard/tv.py

@medariox @ratoaq2 thoughts?
WARNING for now so everybody can easily test without digging into log
I tested this for one week
```
2016-07-03 03:08:36 WARNING  SHOWQUEUE-REFRESH :: [42fd472] 75682: Found hanging associated files for S11E19, deleting: [u'/media/SAMSUNG/media/series/Bones/Season 11/Bones.S11E19.1080p.WEB-DL.DD5.1.H.264-NTb.pt-BR.srt']
2016-07-03 03:08:36 INFO     SHOWQUEUE-REFRESH :: [42fd472] Looking for hanging associates files for: /media/SAMSUNG/media/series/Bones/Season 11/Bones.S11E19.1080p.WEB-DL.DD5.1.H.264-NTb.mkv
2016-07-03 03:08:36 DEBUG    SHOWQUEUE-REFRESH :: [42fd472] 75682: Location for S11E19 doesn't exist, removing it and changing our status to Archived (1080p WEB-DL)
```

Remove associated files when episode gets deleted

---

sickbeard/server/web/home/handler.py
sickbeard/tv.py

* Fixed route, deleteShow was renamed to delete_show. That's okay for variables, but with routes we should be extra careful.
* Fixed bug where location is called as an attribute, but the attribute itself is verifying the location. Which does not work, if the file/location has been deleted from disk.
Fix for: https://github.com/pymedusa/SickRage/pull/746
And issue: https://github.com/pymedusa/SickRage/issues/765

Fix routes and location called from logger

---

sickbeard/tv.py

This should fix #768 
- location changes should make object dirty; and dirty flag shouldn't be resetted when changed value evaluates to false.

Dirty flag fix

---

sickbeard/name_parser/rules/rules.py
tests/datasets/tvshows.yml

This is a guessit rule until https://github.com/guessit-io/guessit/issues/327 is fixed.
This rule will detect multiple formats and will keep the last format if the last format is surrounded by screen_size, video_codec and release_group
The episode_title is not handled/fixed since it doesn't cause issues for us.
Fixes https://github.com/pymedusa/SickRage/issues/772

Fixing guessit multiple formats

---

sickbeard/name_parser/rules/rules.py
tests/datasets/tvshows.yml

This should fix #772 
The problem happened again because the file path has 2 portions with the same information, but the first part has a release group with additional words between brackets; so the second part would have all info except the release_group, which was affecting the logic of our fix.

Additional fix for guessit multiple formats

---

sickbeard/logger.py

Lazy logging is here :+1: 
- PEP257 and PEP8 fixes.
- Add support for new string format style: for current custom logger and standard logging (lazy logging)
- There's no code change on other classes to use it. This PR just adds support for it.
How to use:
```
import logging
logger = logging.getLogger(__name__)
logger.info('Really {param} message', param='nice')
logger.log(logging.DEBUG, 'Hello {world}', world='rato')
logger.debug('{what} idea', what='No')
```

Logger improvements (Lazy logging)

---

sickbeard/databases/main_db.py
sickbeard/tv.py

as pointed by @medariox 
Dont change anything else otherwise will conflict with rato's rewrite in tvrefiner
Could not delete associate file: /media/Data/Media/TV Shows/Lucifer/S01/Subsè/Lucifer.S01E08.HDTV.XviD-FUM.it.srt. Error: 'ascii' codec can't encode character u'\xe8' in position 43: ordinal not in range(128)

Fix delete file when non-ascii

---

sickbeard/common.py
sickbeard/refiners/release.py
sickbeard/refiners/tvepisode.py
sickbeard/subtitles.py
sickbeard/tv.py

Adding a subliminal refiner that will enrich the video information with tvdbid, imdb_id and other information present in our database. That way, some refiners in subliminal will be skipped since the information is already present (it can improve performance in a show refresh). I'm not disabling those refiners since they can act as a fallback if no TVEpisode is present (for any reason).

tvepisode refiner

---

sickbeard/tv.py

For some old shows I had a lot of empty season folders: Season 1, Season 2, etc...
@ratoaq2 as I said the ideia

 Clean up any empty season folders after deletion of associated files

---

sickbeard/providers/torrentday.py

@p0psicles 
Fixes https://github.com/pymedusa/SickRage/issues/728
From my PR I got:
Torrentday response to send to devs: {u'Fs': [{u'Cn': 0, u'Fn': u'Oarrive'}], u'er': 0}
```python
>>> jdata = {u'Fs': [{u'Cn': 0, u'Fn': u'Oarrive'}], u'er': 0}
>>> torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'get'
```

Fixes pymedusa/SickRage/issues/728 and warn about no cookies set

---

sickbeard/properFinder.py

How it works:
- First run: fetch all available propers. store processed propers
- Second run: fetch all available propers. if found in processed propers list, dont parse, dont do anything. ignores it

Avoid reprocess same PROPER over and over

---

gui/slick/css/style.css
gui/slick/views/displayShow.mako

Add footers to season tables with information for each season.
* Num of episodes downloaded
* Total size of files for season
See Issue #575 for Request

Add footers to season tables

---

sickbeard/name_parser/guessit_parser.py
sickbeard/name_parser/rules/rules.py
sickbeard/tv.py
tests/datasets/tvshows.yml
tests/guessit_tests.py

- Remove hardcoded list of show names that contains numbers and make use of user's show list to build the expected titles list
- Added unit test and updated dataset with a real scenario

guessit: use user's show list as expected titles

---

gui/slick/css/light.css
gui/slick/css/style.css
gui/slick/js/core.js
gui/slick/views/snatchSelection.mako

Add Fan Art to snatchSelection.mako

---

gui/slick/views/snatchSelection.mako

Another labrys issue. More time wasted
This it not the same!!
% if manual_search_type != 'season' and 'E00' not in hItem["name"]:

Rever old logic to hide special episode in season search

---

gui/slick/views/manage.mako

Fixes Issues #842
Footer column span was 1 column wider then the actual columns used dues
to a column being hidden ( "Force Metadata Regen" )

Fix Column Filter for blank item - Issue #842

---

.pullapprove.yml

will only have effect when merged into master
@Thraxis 
No idea why it failed:
Parsing errors
"{'required': 1, 'name': 'devs', 'members': ['duramato', 'fernandog', 'labrys', 'medariox', 'ratoaq2', 'p0psicles', 'OmgImAlexis', 'adaur', 'Thraxis']}" is an invalid value for reviewers: 'Thraxis' is not a collaborator of this repo

Update pull approve to include Thraxis

---

CONTRIBUTING.md

1. If you want to make a change, like different titles, paragraph order, etc. Then please let me know here, or in irc. And i'll change it.
2. If you want to add a chapter. For example, some more in depth Javascript guidelines, please add them yourself.
3. If you think any grammatical improvements can be made, please make them!
I'll keep this open for 1 week.

Concept version of a CONTRIBUTING.md

---

gui/slick/views/config_general.mako
sickbeard/__init__.py
sickbeard/server/web/config/general.py
sickbeard/versionChecker.py

@pymedusa/developers 
we recently had to remove one commit from develop which caused a "Local branch is ahead of develop. Automatic update not possible" to develop users
this will affect only develop and master branches.

Force update when local branch is ahead

---

sickbeard/helpers.py

Need to fix https://github.com/pymedusa/SickRage/issues/856
Requests.exceptions.ConnectionError is not being catched. any idea?
looks like an error inside another error
```
2016-08-09 18:14:29 ERROR    DAILYSEARCHER :: [8ae98dd] Exception generated in thread DAILYSEARCHER: error HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x69eca530>: Failed to establish a new connection: [Errno -2] Nome ou servi\xc3\xa7o desconhecido',))
File "/home/osmc/SickRage/sickbeard/scheduler.py", line 106, in run
self.action.run(self.force)
File …
```

Catch all requests exceptions

---

sickbeard/logger.py

Fix for #876 
An example when the error occurs:
```
logger.error("{'type': 'abc', 'anotherkey': True}")
```
If the message (that might come from an exception or something similar) has set or dict representation, it might lead to an exception when the logger tries create the displayed message.

Shouldn't format logger message when there's no arguments

---

pytest.ini
sickbeard/server/web/core/error_logs.py
tests/test_logger.py

- Escaping html characters in logs view page: When the log message contains < > all the information inside brackets are not displayed. This should fix #560 
- Removing errors_logs.py from flake8 whitelist.
- Making it more efficient (precompile log regex and other minor enhancements)

Escaping html characters in logs view page

---

sickbeard/name_parser/guessit_parser.py
sickbeard/name_parser/parser.py
sickbeard/name_parser/rules/rules.py
tests/datasets/tvshows.yml
tests/test_guessit.py

- When user has a show with numbers and unicode characters a guessit exception happens when trying to parse any release name:
```
File "C:\sickbeard\name_parser\guessit_parser.py", line 91, in guessit
return default_api.guessit(name, options=final_options)
File "C:\lib\guessit\api.py", line 113, in guessit
raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.0.dev0
string=someshow
options={'allowed_languages': ['ru', 'hu', 'en', 'nl', 'pt', 'de', 'jp', 'sv', 'it', 'fr', 'es', 'uk', 'ro', 'pl', 'he'], 'expected_group': ['re:\\bCDD\\b', 're:\\bF4ST3R\\b', 're:\\bTGNF4ST\\b', 're:\\bNovaRip
\\b', 're:\\bRiPRG\\b', 're:\\bPtM\\b', 're:\\bbyEMP\\b', …
```

Fix guessit parser when show titles contains numbers and unicode chars

---

sickbeard/name_parser/rules/rules.py
tests/datasets/tvshows.yml

This is a small enhancement for some cases in  #810 
- Removing words in a release group after a dash. e.g.: GROUP-BUYMORE will become GROUP
The scenario above works fine. We need to do regression test on other scenarios to make sure there's no side effect.

Scene releases: release groups should drop all words after dash

---

sickbeard/notifiers/kodi.py
sickbeard/postProcessor.py

@medariox @ratoaq2 I improved replace file detection:
Snatched SDTV. No Kodi clean as there is not existing file:
```
Snatch history had a quality in it, using that: SDTV
Medusa snatched this episode and it is not processed before
This episode is a priority download: True
There is no existing file so there's no worries about replacing it
This download is marked a priority download so I'm going to replace an existing file if I find one
Found release name Stranger.Things.S01E03.WEBRip.x264-TURBO
Destination folder for this episode: /media/SAMSUNG/media/series/Stranger Things/Season 1
```
Snatched 1080p WEB-DL: Kodi clean as I snatched SDTV before:
```
Snatch history had a quality in it, using that: 1080p WEB-DL
Medusa snatched this episode and it is not processed before
This episode is a …
```

Fixes pymedusa/SickRage/issues/911

---

lib/traktor/trakt.py

When no http status code, it will raise an exception but will break medusa flow.
So now we will only raise a 'unknown exception' when we know the http status code and its something devs should fix in code.
This exceptions should not break flow:
` Unknown Trakt request exception. Code error: None`
`ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)`
@ratoaq2 @p0psicles 
https://github.com/pymedusa/SickRage/issues/954
https://github.com/pymedusa/SickRage/issues/928

Handle when no http status code while connection to trakt

---

gui/slick/views/config_general.mako

@p0psicles @xo @medariox is there a reason for this second one uses metadatadiv?
html
```
<select class="form-control input-sm ${'' if not sickbeard.FUZZY_DATING else ' metadataDiv'}
```

Fix UI showing two "date style" selects

---

sickbeard/search.py

We already log here: https://github.com/pymedusa/SickRage/blob/develop/sickbeard/search_queue.py#L251
Fix:
```
INFO     SEARCHQUEUE-DAILY-SEARCH :: [9dc5945] No needed episodes found
INFO     SEARCHQUEUE-DAILY-SEARCH :: [9dc5945] No episodes needed.
```

Remove duplicate log message

---

gui/slick/views/config_subtitles.mako
sickbeard/__init__.py
sickbeard/server/web/config/subtitles.py
sickbeard/subtitles.py

@ratoaq2 
it will always download subs in PP folder when "postpone if no subs" enabled
User had setting "subtitles_download_in_pp" enabled and 'postpone' disabled.
No reason to have this setup.

Fixes pymedusa/SickRage/issues/874

---

sickbeard/server/core.py

@OmgImAlexis 
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://0.0.0.0.:80/api/v2/info?api_key=****

Fix viewlogs

---

sickbeard/tvcache.py

Its was cleaning only daily/backlog search providers
This is when user has only manual search providers enable as fall back providers
Like provider A and B as daily and backlog search only
and
Provider C, D and E as manual search providers only.
So those manual search providers would never be cleaned
@p0psicles

Also trim cache in manual search providers

---

sickbeard/providers/torrent/html/zooqle.py

Fixed Zooqle size, leechers and seeders display

---

pytest.ini
sickbeard/scene_exceptions.py

Improve scene_exceptions

---

sickbeard/showUpdater.py
sickbeard/show_queue.py
sickbeard/tv.py

A lof ot duplicate line for every show
Flow:
show_queye.py calls:
```python
logger.log(u"Loading all episodes from the database", logger.DEBUG)
DBEpList = self.show.load_episodes_from_db()
logger.log(u"Loading all episodes from " + sickbeard.indexerApi(self.show.indexer).name + "", logger.DEBUG)
try:
IndexerEpList = self.show.load_episodes_from_indexer(cache=not self.force)
```
In `load_episodes_from_db` we were also calling `load_from_indexer` that is called from `load_episodes_from_indexer` later in show_queue. So we were calling twice `load_from_indexer`
```
2016-08-26 03:04:15 INFO     SHOWQUEUE-FORCE-UPDATE :: [555b0cb] This episode The Blacklist - S04E04 has no name on theTVDB. Setting to an empty string
2016-08-26 03:04:15 INFO     SHOWQUEUE-FORCE-UPDATE :: [555b0cb] This episode …
```

Several fixes in show updater

---

sickbeard/db.py

Fixes https://github.com/pymedusa/SickRage/issues/704

Fix pymedusa/SickRage/issues/704

---

gui/slick/views/history.mako

@duramato Adds proper tags to history as you always wanted lol
Each snatch_proper has its own proper tags
So if user has a snatch with `PROPER` proper tag and  another `REAL PROPER` proper tag,  it will show two icons because its two snatches

Show proper tags using INFO icon

---

sickbeard/name_parser/guessit_parser.py
sickbeard/name_parser/rules/rules.py
tests/datasets/tvshows.yml
tests/report_guessit.py
tests/test_guessit.py

Anime with numbers in title and no season information causes guessit exception

---

gui/slick/js/manage/init.js

It will always be "None"
After:
Before:

Don't show column subs if user choosed to show "Episodes without All subtitles"

---

gui/slick/js/config/notifications.js
gui/slick/views/config_notifications.mako
sickbeard/server/web/home/handler.py

If user already have trakt authorized, PIN input will be disabled and button will be "Get new Trakt PIN"
If never setup trakt, button wil be "Get Trakt PIN"
AS soon user clicks the button, the PIN input will be enabled to type pin
when PIN typed, button "Get new Trakt PIN" will be hidden and button "Authorize Medusa" will appear
after trakt authorized, PIN input will be disabled and ""Get new Trakt PIN" will appear

Fix not able to get new pin when token expired

---

sickbeard/providers/torrent/json/hdbits.py

Uses find_proper from Generic Provider

Fix No value for argument 'seeders' in constructor call

---

sickbeard/metadata/kodi.py

Fixing kodi __init__ method not calling super by mistake

---

gui/slick/css/style.css
gui/slick/js/manage/failed-downloads.js
medusa/helpers.py

As database failed.db, table failed has no date, when we default sorting to release, we lose the chronological order of failed (database order)

Remove "Failed Downloads" release sorting. Use database order

---

medusa/name_parser/guessit_parser.py
tests/datasets/tvshows.yml
tests/test_guessit.py

Fix for #1155: Expected titles should not contain number-only items.

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Fixing release group detection issues with guessit

---

medusa/providers/torrent/html/limetorrents.py

Fixes release name beeing cut off
**Previously:**
`F-ck Thats Delicious S02E02 The Other City By The Sea 720p HDTV x264-[eSc] - [SR..`
**Now:**
`F-ck-Thats-Delicious-S02E02-The-Other-City-By-The-Sea-720p-HDTV-x264-[eSc]--[SRIGGA]`
**Down side:** string now has dashes `-`
**Prevention of the "downside":** only take the "longer" release name if it's actually longer than the previous to avoid the dashes

Fix release names being cut off for Limetorrents

---

medusa/tvcache.py

just guessing what is wrong because i can't reproduce and I can't get more info in the issue
```
2016-09-25 05:17:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nutech] :: [baa22c5] Error while searching Nutech, skipping: 'NoneType' object is not iterable
File "/home/home/SickRage/medusa/search/core.py", line 445, in searchForNeededEpisodes
curFoundResults = cur_provider.search_rss(episodes)
File "/home/home/SickRage/medusa/providers/GenericProvider.py", line 408, in search_rss
return self.cache.findNeededEpisodes(episodes)
File "/home/home/SickRage/medusa/tvcache.py", line 442, in findNeededEpisodes
sql_results = list(itertools.chain(*sql_results))
TypeError: 'NoneType' object is not iterable
```

Fix TypeError: 'NoneType' object is not iterable

---

medusa/__init__.py
medusa/app.py
medusa/name_parser/__init__.py
medusa/name_parser/guessit_parser.py

custom guessit function should be loaded before subliminal and other modules that depends on it

---

medusa/__init__.py
medusa/server/web/home/handler.py
medusa/server/web/manage/handler.py
medusa/subtitles.py
medusa/tv.py
static/css/dark.css
static/css/style.css
static/js/ajax-episode-subtitles.js
static/js/home/display-show.js
static/js/manage/subtitle-missedPP.js
views/displayShow.mako
views/manage_subtitleMissedPP.mako
views/partials/footer.mako
views/partials/header.mako
views/subtitle_modal.mako

If show has no subtitles, user clicks the `CC` image, and we ask if he wants to `auto` search subs or `manual` download subs

Adds manual subtitle search in displayShow and re-download subtitle (clicking in the existing flag)

---

medusa/db.py

In a fresh install, Medusa creates a sickbeard.db then start do all migrations. When minor is none it created a `~\Medusa\sickbeard.db.v42.None` - this fixes it

Fix minor_version as None

---

medusa/logger.py
tests/test_logger.py

Read log files should return unicode lines.

---

static/js/common/init.js

This fixes `e.context` as it's now `e[0]`.

fix jQuery 3.0.0 context

---

medusa/server/web/core/base.py

@ratoaq2 should we change `loggedIn` to use `bool(get_current_user)` so it doesn't accidentally leak the cookie onto the page?

fix secure cookie

---

medusa/providers/nzb/omgwtfnzbs.py

Fixes: 
```2016-10-26 22:01:47 DEBUG    SEARCHQUEUE-MANUAL-282401 :: [OMGWTFNZBs] :: [683951e] Found result: None```

Avoids logging results when they are null

---

static/js/config/post-processing.js
static/js/home/display-show.js
static/js/plot-tooltip.js
static/js/rating-tooltip.js
static/js/scene-exceptions-tooltip.js

Fixes tooltips not loading as `viewport: $(window)` breaks on jQuery 3.x.x

fix tooltips

---

medusa/postProcessor.py

Previous commit changed parameter name from filePath to file_path this breaks post processing of anime

fix adba.Episode parameter name

---

views/history.mako

Without this PR it shows again the provider icon
@duramato @medariox

Show a "x" icon for failed download in compact view

---

medusa/show_updater.py

I think as we are showing the full object while calling the showupdater, it raises that warning about:
"in process of being updated by Post-processor or manually started, can't update again until it's done."
Traceback:
```
2016-11-02 03:00:10 WARNING  SHOWUPDATER :: [cb32c93] Automatic update failed. Error: Once Upon a Time (2011) is in process of being updated by Post-processor or manually started, can't update again until it's done.
2016-11-02 03:00:10 INFO     SHOWUPDATER :: [cb32c93] Updating season indexerid: 248835
indexer: 1
name: Once Upon a Time (2011)
location: /media/SAMSUNG/media/series/Once Upon a Time (2011)
network: ABC (US)
airs: Sunday 8:00 PM
status: Continuing
startyear: 2011
genre: Adventure|Drama|Fantasy|Romance
classification: Scripted
runtime: 45
quality: 80
scene: …
```

Fix showing show object in show updater

---

medusa/providers/generic_provider.py

There is no good reason to verify the certs of a download URL for public trackers, as they use an external provider anyway or no auth at all (no sensitive data).

Don't verify TLS certs for public trackers downloads. Fixes #1425

---

medusa/show_updater.py

Making sure we only do full show refreshes, and not the per season updates. As it seems the reset of the update code is not ready for that.

Disable per season updates.

---

views/history.mako

Fix after @duramato added the provider to the title in faled
This happens when provider is no longer in providers (like a RSS provider that got deleted) or provider we removed in the past like Torrentz and have a failed download

Fix AttributeError: 'NoneType' object has no attribute 'name'

---

medusa/network_timezones.py
medusa/show_queue.py
medusa/show_updater.py
medusa/tv.py

These changes should fix following issues in develop:
* Complete seasons vanished from db (displayShow).
* Error message in log like: None object missing attribute paused. Or something like that.
* Already episodes snatched while they where already downloaded. Or at least show statussus changed unintentional.

Multiple improvements and fixes to show season updating.

---

medusa/server/web/config/search.py

Unicode error happens only after user saves config because the config value is INT

Fix pymedusa/Medusa/issues/1455

---

medusa/indexers/tvdbv2/tvdbv2_api.py

Skipping the show when it doesn't have a result in the requested language.
your can reproduce the issue by searching for: '24 h berlin' in english.

Fixed: For some shows there isn't an 'en' language available. But a result is provide, without the showname.

---

medusa/helpers.py

Like swithing anime show to language japanese.
Don't know if this is the way though.
At least the error occurs because it tries to do a ''.join(unicode). As it's mixing str and unicode in the anon_url function.
The problem goes a little bit further then this.
The root cause why the anon_url is called with unicode chars, is because of the xem url.
But that url is invalid.
Meaning, the url for xem is created from the shows title. But the shows title changes with the language you select on it. How should this work? Because if we should use the english language by default, this could be another challenge. As when changing your language for the show, you loose the english title.

Fixed unicodeDecode error, when opening shows with a unicode name.

---

medusa/name_parser/rules/properties.py
medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Changes:
- AHDTV
- Bluray splitted in BRRip, BDRip and BluRay
- DVD splitted in DVD and DVDRip
- WEBCap is WEBRip
- Use SATRip instead of DSRip
- 4K renamed to 2160p
- Added 4320p
- Fixed interlaced detection for SD qualities (480i != 480p)
- DolbyDigital is actually AC3
- Renamed DVB to PDTV
- Added video_encoders: x264 and x265

Guessit rules to follow quality standards #1266

---

medusa/name_parser/rules/rules.py

This fixes latest bug in logger call reported in #1093

Standard logging call should be used in rules.py 

---

static/js/core.js
views/config.mako

@p0psicles @ratoaq2 from what I can see there is an issue where the shutdown page now shows the ajax error since it's trying to load the API on that page but that can wait till the next release as once it's shutdown it doesn't matter all that much what happens since the server is off...

fix vue issues

---

medusa/post_processor.py
tests/legacy/pp_tests.py
tests/legacy/test_lib.py

Return full file path instead of parent in get_rel_path

---

medusa/search/core.py
medusa/search/queue.py
medusa/tv_cache.py

Backlog = specific search. Doesn't need to run daily. 
Daily runs a lot more frequent than backlog.
@pymedusa/developers 
Daily uses another function:

Don't run RSS search before backlog search

---

medusa/scene_numbering.py

@p0psicles 
Fix:
```
2016-11-28 22:26:02 DEBUG    SHOWQUEUE-ADD :: [b88941f] Looking up XEM scene mapping for show 21756 on TVmaze
2016-11-28 22:26:02 WARNING  SHOWQUEUE-ADD :: [b88941f] Exception while refreshing XEM data for show 21756 on TVmaze: xem_origin
2016-11-28 22:26:02 DEBUG    SHOWQUEUE-ADD :: [b88941f] Traceback (most recent call last):
File "/home/home/SickRage/**********/scene_numbering.py", line 496, in xem_refresh
url = "http://thexem.de/map/havemap?origin=%s" % indexerApi(indexer).config['xem_origin']
KeyError: 'xem_origin'
```

Fix xem keyerror

---

medusa/notifiers/pushbullet.py
medusa/server/web/home/handler.py

which is returned instead of a generic error message.
Replaced getURL with default session object. As there is no reason IMO to use getURL here. getURL isn't really usefull for json requests anyway, as it will return None when a 4xx response is returned.

Improved pushbullet.py to return the error message

---

medusa/helpers.py

There is still the issue where some exceptions are swallowed and returned as None. But don't want to change too much in one go.

Do not return None, for non 2xx response, when the request type is 'response'.

---

medusa/search/proper.py

@ratoaq2 @duramato 
To check if is already in history we do:
if any(clean_proper_name == self._canonical_name(cur_result[b'resource'], clear_extension=True)
with `parsing_time` added to parse, it was comparing it with history, and history doesn't have this info, so proper was snatched again.
clean_proper_name = u'title:show|season:1|episode:1|other:proper|proper_count:1|proper_tag:repack|screen_size:1080p|format:hdtv|video_codec:h264|video_encoder:x264|release_group:dimension|type:episode|parsing_time:0.553999900818'

Fix proper being redownloaded.

---

medusa/failed_history.py

@labrys as i said in chat
i think @duramato had this issue before about composite FAILED status.
FAILED is temporary status.  After set to failed medusa set to WANTED so medusa starts a new search OR revert old episode status (as user already have the file in the library)
To reproduce:
1) Snatch & PP an episodes in allowed
2) Preferred quality is released
3) Snatch the preferred
4) Download of preferred failed
Without this PR:
5) Status is set to compound FAILED (preferred quality)
6) Revert of episode not saved to database
7) Medusa starts a search with episode status FAILED (which is wrong)
With this PR:
5) Episode is reverted to allowed quality and library file is untouched
6) Medusa starts a search with old episode status DOWNLOADED (allowed) , so it will still look for preferred.

Fix failed history not saving to DB when reverting episode

---

medusa/server/web/manage/handler.py
medusa/subtitles.py

TVEpisode.from_filepath may return None and cause tv_episode.status to raise an exception.

Fix status check happening too early

---

medusa/indexers/tvdbv2/tvdbv2_api.py
medusa/metadata/generic.py
medusa/show_queue.py
medusa/tv.py

* Improved speed, as i'm caching the indexer api, for every season that it's getting images.
Previously we did one call to the indexer for every season poster and banner. For a show with 24 seasons, that means 48 calls. I've reduced this to one.
I've changed the structure a little. So i'll need to further investigate if this as any other side effects. For example if the indexers images are used by anything other then the metadata generators.
There is language support. As it will try to get the images in your language. Unfortunately also here again tvdb api is coming short. As for example with the show House of anubis (NL), the show has a poster, banner and fanart in language 'en', but no season or seasonwide. In in the language 'nl' it has season (no seasonwide) but also no poster, banner …

Fixed creation of tvdb season posters and banners (seasonwide) metadata

---

medusa/providers/torrent/html/bithdtv.py

Fixes pymedusa/Medusa/issues/1675
File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 133, in parse
title = cells[2].find('a')['title']
IndexError: list index out of range

Fix pymedusa/Medusa/issues/1675

---

medusa/helpers.py

It was detecting RARBG.mp4 as valid media info file.
hey, @rarbg are there any other file formats other than `RARBG.mp4` ?

Fix RARBG regex when check if is media file

---

medusa/server/api/v2/auth.py
medusa/server/api/v2/config.py
tests/apiv2/test_config.py

This allows the use of a form when posting to `/api/auth/login` instead of just basic auth. It also allows users to authenticate and get an API key when there's no username/password set. This is mainly used when Medusa is first installed.

fix api auth when using no user/pass, add new field to api config

---

medusa/metadata/generic.py

This should prevent the IndexerAttributeMissing exception.

Forgot to add this check to the _season_banners_dict() function.

---

medusa/common.py
medusa/post_processor.py
pytest.ini
tests/test_quality_replace.py

Here the check can be simple as before. Don't need to do all `should_replace_ checks
This code is when user manually adds a file in PP folder
So it will only run this code when not priority_download (if is it snatched, in history, PROPER, or BEST)
This won't fix issue 1856 neither omg issue

Revert quality method should_replace in PP

---

lib/knowit/providers/mediainfo.py
lib/unrar2/windows.py

http://bugs.python.org/issue29082

Fix #1843: Medusa does not start with Python 2.7.13

---

static/js/browser.js

Fixes https://github.com/pymedusa/Medusa/issues/1353#issuecomment-257041472

remove "Close" from fileBrowser dialog since we use x

---

medusa/helper/externals.py

Trakt is used to enrich with external id's. If trakt is down, adding shows was not possible.

Catch possible Trakt exception while adding a show.

---

medusa/providers/generic_provider.py

This can happen with shows added with a non-default indexer language
In case https://github.com/pymedusa/Medusa/blob/master/medusa/name_parser/parser.py#L66 fails (e.g. different indexer language with tvdb), it will be used instead https://github.com/pymedusa/Medusa/blob/develop/medusa/name_parser/parser.py#L70

Fall back to searched show if indexer ID can't be found

---

medusa/providers/generic_provider.py

As it can cause wrong results to be associated with the searched show.

Don't fall back to show ID. Reverts #1957

---

medusa/providers/generic_provider.py
medusa/providers/nzb/anizb.py
medusa/scene_exceptions.py
pytest.ini
tests/legacy/scene_helpers_tests.py

If a anime show has a season scene exception with a scene_season > 1 use the scene_episode (indexers) as episode number.
As an example. The show ajin with season scene exception "Ajin 2nd season" for season 2. Searching for absolute episode 26, will now search for Ajin 2nd season 13, instead of Ajin 2nd season 26, as it is currently.
* Made sure get_scene_exceptions is multi-indexer.
* Use * wildcard for anizb searches, to increase results.

Improve anime episode search strings

---

medusa/providers/generic_provider.py
medusa/providers/torrent/html/bithdtv.py
medusa/providers/torrent/html/freshontv.py
medusa/providers/torrent/html/scenetime.py
medusa/providers/torrent/html/speedcd.py
medusa/providers/torrent/html/tvchaosuk.py

Some providers return the same results with `Show S01E01` or `Show S01E01 PROPER`, so this makes them just use `Show S01E01` propers, as they will still return "proper" results

Remove proper strings from providers which return "propers" without them

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Fix for #1986
Detect release as anime when screen_size is inside a group (e.g.: [720p] or [HD_1280x720p])

Fix anime detection

---

medusa/tv.py

because user have a file in library.
@OmgImAlexis

Fix redownload when status "SNATCHED BEST" is replaced with DOWNLOADED

---

medusa/post_processor.py

@medariox as we discussed
https://github.com/pymedusa/Medusa/issues/2087

Remove nzb_name log as manual PP doesn't have nzbname input. Only nzbtomedia/etc

---

medusa/name_cache.py
medusa/name_parser/guessit_parser.py
medusa/providers/generic_provider.py
medusa/providers/torrent/html/animetorrents.py
medusa/providers/torrent/json/btn.py
medusa/scene_exceptions.py
medusa/server/web/home/handler.py
medusa/show_name_helpers.py
medusa/show_queue.py
medusa/show_updater.py
medusa/tv.py
tests/legacy/scene_helpers_tests.py

get_scene_exceptions did two things. 1. Check if a indexerid, indexer, (optional) season combination is available in exceptionsCache. If not search in db, and update the exceptionCache in the process.
Now those are two methods. We now "trust" the cache, as in, when it can't find in cache, it isn't there.
And the second methods constructs the cache.
This PR will also improve startup time, as previously it was creating the cache, trough looping by show and creating the cache per show.
Now i'm doing one db query, and creating two caches in one go.
* ~~Update is only run on startup and on editShow.~~
* Update is only run on editShow.
* get_scene_exceptions only get's exceptions from cache
* update_scene_exceptions_cache, updates the cache (db) for a specific show.
* refresh_exceptions_cache, …

Split up get_scene_exceptions in get and update.

---

medusa/tv.py

Fix log while refreshing file
Sorry about that, it was a last minute commit.
No risk here as this log is only to tell episode status won't be changed.
I didn't messed up the DB.

Fix log while refreshing file

---

static/js/ajax-episode-search.js

@OmgImAlexis @duramato  (finally fixed this one)
UPDATE: this issue happens only when you forced a search and gets a SNATCHED BEST and don't restart medusa, so JS keeps updating status. See this comment: https://github.com/pymedusa/Medusa/pull/2120#issuecomment-278142762
Existing regex creates this issue:
----------------------------
With this PR:
https://regex101.com/r/2yhi7u/3

Fix SNATCHED (BEST) render pill not working

---

medusa/server/api/v2/show.py
medusa/tv.py
static/js/quality-chooser.js
views/editShow.mako
views/inc_qualityChooser.mako

Before user save new quality, a WARNING label in html will be shown with number of current backlogged episodes and the number of new backlogged episodes after quality change
ping @jxer
**User current settting:**
-----------------------------------
**After changes quality:**

Show number of backlogged episodes with new and existing qualities

---

medusa/post_processor.py

Not that .nfo with different basename is detected
``` 
2017-02-09 16:19:04 DEBUG    Thread-27 :: [51ff22a] Found the following associated files for C:\Users\Fernando\Documents\PP\Quantico.S02E11.720p.HDTV.X264-DIMENSION\Quantico.S02E11.720p.HDTV.X264-DIMENSION.mkv: [u'C:\\Users\\Fernando\\Documents\\PP\\Quantico.S02E11.720p.HDTV.X264-DIMENSION\\quantico.211.720p-dimension.nfo', u'C:\\Users\\Fernando\\Documents\\PP\\Quantico.S02E11.720p.HDTV.X264-DIMENSION\\Quantico.S02E11.720p.HDTV.X264-DIMENSION.pt-BR.srt']
2017-02-09 16:20:20 DEBUG    Thread-27 :: [51ff22a] Hard linking file from C:\Users\Fernando\Documents\PP\Quantico.S02E11.720p.HDTV.X264-DIMENSION\quantico.211.720p-dimension.nfo to C:\Users\Fernando\Documents\Series\Quantico\Season 2\Quantico.S02E11.720p.HDTV.X264-DIMENSION.nfo
``` …

Fix associated file not recognized when torrent is RARed

---

medusa/providers/torrent/__init__.py
medusa/providers/torrent/rss/extratorrent.py

ExtraTorrent started to encrypt their website source code again, so we
are forced to use the RSS feed. It is usually a few hours behind the
website, but better than nothing.

Use RSS instead of html for ExtraTorrent provider

---

medusa/post_processor.py

@duramato 
Fixes https://github.com/pymedusa/Medusa/issues/1964
2017-02-14 11:04:35 DEBUG    Thread-28 :: [51ff22a] Parsed 'Under.the.Dome.S03E01E02.720p.HDTV.X264-DIMENSION' into title: Under the Dome, season: 3, episode: [1, 2], screen_size: 720p, format: HDTV, video_codec: h264, video_encoder: x264, release_group: DIMENSION, type: episode, parsing_time: 0.266000032425, total_time: 0.266000032425, absolute_episode: [], quality: 720p HDTV
Display show is ok (tv_episodes table):

Fix multi episode downloads not getting marked as downloaded on the history page

---

medusa/common.py
tests/test_should_search.py

More rules and tests to should_search
I had an episode SNATCHED BEST and moved best quality to allowed and remove all preferreds
should_search returned True. which is wrong

More rules and tests to should_search

---

views/snatchSelection.mako

Fixes extra alert display on snatchSelection when a show is updating.
alert display is contained in showHeader.mako

remove extra alert display

---

medusa/server/web/home/handler.py
views/partials/home/poster.mako

Only Show update will update xem data by calling xem_refresh,so it will improve mako loading
ping @p0psicles @duramato

Don't refresh XEM while loading mako. Only in show_refresh

---

medusa/show_queue.py
medusa/tv/series.py
static/js/quality-chooser.js
views/displayShow.mako
views/editShow.mako

IMO show object must have this unique identifier as an attribute, example 'tvmaze1234'
With new api V2, we will need it in mako and in JS, so it would be good to have in the show object
ping @OmgImAlexis 
Fixes https://github.com/pymedusa/Medusa/issues/2073

 Add support to recently deleted global var for multi-indexer

---

medusa/search/backlog.py
views/config_search.mako
views/manage_manageSearches.mako

as @ratoaq2 pointed
dividing integers will result in integer so
`self.cycleTime = app.BACKLOG_FREQUENCY / 60 / 24` will result 0.5 but value will be 0
so a backlog of 12 hours, will always have a cycleTime of  0 in case of the default of 720
So when checking if we should run a forced search, it will never reach that limit code:
`if not which_shows and not ((curDate - self._last_backlog) >= self.cycleTime):`
as `(curDate - self._last_backlog)` will always be higher than cycleTime
Imo this code was done to check if user runned a backlog before waiting for next backlog (so, a forced backlog)

Fix forced backlogged not being limited by BACKLOG_DAYS

---

medusa/show_queue.py

Fixes https://github.com/pymedusa/Medusa/issues/1538
I set:
It loads the page with default episode status, but if you change it. ofc it will use the one you choosed:
```html
<option value="${cur_status}" ${'selected="selected"' if app.STATUS_DEFAULT == cur_status else ''}
```
SHOWQUEUE-ADD :: [51ff22a] 262414: Bates Motel S04E10 not found in the database
SHOWQUEUE-ADD :: [51ff22a] 262414: Bates Motel S04E10 has absolute number: 40 
SHOWQUEUE-ADD :: [51ff22a] 262414: Bates Motel S04E10 has already aired, marking it 'SKIPPED'
SHOWQUEUE-ADD :: [51ff22a] 262414: Bates Motel S05E01 not found in the database
SHOWQUEUE-ADD :: [51ff22a] 262414: Bates Motel S05E01 has absolute number: 41 
SHOWQUEUE-ADD :: [51ff22a] 262414: Bates Motel S05E01 airs in the future or has no airdate, marking it …

Fix wrong log about default previously aired episodes status

---

medusa/classes.py
medusa/name_parser/parser.py
medusa/providers/generic_provider.py
medusa/providers/nzb/nzb_provider.py
medusa/providers/torrent/torrent_provider.py
medusa/search/queue.py
medusa/tv/cache.py

This started as a PR to change the following apparent issue:
Apparently someone decided that when finding new results we store them in cache and then continue. This results in users having to perform two forced searches for a single episode.
While trying to come up with a proper fix for this issue. I noticed I had to make some more changes to fix it, without causing any new bugs. That's why i've decided to rewrite part of the GenericProvider search code.
This PR's has made some design choices, that could be debatable. And i'm open for that. I can provide arguments for most of them, but if anything can be done in a better/different way, let me know. In short i've made the following changes:
* Added a new class EvaluateSearchResult(SearchResult), that can be used as a Search result object, …

Refactor generic provider search

---

medusa/name_parser/parser.py
medusa/tv/cache.py

Now we can clearly know it was a cached result and know the indexer id
Also which show was matched in the database
This usefull if user adds one show with tvdb and later removed that show to add in tvmaze.
So when we get the cached result we will know we are using the correct cache item

Improved logs for cached results and show match

---

static/js/config-providers.js

Fix initial load of search provider settings are displayed as blank
Fixes https://github.com/pymedusa/Medusa/issues/2020
@OmgImAlexis finally!

Fix initial load of search provider settings are displayed as blank

---

medusa/scene_exceptions.py
medusa/server/web/home/handler.py

Fixed missing season scene exception (medusa and xem) icons in displayShow page.
* Return key: list(list_of_exceptions) instead of key: set_of_exceptions. As a set is not json serializable.
* Cast to int, as a json requests was passing the indexer_id as str.
* Use iteritems from six, as i've already imported it. And it's a little bit faster.

Hotfix/fix season scene exceptions not shown (#2259)

---

medusa/providers/torrent/html/speedcd.py

I just logged from browser:
```
:authority:speed.cd
:method:POST
:path:/take_login.php
:scheme:https
```
```
2017-02-23 19:34:14 DEBUG    SEARCHQUEUE-MANUAL-257655 :: [Speedcd] :: [6399d78] Found result: Arrow S05E14 The Sin-Eate 1080p WEBRip DD5 1 x264 with 3 seeders and 0 leechers
2017-02-23 19:34:13 DEBUG    SEARCHQUEUE-MANUAL-257655 :: [Speedcd] :: [6399d78] GET URL: https://speed.cd/browse.php?c55=1&c52=1&search=Arrow+S05E14&c41=1&c50=1&c2=1&c30=1&c49=1 [Status: 200]
2017-02-23 19:34:12 DEBUG    SEARCHQUEUE-MANUAL-257655 :: [Speedcd] :: [6399d78] Search string: Arrow S05E14
```

Fix speedcd login page

---

static/js/root-dirs.js
views/addShows_newShow.mako
views/addShows_trendingShows.mako

root-dirs.js was included both in main.mako and in addShows_newShow.make and addShows_trendingShows.mako causing the delete event to fire multiple times.

will fix multiple dirs removed when delete pressed for RootDirs

---

medusa/__main__.py

Fix root dir not decoded
Related: https://github.com/pymedusa/Medusa/issues/1652#issuecomment-280756677

Load config file as UTF-8

---

medusa/process_tv.py

When we call process_media it can postpone the PP of a media file because it doesn't have subtitles
so after that, we delete all rar content files (nfo, srt) that wasn't listed as wanted "associated files"
This fixes the deletion of the media file when media was postponed
2017-03-02 01:32:04 DEBUG    FINDSUBTITLES :: [32b3c7d] No subtitles associated. Postponing the post-process of this file: Show.S06E16.720p.HDTV.x264-AVS.mkv
2017-03-02 01:32:04 DEBUG    FINDSUBTITLES :: [32b3c7d] Deleting file: Show.S06E16.720p.HDTV.x264-AVS.mkv

Don't delete extracted media file if it was postponed

---

static/js/home/snatch-selection.js
views/snatchSelection.mako

- Table is only initialized once
- results replace only table content
- sort and filter are restored after search is finished,

Will change manual search to fix loading of results

---

static/js/add-shows/init.js
static/js/add-shows/popular-shows.js
static/js/add-shows/recommended-shows.js
static/js/add-shows/trending-shows.js
static/js/common/init.js
static/js/root-dirs.js

- disables 'add' buttons
- shows alert at top of page
- opens custom settings to add root directories
- clears alert and re-enables buttons when directory added
- fixes #2214
@labrys

will fix prevent adding shows on recomended pages if no root dir set

---

medusa/config.py
medusa/server/web/config/general.py
medusa/version_checker.py

- fix git alert disappearing on config change #2349
- allows git_path change while application is running

fix disappearing git alert, allows git_path change without restart

---

medusa/clients/torrent/transmission_client.py

Also log stopped and unmapped status
@duramato ~needs testing~ tested
TORRENTCHECKER :: [5f2155a] Torrent completed and reached minimum ratio but it was restared to seed more. Current ratio: [0.842/0.500]. Keeping it: [Show.S01E01.1080p.HDTV.X264-DIMENSION]

Check if user manually started seeding a finished torrent

---

medusa/indexers/tvdbv2/tvdbv2_api.py

@p0psicles don't know why our new API is not working. Reverting until we figure it out

Fix could not authenticate to the indexer TheTvdb.com, with reason 'Unauthorized'

---

medusa/clients/deluge_client.py

Deluge 1.3.14 requires `Content-Type: application/json`
```
2017-03-11 19:07:56 DEBUG    SNATCHQUEUE-MANUALSNATCH-78901 :: [f51338e] Traceback (most recent call last):
File "H:\usr\local\medusa\medusa\search\queue.py", line 426, in run
self.success = snatch_episode(search_result)
File "H:\usr\local\medusa\medusa\search\core.py", line 136, in snatch_episode
result_downloaded = client.send_torrent(result)
File "H:\usr\local\medusa\medusa\clients\generic.py", line 221, in send_torrent
if not self._get_auth():
File "H:\usr\local\medusa\medusa\clients\**********_client.py", line 65, in _get_auth
self.auth = self.response.json()['result']
File "H:\usr\local\medusa\lib\requests\models.py", line 812, in json
return complexjson.loads(self.text, **kwargs)
File …
```

Fix Deluge 1.3.14 requires Content-Type header

---

runscripts/init.gentoo

runscript is deprecated; please use openrc-run instead.
https://bugs.gentoo.org/show_bug.cgi?id=494220
https://forums.gentoo.org/viewtopic-t-1007118-start-0-postdays-0-postorder-asc-highlight-.html
Also added string for proper stopping.

Update init.gentoo runscript.

---

views/errorlogs.mako

@Thraxis @p0psicles
~~I don't get why text is wrapping. Any idea?~~
~~I tried several things but i can't fix it~~
~~In viewlogs.mako this doesn't happen~~

Fix wrapping in errorlogs

---

tests/test_list_associated_files.py
tests/test_process_tv.py

Need to switch base after `rewrite-process-tv` gets merged as I'm not allowed to PR to that branch =)
~~ratoaq2 confirm i can't run two tests?~~
~~I tried to use the existing structure from `test_should_process`  to avoid call `test_path = create_structure(p['path'], structure=p['structure'])` twice by creating another function called `def test_list_associated_files` but didn't worked~~
~~is there a way ?~~

Add list_associated_files test

---

medusa/post_processor.py

As the snatched quality has to come from guessit. Avoid wrong matches in history and allows matches with unknown quality.
@fernandog @OmgImAlexis

Don't use knowit quality to check for quality in history

---

runscripts/init.gentoo

Also rewrited old sed string, because of possible errors when unencrypted password in config.ini used
http://www.shellcheck.net/

Eliminated ShellCheck warnings from init.gentoo

---

medusa/databases/main_db.py
medusa/history.py
medusa/server/web/home/handler.py
views/snatchSelection.mako

Fixes the issue where N releases names from same provider (with same release name) were marked as SNATCHED but user had only one SNATCH
@duramato as we talked
TODO:

Improve match of snatched NZB items in snatchSelection using size

---

medusa/trakt_checker.py

2017-03-23 16:11:07 WARNING  TRAKTCHECKER :: [624b1d3] Could not connect to Trakt. No http status code
2017-03-23 16:11:07 WARNING  TRAKTCHECKER :: [624b1d3] Unable to retrieve shows from Trakt watchlist. Error: Could not connect to Trakt. No http status code

Fix trakt duplicate warning

---

medusa/indexers/tvdbv2/tvdbv2_api.py

As discussed in https://github.com/pymedusa/Medusa/issues/2424

Fix TypeError when updates_api returns None. Fixes #2424

---

medusa/providers/torrent/json/rarbg.py

@duramato you might confirm it works with BTN too
UPDATE: BTN does it correctly. It only adds scene names if not tvdb

Don't use all scene names when searching with tvdb

---

medusa/providers/torrent/json/rarbg.py

Needs to also remove the show name and there's is no easy way to do this now
the search string should be only "S01E01" and not "Show S01E01" when searching with tvdb_id
sorry about that

Revert "Don't use all scene names when searching with tvdb"

---

medusa/clients/torrent/deluge_client.py
medusa/clients/torrent/deluged_client.py
views/config_search.mako

Continue the implementation of: https://github.com/pymedusa/Medusa/issues/1139
Now Deluge/Deluged has both features transmission has: 
1) remove when ratio reached
2) move to seeding folder
@OmgImAlexis @Nicoleoca @ratoaq2
TODO:
This is the log when removal is uncommented:
```
2017-03-28 15:41:45 DEBUG    TORRENTCHECKER :: [b4a8a54] Deluge: Requested a POST connection to http://localhost:8112/json with params: None Data: {"params": ["3513ede325....", true], "method": "core.remove_torrent", "id...
2017-03-28 15:41:45 DEBUG    TORRENTCHECKER :: [b4a8a54] Deluge: Response to POST request is {"id": 5, "result": true, "error": null}
```

 Deluge and DelugeD: add feature to remove torrent when ratio reached

---

medusa/search/proper.py

Don't need to keep comparing previous with new processed list. Just need to not check it
self.processed_propers i now is a list of dict with dates, so i need to check if proper is already in the list.
Tested:
- 2 normals runs (second run it didn't re-processed the proper)
- 1 normal run then 1 forced run then 1 normal run. In the second run it reprocessed again (forced) and in the last one it didn't because it was already processed in the first run
Also fixes this that happens in a forced proper search
```
File "/home/osmc/Medusa/medusa/search/proper.py", line 95, in run
current_processed_propers.extend(set(self.processed_propers).difference(set(current_processed_propers)))
TypeError: unhashable type: 'dict'
```

Improve already processed propers code check and fix unhashable type: 'dict'

---

medusa/name_parser/parser.py
medusa/scene_numbering.py
medusa/server/web/home/handler.py
medusa/tv/series.py

Fixes: https://github.com/pymedusa/Medusa/issues/1975
@p0psicles @duramato @ratoaq2
```
[b4a8a54] Removed parsed cached result for release: Bull.2016.S01E17.1080p.HDTV.X264-DIMENSION[rartv]
[b4a8a54] Removed parsed cached result for release: Bull.S01E17.REPACK.720p.HDTV.x264-AVS[rartv]
[b4a8a54] Removed parsed cached result for release: Bull.S01E17.HDTV.x264-SVA[rartv]
```

Fix reusing "wrong" guessit cached name parsing after new numbering

---

medusa/databases/main_db.py
medusa/indexers/indexer_config.py
medusa/tv/series.py

Normalize show status while loading from indexer

---

medusa/indexers/indexer_config.py

All status need to be added in the map, including `continuing`

Fix 'unknown' status for 'continuing' status shows

---

medusa/logger/adapters/style.py

If string formatting of BraceMessage fails, fall back to the `repr` to log the message and log a traceback of the reason.

Add fallback for BraceMessage formatting

---

medusa/search/proper.py

Add default to avoid raising exception with getattr(). Fixes #2665

---

medusa/tv/series.py

Also don't show as list:  deleting: [u"abc.srt", u"abc.nfo"]

Change another missed warning log to INFO

---

medusa/search/core.py

Undesired words short-cuts check too early causing releases with undesired words to be selected.

Fix undesired words

---

medusa/providers/torrent/json/t411.py

No easy solution to make remote URL like we do with broken providers. 
Also my design won't be approved anyway so someone more experience could do that.
For now just changing develop as redirect still works
@IDerr

Use t411 new domain

---

medusa/server/core.py
medusa/ui.py
medusa/ws/MedusaWebSocketHandler.py
package.json
pytest.ini
static/js/ajax-notifications.js

This is a working POC, for replacing the current REST polling mechanisme we use for the Pnotifications, with Websockets. For more info please refer to FR: #495.
Currently it's just a POC and based on #432 , for discussing the actual implementation.
Replaced the Rest call used for the notification, with the websockets.

POC: First working implementation of websockets.

---

medusa/providers/generic_provider.py
tests/providers/test_generic_provider.py

* Fixed issue where .seconds() on 24 hours ago would test as 0. Because .seconds resets after one day. Used total_seconds() instead.
* Added test for failing assertion on human times.

Added aliasses for 'right now' 'just now'.. etc.

---

medusa/tv/series.py

~~Possible fix to: https://github.com/pymedusa/Medusa/issues/2652~~
From his logs:
`SHOWQUEUE-REFRESH :: [a011615] 258368: Not changing **current status 'Unaired'** based on file: /tv/Inventions that Shook the World/Season 01/Inventions that Shook the World - S01E01 - The 1900s.wtv`
**Reason: New file is the same as current file**
if status is UNAIRED, then episode object file size is 0, and if we can't get a size, size will also be 0, thus the reason above showing both have the same size (which is wrong)
He copied the file to show folder without using the PP and hit re-scan files

Don't assume same_file if size is 0 (unable to get size)

---

medusa/app.py
medusa/search/core.py

Make "internal" and "xvid" undesired by default (like it was) but configurable

---

medusa/providers/torrent/html/morethantv.py

Fix issue when MTV has seeders/leechers > 999

Fix ValueError: invalid literal for int() with base 10: '3,124'

---

lib/knowit/__init__.py
lib/knowit/__main__.py
lib/knowit/api.py
lib/knowit/properties/audio/channels.py
lib/knowit/properties/basic.py
lib/knowit/properties/duration.py
lib/knowit/properties/language.py
lib/knowit/properties/quantity.py
lib/knowit/provider.py
lib/knowit/providers/enzyme.py
lib/knowit/providers/ffmpeg.py
lib/knowit/providers/mediainfo.py
lib/knowit/rules/__init__.py
lib/knowit/rules/video/resolution.py

it should be mediainfo, ffmpeg, enzyme.
This should fix all windows/mac warnings related to ffmpeg since mediainfo is provided for these OSes

Fixing knowit random provider order

---

medusa/server/api/v2/config.py
medusa/server/web/home/handler.py
static/js/home/index.js
tests/apiv2/test_config.py

Fixes https://github.com/pymedusa/Medusa/issues/2893
The value of the select is the index number of the root dirs list
Also fixes:
When selected root index is 0 it would set as None

Fix config patch ignored {u'selectedRootIndex': u'0'}. Needs to be int

---

medusa/subtitle_providers/legendastv.py
medusa/subtitles.py

Fixes an old issue when it doesn't find subtitles because show in provider uses a different name
Examples:
`TURN` and `Turn: Washington's Spies`
`DC’s Legends of Tomorrow` and `Legends of Tomorrow`
`Marvels Agents of SHIELD` vs `Agents of SHIELD`
`Marvel's Jessica Jones` vs `Jessica Jones`
*Most Marvel's shows
It will also work for releases with translated releases like `La Lista Negra` for `The Blacklist`
@ratoaq2 @duramato
PR is in sync with upstream

LTV: Use alias as fallback to original series name

---

medusa/subtitle_providers/legendastv.py

Show a 'Invalid subtitle' warning instead
Without this, until subtitle is manually downloaded, it will keep discarding provider every run
@ratoaq2

LegendasTV: Don't discard provider when BadRarFile or BadZipFile

---

medusa/subtitle_providers/legendastv.py

Subtitle class is: `__init__(self, language, hearing_impaired=False, page_link=None, encoding=None):`
@ratoaq2 added this commit upstream in the minor provider fix PR

LegendasTV: LegendasTVSubtitle class storing page_link in hearing_impaired attribute

---

medusa/subtitles.py
static/js/ajax-episode-subtitles.js

If subtitle id has a "+" (when audio codec is DD+), when requesting the URL with subtile ID,
the "+" becomes " " so it won't find in dogpile cache
Example:
subtitle_id=59644c416024b-fear.the.walking.dead.s03e07.1080p.amzn.web-dl
.dd+5.1.h.264-vlad.srt
in handler picked_id will be:
picked_id=59644c416024b-fear.the.walking.dead.s03e07.1080p.amzn
.web-dl.dd 5.1.h.264-vlad.srt
@ratoaq2 @duramato

Fix not finding subtitle ID in dopile cache while manual searching & snatching

---

medusa/show/recommendations/__init__.py
medusa/show/recommendations/anidb.py
medusa/show/recommendations/imdb.py
medusa/show/recommendations/trakt.py

This will make imdb rec load fast after a first load.
Because we recently started to use imdbpy, it needs to load additional information for each show, as opposed to getting it in one request.
This will cache the detailed show info, for a duration of 7 days.
* Refactored the 'old' caching class. And added a caching class which can store a key and value. But does also expire. I could have used existing caching libs for this. But the code I added fit's my purpose perfect. And it's only needed until we properly store this info in db. Maybe dogpile was also an option.
* Cached imdb rec list. So it will be usable after the first load.

Implemented smart caching for imdb recommended lists

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Don't know if this is the right fix @ratoaq2
Please review
Fix to: https://github.com/pymedusa/Medusa/issues/2386
```
? The.Walking.Dead.S07E13.720p.HDTV.x264-AVS-Scrambled/1e5e2f3464df439b92afea14932a87a4.mkv
: title: The Walking Dead
season: 7
episode: 13
screen_size: 720p
format: HDTV
video_codec: h264
video_encoder: x264
release_group: AVS
uuid: 1e5e2f3464df439b92afea14932a87a4
container: mkv
type: episode
parsing_time: 0.155999898911
```

Fix Wrong group when "guessing" with file name

---

medusa/indexers/tmdb/tmdb.py
medusa/indexers/tvmaze/tvmaze_api.py

The same way we do in tvmaze:
https://github.com/pymedusa/Medusa/blob/develop/medusa/indexers/tvmaze/tvmaze_api.py#L491-L496 @p0psicles
@duramato this is why your tmdb country doesn't work for non tmdb shows

Add TMDB to externals after filtering. Otherwise info will be lost

---

medusa/failed_processor.py
medusa/issue_submitter.py
medusa/scheduler.py

small files
I have enough of log changes lol.
A regex replace would be better
I use this but it not always work, specially when logger.INFO is missing:
```regex
(?:\.format)(?:\s)*(?:\()(?:(.*?)(?:=)(.*?))(?:(?:,\s*)(.*?)(?:=)(.*))?(?:\)(?:,\s*)logger\.(?:INFO|DEBUG|WARNING)\))
```
replace with:
`, {'$1': $2, '$3': $4, '$5': $6})`

New logging for scheduler, failed_processor and issue_submitter

---

medusa/clients/torrent/transmission_client.py

@p0psicles I did some more reading and found this

Transmision Retry session: POST needs to be whitelisted as it's not default

---

medusa/clients/torrent/transmission_client.py

Need to revert as today Transmission has an issue that we don't send the x-TrasmissionSessionID in header and it returns 409 because of that. So that need to be fixed before adding the retry to fix the actual 409 issue
@p0psicles

Revert "Transmision Retry session"

---

medusa/subtitle_providers/legendastv.py

It should only cache titles that matches give season when episode type
@ratoaq2 if ok, I will commit upstream to the respective PR

LegendasTV: fix caching titles for wrong season

---

static/css/style.css
static/js/common/init.js
views/displayShow.mako
views/manage.mako
views/manage_backlogOverview.mako
views/manage_massEdit.mako
views/partials/footer.mako
views/snatchSelection.mako

This will result in only showing a scrollbar for tables that exceed the page viewport.
* Added buttons at the bottom of the page, when a scrollbar is visible, similar to the one that has been implement to scroll all the way up.
Biggest advantage of this is, that we will not have a messed up overal UI, like needing to scroll to the right for the menu button on mobile.
Maybe I wasn't clear before. But the buttons only _should_ appear when there are scrollbars visible. It's implemented, and works pretty well on screen size changes. There are some small issues to be worked out on screen initialization.
As Fernandog showed me in #3016, we already have class for this, named `horizontal-scroll`.
```css
.horizontal-scroll {
overflow-x: auto;
}
```
I'll see if I can create something easy applyable …

Improved the overall UI, by overflowing the tables with a scrollbar

---

medusa/helpers/externals.py

Catch SSLError and other Requests exceptions.

---

medusa/providers/torrent/html/hebits.py

Seems that there are some titles that have a backslash ('\\') separator between the English and Hebrew title instead of regular slash ('/'). So I had to add this case to prevent out of bound error. I also added that in case none of those exist, it will skip that result.

Fix HeBits title split issue

---

medusa/providers/torrent/html/torrent9.py
medusa/session/hooks.py

I don't know why it was set to False, but it breaks the provider.

Allow redirects for Torrent9 provider

---

medusa/__main__.py

```
File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 7, in <module>
main()
File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/__main__.py", line 2104, in main
application.start(sys.argv[1:])
File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/__main__.py", line 297, in start
self.initialize(console_logging=self.console_logging)
File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/__main__.py", line 423, in initialize
if app.GIT_RESET_BRANCHES[0] == '':
IndexError: string index out of range
```

Fix start when git_reset_branches config setting is empty

---

lib/rtorrent/lib/xmlrpc/requests_transport.py

Fix double slash in rtorrent-python. Should fix #3084

---

medusa/providers/nzb/newznab.py

`newznab` and `torznab` namespaced tags are not parsed properly by BeautifulSoup 4 v4.6.0
Using a regex to find tags works until the bug is fixed.
https://bugs.launchpad.net/beautifulsoup/+bug/1720605

Fix newznab and torznab attributes not being parsed

---

medusa/post_processor.py

```files``` was mistakenly being used instead of ```file_list```. I also removed the ```if not file_list:``` check, as it could never happen.

Fix associated files not being deleted on replace. Fixes #3157

---

medusa/indexers/tvdbv2/tvdbv2_api.py
medusa/metadata/generic.py

This is a quick fix for TVDB v2 API currently not supporting thumbnails (or I missed something). The old method used helpers.validate_show(), but I don't know why and it can possibly be removed completely.

Fix thumbnails not being created. Fixes #3155

---

medusa/providers/torrent/html/elitetracker.py

The goal of this PR is to:
* Limit search to the relevant category (ie TV Shows)
* Prevent an issue when pubdate is not available but only PRE date is, which we don't want (see attached)
Causing the following error
```
2017-10-28 22:36:19 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [EliteTracker] :: [b16e0e5] Failed parsing publishing date: PRE:16 Années, 10 Mois, 3 Semaines, 5 Jours, 7 Heures, 13 Minutes, 25 Secondes
File "/home/www/medusa/medusa/providers/generic_provider.py", line 566, in parse_pubdate
dt = parser.parse(pubdate, dayfirst=df, yearfirst=yf, fuzzy=True)
File "/home/www/medusa/ext/dateutil/parser.py", line 1182, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File "/home/www/medusa/ext/dateutil/parser.py", line 559, in parse
raise …
```

Enhance EliteTracker

---

medusa/clients/torrent/qbittorrent_client.py

Allow no label to be set for qbittorrent client. Fixes #3211

---

medusa/indexers/tvdbv2/tvdbv2_api.py

This caused `filename` to not be empty and get_image() would try to download the image anyway, querying a non-existent endpoint.

Don't add artwork_prefix to image if empty string. Fixes #3225

---

medusa/search/proper.py

cur_proper.show.episodes is the episode we are searching for.
cur_proper.parse_result is the possible proper parsed result
```
FINDPROPERS :: [Speedcd] :: [4c2ace8] Search string: Show S07E06 PROPER
FINDPROPERS :: [4c2ace8] Skipping proper for wrong season/episode: Show.S06E02.PROPER.HDTV.x264-BATV
FINDPROPERS :: [4c2ace8] Skipping proper for wrong season/episode: Show.S05E04.PROPER.720p.HDTV.x264-0SEC
```

Skip propers for wrong season/result

---

medusa/server/web/manage/handler.py
medusa/subtitles.py
views/config_subtitles.mako

Archived status is generally used to mark a episode as downloaded and watched, so it doesn't need subtitles
@duramato all good?
Related to: https://github.com/pymedusa/Medusa/issues/3248

Don't search subtitles for archived episodes

---

medusa/providers/torrent/html/elitetracker.py

Currently if no result is found the following error occurs:
```
2017-11-19 01:49:03 ERROR    SEARCHQUEUE-BACKLOG-270915 :: [EliteTracker] :: [b16e0e5] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/www/medusa/medusa/providers/torrent/html/elitetracker.py", line 138, in parse\n    title = torrent.find(class_=\'tooltip-content\').div.get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'div\'\n'
File "/home/www/medusa/medusa/providers/torrent/html/elitetracker.py", line 138, in parse
title = torrent.find(class_='tooltip-content').div.get_text(strip=True)
AttributeError: 'NoneType' object has no attribute 'div'
```
The current check of len < 2 doesn't work and neither does increasing or …

Fix EliteTracker empty result

---

medusa/process_tv.py

I can't check `isdir` for a remote location
If folder is not valid Transmission will return an error
Related to https://github.com/pymedusa/Medusa/issues/3295

Fix moving torrent feature not working with remote client

---

ext/subliminal/providers/addic7ed.py
ext/subliminal/providers/legendastv.py
ext/subliminal/providers/opensubtitles.py
ext/subliminal/providers/podnapisi.py
requirements.txt

LegendasTV:
- Check if UNRAR is installed
- Don't discard multi episode archive
Opensubtitles:
- Use season and episode while imdb search

Sync with latest subliminal

---

medusa/server/api/v1/core.py

Fixes API for RootDirs.  Fixes #3267 
This also extends the DeleteRootDirs to raise a DENIED error when trying to delete the default directory and FAILURE when the directory is not in the RootDirs.

Fix API for RootDirs

---

medusa/helpers/utils.py
medusa/providers/nzb/newznab.py

If passing the cats as a list to requests.get(), it will add them like: `cats=5000&cats=5020&cats=5030`.
This will result in the backend matching if the searched show matches all of the passed cats, not if it's in one of them.
passing it comma separated like: `cats=5000,5020,5030` potentially gives more results.

Join categories list into a comma separated list.

---

medusa/clients/torrent/generic.py
medusa/session/hooks.py

Shorten the debug output for the torrent client requests.

---

medusa/clients/torrent/deluge_client.py
medusa/clients/torrent/transmission_client.py
medusa/helpers/__init__.py

`isFinished` is not set to True when idle timeout (torrent is stopend seeding when inactive for N minutes)
Got the wrong information from #transmission IRC
@duramato also fixes https://github.com/pymedusa/Medusa/issues/3146
TORRENTCHECKER :: [bc468f4] Torrent completed and reached minimum ratio: [0.467/3.000] or seed idle limit: [10080 min]. Removing it: [Show.S03E10.MULTi.1080p.WEB.x264-CiELOS]
Had to change the is_media_file check because when it wasn't a media file, the is_info_hash_processed is called. But it shouldn't

Transmission: Fix remove torrents by idle timeout

---

medusa/notifiers/nma.py

@duramato
Seems really inconsistent.
Testing multiple times sometimes it works and sometimes it doesn't
```
Thread-29 :: [4c2ace8] NMA: Could not send notification to NotifyMyAndroid. Maximum number of API calls per hour exceeded
Thread-28 :: [4c2ace8] NMA: Notification sent to NotifyMyAndroid
Thread-29 :: [4c2ace8] NMA: Could not send notification to NotifyMyAndroid. Maximum number of API calls per hour exceeded
Thread-28 :: [4c2ace8] NMA: Could not send notification to NotifyMyAndroid. Maximum number of API calls per hour exceeded
Thread-29 :: [4c2ace8] NMA: Notification sent to NotifyMyAndroid
```

NMA: proper handle status code

---

medusa/server/web/home/add_shows.py
static/js/add-shows/new-show.js

Add network information while adding new show

---

medusa/providers/torrent/html/yggtorrent.py

I thought they were not needed since they are not to be translated but apparently they are.
Once again, I think this should be a soft warning, not a hard error preventing the snatch...
Also could we do a hotfix for this one? Otherwise I guess we'll see at least 10 tickets about this until next release.

Add missing mappings for YggTorrent, fixes #3427

---

medusa/notifiers/slack.py

Removes the webhook construction using 'SLACK_WEBHOOK_URL' and
requires that the plugin-defined URI is the absolute URL to the
incoming webhook.
Any Slack-compatible incoming webhook will now support announcements.

Adds support for self-hosted Slack instances.

---

medusa/providers/generic_provider.py
medusa/providers/torrent/html/iptorrents.py
tests/providers/test_generic_provider.py

* Needed to enhance the parse_pubdate method a little. The parse method does not support passing decimals like 1.0 months, 4.2 years.
For for these granularity i'm casting them to int.
* Added tests.
Fix #3402

Added pubdate parsing for iptorrents.

---

medusa/subtitles.py

I reproduced the issue by adding a language or `srt` to a srt file
FINDSUBTITLES :: [4c2ace8] Unable to convert language code 'srt' for: Show.S01E10.1080p.WEB.H264-STRiFE.srt.srt
Fixes: https://github.com/pymedusa/Medusa/issues/3441

Fix Language convertion error when bad naming

---

medusa/providers/torrent/html/speedcd.py

They keep changing login URL (post)
@duramato

Get speed.cd login URL instead of looping a list of URLs

---

medusa/post_processor.py
medusa/subtitles.py
tests/test_rename_associated_file.py

Fixes https://github.com/pymedusa/Medusa/issues/3489
@medariox when calling from_ietf_code with `srt`, it returns an alpha3 code with `srt` in Language object but no country information 
IMO if no country, so the Language object is not a valid language, so we should not use it. 
Let me know what do you think
This issue was introduced recently as moving a SRT with no language wasn't a issue since I first started to used subtitles in Medusa/SR

Fix PP renaming subtitle to .srt.srt

---

medusa/post_processor.py

Language code for `Chinese Simplified, People's Republic of China` is `zh-CN` not `zh-CH`.

Incorrect language code for `Chinese Simplified, People's Republic of China`

---

views/partials/home/banner.mako
views/partials/home/poster.mako
views/partials/home/simple.mako

Removed redundant if/then.

---

medusa/providers/torrent/xml/torrentz2.py

Many releses only have `video` as category, this was overly restricting to only releases categorized as `video tv`.
I also tought of removing the "category" restriction altogether, as getting other results isn't the end of the world, but only `video` seems to be fine as it isn't too broad nor too restrictive.

Fix Torrentz2 being to strict on the category

---

Dockerfile

[Docker] Rev alpine linux to 3.7 after testing

---

medusa/server/web/home/add_shows.py
static/js/add-shows/add-existing-show.js
static/js/add-shows/new-show.js
views/addShows_addExistingShow.mako

Fix for https://github.com/pymedusa/Medusa/issues/3529
This change:
- adds anime option
-  fixes the dialog for 'you must select a show to continue' when adding an exising show with prompt for settings

Show anime checkbox when adding existing shows

---

medusa/server/web/manage/handler.py

Fix typo in the image image_update summary.

---

medusa/init/filesystem.py

Fixes https://github.com/pymedusa/Medusa/issues/3567

Only apply UTF-8 monkey patch when necessary

---

medusa/init/filesystem.py

- [ x ] PR is based on the DEVELOP branch
- [ x ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ x ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
Fixes openwrt / entware / synology issues with monkeypatching.
Deeper explanation: after printing the `f, args, type(args[0]), args[0].__type__` in the `patch_output` wrapper. 
```
<built-in function unlink> (u'/tmp/JhfhpO',) <type 'unicode'> <type 'unicode'>
<built-in function unlink> (<closed file '<fdopen>', mode 'w+b' at 0x244f600>, u'/tmp/tmpwipQTM') <type 'instance'> tempfile._TemporaryFileWrapper
<built-in function unlink> (<closed file '<fdopen>', mode 'w+b' at 0x2455850>, u'/tmp/tmpMSDo2T') <type 'instance'> …
```

Import tempfile early on to ensure it is monkey patched

---

medusa/init/filesystem.py

No, because hotfix for master.
See https://github.com/pymedusa/Medusa/pull/3619 for the develop version.
Tested by me on x64 entware
Tested by Kilay on Synology [here](https://github.com/SynoCommunity/spksrc/issues/3111#issuecomment-358290028)

HOTFIX - medusa fails to start with recent python 2.7.14 version (openwrt, synology)

---

medusa/init/filesystem.py

Add is_rarfile() to patched functions. Fixes #3222

---

medusa/notifiers/slack.py

I added a slack_url field so that the medusa Icon shows up in slack instead of the generic webhook icon.

Added Medusa Icon to Slack Notifications

---

medusa/providers/torrent/html/torrent9.py

Update torrent9 URL

---

medusa/server/web/home/handler.py

Happens when changing show to e.g. Anime and have old cache entries without indexer column.
I think it's okay to delete the cache entries just with the series id for this.
@p0psicles

Delete cache entry with series_id to support entries without indexer

---

medusa/providers/torrent/html/archetorrent.py

They added a link so the index was broken

Fix ArcheTorrent

---

medusa/server/api/v2/auth.py

Switched from JWT to JSON for content-type.
Removed unneeded token fields and moved the jwt to a field called token in the auth response.
Fixes https://github.com/pymedusa/Medusa/issues/3725

Fix apiv2 auth

---

medusa/trakt_checker.py

Fix exception when deleting a tvmaze show, with trakt enabled.

---

.travis.yml
dredd/api-description.yml
dredd/dredd.yml
package.json

Try to enable API tests

---

themes-default/legacy/views/config_general.mako
themes-default/slim/views/config_general.mako
themes/dark/templates/config_general.mako
themes/legacy/templates/config_general.mako
themes/light/templates/config_general.mako

This PR fix the inability to see all branches when using a git token instead of user/pass in the General Configuration page.

Fix branches missing in list when using git token in General Configuration

---

medusa/__main__.py

This PR bypass the git_remote_url validation when app.developer=1. This allow the usage of a forked repo for development.

Fix to allow dev to use triangular workflow

---

medusa/cache.py
medusa/providers/torrent/html/torrent9.py
tests/providers/torrent/torrent9/torrent9_test.yaml

Update Torrent9 domain, improve search query

---

medusa/version_checker.py

This PR fix #3779:
- Removed the if for app.git_auth_type as it is not needed.
- Removed the if for app.developer as both URL should point to the same location.

Fix git origin.remote.pushurl invalid when using git_token

---

medusa/__main__.py
medusa/clients/torrent/generic.py
medusa/config.py
medusa/server/web/config/search.py
medusa/torrent_checker.py

This PR fix an issue with torrent_checker not starting/stopping properly after enabling it in the config and at startup.
Also added remove_ratio_reached() and remove_torrent() in generic.py as they should be a requirement for torrent_checker.py
Replaced the log debug in torrent_checker.py to logger.exception as I think remove_ratio_reached() should handle it's own exception and anything else should constitute an error.

Fix torrent_checker scheduler not working properly

---

medusa/name_parser/parser.py

indexer mismatch.
E.g: Cardcaptor Sakura Clear Card - thexem S02, thetvdb S04

Fix some anime shows not returning any results because of xem and

---

medusa/show/recommendations/anidb.py
medusa/show/recommendations/recommended.py

Lazy load the anidb (simpleanidb) object on module level.

---

runscripts/init.systemd

Summary: Make sure the medusa service is started after the network becomes available.
The current (default) systemd startup options will fire up medusa before the network becomes available.  This is fine if web_host is is set to 0.0.0.0, but if its set to the address of eno1/eth0 (eg, 192.168.0.254) then medusa will immediately die with the following error.
MAIN :: [ccbc0ce] Starting Medusa [master] using u'/opt/medusa/config.ini'
TORNADO :: [ccbc0ce] Starting Medusa on http://192.168.0.254:8081/
TORNADO :: [ccbc0ce] Could not start the web server on port 8081, already in use!
The error above is actually incorrect, which needs to be fixed as well.  The port 8081 is available, but the address of 192.168.0.254 is not as medusa tried to start before network.target.
This fix should ensure …

Fix systemd startup

---

medusa/metadata/kodi_12plus.py

Needed because tmdb stores the runtime as int.

Parse runtime (int) to str.

---

themes-default/slim/views/404.mako
themes-default/slim/views/500.mako
themes-default/slim/views/partials/home/poster.mako
themes-default/slim/views/partials/home/simple.mako
themes-default/slim/views/partials/home/small.mako
themes/dark/templates/404.mako
themes/dark/templates/500.mako
themes/dark/templates/partials/home/poster.mako
themes/dark/templates/partials/home/simple.mako
themes/dark/templates/partials/home/small.mako
themes/light/templates/404.mako
themes/light/templates/500.mako
themes/light/templates/partials/home/poster.mako
themes/light/templates/partials/home/simple.mako
themes/light/templates/partials/home/small.mako

Fixes #3892 and some character escaping issues

Template fixes

---

medusa/__main__.py
medusa/config.py

This is one way to solve the issue (tested, working).
Though, it may be a bit confusing to see other encrypted config entries without the `encrypted=True`.
In my mind - it's either this fix or changing the entry name to `git_token_password`, which looks weird.
(Note: Adding `token` as a keyword for encryption like `password` would cause a bigger change)
Your thoughts?
Fixes #3895

Fix Git token re-encryption

---

themes-default/legacy/views/manage_backlogOverview.mako
themes-default/slim/views/manage_backlogOverview.mako
themes/dark/templates/manage_backlogOverview.mako
themes/legacy/templates/manage_backlogOverview.mako
themes/light/templates/manage_backlogOverview.mako

Fixes #3928 (for legacy themes as well)

Fix 'Edit Show' link in Backlog Overview

---

medusa/providers/torrent/json/torrentday.py

The `t.json` endpoint doesn't return the `download-multiplier` key for items that isn't freeleech.

[Torrentday] The `download-multiplier` key is optional

---

medusa/search/manual.py

Update thread name with provider name while processing cached results from the database (for manual search). In the future this might help determine issues with cached results more easily (like the issue of timezone-naive/null `pub_date`s discussed on Slack)

Update thread name while processing cached results from DB

---

medusa/tv/episode.py

`https://localhost:8081/api/v2/series/tvdb12345?api_key=xxx`
```
File "C:\Medusa\ext\tornado\web.py", line 1541, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "C:\Medusa\medusa\server\api\v2\series.py", line 60, in get
data = series.to_json(detailed=detailed)
File "C:\Medusa\medusa\tv\series.py", line 2050, in to_json
groupby([ep.to_json() for ep in episodes], lambda item: item['season'])]
File "C:\Medusa\medusa\tv\episode.py", line 1098, in to_json
data['wantedQualities'] = [ep.identifier() for ep in self.related_episodes]
TypeError: 'unicode' object is not callable
```

Fix Error in Episode.to_json function

---

medusa/providers/torrent/html/hebits.py

When only one result appeared in the search it was not parsing it.
Tiny fix.

Fixing issue of no matches showing when only one result available (hebits)

---

medusa/logger/__init__.py
medusa/server/web/core/base.py
tests/test_logger.py

- Changes `ThreadPoolExecutor-%d_%d` back to `Thread_%d`
This was changed in the recently updated [`[concurrent.]futures` package](https://github.com/agronholm/pythonfutures/commit/e8543e620d87f41f78751b4285a3f1af06023a62).
- Update log filter accordingly.
- **This is an optional change** - Remove `cpu_count()`
There is no need for this, and it also might make the server go slower, as there would only be as many threads as CPU cores on the machine.
Default value is cores times 5, as can be seen here: https://github.com/pymedusa/Medusa/blob/d976ae6b9665bd619ba7ad957221389c82266728/ext/concurrent/futures/thread.py#L106-L109

Fix thread names and up thread count

---

medusa/torrent_checker.py

Fixes:
```
2018-04-12 17:33:37 ERROR    TORRENTCHECKER :: [204cf56] Exception while checking torrent status.
File "/home/osmc/Medusa/medusa/torrent_checker.py", line 43, in run
client.remove_ratio_reached()
File "/home/osmc/Medusa/medusa/clients/torrent/transmission_client.py", line 313, in remove_ratio_reached
if not self._request(method='post', data=post_data):
File "/home/osmc/Medusa/medusa/clients/torrent/generic.py", line 60, in _request
self._get_auth()
File "/home/osmc/Medusa/medusa/clients/torrent/transmission_client.py", line 65, in _get_auth
verify=app.TORRENT_VERIFY_CERT)
File "/home/osmc/Medusa/ext/requests/sessions.py", line 555, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File …
```

Torrent Checker: Show warning when connection error

---

lib/tmdbsimple/__init__.py
lib/tmdbsimple/account.py
lib/tmdbsimple/base.py
lib/tmdbsimple/changes.py
lib/tmdbsimple/configuration.py
lib/tmdbsimple/discover.py
lib/tmdbsimple/find.py
lib/tmdbsimple/genres.py
lib/tmdbsimple/movies.py
lib/tmdbsimple/people.py
lib/tmdbsimple/search.py
lib/tmdbsimple/tv.py
medusa/indexers/tmdb/tmdb.py

- Updated `tmdbsimple` to version 2.2.0 for `TV(<id>).content_ratings()` (don't worry @p0psicles, I noticed the function you re-added :wink: )
- Fixed shows from TMDB not saving `tvshow.nfo` and `<episode>.nfo` properly
Fixes #4013 @duramato 
[(explanation)](https://github.com/pymedusa/Medusa/pull/4026#issuecomment-381434390)
Fixes #4022

Fix #4013, #4022 TMDB metadata errors (TypeError, ZeroDivisionError)

---

themes-default/slim/views/manage_massEdit.mako
themes-default/slim/views/vue-components/quality-chooser.mako
themes/dark/templates/manage_massEdit.mako
themes/dark/templates/vue-components/quality-chooser.mako
themes/light/templates/manage_massEdit.mako
themes/light/templates/vue-components/quality-chooser.mako

As suggested on Slack.
For the current sceduled release.
This is basically restoring a functionality that's available in current master, and I implemented it in a wrong way when I converted the page to Vue.
**Always** show "Keep" option for quality chooser on **mass edit page**
If the qualities of the edited shows are the same, it will still select the correct quality.
But, you get the option to just select "Keep".
So if you changed a bunch of options including the quality, then changed your mind before submitting the form, you don't have to remember what quality was selected, or refresh the page.

Always show "Keep" option for quality chooser on mass edit page

---

medusa/nzb_splitter.py
medusa/providers/generic_provider.py
medusa/search/core.py

- Never split torrent files on NZB providers, hopefully fixes #3946 
- Use BraceAdapter logging in nzb_splitter.

Never split torrent files on NZB providers. Fix #3946

---

medusa/db.py
medusa/tv/cache.py

The altered line used to not exist, as can be seen [here](https://github.com/pymedusa/Medusa/commit/18056a265f866fc0352761cccd1777e8287985ae#diff-04bdc0be0e7d1bf798758336637007b6).
As I explained [in this comment](https://github.com/pymedusa/Medusa/issues/4092#issuecomment-383708438), that function should return `None`.
Python methods that exit without a `return <VALUE>` statement, or with just a `return`, return `None`.
The commit above changed that to `False`.
This should fix #4092.

Cache: Fix incorrect return value

---

medusa/exception_handler.py

Oh yeah, THAT happened:
```
>>> import exception_handler
>>> exception_handler.handle(IOError('da!'))
File "<stdin>", line 1, in <module>
File "exception_handler.py", line 24, in handle
logger.exception('{m}Environment error: {error_msg}', m=m, error_msg=err)
File "C:\Python27\lib\logging\__init__.py", line 1200, in exception
self.error(msg, *args, **kwargs)
File "C:\Python27\lib\logging\__init__.py", line 1193, in error
self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'm'
```

Fix exception_handler exception

---

medusa/providers/nzb/newznab.py
medusa/providers/torrent/torznab/torznab.py

Fixes:
```
2018-04-25 17:15:48 DEBUG    SEARCHQUEUE-BACKLOG-80748 :: [NZBGeek] :: [c3e7e58] Traceback (most recent call last):
File "C:\Medusa\medusa\session\core.py", line 147, in request
timeout=timeout, verify=verify, **kwargs)
File "C:\Medusa\medusa\session\core.py", line 99, in request
**kwargs)
File "C:\Medusa\ext\requests\sessions.py", line 494, in request
prep = self.prepare_request(req)
File "C:\Medusa\ext\requests\sessions.py", line 437, in prepare_request
hooks=merge_hooks(request.hooks, self.hooks),
File "C:\Medusa\ext\requests\models.py", line 305, in prepare
self.prepare_url(url, params)
File "C:\Medusa\ext\requests\models.py", line 423, in prepare_url
enc_params = self._encode_params(params)
File "C:\Medusa\ext\requests\models.py", line 105, in _encode_params
return …
```

Newznab|Torznab: Replace newstr with six.text_type

---

lib/traktor/trakt.py

- Not really a bugfix since we couldn't figure out what the was the actual issue.
Added a check for HTTPError 413, and request + response info for troubleshooting.
- Added the attempt counter to HTTPError 502.
Related to #4090

Traktor: Catch HTTPError 413, log attempt counter

---

medusa/helper/common.py
medusa/providers/nzb/anizb.py
medusa/providers/torrent/html/abnormal.py
medusa/providers/torrent/html/alpharatio.py
medusa/providers/torrent/html/anidex.py
medusa/providers/torrent/html/animebytes.py
medusa/providers/torrent/html/animetorrents.py
medusa/providers/torrent/html/bithdtv.py
medusa/providers/torrent/html/elitetracker.py
medusa/providers/torrent/html/hdspace.py
medusa/providers/torrent/html/hdtorrents.py
medusa/providers/torrent/html/hebits.py
medusa/providers/torrent/html/horriblesubs.py
medusa/providers/torrent/html/iptorrents.py
medusa/providers/torrent/html/morethantv.py
medusa/providers/torrent/html/nebulance.py
medusa/providers/torrent/html/pretome.py
medusa/providers/torrent/html/scenetime.py
medusa/providers/torrent/html/speedcd.py
medusa/providers/torrent/html/tntvillage.py
medusa/providers/torrent/html/torrentbytes.py
medusa/providers/torrent/html/tvchaosuk.py
medusa/providers/torrent/json/bitcannon.py
medusa/providers/torrent/json/xthor.py
medusa/providers/torrent/xml/torrentz2.py

Pretty sure that's the way it's supposed to be?

Providers: Remove Traceback from errors, use log.exception

---

themes-default/slim/views/layouts/main.mako
themes/dark/templates/layouts/main.mako
themes/light/templates/layouts/main.mako

@OmgImAlexis  According to https://router.vuejs.org/en/api/options.html#base we should use a relative path and not the full URL for the router `base`.
Tested and working for both an empty `WEB_ROOT` and a non-empty one.
Notice that I added `/` that will always be there.
@medariox @p0psicles

Fix /config for web root users

---

medusa/providers/nzb/newznab.py

If the provider doesn't have any `(tv)-search params` it should still try to search without them, instead of giving up.

Don't stop newznab search if params are missing. Fixes #4115

---

medusa/clients/torrent/qbittorrent_client.py

Stop errors like:
<pre>
DEBUG    THREAD :: [6148669] POST URL: http://x.x.x.x:xxxx/command/increasePrio [Status: 403]
INFO     THREAD :: [6148669] qbittorrent: Forbidden
<b>ERROR</b>    THREAD :: [6148669] qbittorrent: Unable to set priority for Torrent
</pre>
This will now show:
<pre>
INFO     THREAD :: [6148669] qbittorrent: Forbidden
<b>INFO</b>     THREAD :: [6148669] qbittorrent: Unable to set torrent priority because torrent queueing is disabled in qbittorrent settings.
</pre>
- Related to #4032
- Related to #2686

qBittorent: Don't error when torrent queueing is disabled

---

.codecov.yml

I added Codecov as a Github App so we no longer needed the comment as it'll show in the checks section with travis, etc.

disable codecov comments

---

medusa/providers/generic_provider.py
medusa/session/core.py
medusa/session/handlers.py
medusa/session/hooks.py

**Issue:** `cloudflare` hook not updating session cookies.
**Cause:** `Response` objects have no `session` attribute so a new session is created within the hook.
**Proposed solution:** Replace hook version with a custom "handler" that can receive a session object.
_Why "Help wanted"?_
I have noticed the following function in `medusa/session/hooks.py`. If we can somehow use it on existing code (before this PR) inside the `MedusaSession` class, then it would probably solve the issue with less code changes.
```py
def sessioned(session):
"""Hooks factory to add a session to a response."""
def sessioned_response_hook(response, *args, **kwargs):
"""Return a sessioned response."""
response.session = session
return response
return sessioned_response_hook
```

Fix CloudFlare Bypass

---

medusa/metadata/generic.py
medusa/metadata/mede8er.py
medusa/metadata/media_browser.py
medusa/metadata/tivo.py
medusa/metadata/wdtv.py

Fixes #3297 - mede8er integers in XML
Tested and working (the written XML file is now valid)
---
Found more metadata providers that had the issue and added a fix for them as well:
- MediaBrowser [Emby]
- WDTV
---
Should also fix #4151 - exception if the episode location is empty.

Fix metadata issues

---

medusa/version_checker.py

Preemptively add this so old branch refs get pruned from git.
When we don't do this, it could lead to git erroring because it can't update the ref.
```
CHECKVERSION :: git fetch origin returned : error: cannot lock ref 'refs/remotes/origin/ui/navbar-fixed-icon-width': 'refs/remotes/origin/ui' exists; cannot create 'refs/remotes/origin/ui/navbar-fixed-icon-width'
From https://github.com/org/repo
! [new branch] ui/navbar-fixed-icon-width -> origin/ui/navbar-fixed-icon-width (unable to update local ref)
error: some local refs could not be updated; try running
'git remote prune origin' to remove any old, conflicting branches
CHECKVERSION :: Unable to contact github, can't check for update
```

GitUpdateManager: Always prune when fetching

---

medusa/__main__.py
medusa/themes/base.py

- Fix crash because of an empty theme folder
- Fix valid values for `theme_name` config option

Fix crash because of an empty theme folder

---

medusa/clients/torrent/qbittorrent_client.py

`hash` data key was changed to `hashes`
Fixes #4167

Fix qBittorrent resume/pause command

---

.travis.yml

Example:
https://travis-ci.org/pymedusa/Medusa/builds/376442637#L3845
`flake8` failed, build succeeded.
~Disable it and always run Python tests for now.
Sorry @OmgImAlexis ...~
Replaced it with a better check.
Current build errors are fixed in #4171

Fix failed Python tests not failing build

---

medusa/server/api/v2/internal.py

- Fix for root dirs containing special chars, also fixes possible XSS
- Update the API handler for internal resources
~**Edit:** I realised I should remove the `root_dirs_lower` part, and just use `tuple(root_dirs)`.~

Update internal resources API

---

medusa/issue_submitter.py

- For example:
With "Missing time zone for network: ***" errors, the network names are sometimes too similar and don't open new issues.
`Missing time zone for network: USA Network` vs. `Missing time zone for network: Hub Network`
The diff ratio is: `0.9285714285714286`, while the minimum for matching is `0.9`.
This adds an option to override the ratio for certain error messages.
- Add debug logs to troubleshoot speed issues
Currently we don't know what makes the issue submitter so slow. This might help.

IssueSubmitter: Add option to override title diff ratios

---

medusa/notifiers/emby.py
pytest.ini

- Add support for indexers other than TVDB by using the show's external ids.
(Emby's `/Library/Series/Updated` API only supports TVDB IDs) - Should fix https://github.com/pymedusa/Medusa/issues/4141#issuecomment-388614665
- Use `MedusaSession` instead of `urllib`
- Fix flake8 docstring warnings
- Remove `u` prefix from strings.

Update Emby Notifier

---

themes-default/slim/views/vue-components/app-link.mako
themes/dark/templates/vue-components/app-link.mako
themes/light/templates/vue-components/app-link.mako

- Fixes #4224 
- Fixes an issue when the current location already has a hash in the url. For example click a season jump link, then refresh the page - the hashes in the season jump links are now doubled.

app-link: Fix anonymised webcal and multiple location hashes

---

medusa/indexers/indexer_api.py

The altered piece of code was broken. `initConfig` had duplicate languages, as the default language was never deleted before sorting and adding it again.
I hope the code is clear enough. Basically `'\0'` (null char) is always smaller than `'en'`, `'de'`, etc...

indexerApi.config: Fix sorting

---

ext/imdbpie/__init__.py
ext/imdbpie/auth.py
ext/imdbpie/constants.py
ext/imdbpie/imdbpie.py
medusa/tv/series.py
requirements.txt

Should fix warnings like:
`123456: Error loading IMDb info: Title not found. tt1234567 is a redirection imdb id`
Also fixes a `LookupError` exception raised by `imdbpie` while adding a show.
This caused the builds to fail because adding a show via API v2 returned an internal server error.

Update imdbpie to 5.4.5 + builds failing

---

setup.py

The `gi` package was removed from GitHub and PyPI :man_shrugging:.
This is used by the notifier `libnotify`.
The [PyGObject](https://pypi.org/project/PyGObject) package ([git](https://gitlab.gnome.org/GNOME/pygobject)) might be a good replacement package (looks maintained),
but I don't have any way to test if that works currently.

Fix travis build

---

medusa/server/api/v2/base.py

Currently:
```http
GET http://localhost:8081/api/v2/series?detailed=true&page=1&limit=20
Link:
</api/v2/series?detailed=true&page=1&limit=20&page=2&limit=20>; rel="next",
</api/v2/series?detailed=true&page=1&limit=20&page=2&limit=20>; rel="last",
</api/v2/series?detailed=true&page=1&limit=20&page=1&limit=20>; rel="first"
```
With the proposed fix:
```http
GET http://localhost:8081/api/v2/series?detailed=true&page=1&limit=20
Link:
</api/v2/series?detailed=true&page=2&limit=20>; rel="next",
</api/v2/series?detailed=true&page=2&limit=20>; rel="last",
</api/v2/series?detailed=true&page=1&limit=20>; rel="first"
```
Fixes #3988

Fix #3988 - API v2 pagination links

---

medusa/indexers/tvmaze/tvmaze_api.py

`contentrating` is for the MPAA rating, not user rating

Fix TypeError: cannot serialize 6.9 (type float)

---

medusa/server/web/home/handler.py

Previous logic was:
```py
if all([status in Quality.DOWNLOADED,
ep_obj.status not in snatched_qualities + Quality.DOWNLOADED + [IGNORED],
not os.path.isfile(ep_obj.location)]):
```
(which is not the same)

Fix changing status to Downloaded

---

ext/enzyme/__init__.py
ext/enzyme/mkv.py
ext/enzyme/tests/test_mkv.py
requirements.txt

Update enzyme (use [pymedusa/enzyme](https://github.com/pymedusa/enzyme))
This fixes `enzyme` to use the correct default values from the Matroska format specification.
For example, default language for the subtitle track is English, not None.
Should fix embedded **English** subtitle tracks getting tagged as `undetermined`, because MKVToolNix drops the element if the value is the default value.
Tested using `knowit`, it wasn't working before, and with this fix it does.

Update enzyme - fixes embedded English subs tagged as undetermined

---

medusa/show_queue.py

Possibly caused by metadata that contained an old or invalid series id.
Should fix #3321 [Untested]
TVDB API is REST, so it returns 404 if the show is not found.

Fix IndexerShowNotFound when adding existing shows

---

medusa/providers/torrent/html/hebits.py

Fixes #3935 
I can't test it, but I do know `html5lib` parser can sometimes not work if the html isn't valid.

HeBits: Change BS4 parser to html.parser

---

medusa/logger/__init__.py

[The test](https://github.com/pymedusa/Medusa/blob/8038afb81da63e612242c51003c5d15969c14981/tests/test_logger.py#L343-L357) was failing on Windows.
The function couldn't find the working dir in the exception because of the forward slash.

Fix LogLine.format_to_html on Windows systems

---

medusa/providers/torrent/html/bjshare.py

The url of the provider has been changed after server migration.
From: https://bj-share.me to:https://bj-share.info

Update bjshare.py - the url of the provider has been changed after server migration

---

themes-default/slim/views/config_backuprestore.mako
themes-default/slim/views/config_search.mako
themes-default/slim/views/editShow.mako
themes-default/slim/views/vue-components/file-browser.mako
themes/dark/templates/config_backuprestore.mako
themes/dark/templates/config_search.mako
themes/dark/templates/editShow.mako
themes/dark/templates/vue-components/file-browser.mako
themes/light/templates/config_backuprestore.mako
themes/light/templates/config_search.mako
themes/light/templates/editShow.mako
themes/light/templates/vue-components/file-browser.mako

:heavy_check_mark: ~Should be rebased on develop after merge of #4055~
- Refactors file-browser to handle multiple browsers on the the same page,
and to rely less on jQuery and more on Vue.
- Use file-browser in `config_search.mako` and `config_backuprestore.mako`.
- Fix #4347 - due to faulty Python to JS conversion. Always use `json.dumps`...
- Fix #4355 and more issues in `config_search.mako`.

Refactor file-browser component and use in select pages

---

medusa/providers/torrent/html/yggtorrent.py

new redirection URL has changed from www.yggtorrent.is to ww1.yggtorrent.is
testing change on my 0.2.5 medusa [c65ca26] worked (I used to get a bdecode error previously)

updated YGGtorrent provider for new URL

---

medusa/server/web/home/handler.py

This should prevent the white page error that is caused when we change values in Python then try to render mako templates with the new values (before Python was restarted)
For example:
Last update we changed `Quality.NONE` to `Quality.NA`.
After the update it tried to render `restart.mako` with `Quality.NA`, but it wasn't available yet,
causing `500.mako` to render, which couldn't render because `quality-chooser.mako` imported in `main.mako` was trying to use `Quality.NA`.
This is a temporary solution, but it should be this way anyway.

Render restart page before updating to prevent errors

---

medusa/indexers/tvdbv2/tvdbv2_api.py

@p0psicles seems like it was missing the exception handling altogether?
Fixes #4369

Fix #4369 - exception when getting TVDB actors

---

medusa/github_client.py
medusa/issue_submitter.py
tests/test_issue_submitter.py

Found and fixed the cause for the slow speeds in the issue submitter.
The `.pull_request` property is lazy - when you call it, it fetches the information from GitHub.
This solves the issue, plus correctly upping the `per_page` parameter to 100 for all GitHub requests.
Keep in mind it fetches issues and pull requests between now and 6 months ago, maybe it's a bit too much.
But it should be **much** faster now.

Fix issue submitter speed

---

medusa/server/core.py

These two "issues" only happen when `app.WEB_LOG` is true.
- Fix requests getting logged twice
(to the console as `tornado.access` and as the Medusa logger, not to log files).
- Fix API v2 requests resulting in codes >= 400 and below 500 getting logged as warnings.

Fix Tornado request logging

---

medusa/tv/episode.py

Looks like it's working.
I just needs to be tested a little better to make sure it works with different naming schemes.
Fixes #4402

Fix #4402 - Only Absolute Number broken for SxxExx format

---

medusa/indexers/tvdbv2/tvdbv2_api.py

Fixes #4419
The endpoint returns an empty list if no shows were updated in the requested time frame.

TVDB: Fix exception when no updates are returned. Fixes #4419

---

medusa/common.py
medusa/providers/generic_provider.py
medusa/recompiled/tags.py
medusa/tagger/episode.py
tests/test_common.py

1) Renamed `scene_quality` to `quality_from_name` as it is more accurate.
2) The resolution is now enough to determine a quality (without source it defaults to HDTV)
3) Fixed detection of `mpeg` releases
Added detection of Amazon releases
Improved detection of Netflix releases
4) Added tests for `quality_from_name`

Improve detection of quality from filename

---

themes-default/slim/views/config_providers.mako
themes/dark/templates/config_providers.mako
themes/light/templates/config_providers.mako

Wanted to use `from __future__ import division`, but we can't do that in mako templates.
Fixes #4408
@p0psicles

Fix #4408 - Search delay UI bug with fractions

---

.travis.yml
setup.py

PyYAML got updated to a new major version, seems to break `knowit`, and thus the tests.

Fix CI tests

---

themes-default/slim/views/config.mako
themes/dark/templates/config.mako
themes/light/templates/config.mako

It will now show the info even when it's unavailable.
Should be less confusing?

Fix missing Medusa Info on config page

---

medusa/providers/torrent/html/yggtorrent.py
tests/providers/torrent/yggtorrent/yggtorrent_test.yaml

Using a hidden timestamp from the HTML:

Simplify/Improve YggTorrent pubdate parsing

---

medusa/server/api/v2/internal.py
themes-default/slim/views/addShows_newShow.mako
themes/dark/templates/addShows_newShow.mako
themes/light/templates/addShows_newShow.mako

It was using the indexer's name and show id instead of the values of the show added to the library.
Made the `displayShow` link invalid as it pointed to a show that didn't exist in the library.

Fix "already added" link using incorrect indexer and show id

---

medusa/search/proper.py

2 issues here:
- Multi episodes would get propers downloaded over and over
- There was no check to make sure that the existing release wasn't already proper, that means that it kept downloading proper releases over and over (not the same, but e.g. by different groups/name)

Fix proper search downloading multiple propers. Fixes #4495

---

medusa/logger/__init__.py

Fixes non-ASCII characters being decoded using an incorrect encoding on Windows.
Also fixes [one of the logger tests](https://github.com/pymedusa/Medusa/blob/06deabf/tests/test_logger.py#L115) not passing on Windows.
~To be merged **after** 0.2.6.~
I really want to give this as much time as possible.
I've been using this fix for a while now (since June 9th according to the commit date) on Windows, so it should be fine.

Decode log lines from UTF-8 on Windows

---

themes-default/slim/views/vue-components/app-link.mako
themes/dark/templates/vue-components/app-link.mako
themes/light/templates/vue-components/app-link.mako

This will allow us to use Ava tests against this component once https://github.com/pymedusa/Medusa/pull/4374 is merged.
Related https://github.com/pymedusa/Medusa/pull/4519 see https://github.com/pymedusa/Medusa/pull/4526#discussion_r199555416

cleanup app-link for tests

---

CHANGELOG.md
medusa/server/web/__init__.py
medusa/server/web/core/__init__.py
medusa/server/web/core/base.py

- `/ui` is no longer used (not to be confused with `/ws/ui`.
- Add 404/500 fallback routes for Vue error pages (500 error isn't on the router yet)

Remove `/ui/` route, add fallback 404/500

---

themes-default/slim/views/layouts/main.mako
themes-default/slim/views/vue-components/app-link.mako
themes/dark/templates/layouts/main.mako
themes/dark/templates/vue-components/app-link.mako
themes/light/templates/layouts/main.mako
themes/light/templates/vue-components/app-link.mako

This is a temporary fix, just to get develop working again.
This fixes:
- Everything related to links with event handlers from jQuery and other libraries other than Vue.
So confirmation popups, everything still using the separate javascript files.
- Images on displayShow

Fix event handlers by restoring app-link to a mako file

---

CHANGELOG.md
medusa/notifiers/emby.py

I made a mistake in #4199, the POST body needs to be a JSON encoded string.
Fixes #4576

Fix Emby test notification

---

themes-default/slim/gulpfile.js
themes-default/slim/package.json

@OmgImAlexis 
If we remove the `async`/`await` for the `sync` task, it doesn't work correctly anymore - only syncs the first theme.
I spent 2 hours trying to get it to work with Promises, and couldn't.
I think this has something to do with how `runSequence` works..

Fix gulp sync for now

---

CHANGELOG.md
themes-default/slim/views/displayShow.mako
themes-default/slim/views/layouts/main.mako
themes-default/slim/views/snatchSelection.mako
themes/dark/templates/displayShow.mako
themes/dark/templates/layouts/main.mako
themes/dark/templates/snatchSelection.mako
themes/light/templates/displayShow.mako
themes/light/templates/layouts/main.mako
themes/light/templates/snatchSelection.mako

Fixes #4618.
Also fixes all the other pages that are not ready when the Vue cloak (`v-cloak`) is lowered,
Help & Info for example.
I've also tested what happens if there was a javascript error on the page, and the mask was still lowered.
Just in case, I added the handler to manually remove the mask.

Display a soft "Loading..." mask until page is ready

---

medusa/issue_submitter.py
tests/test_issue_submitter.py

Includes tests
Example: #4611
The gist is really not needed in cases like these.

Don't create a gist if context lines equal error

---

CHANGELOG.md
medusa/notifiers/growl.py
medusa/notifiers/telegram.py

Fix Telegram/Growl notifiers message encodings

---

medusa/providers/torrent/html/bjshare.py

Fix bj-share animes, for some reason Anime EXX stopped being recognized as Absolute format, so changed it to Anime XX. Added boruto as absolute format, it also started having the wrong season on the tracker

Fix bj-share animes

---

.travis.yml

`.eggs` is a cache folder for dependencies used by `setup.py`.
It might make Python tests run a bit faster as we don't have to keep downloading and building the same packages with each build job.

Add .eggs to Travis cache

---

.travis.yml

This reverts commit 42cd141ce70515d6c3573aaf93a556976bd3de41 (#4714).
Sorry, this was a bad idea. :man_facepalming: 
If we cache `.eggs`, then the tests might keep using old dependencies instead of downloading the latest version.

Revert "Add .eggs to Travis cache (#4714)"

---

dredd/api-description.yml
medusa/server/api/v2/alias.py
medusa/tv/episode.py
medusa/tv/series.py

Fixes #4633
See: https://github.com/pymedusa/Medusa/issues/4633#issuecomment-408007736 for the explanation.
In short, it affected users with timezones smaller than UTC.
Changelog updated in #4756

Fix API error when an episode airdate is `datetime.date.min`

---

CHANGELOG.md
medusa/app.py
medusa/common.py

I'm still unsure about what we're going to do with the `CHANGELOG.md` file,
but if it stays updated as PRs get merged, it should make the changelog easier to read.
So maybe we just list the changes here, but on release copy them over to [CHANGES.md](https://github.com/pymedusa/medusa.github.io/blob/master/news/CHANGES.md)...

Prepare v0.2.7 release

---

themes-default/slim/package.json
themes-default/slim/yarn.lock

Unused, switched to Vuex (#4668).

Remove puex

---

medusa/providers/torrent/html/yggtorrent.py

It would otherwise show `Unable to connect or login to provider` on the very first login check as well.

Avoid Yggtorrent warning on first auth check

---

themes-default/slim/src/components/login.vue
themes-default/slim/views/layouts/main.mako
themes/dark/assets/js/vendors.js
themes/dark/templates/layouts/main.mako
themes/light/assets/js/vendors.js
themes/light/templates/layouts/main.mako

- Fix config being loaded twice for pages using the main app
- Remove unnecessary code from `login.vue` (Confirmed it's working without it)
- Reorganize `main.mako`
- Fix mixin scope to only the root Vue
This fixes the `pageComponent` and `globalLoading` data being added to **every** component.
It will now only add them to the root instance.

Fix config being loaded twice for pages using the main app

---

CHANGELOG.md
medusa/tv/series.py

Use indexer ID in get_episode(). Fixes #4857

---

medusa/name_parser/parser.py
medusa/scene_exceptions.py

When parsing an episode like Lupin III/Season 02/S2E22.mkv, it will parse it in two goes.
First attempt parsing `Lupin III/Season 02/S2E22.mkv` and then `S2E22.mkv`. The second parse, cannot resolve it to a series name.
And therefor the scene_exceptions call resulted in an exception.
Should fix #4941
@medariox can you double check the solution?
Alternative could be changing to
`scene_season = scene_exceptions.get_scene_exceptions_by_name(result.series_name or result.series.name)[0][1]`
in parser.py:L189

Only check for scene_exception when series_name is known.

---

themes-default/slim/package.json
themes-default/slim/webpack.config.js
themes-default/slim/yarn.lock

Related: #4956, #4954
* FileManagerPlugin runs **after** the bundle has finished (on `--watch` as well).
* CopyWebpackPlugin runs **as the bundle is generated**, so it copies the old files.
It's fine for the files from `./static` and `./views` as they are not created using Webpack.
Note that when using `--watch`, this plugin will only clean the folder on the initial build.
(I initially thought this was the plugin that caused an issue, but it wasn't).

Use FileManagerPlugin to copy bundled assets

---

CHANGELOG.md
themes-default/slim/static/js/config/notifications.js
themes/dark/assets/js/config/notifications.js
themes/light/assets/js/config/notifications.js

Test email notification is not working. I tested with 2 email providers `inbox.ru` and `gmail.com`
Both email provides requires SSL for SMTP connections. I'm always getting this message:
```
ERROR: SMTP AUTH extension not supported by server.
```
I found that the problem is in the UI, the TLS checkbox is always sent as 0.

Fix test email notification with TLS

---

medusa/tv/series.py

Reported on Slack
```
File "/home/pi/Medusa/ext/tornado/web.py", line 1590, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/home/pi/Medusa/medusa/server/api/v2/series.py", line 52, in get
data = [s.to_json(detailed=detailed) for s in Series.find_series(predicate=filter_series)]
File "/home/pi/Medusa/medusa/tv/series.py", line 2000, in to_json
data['countries'] = self.countries  # e.g. ['ITALY', 'FRANCE']
File "/home/pi/Medusa/medusa/tv/series.py", line 514, in countries
return [v for v in self.imdb_info.get('countries', '').split('|') if v]
AttributeError: 'NoneType' object has no attribute 'split'
```

Ensure show IMDB info is never None

---

themes-default/slim/views/displayShow.mako
themes/dark/templates/displayShow.mako
themes/light/templates/displayShow.mako

Fixes:
> #4888 introduced a bug on displayShow, the `Column Selector` dropdown doesn't have the `Scene` column in it and it's causing incorrect columns to be hidden

Re-add removed Scene column header

---

medusa/name_parser/guessit_parser.py

Before:
```
? Law.and.Order.S18E18.HDTV.XviD-E7
: title: Law and Order
season: 18
episode: [18, 7]
source: HDTV
video_codec: Xvid
type: episode
parsing_time: 0.281111001968
```
After:
```
guessit "Law.and.Order.S18E18.HDTV.XviD-E7" -G "E7"
For: Law.and.Order.S18E18.HDTV.XviD-E7
GuessIt found: {
"title": "Law and Order",
"season": 18,
"episode": 18,
"source": "HDTV",
"video_codec": "Xvid",
"release_group": "E7",
"type": "episode"
}
```
Other examples:
```
guessit "Bones.S03E12.REPACK.HDTV.XviD-E7" -G "E7"
For: Bones.S03E12.REPACK.HDTV.XviD-E7
GuessIt found: {
"title": "Bones",
"season": 3,
"episode": 12,
"other": "Proper",
"proper_count": 1,
"source": "HDTV",
"video_codec": "Xvid",
"release_group": "E7",
"type": "episode"
}
```
And with filename
```
For: e7-bones.s03e12.720p-x264.mkv …
```

Fix Scene release group E7 match confused with episode.

---

CHANGELOG.md
themes-default/slim/views/addShows_recommended.mako
themes-default/slim/views/home.mako
themes-default/slim/views/status.mako
themes/dark/templates/addShows_recommended.mako
themes/dark/templates/home.mako
themes/dark/templates/status.mako
themes/light/templates/addShows_recommended.mako
themes/light/templates/home.mako
themes/light/templates/status.mako

jQuery UI tabs widget was fetching the whole page using AJAX.
We should wait a little more to see if more bugs pop up, if they do we should probably cherry pick fixes into a hotfix release.

Fix UI bugs

---

CHANGELOG.md
medusa/providers/torrent/html/speedcd.py

Fix Speedcd parsing and add pubdate

---

medusa/databases/cache_db.py
medusa/databases/failed_db.py
medusa/databases/main_db.py
medusa/db.py

Fix database always trying to update

---

medusa/notifiers/__init__.py
medusa/notifiers/boxcar2.py
medusa/notifiers/emailnotify.py
medusa/notifiers/freemobile.py
medusa/notifiers/growl.py
medusa/notifiers/kodi.py
medusa/notifiers/libnotify.py
medusa/notifiers/plex.py
medusa/notifiers/prowl.py
medusa/notifiers/pushalot.py
medusa/notifiers/pushbullet.py
medusa/notifiers/pushover.py
medusa/notifiers/slack.py
medusa/notifiers/synology_notifier.py
medusa/notifiers/telegram.py
medusa/notifiers/tweet.py
medusa/post_processor.py
medusa/tv/episode.py

This prepares the terrain for tackling a proper Discord notifier. 
Sending the episode object allows to use embeds in the Discord notifier, as we'll have easy access to season, episode number, quality and other information, and will probably allow us to make other notifiers nicer in the future as well.

Send episode object to download and subtitle notifications

---

medusa/__main__.py

Fixed typo in __main__.py that was preventing join notifier settings being maintained after restart.

Bugfix join notifier

---

CHANGELOG.md
medusa/notifiers/growl.py

Fixes #5683
Reverts the change made in #4657, because the encode functions are not string encode functions...
https://github.com/pymedusa/Medusa/blob/0c0a73583452f988c518adeafa75ee1f17987bdf/ext/gntp/core.py#L354
https://github.com/pymedusa/Medusa/blob/0c0a73583452f988c518adeafa75ee1f17987bdf/ext/gntp/core.py#L257

Fix Growl registration error

---

medusa/providers/torrent/html/anidex.py

Anidex has a Live Action category, this allows the provider to make use of it by adapting the RSS URL depending if the series has the is_anime flag or not.

Enable non-anime search on Anidex

---

CHANGELOG.md
medusa/providers/torrent/rss/nyaa.py

Nyaa has a Live Action category, this allows the provider to make use of it by adapting the RSS URL depending if the series has the is_anime flag or not.

Enable non-anime search on Nyaa

---

.codecov.yml
.travis.yml
dredd/dredd_hook.py
tox.ini

Runs pytest tests on Python 3.6.
Dredd tests disabled for now, because they take too long (13 minutes ... to fail).
Re enable them when Medusa can *actually* start on Python 3.

CI: Test on Python 3.6

---

CHANGELOG.md
medusa/subtitles.py
tests/test_subtitles.py

Change perfect match in order to make it less strict as discussed in #5729.

Perfect match for subtitles is too strict

---

medusa/providers/generic_provider.py
medusa/search/core.py
medusa/tv/cache.py

fix #5582 
ASIS: In each backlog for every episode search, we check the cache if we get anything back. If so, we dont bother searching the provider. This makes the searching process heavily dependent on the Daily/RSS search.
With this change, we also check if the results from cache, include any candidates, where we also check quality, required words, release groups, etc.
If the results do not have any candidates, we start a search for the provider.

Check cache for candidates when searching using backlog search.

---

medusa/server/api/v1/core.py
medusa/updater/version_checker.py

Fix deprecated get_newest_commit_hash() reference. Fixes #6081

---

medusa/notifiers/telegram.py

Fix trying to use error.response while None for Telegram. Fixes #6065

---

themes-default/slim/package.json
themes-default/slim/yarn.lock

Removed packages:
- `esm`
- `@babel/register`
- `@babel/polyfill`
`ava` tests were failing because of the `esm` entry in ava's `require` config (something must have changed in `ava` recently)
and tests seem to be working just fine without both `babel` packages now.

Remove esm, @babel/register and @babel/polyfill

---

medusa/__main__.py

When running inside a Docker container with the `--user` Docker run option,
username might not exist. See: https://docs.docker.com/engine/reference/run/#user.
Fallback on the uid in this case.

Fix username retrieval inside Docker container

---

medusa/providers/torrent/html/tntvillage.py

For some reason right now there are two "showrelease_tb" classes in the page, so maybe it's better to select the one with a meaningful <td> label.
- [X ] PR is based on the DEVELOP branch
- [X ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fix TNTVillage search

---

lib/unrar2/windows.py

Don't enable `faulthandler` if running `pythonw`

---

CHANGELOG.md
medusa/notifiers/emailnotify.py
tests/notifiers/test_emailnotify.py

Fixes #6526 
It seems like I made a mistake when I wrote the parser (#4450).
`%AD` uses spaces, not dashes:
https://github.com/pymedusa/Medusa/blob/532abfa8fb462fd1aa31ebe0cd64e828abb2104a/medusa/tv/episode.py#L1542-L1545
```py
from medusa.notifiers.emailnotify import Notifier
Notifier._parse_name('Jeopardy! - 2019 04 15 - Returning Champion Vs. , show # 7971 - 720p HDTV')
{'show': 'Jeopardy!', 'episode': '2019 04 15 - Returning Champion Vs. , show # 7971 - 720p HDTV'}
from medusa.notifiers.emailnotify import Notifier
Notifier._parse_name('Jeopardy! - 2019 04 15 - Returning Champion Vs. , show # 7971 - 720p HDTV')
{'show': 'Jeopardy!', 'ep_id': '2019 04 15', 'episode': 'Returning Champion Vs. , show # 7971 - 720p HDTV'}
```

Fix email notifier name parser. Fixes #6526

---

CHANGELOG.md
lib/readme.md
lib/send2trash/__init__.py
lib/send2trash/compat.py
lib/send2trash/exceptions.py
lib/send2trash/plat_gio.py
lib/send2trash/plat_osx.py
lib/send2trash/plat_other.py
lib/send2trash/plat_win.py

- Update to `send2trash` version `1.5.0` to fix Python 3.6+ bug (https://github.com/hsoft/send2trash/pull/17)
- Apply https://github.com/hsoft/send2trash/pull/33 (to fix a bug in the current version)

Fix sending to trash not working on Python 3.6+

---

medusa/providers/torrent/torrent_provider.py

Change get_redirect_url() to retrieve the last redirect URL. Fixes #6610

---

CHANGELOG.md
medusa/providers/torrent/html/elitetracker.py

Thanks to @jbnitro for providing access to the provider.

Fix Elite-Tracker exception when no result is returned

---

CHANGELOG.md
medusa/server/api/v2/auth.py
medusa/server/api/v2/base.py
tests/apiv2/test_auth.py

Fixes #5425, added 2 small tests for that
Fixes RESTful `HTTPError`s causing real exceptions.

Fix API v2 exception on incorrect API key. Fixes #5425

---

CHANGELOG.md
medusa/logger/__init__.py

Newznab used to be a long string (`NEWZNAB_DATA`), and didn't have actual config sections, but that's changed now (#2970).
So now when `newznab`/`torznab` providers and loaded, the API key gets added to the censored items list.
The other reason for removing this is because the pattern isn't very accurate and can cause issues with logs.
For example, I noticed this with a log from `tornado`: https://regex101.com/r/09dy7L/3
You can see the different variations in which `apikey` is sometimes first, sometimes last, sometimes the only parameter,
And whatever is matched as "Group 2" (in red), will is replaced with asterisks (\*)

Remove old regex pattern from `CensoredFormatter`

---

medusa/server/api/v2/base.py
medusa/server/api/v2/series.py

- Log exceptions regardless of `app.WEB_LOG`
- Fix `/api/v2/series` not documented to have the `POST` method implemented

Fix 2 small mistakes in APIv2

---

medusa/issue_submitter.py
tests/conftest.py
tests/test_issue_submitter.py

Should fix:
> @sharkykh if it's closed as a dupe is there any way we can get the comment added to the original instead of the newer issue? Do we maybe need to lock the dupes so it'll try the old one?
>>_Originally posted by **OmgImAlexis** in https://github.com/pymedusa/Medusa/issues/4080#issuecomment-404773126_
>@sharkykh would it be worth the effort to merge these errors into a single one for the submitter?
>>_Originally posted by **OmgImAlexis** in https://github.com/pymedusa/Medusa/issues/5146#issuecomment-419632111_
I added this to the tests, but didn't actually try to submit an issue. The test seems good enough.

IssueSubmitter: Ignore issues marked as duplicates

---

CHANGELOG.md
themes-default/slim/views/home.mako
themes/dark/templates/home.mako
themes/light/templates/home.mako

Should improve the performance of the home page by at least 50%.
Was bugged since v0.2.9
Fixes #5311

Fix home page slowdown - layout imported twice

---

CHANGELOG.md
lib/pymediainfo/__init__.py
lib/readme.md

Downgrade pymediainfo to v3.2.1. Fixes #6794 #6793 #6789

---

CHANGELOG.md
medusa/providers/torrent/torrent_provider.py

Use alternative method to get the redirect URL for Jackett. Fixes #6826

---

CHANGELOG.md
medusa/app.py

This only occurred on fresh installs where the config hadn't been saved yet.
There is no reason to keep the allowed extensions as set (and they are converted to list after the first config save anyway).

Fix APIv2 exception while serializing allowed extensions to JSON

---

CHANGELOG.md
medusa/notifiers/freemobile.py

Fix freemobile notifier

---

CHANGELOG.md
medusa/server/api/v2/base.py
medusa/server/api/v2/log.py

**The test:**
`raise Exception('test')` in [`medusa/server/api/v2/log.py @ LogHandler # get`](https://github.com/pymedusa/Medusa/blob/bd55cbeeb971f1668344e346e0ac85793ababde3/medusa/server/api/v2/log.py#L91)
**Before:**
```python-traceback
File "c:\Dev\Medusa\ext\tornado\web.py", line 1592, in _execute
result = yield result
File "c:\Dev\Medusa\ext\tornado\gen.py", line 1133, in run
value = future.result()
File "c:\Dev\Medusa\ext\tornado\concurrent.py", line 261, in result
raise_exc_info(self._exc_info)
File "c:\Dev\Medusa\ext\tornado\gen.py", line 1141, in run
yielded = self.gen.throw(*exc_info)
File "c:\Dev\Medusa\medusa\server\api\v2\base.py", line 99, in async_call
content = yield IOLoop.current().run_in_executor(executor, prepared)
File …
```

API v2 fixes

---

medusa/logger/__init__.py
tests/test_logger.py

Fixes issue titles such as: #3575
`[APP SUBMITTED]: ====================================================================`
to be the real last line of the stack trace, for example:
`ValueError: list.remove(x): x not in list`
I realize this is specific to Guessit, but I don't know if it's **too** specific.
Anyway I can't think of a more dynamic solution to this problem.

Fix Guessit issue titles

---

themes-default/slim/.eslintrc.js
themes-default/slim/package.json
themes-default/slim/yarn.lock

- Enable [`vue/html-quotes`](https://eslint.vuejs.org/rules/html-quotes.html) (require double quotes in SFC templates)
- Add simple component not registered lint check:
In SFCs it will raise an error if you try to use a component in the template without importing and registering it in `components: { ... }`. [Dynamic components are not yet supported.](https://github.com/sharkykh/eslint-plugin-vue-extra/issues/1)
```vue
<template>
<router-link to="home/">Home</router-link>
<app-link href="home/">Home</app-link>
<component is="app-link">Home</component>
</template>
<script>
export default {
name: 'app',
};
</script>
```

Add ESLint rules

---

medusa/themes/base.py

Found a note from some time ago:
```
// medusa_py3_warnings.txt
C:\Github\Medusa-Py3\medusa\themes\base.py:73: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Github\\Medusa-Py3\\themes\\dark\\package.json' mode='r' encoding='cp1255'>
package_json = json.load(open(os.path.join(theme_path, 'package.json')))
C:\Github\Medusa-Py3\medusa\themes\base.py:45: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Github\\Medusa-Py3\\themes\\dark\\package.json' mode='r' encoding='cp1255'>
package_json = json.load(open(os.path.join(theme_path, 'package.json')))
C:\Github\Medusa-Py3\medusa\themes\base.py:73: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Github\\Medusa-Py3\\themes\\light\\package.json' mode='r' encoding='cp1255'>
package_json = …
```

Fix open file handles

---

themes-default/slim/views/displayShow.mako
themes/dark/templates/displayShow.mako
themes/light/templates/displayShow.mako

DisplayShow was broken with py3. When app.DOWNLOAD_URL was used. Guess nobody uses that feature.

Fix loading displayShow using python3 when app.DOWNLOAD_URL is used

---

CHANGELOG.md
medusa/notifiers/plex.py
medusa/server/web/home/handler.py

Fix testing plex media server (PMS)

---

medusa/providers/torrent/xml/torrentz2.py

Fixes https://github.com/pymedusa/Medusa/issues/7077

Fix Torrentz2 size parsing confusing GB with MB

---

CHANGELOG.md
medusa/tv/episode.py

Reset dirty flag when changes to episodes are made

---

CHANGELOG.md
medusa/providers/torrent/json/xthor.py

Fixes https://github.com/pymedusa/Medusa/issues/6870

Fix snatching for Xthor provider with Python 3

---

CHANGELOG.md
medusa/providers/torrent/html/btdb.py
medusa/providers/torrent/json/xthor.py

Fixes https://github.com/pymedusa/Medusa/issues/7272

Fix BTDB manual search & update Xthor domain

---

CHANGELOG.md
medusa/classes.py
medusa/databases/cache_db.py
medusa/providers/generic_provider.py
medusa/providers/nzb/binsearch.py
medusa/providers/torrent/torznab/torznab.py
medusa/tv/cache.py

Currently by default use the url for the identifier. In future this can be overwritten per provider.
NOTE! **This change will remove all provider cache tables, you will lose your cache**
This could in the future fix providers like jacket and binsearch #7304

Add field `identfier` to provider cache tables.

---

runscripts/init.debian
runscripts/init.fedora
runscripts/init.freebsd
runscripts/init.gentoo
runscripts/init.systemd
runscripts/init.ubuntu

This PR attempts to close #6892. Instead of hardcoding a specific version of /usr/bin/python3.x, I used the generic /usr/bin/python3. I have only tested this with systemd using OSMC, but the changes seemed minimal enough. Used the wiki as a base for changes made. Feel free to disregard this PR if it isn't up to standards.
I did not touch solaris11 or upstart init scripts as neither made reference to python.

Update Init Scripts to python3

---

CHANGELOG.md
medusa/search/core.py

Likely happens when show is added as non-anime and switched to anime afterwards.
Fixes https://github.com/pymedusa/Medusa/issues/7328 https://github.com/pymedusa/Medusa/issues/5458

Fix exception when release groups aren't available for anime shows

---

runscripts/init.freebsd

On FreeBSD (specifically FreeNAS in this case), changing from Python 2.7 to 3.7 resulted in an issue (#6891) where scheduled tasks would fail to report their status on the "Server Status" page. I determined this to be caused by using the `-d` flag when launching medusa. Removing this flag fixes that issue, but prevents Medusa from launching as a service.
This pull request changes the runscript for FreeBSD to use FreeBSD's included [daemon utility](https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8) to run Medusa instead.
The daemon utility will handle automatically starting Medusa, as well as restarting it when it stops (this means that the "No Restart" setting under `General > Advanced Settings > Advanced Settings` must be used to prevent duplicate processes from starting).
This …

FreeBSD - Run Medusa using the daemon utility

---

medusa/search/backlog.py
medusa/show_queue.py
medusa/system/schedulers.py
medusa/tv/series.py
themes-default/slim/views/status.mako
themes/dark/templates/status.mako
themes/light/templates/status.mako

* In stead of the scheduled search queue.
* Moved _get_segments function to Series class.
fix #7422

addShow: Start backlog search in forced queue, instead scheduled queue.

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Fix guessit parsing episodes with 1 before release group as multi

---

medusa/indexers/tvdbv2/tvdbv2_api.py

It had been removed because theTVDB API was faulty. They fixed it now so we can keep getting the season images.

Bring back code to use season images for TVDB API

---

CHANGELOG.md
medusa/clients/torrent/qbittorrent.py

- https://github.com/pymedusa/Medusa/issues/3134#issuecomment-561970205
- #7473
- #6974
I'll try to figure out a better way to do this in this PR. Hopefully before the hotfix is released.
---
| qBittorrent version | Highest API version |
|---------------------|---------------------|
| v4.2.0 | v2.3.0 |
| v4.0.4 | v17 (v1.17.0) |
| v3.1.12 | v1 (v1.0.0) |

qBittorrent client maintenance

---

medusa/clients/torrent/qbittorrent.py

I forgot that if this command returns a false-y value, it logs an error.
https://github.com/pymedusa/Medusa/blob/29c11f38143d52dbee7ca0067dab22fcc3e90268/medusa/clients/torrent/generic.py#L266-L268
Ref: #7474

Fix missing qBittorrent category/label logs error

---

CHANGELOG.md
medusa/notifiers/emby.py

From #7486
```python-traceback
File "/app/medusa/medusa/server/web/core/base.py", line 251, in async_call
result = function(**kwargs)
File "/app/medusa/medusa/server/web/home/handler.py", line 434, in testEMBY
result = notifiers.emby_notifier.test_notify(unquote_plus(host), emby_apikey)
File "/app/medusa/medusa/notifiers/emby.py", line 80, in test_notify
return self._notify_emby('This is a test notification from Medusa', host, emby_apikey)
File "/app/medusa/medusa/notifiers/emby.py", line 60, in _notify_emby
log.debug('EMBY: HTTP response: {0}', resp.content.replace('\n', ''))
TypeError: a bytes-like object is required, not 'str'
```
Fixes #7339 too, it seems.

Fix Emby notifier error on Python 3

---

CHANGELOG.md
setup.py
themes-default/slim/views/snatchSelection.mako
themes/dark/templates/snatchSelection.mako
themes/light/templates/snatchSelection.mako

- Fixes #7516
- Fix tests - Pin `vcrpy` to `<4.0.0` for Python 2

Fix manual search page release name bug - Fixes #7516

---

medusa/clients/torrent/qbittorrent.py

This is an fix for an bug that was fixed in #4219 and then reintroduced in #7040
The problem happens when there's an torrent with accents in file name, it will not be sent to qbittorrent, as already discussed in the pull request #4219 the filename in the api call is not necessary (tested again in v2 and still work without it) and cause it to fail when there's accents.

Fix for an reintroduced bug: Failed to send torrent to qBittorrent if theres an accent in the file name (#4218)

---

CHANGELOG.md
medusa/clients/torrent/qbittorrent.py

Should fix #7539 (though I'm not 100% sure because there are no logs)
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#increase-torrent-priority

Fix error when torrent queueing is disabled on qBT

---

medusa/__main__.py

Fixes Python 3 showing threads as not alive.

Start threads after daemonization

---

medusa/clients/torrent/deluged.py

The deluge RPC client is not initialized on a deluged API client until after the call to `connect()`, so we need to ensure `connect()` is called to initialize the RPC client and verify the authentication before calling any RPC methods. `move_torrent()` is called on a fresh deluged client from `process_tv.py` without any other previous connection attempt.
The RPC method for moving torrents (`core.move_storage`) also takes a list of torrent IDs instead of a single ID, so pass a list (of one) to the call instead.
This fix has been tested and verified.

Fix deluged move_torrent() when seed location is specified in the configuration

---

medusa/providers/torrent/json/btn.py

Hardly a full rewrite of the provider, but this at least enables proper/repack searches for BTN. Verified this worked with at least the REPACK of the first episode of Star Trek: Picard.

Remove proper strings override for BTN provider

---

medusa/helpers/__init__.py

OpenSSL 1.1.1 requires RSA keys to be >= 2048 bits. Fixes #7562

---

medusa/providers/torrent/torznab/torznab.py

Peers is the combination of both leechers and seeders, the provider was assuming it was the leechers count.

Fix torznab number of leechers

---

CHANGELOG.md
lib/rtorrent/lib/xmlrpc/requests_transport.py
medusa/tv/series.py
tests/legacy/ssl_sni_tests.py

Fixes https://github.com/pymedusa/Medusa/issues/7813

Replace deprecated error.message syntax

---

medusa/providers/__init__.py
medusa/providers/torrent/__init__.py
setup.cfg

Old code didn't work with Python 3.5 for some reason.

Fix dynamic provider import for Python 3.5

---

.travis.yml
CHANGELOG.md
medusa/server/core.py

Run WindowsSelectorEventLoop event loop explicit on windows and py3.

---

CHANGELOG.md
medusa/providers/torrent/html/speedcd.py

Fix speed.cd login

---

medusa/scene_exceptions.py

`dict.values()` is a generator. So it can cause errors when the dict is changed during iteration.
Prevent this by casting to an array, before iterating. Most py2 backwards compatible solution.
Fix for #7947

Fix size changed during iteration.

---

CHANGELOG.md
medusa/scheduler.py

Fixes https://github.com/pymedusa/Medusa/issues/7961

Fix running of Scheduler with specific start time

---

themes-default/slim/package.json
themes-default/slim/yarn.lock

Sorry, this is a better format than the "codeload" url when it comes to `renovate`.
https://docs.npmjs.com/files/package.json#github-urls

Use correct version format for `vue-good-table`

---

medusa/post_processor.py

Show.Name.1x1 was being matched to Show.Name.1x12, Show.Name.1x13, etc.

Fix associated files matching more files than wanted. Fixes #8051

---

medusa/clients/torrent/generic.py
medusa/init/__init__.py
medusa/providers/torrent/rss/rsstorrent.py
medusa/providers/torrent/torrent_provider.py
tests/test_init.py

Fixes #8257 
I specifically made sure this part worked, by using an actual torrent file. Hash matched against https://torrenteditor.com.
https://github.com/pymedusa/Medusa/blob/494fa1ea5fd8267f9f71db24afd71ec685be6a2b/medusa/clients/torrent/generic.py#L206-L208
And I added a test torrent to the tests.

Rework `bencodepy` integration

---

medusa/helpers/utils.py
medusa/tv/series.py

* Add the decorator to Series.prev_airdate.
* Removed conditions for prev_aired that will never trigger.
If you want to play around with the decorator. Place this in a py file.
```python
import functools
from datetime import (datetime, timedelta)
class _TimeCache(object):
"""Cache the result for x hours."""
def __init__(self, func, seconds=3600):
"""Initialize the PlexFallback decorator."""
self.func = func
self.seconds = seconds
self.timer = None
self.cached = None
def __get__(self, obj, objtype):
"""Support instance methods."""
return functools.partial(self.__call__, obj)
def __call__(self, *args, **kwargs):
"""
Return a cached value, if the timer hasn't expired yet.
Fixed the timeout to 1 hour.
"""
if self.timer and self.timer > datetime.now() - timedelta(seconds=self.seconds):
return …
```

Add decorator to cache a method's return value for x seconds.

---

renovate.json

- Limit `dogpile.cache` to `<1`
[Dropped support for Python 2.7 **AND** Python 3.5](https://github.com/sqlalchemy/dogpile.cache/blob/8a2983731190a1f2491ca232eb791cf7b493acd4/docs/build/changelog.rst#L9-L20)
Related to #8299 
- Limit `validators` to `<0.17.0`
[Dropped support for Python 2.7](https://github.com/kvesteri/validators/blob/f441a098655cce2edf94a74b35556b1a17aea135/CHANGES.rst)
Related to #8295

Limit Python dependency versions

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Fixes https://github.com/pymedusa/Medusa/issues/8384

Fix guessit parsing numbered episode titles as multi season

---

medusa/updater/github_updater.py

Catch error for using --set-remote-to on old git installations.

---

CHANGELOG.md
medusa/clients/torrent/generic.py

Fixes #8245
This isn't related to the first fix in any way. `bencode` had nothing to do with it this time 😉

Fix torrent hash from magnet to be unicode

---

medusa/__main__.py
medusa/config.py
medusa/helpers/__init__.py
medusa/process_tv.py
medusa/server/web/config/general.py
tests/test_process_tv.py

decode() bytes for saving into config.ini

---

medusa/show/recommendations/trakt.py

* Caused by a show that does not have a tvdb id mapped.

Fix trakt showing errors.

---

medusa/post_processor.py
medusa/process_tv.py

I believe it is desireable to allow torrent move when process_method is 'copy'. See https://github.com/pymedusa/Medusa/issues/8927

Allow torrent client move when process_method is 'copy'

---

medusa/post_processor.py
medusa/process_tv.py

See https://github.com/pymedusa/Medusa/pull/8936

Allow torrent client move when process_method is 'copy' (2)

---

medusa/name_parser/cache.py
medusa/name_parser/guessit_parser.py
medusa/name_parser/parser.py

First off, I don't have much experience with python nor writing pull requests, so I hope this is according to your standards
guessit is one of the slowest parts of the name parsing. This PR adds a cache for guessit results to improve performance if called repetitive. This happens for example when scheduled post-processing is used.
Normal name parsing already has a cache, however it's only used for successful parses (which makes sense as it also includes db searches). If there are many files in the torrent/nzb download folder which aren't related to medusa (basically any other torrent download) it will take a very long time, as files without a show will cause a parse to be unsuccessful.

Add cache for guessit

---

medusa/server/web/home/handler.py
medusa/tv/series.py

Remove get_scene_exceptions() call from massUpdateShow handler.

---

medusa/providers/torrent/json/animebytes.py

I've seen some releases with an EpCount of 0. This allow season pack
with an EpCount of 0 and show 'unknown' multi episode end instead.

Fix skipping season pack with no EpCount

---

ext/readme.md
ext/trakt/calendar.py
ext/trakt/core.py
medusa/helpers/trakt.py
medusa/show/recommendations/trakt.py
requirements.txt

* Fix newshow and newseason layouts.
Took me a little longer. But I made the changes to pyTrakt in a way that have the highest chance of being accepted.
Tested most of the layouts, inc the Calendar routes.

Fix trakt recommended shows

---

ext/readme.md
ext/tvdbapiv2/rest.py
medusa/indexers/tvmaze/api.py
requirements.txt

Tvmaze api depends on .status_code in.., but does not catch request exceptions.
Therefor the AttributeError.
fix #8848 #8902

Catch attributeerror

---

medusa/providers/torrent/json/animebytes.py

Animebytes caches all their peer numbers, causing new torrents to have zero seeders and leechers. This adds a workaround by manually setting the seeders to one if a torrent is more recent than one hour and has zero seeders and leechers.

Add workaround for animebytes caching issue

---

medusa/name_parser/rules/rules.py

Fix guessit exception when episode initiator is int

---

medusa/queues/generic_queue.py
medusa/server/api/v2/postprocess.py
medusa/server/api/v2/providers.py
medusa/server/core.py

Will add endpoints:
GET: /apiv2/postprocess
GET: /apiv2/postprocess/[identifier]
POST: /apiv2/postprocess (with body params)
example body:
```json
{
"proc_dir": "D:\\pp",
"resource": "",
"process_method": "copy",
"force": true,
"is_priority": true,
"delete_on": true,
"failed": true,
"proc_type": "auto",
"ignore_subs": true
}
```
example POST: `/apiv2/postprocess`
```
{
"status": "success",
"message": "Post process action queued",
"queueItem": {
"identifier": "26c9708f-772d-4a8c-93b9-9ee4d168005c",
"name": "POST-PROCESS",
"priority": 20,
"actionId": 0,
"queueTime": "2021-02-12 14:32:46.653856",
"success": null,
"inProgress": false,
"startTime": null,
"updateTime": "2021-02-12 14:32:46.653856",
"force": false,
"config": {
"path": "D:\\pp",
"info_hash": null,
"resource_name": "",
"force": …
```

Add postprocess apiv2 endpoint

---

medusa/process_tv.py

* Like for example where guessit can't parse a decent show from the proc_dir.
I'm checking if resource_name is passed.
Because if it's not postprocessing a specific resource. And we can only `RETRY` a specific resource. Not a folder with x downloads.

Apply FDH for downloads where the PP fails.

---

medusa/clients/torrent/qbittorrent.py

The cookies where not handled as recommended. As we should let the requests session handle this.
But this is a workaround to this issue: https://github.com/qbittorrent/qBittorrent/issues/14497

Don't empty SID cookie when qbittorrent is not returning any cookies

---

CHANGELOG.md
medusa/clients/torrent/downloadstation.py

Workaround to fix an issue with DS 3.8.16.3566.

---

medusa/__main__.py
medusa/schedulers/episode_updater.py

prev_episode() is not cached.
This fixes an issue where the user starts up medusa and directly after tries to open the home page.
It will be in the process of getting all the prev / next airdates from the startup, and then will again get the prev / next airdates through the api call. Running both can results in db lockups. Which will result in api call timeouts.

Utilize the prev_airdate property in stead of prev_episode()

---

medusa/clients/torrent/deluge.py
medusa/clients/torrent/deluged.py
medusa/clients/torrent/downloadstation.py
medusa/clients/torrent/generic.py
medusa/clients/torrent/qbittorrent.py
medusa/clients/torrent/rtorrent.py
medusa/clients/torrent/transmission.py
medusa/clients/torrent/utorrent.py

* self.get_auth() was called just after self.url = None was set.

Fixed Transmission (and prob others) authentication.

---

CHANGELOG.md
medusa/providers/generic_provider.py
medusa/providers/torrent/json/torrentday.py

* Needed new cookie cf_clearance.

Fix provider torrenday.

---

medusa/providers/torrent/json/animebytes.py

If there isn't a season available, asume it's an absolute numbered ep.

---

CHANGELOG.md
medusa/notifiers/__init__.py
medusa/notifiers/boxcar2.py
medusa/notifiers/discord.py
medusa/notifiers/emailnotify.py
medusa/notifiers/freemobile.py
medusa/notifiers/growl.py
medusa/notifiers/join.py
medusa/notifiers/kodi.py
medusa/notifiers/libnotify.py
medusa/notifiers/nmj.py
medusa/notifiers/nmjv2.py
medusa/notifiers/plex.py
medusa/notifiers/prowl.py
medusa/notifiers/pushalot.py
medusa/notifiers/pushbullet.py
medusa/notifiers/pushover.py
medusa/notifiers/pytivo.py
medusa/notifiers/slack.py
medusa/notifiers/synoindex.py
medusa/notifiers/synology_notifier.py
medusa/notifiers/telegram.py
medusa/notifiers/trakt.py
medusa/notifiers/tweet.py
tests/notifiers/test_emailnotify.py

* Make sure to look up the show by id's, in stead of by name.
fix #9500

Fix email notifications for shows with special cars.

---

CHANGELOG.md
medusa/notifiers/prowl.py

Fix call to _generate_recipients()

---

medusa/clients/torrent/qbittorrent.py

This takes care of cases where torrent sizes may be zero. Which may be when a magnet is queued, and metadata and size has not yet been fetched.
Closes #9608.

Avoid division by zero error

---

medusa/clients/nzb/nzbget.py
medusa/clients/nzb/sab.py
medusa/clients/torrent/deluge.py
medusa/clients/torrent/deluged.py
medusa/clients/torrent/generic.py
medusa/clients/torrent/qbittorrent.py
medusa/clients/torrent/rtorrent.py
medusa/clients/torrent/transmission.py
medusa/clients/torrent/utorrent.py
medusa/helper/exceptions.py
medusa/post_processor.py
medusa/schedulers/download_handler.py
medusa/session/core.py

* This is needed because we want to raise exceptions when a connection error occurs.
The downloadhandler will remove tracked info_hashes when it doesn't get them back from the client. We don't want to untrack info_hash because it doesn't get them back, due to a connection error.

Added "back" exception handling for the download clients.

---

medusa/failed_processor.py
medusa/process_tv.py
medusa/schedulers/download_handler.py

This will fix an issue where the failed processor gets a release name to parse, for which it can't find a valid show/title. As at that time we already know we can't process the file, we just want to RETRY the specific episode/season pack.
Currently a bad release name, can fail in the postprocessor, but then it also can't retry a new ep. Because it doesn't know for which show/ep it needs to retry.
Using the download_handler we always know for which show/ep is being processed, so now we're using that information.

Make the show/season/ep leading and not the release_name for the failedProcessor

---

medusa/server/api/v2/history.py

Group history compact layout results by quality

---

CHANGELOG.md
medusa/helpers/anidb.py
medusa/show/recommendations/imdb.py
medusa/show/recommendations/recommended.py

Handle error where we can't get the imdb details request.

---

medusa/clients/nzb/nzbget.py
medusa/clients/nzb/sab.py
medusa/clients/torrent/deluged.py
medusa/clients/torrent/generic.py
medusa/clients/torrent/rtorrent.py
medusa/schedulers/download_handler.py
medusa/server/web/home/handler.py

Normalize clients test_authentication() results

---

CHANGELOG.md
medusa/process_tv.py
medusa/server/api/v1/core.py
themes-default/slim/src/components/manual-post-process.vue

Always check if folder is empty, even when moved

---

CHANGELOG.md
medusa/clients/torrent/deluge.py

Fix getting daemon version on deluge < 2.x

---

CHANGELOG.md
lib/pytvmaze/endpoints.py
lib/pytvmaze/exceptions.py
lib/pytvmaze/tvmaze.py
medusa/indexers/tvmaze/api.py

Add support for banner and background images to tvmaze

---

CHANGELOG.md
medusa/init/__init__.py
medusa/subtitle_providers/addic7ed.py
themes-default/slim/src/components/config-subtitles.vue
themes-default/slim/src/components/subtitle-search.vue

Fix addic7ed subliminal subtitle provider

---

medusa/__main__.py
medusa/app.py
medusa/notifiers/discord.py
medusa/server/api/v2/config.py
medusa/server/web/home/handler.py
tests/apiv2/test_config.py
themes-default/slim/src/components/config-notifications.vue
themes-default/slim/src/store/modules/config/notifiers/discord.js

Add option to override avatar

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Better rule for removing the wrongfully parsed absolute_episode in a multi part release string.

Fix parsing number for shows, in multipart string

---

medusa/__main__.py
medusa/app.py
medusa/generic_update_queue.py
medusa/server/api/v2/config.py
tests/apiv2/test_config.py
themes-default/slim/src/components/config-general.vue
themes-default/slim/src/store/modules/config/general.js
themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap

Purge cached recommended shows afte x days

---

medusa/__main__.py
medusa/updater/version_checker.py

* Pass in the branch and commit through env variables. Medusa didn't pick up the branch name.
* Fix setting the RUNS_IN_DOCKER flag. So we prevent from updating from within container.

Fix the runs_in_docker flag.

---

medusa/indexers/tmdb/api.py

Fixes #10750
The old query param had no effect. If it actually worked, lots of foreign series would have no posters.
Instead, the new code tries to select an English one. If there's none, any language is used.

Actually use the language filter for TMDB image searches

---

medusa/server/api/v2/config.py
tests/apiv2/test_config.py
themes-default/slim/src/components/add-show-options.vue
themes-default/slim/src/components/config-general.vue
themes-default/slim/src/components/config-post-processing.vue
themes-default/slim/src/components/config-search.vue
themes-default/slim/src/components/display-show.vue
themes-default/slim/src/components/home.vue
themes-default/slim/src/components/irc.vue
themes-default/slim/src/components/recommended.vue
themes-default/slim/src/components/show-header.vue
themes-default/slim/src/store/modules/config/system.js
themes-default/slim/src/store/modules/shows.js
themes-default/slim/test/__fixtures__/common.json

* Fix issue when refreshing the page from another page then /home.
And navigating to /home, would result in an empty page. Shows would have been reset.

Fix loading shows from local storage.

---

CHANGELOG.md
medusa/search/core.py
medusa/search/queue.py
medusa/tv/episode.py
themes-default/slim/src/store/index.js
themes-default/slim/src/store/modules/shows.js

* Improved auto UI updating when searching / snatching.

Auto change status to Wanted, when starting a forced search for an episode

---

CHANGELOG.md
medusa/clients/torrent/deluge.py
medusa/clients/torrent/deluged.py
medusa/schedulers/download_handler.py

* Issue popup up in Deluge.
fix https://github.com/pymedusa/Medusa/issues/10822

Fix allowed statusses for postprocessing.

---

CHANGELOG.md
medusa/server/api/v2/history.py
themes-default/slim/src/components/history-detailed.vue

Fix filtereing by multiple fields

---

Dockerfile

Add ffmpeg binaries to the docker container for use in Medusa postprocessing.
Without it the PostProcessing Settings page displays error:
"Ffmpeg binary not found. Add the ffmpeg bin location to your system's environment or configure a path manually below."

Add ffmpeg to docker build for postprocessing

---

medusa/helpers/__init__.py

Currently, when hardlink failed, the fallback behavior will be copying file. This could fill up disks space and make unnecessary disks read/write if Medusa is run unattended. This PR remove this behavior and only raised the errors.

remove copy fallback when hardlink failed

---

medusa/indexers/tvdbv2/api.py

Change log level for episodes not in DVD order from `warning` to `info` because it is a normal situation when episodes have aired recently but there is no DVD release yet because it's too early for that. Thus warning level is not relevant. 
Message is :
```
No DVD order available for episode (season: 30, episode: 1). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Detective Conan(72454)
```

Change log level for episodes not in DVD order

---

medusa/subtitle_providers/addic7ed.py

Addic7ed force language based on IP location so if your medusa instance is located in a country where english is not the first language. Subliminal will failed to download subtitle because it match only on  `Completed` results. if the request is made from france the word will be "Terminé". 
set `en-US,en;q=1.0` as Accept-Language in requests header solve this issue
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
Cheers

fix(subliminal): set english language in requests header

---

ext/readme.md
ext/wrapt/__init__.py
ext/wrapt/arguments.py
ext/wrapt/decorators.py
ext/wrapt/importer.py
ext/wrapt/wrappers.py

The new version should work with 3.5 and greater
This fixes #11007 and allows medusa to open on my system with python 3.11.0. I added a new show to make sure it worked. No issues.
Side note: At some point we should remove the python 2 vs 3 stuff. I see elsewhere we dropped support for Python 2 a while ago, but the code still seems to act like both are supported in some places.
The new wrapt is the python files copy/pasted from the release here: https://pypi.org/project/wrapt/1.14.1
- [x ] PR is based on the DEVELOP branch
- [x ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Upversion the ext version of wrapt since the old version was not compatible with python 3.11.0

---

medusa/name_parser/rules/rules.py
tests/test_guessit.yml

Specific show 1923.
Added conditions to the rule wrongfully parse year in a multi part release string.

Fix parsing for shows that have year in the title

---

medusa/__main__.py

On startup, init will overwrite previous values set for `process_method_torrent` and `process_method_nzb` because it's actually reading `process_method` for each setting.
This change fixes that by setting `PROCESS_METHOD_NZB` and `PROCESS_METHOD_TORRENT` to read from the correct string within config.
For quick reference, the config names for the specific process methods:
https://github.com/pymedusa/Medusa/blob/49ad1f901a050c79b7e8cb583cb02ee1a6abeecf/medusa/__main__.py#L1714-L1715

Read correct process_methods from config on startup

---

medusa/updater/github_updater.py

Fix git subprocess call for Windows paths with spaces

---

themes-default/slim/static/css/light.css

works for me
problem is that in light theme there is a "hidden" link to the Show . Hidden because white on white.
dark theme is OK.

fix color of show-header in light-theme

---

medusa/scene_exceptions.py
tests/test_scene_exceptions.py

correctly refresh exceptions cache

---

medusa/server/api/v2/history.py
themes-default/slim/src/components/history-detailed.vue
themes-default/slim/src/store/modules/history.js

Fix history filter (develop)

---

medusa/providers/torrent/json/btn.py

Try to use TVDB ID for BTN search even if a different indexer is used

---

medusa/__main__.py

Provide means to set the web_port by environment variable, with "MEDUSA_WEB_PORT"

Set the WEB_PORT by enviroment variable if enviroment variable is set.
